58	Attempts to add the given user to the set of users liking this interpretation . If user not already present , increments the like count with one .
231	Checks whether the given block has a buffer assigned to it . If not , it synchronously gets an available buffer and assigns it to the block .
271	Creates an XNIException from a SAXException . NOTE : care should be taken *not* to call this with a SAXParseException ; this will lose information ! ! !
478	Since we ca n't use the application context to retrieve the current theme , we retrieve the theme from the Activity context when the object is initialized .
567	Reset any internal state , allowing this builder to be recycled . < p > Calling this method is more efficient than creating a new SelectionBuilder object .
712	Called when the swipe ends ; most likely on finger up event . It gives a chance to start an ending animation to exit the mode gracefully .
731	Determine if it 's unnecessary to write or update the file-backed cache . If only a few items are reparsed , then the cache is fresh enough .
762	Returns a QueueReader object containing all edges added so far , and which will be informed of any new edges that are later added to the graph .
792	Removes all the joints and bodies from this world . < p/ > This method does < b > not < /b > notify of destroyed objects .
797	Load preview images for each component into a file cache . Each combination of theme , device density , and API level will have its own cache .
1002	Nesting a 'count ' aggregation changes the outer aggregation to a 'longSum ' whereas the inner aggregation remains unchanged . Base class aggregation transformation is also performed .
1180	Returns the system runtime environment . < p > Methods in this environment methods delegate to the system environment accessible by the Java Virtual Machine. < /p >
1201	Indicates whether < a href= '' https : //code.google.com/p/android/issues/detail ? id=170841 '' > a known layout rendering issue < /a > is present in the given model .
1227	Inserts a Bundle value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
1469	Inserts a Boolean value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
1524	ID of the user or community that owns the wall . By default , current user ID . Use a negative value to designate a community ID .
1906	Inserts a Serializable value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
2327	Returns true if the change needs sending to the process . If false , the processId field points to the affected process : a restart is required .
2381	Return true if the given loader is the system class loader or its parent ( i.e . the loader for installed extensions ) or the null class loader
2845	This method will be used to read int from file from postion ( offset ) , here length will be always 4 bacause int byte size if 4
3112	Creates , updates or deletes zero or more pieces of content in the data store . You can attach a set of databus event tags for these updates
3549	Called when the WebView does a top-level navigation or refreshes . Plugins should stop any long-running processes and clean up internal state . Does nothing by default .
3693	Creates an instance that is the same as x except that it has the sign of y. abs ( x ) = dfp.copysign ( x , dfp.one )
3890	Although the following permission concerns the databus it is placed in the `` system '' resource since databus replication should only be performed internally by the system .
4245	Inserts a CharSequence value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
4444	Adds the given point to this point . Note that there is no guarantee that the new point will be < em > valid < /em > .
4614	Generates a random IV and encrypts this plain text with the given key . Then attaches a hashed MAC , which is contained in the CipherTextIvMac class .
4669	Instantiate the Client to communicate with the ElasticSearch cluster . If it is well instantiated , retrieve the indices and and create a bulkProcessor for batch writes .
4954	Retrieves the indexed node from the collection . Nodes are numbered in tree order - depth-first traversal order . This method might traverse the entire document tree .
4967	Searches the list for values satisfying < tt > condition < /tt > in the manner of the *nix < tt > grep < /tt > utility .
5139	Put a key/value pair in the JSONObject . If the value is null , then the key will be removed from the JSONObject if it is present .
5281	Enforces that only the system UID or root 's UID or apps that have the { android.Manifest.permission.MANAGE_USERS MANAGE_USERS } permission can make certain calls to the VUserManager .
5290	Get an optional JSONArray associated with a key . It returns null if there is no such key , or if its value is not a JSONArray .
5422	Removes Dotcms services that are tracked by the ExtendedGenericBundleActivator . These are services that require more than just a simple register/unregister . For instance Servlets and Filters .
5433	Inserts a SizeF value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
5437	Here , resource can double as a full address ( `` resource # name '' ) , though if name is specified it will always be used .
5583	Sends message to all group members ( regular player group , or alliance sub-group Error 105 , random value for players to report . Should never happen .
5909	Searches the list front to back for the index of < tt > value < /tt > , starting at < tt > offset < /tt > .
6285	Deletes an observer from the set of observers of this object . Passing < code > null < /code > to this method will have no effect .
6412	Inserts a SizeF value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
6486	Builds a copy of this ParameterDeclaration node where all occurrences of type variables in the original type parameter list have been replaced by the substitution type parameters .
6601	Creates a string with information including the passed message , the last passed message and the time since the last call , and the time since the beginning
6869	Track the specified file , using the provided marker , deleting the file when the marker instance is garbage collected . The speified deletion strategy is used .
7049	Builds a copy of this Access node where all occurrences of type variables in the original type parameter list have been replaced by the substitution type parameters .
7069	Shows a dialog used to accept input for adding a ray to the world . < p > Returns null if the dialog is closed or canceled .
7100	Remove empty lines . An empty line means a line ends in \n or \r\n and contains only white space characters , or no characters at all .
7373	Inserts a Bundle value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
7895	Expands a string that is a 10 to 12 digits number into a list of English words . For example , `` 27000000000 '' into twenty-seven billion .
7999	Verifies that the argument < code > set < /code > is not catchable as any of the exceptions in < code > members < /code > .
8082	ID of the user or community that owns the wall . By default , current user ID . Use a negative value to designate a community ID .
8478	Renders the named screen using the render environment configured when this ScreenRenderer was created . < p > SCIPIO : now delegating . Renders directly to writer .
8535	Called when this ViewModel instance was destroyed and removed from cache . < p > This is a place to do any cleanup to avoid memory leaks .
8650	PageObjectInjectorListener calls this method to check if the provider is able to handle currently injected field . < p > DialogFieldProvider handles fields decorated with DialogField annotation .
8719	Reads the contents of a file line by line to a List of Strings using the default encoding for the VM . The file is always closed .
8941	Releases resources used by the service for playback . This includes the `` foreground service '' status and notification , the wake locks and possibly the MediaPlayer .
9008	Updates the Android Gradle plugin version , and optionally the Gradle version of a given project . This method notifies the user if the version update failed .
9046	Inserts a String value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
9132	Expands a string that is a 10 to 12 digits number into a list of English words . For example , `` 27000000000 '' into twenty-seven billion .
9158	Throws a < code > SecurityException < /code > if parameter < code > e < /code > is instanceof < code > ServiceControlled < /code > .
9210	Returns true if this node is the left child of its parent node . < p > Returns false if this node does not have a parent .
9378	Removes a command class from the node . This is used to remove classes that a node may report it supports but it does n't respond to .
9398	Handles termination of the interaction . This method is called when the interaction has terminated ( either through successful completion , or because it was canceled ) .
9540	Removes Dotcms services that are tracked by the ExtendedGenericBundleActivator . These are services that require more than just a simple register/unregister . For instance Servlets and Filters .
9808	Returns the Intent used to send a user to a details page about the app . The IntentSender stored inside dictates what package needs to be launched .
9899	Starts a share intent with the activity that was most recently used to share . If there is no most recently used activity , it does nothing .
10505	Randomly sample values from a single column , in all sequences . Values may be taken from any sequence ( i.e. , sequence order is not preserved )
10541	Reports an error . The error message passed to the error handler is formatted for the locale by the message formatter installed for the specified error domain .
10562	This method will be used to read long from file from postion ( offset ) , here length will be always 8 bacause int byte size is 8
10577	Tests whether the two decimal numbers are equal with a tolerance of 0.01 . If one or both of the numbers are null , false is returned .
10621	Entry point of the application . Run this method to start the sample bots , but do n't forget to add the correct tokens in application.properties file .
11125	Called when the animation is done . At this point , we can get rid of the View that used to represent the InfoBar and re-enable controls .
11184	Reads the contents of a file line by line to a List of Strings using the default encoding for the VM . The file is always closed .
11199	< code > multLocal < /code > multiplies this vector by a scalar internally , and returns a handle to this vector for easy chaining of calls .
11619	return the euclidian distance square between two coords Hint : prefer this square distance if you want to compare distances rather than the exact distance that cost more
11625	Removes Dotcms services that are tracked by the ExtendedGenericBundleActivator . These are services that require more than just a simple register/unregister . For instance Servlets and Filters .
11730	Update position of VisibleObject [ used when object is moving on one map instance ] . Check if active map region changed and do all needed updates .
11783	Returns < code > true < /code > if < code > start < /code > and < code > end < /code > intersect this range .
11894	Creates a temporary file near the passed file . The name of the given one will be used and the suffix `` .temp '' will be added .
12125	Following methods remove the last node from the end of the nodeStack arrayList Since the previous node now becomes the closest target to an implicit break or continue
12128	It visits the in-memory tree that represents a bill of materials and it collects info of its nodes in the StringBuffer . Method used for debug purposes .
12230	< code > multLocal < /code > multiplies this vector by 3 scalars internally , and returns a handle to this vector for easy chaining of calls .
12265	Ensures that `` External Build '' is enabled for the given Gradle-based project . External build is the type of build that delegates project building to Gradle .
12487	The point ' p ' does not need to be normalized . This is a fast operation ( logarithmic in the size of the cell union ) .
12514	Return the workspace path for the package label for the given label . For example , if the package is //j/c/g/a/apps/docs : release , it returns j/c/g/a/apps/docs .
12947	Changes how results are displayed . Clicks the list view button . If the tab does n't contain this button , in that case IllegalStateException is thrown .
13027	Method which gets cluster xml Dom element and cluster xsl schema input stream . It calls the XSLT converter which produces a full cluster configuration Dom document .
13383	Inserts a Size value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
13511	The coordinates of the `` tip '' of the shadow ( relative to its top left corner ) ( the same as iconAnchor if not specified ) .
13544	Inserts a Parcelable value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
14254	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
14504	isInternationalPhoneNumber returns true if string s is a valid international phone number . Must be digits only ; any length OK. May be prefixed by + character .
14743	Track the specified file , using the provided marker , deleting the file when the marker instance is garbage collected . The speified deletion strategy is used .
14929	Establishes a processing stage . Runs the chain of all processors required to guarantee the given key is attached at the model . Returns true on success .
15272	PageObjectInjectorListener calls this method to check if the provider is able to handle currently injected field . < p > CurrentFrameProvider handles fields decorated with CurrentFrame annotation .
15303	Checks if the partition has the given vertex ( labels in vertex ) . This implementation returns < code > true < /code > for all vertices .
15329	Associates an asynchronous pretty printer with a response request id The pretty printer will be used to pretty print the response body that has the particular request id
15408	Removes Dotcms services that are tracked by the ExtendedGenericBundleActivator . These are services that require more than just a simple register/unregister . For instance Servlets and Filters .
15656	Multiplies this Vector2f 's x and y by the scalar and stores the result in product . The result is returned for chaining . Similar to product=this*scalar ;
15744	Limit of number of returned ads . Used only if ad_ids parameter is 'null ' , and `` campaign_ids '' parameter contains ID of only one campaign .
15917	Creates a simple bucket with only required values set . This bucket does not belong to the control group by default . The allocation percentage is 1/3 .
16115	This is advice method . It retrieves subreport name from the Subreport annotation , opens the subreport , proceeds with the method and finally closes the subreport .
16486	Searches the list front to back for the index of < tt > value < /tt > , starting at < tt > offset < /tt > .
16504	Expands a string that is a 7 to 9 digits number into a list of English words . For example , `` 19000000 '' into nineteen million .
16580	Shows a dialog used to accept input for applying a torque to a body . < p > Returns zero if the dialog is closed or canceled .
16655	Removes a < code > ClientDataTagValueUpdateListener < /code > instance from listener that will be informed when this < code > ClientRuleTag < /code > gets updated .
16690	Remove empty lines . An empty line means a line ends in \n or \r\n and contains only white space characters , or no characters at all .
16709	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
16875	Determines if the output is done . Access to the done variable should be within a synchronized block such as this to ensure that access is coherent .
17190	This method will be used to read int from file from postion ( offset ) , here length will be always 4 bacause int byte size if 4
17228	When an instance of this class is deserialized , this method is automatically invoked . This implementation of this method validates the state of the deserialized instance .
17317	Check the passing conditions represent to affect all lines or not . < br > Do not pass anything to the conditions parameter means affect all lines .
17340	< code > multLocal < /code > multiplies this vector by a scalar internally , and returns a handle to this vector for easy chaining of calls .
17398	Clear this TupleSet , calling clear on all contained TupleSet instances . All contained TupleSets remain members of this composite , but they have their data cleared .
17446	Clears the transient key store used by allowCertForProcess ( ) , and optionally clears the persistent key store ( by deleting its file and re-initializing it ) .
17675	Registers a prefix of class names to be included when generating taints . All classes whose names do n't start with a registered prefix will be skipped .
17738	Randomly sample a set of invalid values from a specified column , for a sequence data set . Values are considered invalid according to the Schema / ColumnMetaData
17753	Track the specified file , using the provided marker , deleting the file when the marker instance is garbage collected . The speified deletion strategy is used .
18239	< p > Adds the value of this fraction to another , returning the result in reduced form . The algorithm follows Knuth , 4.5.1. < /p >
18356	Generates a random IV and encrypts this plain text with the given key . Then attaches a hashed MAC , which is contained in the CipherTextIvMac class .
18647	Returns the concrete < code > MapEntry & lt ; K , V & gt ; < /code > type that represents the entries of the given map
18649	Returns the locale formatted as language-region . If region is not set , language is returned . If language is not set , empty string is returned .
18725	Reports an error . The error message passed to the error handler is formatted for the locale by the message formatter installed for the specified error domain .
19020	DOM Level 3 WD - Experimental . Replace the content of the document with the result of parsing the input string , this method is always synchronous .
19062	Returns a QueueReader object containing all edges added so far , and which will be informed of any new edges that are later added to the graph .
19301	Makes a call to get the number of clusters , if it is > 0 then we assume the setup has already been done and we skip it
19446	Removes Dotcms services that are tracked by the ExtendedGenericBundleActivator . These are services that require more than just a simple register/unregister . For instance Servlets and Filters .
19471	Inserts a Parcelable value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
19628	ID of the user or community that owns the wall . By default , current user ID . Use a negative value to designate a community ID .
19893	if the given key ( s ) is present in the map , create a long switch ( -- switch ) with the same name as the key
19907	Resets the display by clearing the offscreen buffer and flushing the internal rendering queue . This method can help reclaim memory when a Display is not visible .
20000	Consumes current token iff it 's a binary operator at the given precedence level ( with special-case handling of 'NOT ' 'IN ' double token binary operator )
20330	This method will be invoked when the current page is scrolled , either as part of a programmatically initiated smooth scroll or a user initiated touch scroll .
20546	Reads the contents of a file line by line to a List of Strings using the default encoding for the VM . The file is always closed .
20565	Handle an error , either by adding to the list , or if there is no list , throwing an < code > IOException < /code > .
20666	Inserts a Boolean value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
20747	Create geometry clipped and then converted to MVT 'extent ' coordinates . Result contains both clipped geometry ( intersection ) and transformed geometry for encoding to MVT .
21126	This method try to find a matching enum value by the given character representation . The character will be evaluated against the stored character of a flag .
21335	Returns < code > true < /code > if the instance has no requirements and no preferences ; returns < code > false < /code > otherwise .
21346	Inserts a CharSequence value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
21393	Given two arbitrary strings representing parts of an address , join them in a guaranteed-unique way , by HTML-escaping both parts and joining them with ' & '
21488	Inserts a String value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
21702	Expands a string that is a 7 to 9 digits number into a list of English words . For example , `` 19000000 '' into nineteen million .
21940	You received the % num0 damage inflicted on [ % SkillTarget ] by [ % SkillCaster ] , because of the protection effect you cast on it .
22007	Adds two half edges to this DCEL object given the vertices to connect . < p > This method assumes that no crossing edges will be added .
22197	This method will be used to clear the dictionary cache after its usage is complete so that if memory threshold is reached it can evicted from LRU cache
22209	Get the next value . The value can be a Boolean , Double , Integer , List , Map , Long , or String , or null .
22397	Determine the amount of available memory . `` Available '' memory is calculated as < code > ( max - total ) + free < /code > .
22660	Determine the insertion index of the next tab . If it 's not the result of a link being pressed , the provided index will be returned .
22713	This method will be used to read int from file from postion ( offset ) , here length will be always 4 bacause int byte size if 4
22758	Calculates the standard deviation ( square root of the variance ) of the distribution , either for the values only , or taking into account the keys .
23010	Cast the provided object to Comparable . Relevant for `` > '' , `` < `` , `` < = '' & `` > = '' operators .
23355	Updates the Android Gradle plugin version , and optionally the Gradle version of a given project . This method notifies the user if the version update failed .
23405	Print Topological Graph -- Print topological graph of transactions . Print a topological graph of the program 's transactions in the format used by the graphviz package .
23591	This method try to find a matching enum value by the given numerical representation . The number will be evaluated against the stored number of a flag .
24108	Returns < code > true < /code > if the space should shutdown on filter init failure . Defaults to < code > false < /code > .
24989	Calculates the standard deviation ( square root of the variance ) of the distribution , either for the values only , or taking into account the keys .
25066	Checks to see if the passed Object is null , if it is returns an empty but non-null string , otherwise calls toString ( ) on the object
25346	Define a folder where the artifact should be extracted to . < p > By default , the artifact will be extracted to Java 's Temp folder .
25494	Return a collector that creates a dictionary using the given key function and the given map supplier . This collector assumes the elements being collected are distinct .
25914	Will return a sample from the counter , will throw exception if any of the counts are < 0.0 or if the totalCount ( ) < = 0.0
25980	Sets the < code > include < /code > flag to the passed boolean value . If given true this element will be included in the manifest .
26175	Return the given gravity value or the default if the passed value is NO_GRAVITY . This should be used for children that are anchored to another view .
26251	Gets the signers of this class . We need an artificial field variable to connect setSigners and getSigners . public native java.lang.Object getSigners ( ) [ ] ;
26280	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
26449	Searches the list for values satisfying < tt > condition < /tt > in the manner of the *nix < tt > grep < /tt > utility .
26492	Escaped the given JSON content using Java String rules . Assumes `` is used as quote char and not used inside values and does not escape ' .
26824	Shows a dialog used to accept input for applying a force to a body . < p > Returns null if the dialog is closed or canceled .
27009	Returns true if element is declared to have element content . Whitespaces appearing inside element content will be ignored , other text will simply report an error .
27016	Get an optional JSONArray associated with a key . It returns null if there is no such key , or if its value is not a JSONArray .
27635	Posts a task to run the necessary actions . The task is delayed to prevent spin-locking in ChromeTabbedActivity.onResume ( ) : http : //b/issue ? id=5864891 & query=5864891
28182	Linear interpolation from startValue to endValue by the given percent . Basically : ( ( 1 - percent ) * startValue ) + ( percent * endValue )
28470	Renders the named screen using the render environment configured when this ScreenRenderer was created . < p > SCIPIO : now delegating . Renders directly to writer .
28552	Since we ca n't use the application context to retrieve the current theme , we retrieve the theme from the Activity context when the object is initialized .
28708	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
29225	Inserts a Size value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
29392	Reads the contents of a file line by line to a List of Strings using the default encoding for the VM . The file is always closed .
29421	For testing : creates a project with a given set of resource roots ; this allows tests to check this repository without creating a gradle project setup etc
29507	Add an adjustment to the order ; do n't worry about setting the orderId , orderItemSeqId or orderAdjustmentId ; they will be set when the order is created
29612	Print Topological Graph -- Print topological graph of transactions . Print a topological graph of the program 's transactions in the format used by the graphviz package .
30107	ID of the user or community that owns the wall . By default , current user ID . Use a negative value to designate a community ID .
30188	Put a key/value pair in the JSONObject . If the value is null , then the key will be removed from the JSONObject if it is present .
30218	Attempts to remove the given user from the set of users liking this interpretation . If user not already present , decrease the like count with one .
30388	Returns a Json map with two entries , one for `` ~table '' and one for `` ~id '' , similar to all System of Record objects .
30614	Track the specified file , using the provided marker , deleting the file when the marker instance is garbage collected . The speified deletion strategy is used .
30677	Generates random bytes and places them into a user-supplied byte array . The number of random bytes produced is equal to the length of the byte array .
30678	This version of putIdentifier is needed to avoid fluffing all of the paths to ID attributes when a node object is created that contains an ID attribute .
30788	Ensures that the PRNG is fixed . Should be used before generating any keys . Will only run once , and every subsequent call should return immediately .
30929	Checks whether a certificate needs renewal . Renewal can be caused either by certificate expiry or if the list of domains requested for a SAN certificate changes .
31014	Inserts a Serializable value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
31082	encodes an unnormalized 2D-vector as an unsigned 32 bit integer. < br > < br > 0xMMMMAAAA ( 16 bit arc , 16 bit magnitude < br >
31133	Get an optional JSONObject associated with a key . It returns null if there is no such key , or if its value is not a JSONObject .
31167	Subtracts the given point from this point . Note that there is no guarantee that the new point will be < em > valid < /em > .
31463	This method will always return false , mainly used in the filter expressions which are illogical . eg : columnName NOT IN ( 'Java ' , NULL )
31536	Shows a dialog used to accept input for applying a force to a body . < p > Returns null if the dialog is closed or canceled .
31603	Get an iterator over all edges that have the given node as a source . That is , edges that link out from the given source node .
31768	Returns < code > pre + base + post < /code > if base String is not null or empty , otherwise an empty but non-null String .
31971	Gets a cursor that has a list of decorations that pass the filter . Having a null or empty filter is the same as calling without a filter
31993	Get an optional JSONObject associated with a key . It returns null if there is no such key , or if its value is not a JSONObject .
32030	Releases the program . < p/ > The appropriate EGL context must be current ( i.e . the one that was used to create the program ) .
32358	Despawn VisibleObject , object will become invisible and object position will become invalid . All others objects will be noticed that this object is no longer visible .
32368	encodes an unnormalized 2D-vector as an unsigned 32 bit integer. < br > < br > 0xMMMMAAAA ( 16 bit arc , 16 bit magnitude < br >
32518	Gets the modality of this conversation . If a conversation is modal , all messages directed to the player are suppressed for the duration of the conversation .
32606	Returns the width in bits of the CRC function . The width is also the position of the implicit set bit at the top of the polynomial .
32630	Sets the number of inactive seconds to wait before automatically abandoning all generated conversations . < p > The default is 600 seconds ( 5 minutes ) .
32637	Registers the listener for update notifications for the specified Tag . Assumes this object is registered as JMS listener on the correct topic for the given Tag .
33017	This method flushes any pending events , which can be startDocument ( ) closing the opening tag of an element , or closing an open CDATA section .
33304	Write a serialized version of the contents of this session object to the specified object output stream , without requiring that the StandardSession itself have been serialized .
33608	Allows instances to be deserialized in pre-1.4 JREs ( which do not have SynchronizedRandomAccessList ) . SynchronizedList has a readResolve method that inverts this transformation upon deserialization .
33647	Parse the document . < p > This method will throw an exception if the embedded XMLReader does not support the http : //xml.org/sax/features/namespace-prefixes property. < /p >
33663	Updates the visibility of the steps depending on the current contents of the panels ( uses the QuickSetup to know what is displayed in the panels ) .
33916	Checks that the given nonce is the same as the last one returned via < code > getNonce ( ) < /code > , and invalidates it .
34262	Reads from < code > input < /code > and initalizes the value in this < code > CharHolder < /code > object with the unmarshalled data .
34280	Tests to see if all objects in the specified < tt > Collection < /tt > are children of this < tt > BeanContext < /tt > .
34402	Sends an event to the bus ATTENTION : ONLY observers that are observing the key AND the same class of the event will retrieve it < p >
34403	Reads a log file provided the user has the authorization . It reads all records but returns the maximum number of most recent records set through configuration .
34465	Make sure a time is UTC . If the time zone is not UTC , the time is adjusted and the time zone set to be UTC .
34599	Consumes the chain of Agera operators and executes a Receiver action for each update ( ) signal and allows in-sequence cancellation through the supplied Closeable to the receiver
34684	Check whether the given character sequence < code > src < /code > is normalized according to the normalization method < code > form < /code > .
34915	Returns true if the client detection service is present or false if the client detection service is not present and the client attributes could not be retrieved .
34916	Copies < code > is-html.xsl < /code > and < code > is-wml.xsl < /code > to base directory < code > /xsl < /code > directory .
34943	Creates a simple LDAP bind request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
35091	This method translates the < code > AuthorizationDecisionQuery < /code > to an XML document String based on the < code > AuthorizationDecisionQuery < /code > schema .
35098	Construct a extensibleObject object class where the set of allowed attribute types of this object class is implicitly the set of all attribute types of userApplications usage .
35311	Creates a property change listener that will be added to the JToolBar . If this method returns null then it will not be added to the toolbar .
35432	Returns a copy of this instant with the specified duration in milliseconds added . < p > This instance is immutable and unaffected by this method call .
35575	Closes this input stream and releases any system resources associated with the stream . This method simply performs < code > in.close ( ) < /code > .
35704	Returns the foos before and after the current foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
35769	Return true if the receiver wants a < code > Format.Field < /code > value and < code > attribute < /code > is equal to it .
35781	Generate a value suitable for use in setId ( int ) This value will not collide with ID values generated at build time by aapt for R.id .
35880	Sets the install root directory of the directory server . < p > The install root is the location where the data and live configuration is stored .
36003	Performs an evaluation of a single UserDNTypeURL of a userdn bind rule using the evaluation context provided . This method is called for the non-anonymous user case .
36044	Transform an exception into a TaskAbandonException . If no exception is passed , the routine checks if the task has been canceled and throws an TaskAbandonException accordingly .
36055	Called by this.transform ( ) if isParserEventsOnMain ( ) ==false . Similar with runTransformThread ( ) , but no priority is set and setTransformThread is not set .
36091	Always returns < code > true < /code > because all < code > JInternalFrame < /code > s must be roots of a focus traversal cycle .
36395	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
36402	If true , the text entered in the field represents the pathname of a file whose contents are to be submitted as the value of the field .
36800	Returns a copy of this duration with the specified duration in hours added . < p > This instance is immutable and unaffected by this method call .
36818	Returns the hash code value for this code signer . The hash code is generated using the signer 's certificate path and the timestamp , if present .
36986	Returns < CODE > true < /CODE > if the node must be refreshed when it is expanded and < CODE > false < /CODE > otherwise .
37312	This method returns a < code > boolean < /code > indicating if the specified < code > DataFlavor < /code > is supported . < P >
37540	Returns the foos before and after the current foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
37741	Sets the success URL and execute the post process login SPI . for < code > internalAutherror < /code > and if already executed just skip this .
37788	Initializes object to be an empty map with the specified initial capacity , which is assumed to be a power of two between MINIMUM_CAPACITY and MAXIMUM_CAPACITY inclusive .
37949	Called whenever the queue becomes empty . Notifies all active iterators that the queue is empty , clears all weak refs , and unlinks the itrs datastructure .
38060	Returns a copy of this duration with the specified duration in minutes added . < p > This instance is immutable and unaffected by this method call .
38129	Returns a specific media subtype , such as `` plain '' or `` png '' , `` mpeg '' , `` mp4 '' or `` xml '' .
38261	Replaces this node with a semantically equivalent text node . This node will be removed from the DOM tree and the new node inserted in its place .
38391	Adds an ImageConsumer to the list of consumers interested in data for this image , and immediately starts delivery of the image data through the ImageConsumer interface .
38439	Flushes this output stream and forces any buffered output characters to be written out . This will notify any readers that characters are waiting in the pipe .
38473	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
38526	Signal that we 're done with the headers , and body will follow . Any implementation needs to notify ContextManager , to allow interceptors to fix headers .
39039	Returns < code > true < /code > if this tag is a block tag , which is a tag used to add structure to a document .
39195	Create space for a new item at the end , and returns the rank for that item . Also sets the current page to the last page .
39550	Clone this NodeSetDTM . At this time , we only expect this to be used with LocPathIterators ; it may not work with other kinds of NodeSetDTMs .
39611	Reads from < code > input < /code > and initalizes the value in this < code > ObjectHolder < /code > object with the unmarshalled data .
39770	Write a serialized version of the contents of this session object to the specified object output stream , without requiring that the StandardSession itself have been serialized .
39888	WriteObject is called to save the state of the FilePermission to a stream . The actions are serialized , and the superclass takes care of the name .
40143	Starts up the channel . This can be called multiple times for individual services to start The svc parameter can be the logical or value of any constants
40159	After the body evaluation : do not reevaluate and continue with the page . By default nothing is done with the bodyContent data ( if any ) .
40450	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
40463	Decrements the count of in-flight transactions to the resource being monitored . If this operation results in the counter falling below 0 - an exception is raised .
40507	WriteObject is called to save the state of the PropertyPermission to a stream . The actions are serialized , and the superclass takes care of the name .
40743	This will traverse the heararchy , calling the visitor for each member . If the called visitor method returns false , the subtree should not be called .
40800	Sets the < code > JSpinner 's < /code > layout manager to null . This method is called by < code > uninstallUI < /code > .
40874	For some reason MappedMember.findNameAndDescWhatever ( name , desc ) does n't exactly work . This is an external implemtation which does the same thing but somehow works .
40918	Removes and transfers nodes until hit non-cancelled one or null . Split out from signal in part to encourage compilers to inline the case of no waiters .
41006	Creates a simple LDAP modify request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
41126	Removes and transfers nodes until hit non-cancelled one or null . Split out from signal in part to encourage compilers to inline the case of no waiters .
41156	Returns the neighbour triangle of this edge , which is different from p_triangle . If p_triangle is not a neighbour of this edge , null is returned .
41258	Returns the round trip time for this ping in nanoseconds , waiting for the response to arrive if necessary . Returns -1 if the response was cancelled .
41323	Adds a new subordinate template to this branch . Note that this should not be used after < CODE > completeBranchInitialization < /CODE > has been called .
41401	Changes the current < code > KeyboardFocusManager < /code > 's default < code > FocusTraversalPolicy < /code > to < code > DefaultFocusTraversalPolicy < /code > .
41464	Construct a name for this component . Called by < code > getName < /code > when the name is < code > null < /code > .
41891	Closes this connection . This cancels all open streams and unanswered pings . It closes the underlying input and output streams and shuts down internal executor services .
41942	Inserts the role specified as an element at the position specified . Elements with an index greater than or equal to the current position are shifted up .
41961	This will traverse the heararchy , calling the visitor for each member . If the called visitor method returns false , the subtree should not be called .
41984	Uninstalls the < code > PropertyChangeListener < /code > returned from < code > createPropertyChangeListener < /code > from the < code > JDesktopPane < /code > .
42008	Redoes all changes from the index of the next edit to < code > edit < /code > , updating the index of the next edit appropriately .
42020	Adds the provided task to the set of completed tasks associated with the scheduler . It will be automatically removed after the appropriate retention time has elapsed .
42068	Installs the < code > PropertyChangeListener < /code > returned from < code > createPropertyChangeListener < /code > on the < code > JDesktopPane < /code > .
42180	Returns a void promise for notify of outcome but no value returned . < p > Callback replyDone can be used instead of replay on service side .
42269	Returns a properly configured < code > PropertyChangeListener < /code > which updates the control as changes to the < code > Action < /code > occur .
42400	Our own little min method , to avoid loading java.lang.Math if we 've run out of file descriptors and we 're trying to print a stack trace .
42451	Reads the contents of a file line by line to a List of Strings using the default encoding for the VM . The file is always closed .
42473	Track the specified file , using the provided marker , deleting the file when the marker instance is garbage collected . The speified deletion strategy is used .
42500	Returns whether the specified node is a leaf node . The way the test is performed depends on the < code > askAllowsChildren < /code > setting .
42516	Sends an event to the bus ATTENTION : ONLY observers that are observing the key AND the same class of the event will retrieve it < p >
42675	Creates an instance of MouseWheelListener , which is added to the JScrollPane by installUI ( ) . The returned MouseWheelListener is used to handle mouse wheel-driven scrolling .
42775	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Logger 's effective level .
42788	Close the UIDbHelper . UI needs to call this method when it is done with the database connection . UIDbHelper is not usable after calling this method .
42791	Determines whether the specified code point is a valid < a href= '' http : //www.unicode.org/glossary/ # code_point '' > Unicode code point value < /a > .
42870	Processes a policy notification . Delegates to < code > RessourceResultCache < /code > . < code > ResourceResultCache < /code > removes the affected cache entries .
42941	Attempt to find the class with the superclass we refuse to load . This is expected to throw an InvocationTargetException , with a NullPointerException as its cause .
42947	Sets the failure URL and execute the post process login SPI . for < code > internalAutherror < /code > and if already executed just skip this ,
43007	Marks the beginning of a new scope in the output stream Writes also 1 , if p_boolean_value is true , or 0 , if p_boolean_value is false ;
43099	Removes and transfers nodes until hit non-cancelled one or null . Split out from signal in part to encourage compilers to inline the case of no waiters .
43197	Connects socket 'fd ' to 'inetAddress ' on 'port ' , with no timeout . The lack of a timeout means this method wo n't throw SocketTimeoutException .
43262	Returns true if the Style should be updated in response to the specified PropertyChangeEvent . This forwards to < code > shouldUpdateStyleOnAncestorChanged < /code > as necessary .
43296	Reduces the expression to a known node type ( i.e . not an Extension node or simply returns the expression if it is already a known type .
43393	This will traverse the heararchy , calling the visitor for each member . If the called visitor method returns false , the subtree should not be called .
43481	Flushes this output stream and forces any buffered output bytes to be written out . This will notify any readers that bytes are waiting in the pipe .
43712	Send a namespace declaration in the output document . The namespace declaration will not be include if the namespace is already in scope with the same prefix .
43767	Set the lead selection index , leaving all selection values unchanged . If leadAnchorNotificationEnabled is true , send a notification covering the old and new lead cells .
43796	Returns a copy of this instant with the specified duration in nanoseconds subtracted . < p > This instance is immutable and unaffected by this method call .
44090	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Logger 's effective level .
44183	Checks if an error message of the given level would actually be logged by this logger . This check is based on the Logger 's effective level .
44227	Determines if this menu result indicates that the user chose to cancel any task currently in progress and go back to the previous main menu if applicable .
44281	WriteObject is called to save the state of the DelegationPermission to a stream . The actions are serialized , and the superclass takes care of the name .
44385	Returns a copy of this instant with the specified duration in milliseconds subtracted . < p > This instance is immutable and unaffected by this method call .
44387	Given a map of already renamed classes , fill in the gaps for classes that were not reached , but have parents that can be pulled from .
44593	Generic promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
44662	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
44697	Returns true if resourceNameTypesEnabled ( ) is true , and the field config provided has a resource name format option , and is configured to use it .
44879	Translates the < code > AuthenticationQuery < /code > to an XML document String based on the < code > AuthenticationQuery < /code > schema described above .
45082	Make bit vector of version information . On success , store the result in `` bits '' . See 8.10 of JISX0510:2004 ( p.45 ) for details .
45122	Convenience method for sub-classes to save them having to call < code > super.init ( config ) < /code > . This is a NO-OP by default .
45124	Creates a new cache key , creates and caches a new < code > ContextHolder < /code > using the key and returns the newly cached object .
45138	Returns the OID from the provided DIT content rule definition , assuming the definition is valid . < p > This method does not perform any check .
45176	Returns a copy of this instant with the specified duration in seconds subtracted . < p > This instance is immutable and unaffected by this method call .
45327	Parse the document . < p > This method will throw an exception if the embedded XMLReader does not support the http : //xml.org/sax/features/namespace-prefixes property. < /p >
45547	Returns a specifier for a grayscale plus alpha image format that will pack pixels of the given bit depth into array elements of the specified data type .
45757	Returns a numeric value for this object that is likely to be unique , making it a good choice as the index value in a hash table .
46006	Upon close , this reads the remainder of the chunked message , leaving the underlying socket at a position to start reading the next response without scanning .
46021	Read a serialized version of the contents of this session object from the specified object input stream , without requiring that the StandardSession itself have been serialized .
46049	This method checks if the binary data is empty . < br > Disregarding the type of the descriptor its content is stored as a byte array .
46109	Reads the specified number of bytes from a given position within a stream . This does not change the current offset of the stream and is thread-safe .
46228	Reads from < code > input < /code > and initalizes the value in this < code > ByteHolder < /code > object with the unmarshalled data .
46250	Returns true if the framework has been started and is any of the following states indicating it is ready : STARTED , PACKAGES_REFRESHED , WARNING , INFO .
46276	Clears the password so that sensitive data is no longer present in memory . This should be called as soon as the password is no longer needed .
46406	Notes a key to a hyphenation tree as missing . This is to avoid searching a second time for a hyphenation pattern file which is not available .
46562	Returns a void promise for notify of outcome but no value returned . < p > Callback replyDone can be used instead of replay on service side .
46612	Compares this object to the specified object . The result is < code > true < /code > if the object is an equivalent set of attributes .
46665	Read a serialized version of the contents of this session object from the specified object input stream , without requiring that the StandardSession itself have been serialized .
46760	Shuts down the channel . This can be called multiple times for individual services to shutdown The svc parameter can be the logical or value of any constants
46862	Releases the program . < p > The appropriate EGL context must be current ( i.e . the one that was used to create the program ) .
46917	This will traverse the heararchy , calling the visitor for each member . If the called visitor method returns false , the subtree should not be called .
46924	Requests focus for this object . If this object can not accept focus , nothing will happen . Otherwise , the object will attempt to take focus .
46998	Writes a message to the access logger with information about a new client connection that has been established , regardless of whether it will be immediately terminated .
47128	Returns a copy of this duration with the specified duration in milliseconds added . < p > This instance is immutable and unaffected by this method call .
47390	Appends a new padstack with the input shapes to this padstacks . p_shapes is an array of dimension board layer_count . The padatack name is generated internally .
47726	Allows instances to be deserialized in pre-1.4 JREs ( which do not have UnmodifiableRandomAccessList ) . UnmodifiableList has a readResolve method that inverts this transformation upon deserialization .
47805	Removes and transfers nodes until hit non-cancelled one or null . Split out from signal in part to encourage compilers to inline the case of no waiters .
47871	Called whenever the queue becomes empty . Notifies all active iterators that the queue is empty , clears all weak refs , and unlinks the itrs datastructure .
48294	Called from setBeanContext to validate ( or otherwise ) the pending change in the nesting BeanContext property value . Returning false will cause setBeanContext to throw PropertyVetoException .
48693	Increases the size of the backing array to accommodate the specified number of additional items . Useful before adding many items to avoid multiple backing array resizes .
48770	Replace colon to make the name more Windows friendly . e.g . `` Sissi : The Young Empress '' - > `` Sissi - The Young Empress ''
48883	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
48886	In a case the protocol message received was not equal to the messages in our protocol message list , we have to clear our protocol message list .
48994	Sets the < code > JSpinner 's < /code > layout manager to null . This method is called by < code > uninstallUI < /code > .
49170	WriteObject is called to save the state of the SocketPermission to a stream . The actions are serialized , and the superclass takes care of the name .
49216	Shuts down the channel . This can be called multiple times for individual services to shutdown The svc parameter can be the logical or value of any constants
49239	An Application is editable if it can be changed by an end user . This method was put in place for subclasses that can not be edited .
49266	Paints text at the specified location . This will not attempt to render the text as html nor will it offset by the insets of the component .
49296	Dispatches an event to the active input method . Called by AWT . If no input method is available , then the event will never be consumed .
49582	Creates a simple LDAP modify request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
49589	Decrements the count of in-flight transactions to the resource being monitored . If this operation results in the counter falling below 0 - an exception is raised .
49672	Indicates whether some other object is `` equal to '' the value . The other value is equal if Object.equals ( value , other ) returns true .
49881	A convenience method that handles painting of the background for subregions . All SynthUI 's that have subregions should invoke this method , than paint the foreground .
49898	Undoes all changes from the index of the next edit to < code > edit < /code > , updating the index of the next edit appropriately .
49915	This method contains the algorithm used to compare the < CODE > HTTPServletRequest < /CODE > user-agent versus the < CODE > Client < /CODE > user-agent .
49929	What it does is to calculate the distance from the projection and the point Note that if the point is exactly colinear then the projection does not exist
49996	Returns the ruleID from the provided DIT structure rule definition , assuming the definition is valid . < p > This method does not perform any check .
50101	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
50151	Builds a new Name for the given type . The generated name will use the given type 's short name as leaf and will have no parent .
50266	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Logger 's effective level .
50292	Handles authentication requests from HTTP both GET and POST . Will then either create the Login Process , as the request will be a new authentication request .
50415	Indicates that skipped entries should be written to the specified file . Note that this applies only to entries that are skipped because they matched exclude criteria .
50541	Returns true if we should use the < code > Image < /code > returned from < code > getVolatileOffscreenBuffer < /code > to do double buffering .
50778	Moves the iterator forwards , along the primary direction of traversal , to the next segment of the path when there are more points in that direction .
51143	Modify the current clipping path by intersecting it with the current path , using the nonzero winding rule to determine which regions lie inside the clipping path .
51254	Wait enough for the system clock to update its value . On some systems ( e.g . old Windows ) the clock granularity is tens of milliseconds .
51307	Returns true if the Geocoder methods getFromLocation and getFromLocationName are implemented . Lack of network connectivity may still cause these methods to return null or empty lists .
51338	Handle any IOExceptions thrown . < p > This method provides a point to implement custom exception handling . The default behaviour is to re-throw the exception .
51412	Returns a copy of this instant with the specified duration in seconds added . < p > This instance is immutable and unaffected by this method call .
51532	Deletes an observer from the set of observers of this object . Passing < CODE > null < /CODE > to this method will have no effect .
51568	Returns the foos before and after the current foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
51579	Decrements the count of in-flight transactions to the resource being monitored . If this operation results in the counter falling below 0 - an exception is raised .
51606	Returns the ERA . We need a special method for this because the default ERA is CE , but a zero ( unset ) ERA is BCE .
51626	Make sure that we can get an exclusive lock for the Directory Server , so that no other operation will be allowed while this is in progress .
51687	Method called when one of the elements that affect the value of the hashcode is modified . It is used to minimize the time spent calculating hashCode .
51755	This will traverse the heararchy , calling the visitor for each member . If the called visitor method returns false , the subtree should not be called .
52435	Initializes the configuration framework using the application 's class loader as the parent class loader , and the current working directory as the install and instance path .
52453	If fractional replication is enabled , this analyzes the operation and suppresses the forbidden attributes in it so that they are not added in the local backend .
52576	Moves the iterator to the next segment of the path forwards along the primary direction of traversal as long as there are more points in that direction .
52619	Returns a copy of this duration with the specified duration in nanoseconds added . < p > This instance is immutable and unaffected by this method call .
52834	Exposes the array backing a non-direct ByteBuffer , even if the ByteBuffer is read-only . Normally , attempting to access the array backing a read-only buffer throws .
52861	Returns the hashCode for the object . The hash code of a TreePath is defined to be the hash code of the last component in the path .
53063	Checks if this month-day is equal to another month-day . < p > The comparison is based on the time-line position of the month-day within a year .
53385	Create an default instance for conversion . Encoding to JSON and decoding from JSON ( when no charset is specified by a header ) will use UTF-8 .
53388	Returns whether this token bucket is expired or not , meaning that the difference between now and the last refill is greater than the bucket 's duration .
53607	Reads from < code > input < /code > and initalizes the value in this < code > ShortHolder < /code > object with the unmarshalled data .
53655	This method flushes any pending events , which can be startDocument ( ) closing the opening tag of an element , or closing an open CDATA section .
53694	Specifies whether `` slash-star '' ( C-style ) comments shall be recognized . Slash-star comments can not be nested and end when a star-slash combination is found .
53750	Deregisters the specified password storage scheme with the Directory Server . If no scheme is registered with the specified name , then no action will be taken .
53964	Clears the current advice associated with this < code > ConditionDecision < /code > . < p/ > Deprecated method as a given instance should be immutable .
54061	Converts the specified long value into its octal string representation . The returned string is a concatenation of characters from ' 0 ' to ' 7 ' .
54099	Parse the document . < p > This method will throw an exception if the embedded XMLReader does not support the http : //xml.org/sax/features/namespace-prefixes property. < /p >
54110	Creates a new menu result indicating that the user chose to cancel any task currently in progress and go back to the previous main menu if applicable .
54225	Returns , if the room overlaps with net dependent objects . In this case it can not be retained , when the net number changes in autorouting .
54545	Attempt to find the class with the superclass we refuse to load . This is expected to throw an InvocationTargetException , with a NullPointerException as its cause .
54598	Returns the foos before and after the current foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
54663	Compares this object to the specified object . The result is < code > true < /code > if the object is an equivalent set of attributes .
54699	Gets the modality of this conversation . If a conversation is modal , all messages directed to the player are suppressed for the duration of the conversation .
54980	Parse the document . < p > This method will throw an exception if the embedded XMLReader does not support the http : //xml.org/sax/features/namespace-prefixes property. < /p >
55005	Set an aspect ratio for crop bounds that is evaluated from source image width and height . User wo n't see the menu with other ratios options .
55031	WriteObject is called to save the state of the ServicePermission to a stream . The actions are serialized , and the superclass takes care of the name .
55058	This < code > LayoutManager < /code > method does nothing . We 're only managing a single child and there 's no support for layout constraints .
55166	Reads from < code > input < /code > and initalizes the value in this < code > TypeCodeHolder < /code > object with the unmarshalled data .
55181	Starts up the channel . This can be called multiple times for individual services to start The svc parameter can be the logical or value of any constants
55436	Obtains a hash code for this object . All instances of this class have the same hash code . There is only one instance of this class .
55499	Checks if this time is before the specified time . < p > The comparison is based on the time-line position of the time within a day .
55932	Sends < code > redo < /code > to all contained < code > UndoableEdit < /code > s in the order in which they were added .
56050	Retrieves records from log file provided it has the required authorization . It reads all records applies query and returns the result as asked by the caller .
56135	Add HTTP POST data . No checking is done in the case where we 're actually building a GET and the post data will still be written .
