149	Updates the barcode instance from the detection of the most recent frame . Invalidates the relevant portions of the overlay to trigger a redraw .
287	Only contains transient or static fields , which is the case for a model that is empty , but says it `` implements Parcelable ''
319	Utility attribute for literal rewriting . Any of the NumericLiteral subclasses have already been rewritten and/or parsed , and should not be rewritten again .
423	NOTE : it is platform-dependent , create a new string , needs to be verified . public static native java.lang.String mapLibraryName ( java.lang.String ) ;
461	Whether to fill the path with color . Set it to false to disable filling on polygons or circles . < /br > default true
488	Check a property . If the property is known and supported , this method simply returns . Otherwise , the appropriate exception is thrown .
582	Convenience method to create a new token with the type set to number value and with the starting index set to the given index .
822	Notifies that a the resource was created . This is called by the thread creating the resource , prior to being given the instance .
838	Return true if and only if the interior of this rectangle intersects any point ( including the boundary ) of the given other rectangle .
900	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
961	Adds a block to the end of the queue , but only if its < i > inq < /i > flag is false .
1019	Splits a given string to its words , without stemming . Words are considered to be everything , but sequences of whitespace and punctuation .
1191	Construct an JobRowFilter object using the same JobField and FilterOperation as the object on which this method is called and using the supplied values .
1304	The return variable is assigned an abstract object representing all classes ( UnknowClassObject ) from environment . public final native java.lang.Class getClass ( ) ;
1424	Called whenever the end of a side swipe scroll is detected . This lets inheriting classes clean up any side swipe behavior they want .
1572	Utility attribute for literal rewriting . Any of the NumericLiteral subclasses have already been rewritten and/or parsed , and should not be rewritten again .
1673	Provides a string representation of a hash table of objects . Calls < code > toString ( StringBuffer , ... ) < /code > .
1895	Set the output buffer size . < p > If output buffer size is 0 , the writes will be transmitted to wire immediately .
2013	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
2086	JSON serialization-focused getter that will `` un wrap '' the map , making it 's entries appear to be those of the parent class .
2220	Writes the default serializable field value for this instance , followed by the registrar 's service ID encoded as specified by the ServiceID.writeBytes method .
2445	Translate the region by the specified amount . < p > The instance is not modified , a new instance is created. < /p >
2558	Set the location of < samp > jhall.jar < /samp > or < samp > jsearch.jar < /samp > ( JavaHelp tools library ) .
2702	Whether to draw stroke along the path . Set it to false to disable borders on polygons or circles . < /br > default true
2707	Return a string representation of the value . If there is an actual value , use toString ; otherwise , use the normalized value .
2825	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
2950	Returns this object . This method prevents a subclass from declaring a < code > readResolve < /code > method with an alternate implementation .
2970	Number of messages to delete . NOTE : If the number of messages exceeds the maximum , the method shall be called several times .
3084	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
3299	Runs a action that requires the rendering lock . Layoutlib is not thread safe so any rendering actions should be called using this method .
3475	Invokes an external mechanism to display an error notification for the specified error code and context . Must be called on the UI thread .
3559	Utility attribute for literal rewriting . Any of the NumericLiteral subclasses have already been rewritten and/or parsed , and should not be rewritten again .
3562	Returns true if the specified character is a valid NCName character as defined by production [ 5 ] in Namespaces in XML 1.1 recommendation .
3879	Use isSameNode ( ) for testing node identity if the DOM implementation supports DOM Level 3 core and it is n't the Xerces implementation .
3898	Delete the subscription by closing and deleting its managed cursor if no consumers are connected to it . Handle unsubscribe call from admin layer .
4165	Produce a JSONObject from a row of comma delimited text , using a parallel JSONArray of strings to provides the names of the elements .
4415	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
4609	Call this to signal a `` pause '' of the given component . < p > No further execution will happen for this component .
4837	Writes the default serializable field value for this instance , followed by the item 's service ID encoded as specified by the ServiceID.writeBytes method .
4969	This method will load the cache of the object already initialized . A Collection is used to keep track of the objects to load .
4990	Removes the given node from this tree and returns true if the node ( not the node 's comparable ) existed and was removed .
5036	Converts the provided byte array to a String using the UTF-8 encoding . If the input is malformed , replace by a default value .
5049	Utility attribute for literal rewriting . Any of the NumericLiteral subclasses have already been rewritten and/or parsed , and should not be rewritten again .
5056	Convert data in arrays ( from CSV reader ) to Map < String , Object > , the current input format for graql templating .
5071	The first line of the input file should be `` rows cols '' , and the following line should be `` rowIndex colIndex value ''
5113	Parses the XLIFF ( from a translation kit ) content and extract the new/changed variants . Then updates the TM with these new variants .
5126	Zooms in or out by the given scale factor . x and y are the coordinates ( in pixels ) of the zoom center .
5403	returns true if this the txn participants need to join it in contrary to a xtn which the participants are known prior to txn propagation
5416	Indicates the end of a number in the JSON input . This method will be called after reading the last character of the number .
5420	All resources which can be loaded not in onCreate ( ) , should be load here , this function called while splash screen is active
5477	Pass the input of this Domino to another two Dominoes and merge their outputs into one , which is the output of this Domino .
5556	This must be called after creation from the ArtifactInfoFactory after this class has been put into the global Map in order to avoid recursive initialization
5642	Given an ImmutablePair , and a right value , returns a new ImmutablePair with the same left value , and the specified right value .
5682	Clicks OK button at the bottom of edit Window . Saves changes and closes the window ( waits for the dialog to disappear ) .
5948	Returns true if the specified URL matches a whitelisted URL regular expression . If the whitelist is disabled , this method always returns false .
5989	Build a list of interval strings . Format of interval string : yyyy-MM-dd ' 'HH : mm : ss/yyyy-MM-dd ' 'HH : mm : ss
6043	Java main to test creating events in elasticsearch . Set the following ENV VARS to point to a local ES running in OpenShift PIPELINE_ELASTICSEARCH_HOST=elasticsearch.vagrant.f8 ELASTICSEARCH_SERVICE_PORT=80
6184	Returns true if the current host matches the default search engine host and location for the default search engine is being granted via x-geo .
6190	Trains the suggester with a new instance , given the estimation values for each category , the original category decided and the actual category .
6685	Returns a copy of the ResizableDoubleArray . Does not contract before the copy , so the returned object is an exact copy of this .
6768	Writes out `` \r\n '' to the response output stream which is required to end the response headers before writing out the body content .
6893	Method perform intelligent escaping of quotes in xpath expressions , if necessary it constructs concat functions otherwise it simply add single or double quotes .
6958	Use this to change whether the setters and getters apply to all views in this layout , or just to the currently selected one .
7024	Tests whether a PeriodType can be defined for the DataElement , which requires that the DataElement is registered for DataSets with the same PeriodType .
7104	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
7210	Indicates if we want to show decorations ( anchor points , resize handles ) . Typically we want to hide decorations when dragging a widget
7445	Return a byte value for the < code > read ( ) < /code > method . < p > This implementation returns zero .
7583	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
7595	< code > negate < /code > returns the negative of this vector . All values are negated and set to a new vector .
7638	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
7649	Sets the max memory in megabytes for all the cached data on disk If not supplied , 100 megabytes will be the default value .
7940	Adds a core data tag changer to the configuration controller . This changers should never fail to maintain a proper state of the DAQ .
8436	Updates the barcode instance from the detection of the most recent frame . Invalidates the relevant portions of the overlay to trigger a redraw .
8816	Turns an Optional < T > into a Stream < T > of length zero or one depending upon whether a value is present .
8843	Get the color code for the given hue , saturation , and brightness values , translating from HSB color space to RGB color space .
8861	Determine whether the unit is an `` edge '' unit , i.e . a unit marking the start or the end of an utterance .
8869	Creates a data string which stores the base information we need to relaunch a task : a unique identifier and the URL to load .
8926	Sends a request to perform a hard reset on the controller . This will reset the controller to its default , resetting the network completely
9039	Counts the number of items that would be need to fill out the last row in the group of items with the given header .
9150	Create an infinite retry policy with backoff time between < i > baseBackOffTimeMs < /i > and < i > maxBackoffTimeMs < /i > .
9238	Resets the SearchBar text opacity when a new search context is set . The search context is made visible and the search term invisible .
9318	Trains the suggester with a new instance , given the estimation values for each category , the original category decided and the actual category .
9584	Creates a segmented stored list - used for highly concurrent lists . this SL supports serving as a EconomyConcurrentHashMap HashEntry for storing an index value
9797	Calculates the dot product of this vector with another . The dot product is defined as x1*x2+y1*y2+z1*z2 . The returned value is a scalar .
9848	Rotates the view provided by this display by the given angle in radians , anchoring the rotation at the specified point in screen coordinates .
10113	Returns true if the object passed in is an instance of EntryClass with the same type hash as this object . Returns false otherwise .
10295	Construct an JobRowFilter object using the same FilterOperation and values as the object on which this method is called and using the supplied JobField .
10304	Get the color code for the given hue , saturation , and brightness values , translating from HSB color space to RGB color space .
10384	filters out Invokes. < br > returns < code > null < /code > if < code > val < /code > is null .
10556	`` true '' - method will return additional fields : likes , can_comment , car_repost , photos . These parameters are not returned by default
10582	Writes the default serializable field value for this instance , followed by the registrar 's service ID encoded as specified by the ServiceID.writeBytes method .
10662	Creates a Permission instance for read permission on a table . This always resolves a new instance and will not return a cached value .
10664	Attempts to find the SteamVR settings within the given locations . The SteamVR settings file contains the VR settings such as renderTargetMultiplier and allowReprojection .
10712	[ % SkillTarget ] will receive the decrease flight time effect in a moment because [ % SkillCaster ] used [ % SkillName ] .
10742	Click the tab on icon bar . TabName parameter is case sensitive . Correct values usually start from upper case letter e.g Images , Documents
11120	Produce a JSONObject from a row of comma delimited text , using a parallel JSONArray of strings to provides the names of the elements .
11254	SCIPIO : Returns true only if the category ID is child of the given parent category ID . < p > NOTE : is caching
11324	Maximum time since a message was sent , in seconds . To return messages without a time limitation , set as `` 0 '' .
11415	Tests if the interior of this < code > Polygon < /code > entirely contains the specified < code > Rectangle2D < /code > .
11823	The opposition has withdrawn from the Dredgion infiltration mission . The mission will stop in % DURATIONTIME0 % and you will leave the Dredgion .
11849	Returns a < code > String < /code > formatted as years : months : days : hours : minutes : seconds : millseconds .
11877	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
11902	Zooms in or out by the given scale factor . x and y are the coordinates ( in pixels ) of the zoom center .
11964	< code > detachChild < /code > removes a given child from the node 's list . This child will no longe be maintained .
12039	Delete a result from a query . This may involve deleting the whole concept or specific edges , depending on what deleters were provided .
12087	Escapes reserved HTML characters in the given string . < p > < b > Warning : < /b > Does not preserve whitespace .
12091	adds < code > o < /code > into the map . no test are made , if it is already in the map .
12273	Tell whether the string contains a positive or negative percentage delta , i.e. , a percentage number with an obligatory + or - sign .
12371	Logical filter resolver will return the left and right filter expresison node for filter evaluation , so in this instance no implementation is required .
12473	Splits a given string to its words , without stemming . Words are considered to be everything , but sequences of whitespace and punctuation .
12542	Convenience method that creates and returns a mapping of a single < code > ServiceRegistrar < /code > instance to a set of groups .
12627	[ % SkillTarget ] will receive the decrease flight time effect in a moment because [ % SkillCaster ] used [ % SkillName ] .
12704	Translate the plane by the specified amount . < p > The instance is not modified , a new instance is created. < /p >
12803	Notifies that a the resource was borrowed . This is called by the thread requesting the resource , prior to being given the instance .
12934	Blatant copy of Integer.toString , but returning a byte array instead of a String , as string charset decoding/encoding was killing us on performance .
13052	true - call the phone number and leave a voice message of the authorization code false - send the code by SMS ( default )
13067	Convert the specified column from an integer representation ( assume values 0 to numCategories-1 ) to a categorical representation , given the specified state names
13112	Utility attribute for literal rewriting . Any of the NumericLiteral subclasses have already been rewritten and/or parsed , and should not be rewritten again .
13267	Convenience method to return a Collection as a delimited ( e.g . CSV ) String . E.g . useful for toString ( ) implementations .
13336	Tell whether the string contains a positive or negative percentage delta , i.e. , a percentage number with an obligatory + or - sign .
13358	Moves to the next index record in B-tree leaves matching the previously-specified search key . Returns false if there are no more such records .
13402	Resets the SearchBar text opacity when a new search term is set . The search term is made visible and the search context invisible .
13593	Sets shadow color and position , please refer to the below function . Note that this function must be called before using this class .
13638	Initialize Webster , serving code as determined by the either the org.jini.rio.tools.webster.root system property ( if set ) or defaulting to the user.dir system property
13675	Use isSameNode ( ) for testing node identity if the DOM implementation supports DOM Level 3 core and it is n't the Xerces implementation .
13684	Signals the end of the document . This is where the specific instances of value stores can verify the integrity of the identity constraints .
13746	Print a start tag with one attribute . The tag will be followed by a newline , and the indentation level will be increased .
14229	Generate a session Id to be used throughout the established session . The Id is generated using a cryptographically strong pseudo random number generator .
14321	Finds the message handler matching the given message type . If no message handler found for the given message type , null is returned .
14465	Notify the SwipeRefreshLayout that a refresh action has completed . Defer the notification by a reasonable minimum to ensure sufficient visiblity of the animation .
14580	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
14841	Returns preference store that belongs to the our plugin . This is important because we want to store our preferences separately from the desktop .
15183	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
15250	Read an unsigned short , 16 bits . Like DataInputStream.readUnsignedShort except little endian . Note , returns int even though it reads a short .
15313	Removes the specified permission from this attachment . < p > If the permission does not exist in this attachment , nothing will happen .
15340	Writes the default serializable field value for this instance , followed by the registrar 's service ID encoded as specified by the ServiceID.writeBytes method .
15362	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
15483	Creates a Context for the given key . Contexts can be created only for keys at the top of the origin and destination Histories .
15745	Write a newline at the end of the document . < p > Pass the event on down the filter chain for further processing .
15747	clear list of all the productionRunRoutingTasks to force re-reading at the next need . This method is used when the routingTasks ordering is changed .
15789	Used for an item inserted into the new list when we need to track moves that effect the inserted item in the old list .
15853	Give the host application a chance to take over the control when a new url is about to be loaded in the current WebView .
15963	Filter the list of files to contain only upgradable files . Note that the current instance is untouched and a new instance is returned .
16004	Returns true if the argument is a `` dangerous '' double to have around , namely one that is infinite , NaN or zero .
16102	Construct an JobRowFilter object using the same JobField and values as the object on which this method is called and using the supplied FilterOperation .
16182	Force computation of the first item in an iterator so metrics calculations for a method reflect the cost of the first batch of results .
16184	Convenience method to create a new token with the type set to string value and with the starting index set to the given index .
16263	Apply retrieved length limit to edit text field . This result may be fresh from the server or it may be from cached values .
16307	< code > negate < /code > returns the negative of this vector . All values are negated and set to a new vector .
16491	Signal that the splash screen is now visible . This is being used to record for how long the splash screen is left visible .
16545	Set the location of < samp > jhall.jar < /samp > or < samp > jsearch.jar < /samp > ( JavaHelp tools library ) .
16562	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
16638	< code > mult < /code > multiplies a vector about a rotation matrix . The resulting vector is returned as a new Vector3f .
17014	You suffered % num0 damage and lost some of your magical buffs because [ % SkillCaster ] used [ % SkillName ] on you .
17027	[ % SkillTarget ] is forced to resurrect at the bind point because [ % SkillCaster ] used [ % SkillName ] on it .
17115	Shrink string over the wire , should be used for constant number of strings which are repetitive ( i.e space names , class names )
17301	Returns true if the specified character is a valid name start character as defined by production [ 5 ] in the XML 1.0 specification .
17323	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
17329	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
17423	Check if the < code > set < /code > method for the given data field can accept values of a given target type .
17560	This must be called after creation from the ArtifactInfoFactory after this class has been put into the global Map in order to avoid recursive initialization
17811	Called when we 've noticed an edit outside of an app module , or in something other than a resource file or a Java file
18060	Renders one hilited field ( multiple passages ) value with < b > ... < /b > tags , and ... separating the passages .
18158	Creates a new color object from an integer that contains the blue , green , and red bytes in the lowest order 24 bits .
18227	Convert a < em > level index < /em > back to a level . Inverse of levelToLevelIdx , see explanations there for rationale .
18361	Not to return photos being hidden from the block above the wall . Works only with owner_id greater than 0 , no_service_albums is ignored .
18447	IDs requested ads or campaigns , separated with a comma , depending on the value set in `` ids_type '' . Maximum 2000 objects .
18464	Returns the current stream as a hexadecimal string of values . Shows the entire stream , and the remaining data at the current position .
18520	Return a non delegating map which snapshots the data visible in this delegating map , disconnected from changes to this and the underlying delegates .
18544	Deletes the file object . < p > This implementation uses < code > FileUtils.forceDelete ( ) < code > if the file exists .
18741	Tests whether this audio input stream supports the < code > mark < /code > and < code > reset < /code > methods .
18759	Convenience method that creates and returns a mapping of a single < code > ServiceRegistrar < /code > instance to a set of groups .
18864	Indicates the beginning of a number in the JSON input . This method will be called when reading the first character of the number .
18994	Opens up a different file . This will run through the `` Open File ... '' dialog to find and select the given file .
19041	Move one or more node ( s ) to our list of children . Note that this implicitly removes them from their previous parent .
19048	Copy text . Copy all sample text to the system clipboard . Remember the current caret position ( selection ) and restore that afterwards .
19108	Generates an ID for a new Tab . Makes sure the DocumentTabModels are loaded beforehand to ensure that the ID counter is properly initialized .
19822	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
19971	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
20019	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
20102	Move one or more node ( s ) to our list of children . Note that this implicitly removes them from their previous parent .
20314	Finds the message handler matching the given message type . If no message handler found for the given message type , null is returned .
20321	Identifier required to get the next page of results . Value for this parameter is returned in `` next_from '' field in a reply .
20562	Get an iterator over all the edges and nodes of this graph . The iterator will return all edges first , then all nodes .
20568	Checks if the class has at lease the resolving level specified . This check does nothing is the class resolution process is not completed .
20604	Compares the given ints , which refer to the indexes of the floats in this column , according to the values of the floats themselves
20840	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
21200	Whether to draw stroke along the path . Set it to false to disable borders on polygons or circles . < /br > default true
21213	PathElement is the only element having values inside - > nothing to do here . Does n't care at the current state of parsing .
21298	Check a property . If the property is known and supported , this method simply returns . Otherwise , the appropriate exception is thrown .
21303	Return true if and only if the interior of this rectangle contains all points of the given other rectangle ( including its boundary ) .
21517	Returns a UUID that sorts greater than or equal to all RFC 4122 timestamp UUIDs ( version = 1 , variant = 2 ) .
21555	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
21567	Execute refresh method . This method is called every time a binding item is refreshed and the corresponding node should be sent a message .
21606	Not to return photos being hidden from the block above the wall . Works only with owner_id greater than 0 , no_service_albums is ignored .
21727	Convenience method to return a Collection as a delimited ( e.g . CSV ) String . E.g . useful for toString ( ) implementations .
21872	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
22531	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
22592	Force computation of the first item in an iterator so metrics calculations for a method reflect the cost of the first batch of results .
23338	Compare two ages . CHILD is less than TEENAGER , and so on . If either age is DONT_CARE , then they are equal .
23339	Whether the tile fade animation is enabled . By default it 's enabled in all browsers that support CSS3 Transitions except Android . default true
23397	Stops listening for updates to the sign-in state . Every call to registerForUpdates ( ) must be matched with a call to this method .
23415	This method will be used to read the byte array from file based on offset and length ( number of bytes ) need to read
23502	Check if the device supports Google Play Services . It 's best practice to check first rather than handling this as an error case .
23537	Adds a core command tag changer to the configuration controller . This changers should never fail to maintain a proper state of the DAQ .
23540	Return a collector that creates a LinkedHashMap using the given key and value functions . This collector assumes the elements being collected are distinct .
23565	Should be used when need to define whether spawn will be deleted after death Using this method spawns will not be saved with //save_spawn command
23666	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML recommendation .
23668	Simple hard assertion that checks the value of the provided condition . If the condition is false , assertion marks whole test as failed .
23729	You can not destroy % 0 because it is used in the `` % 1 '' quest which can not be abandoned once started .
23915	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
23971	Queries for a provider . This may return if no provider has been registered for a service . The highest priority provider is returned .
23999	Gets the set of labels required at the time of matching the vertex in a Cypher MATCH pattern . This implementation returns no labels .
24078	Load < code > persistentProperties < /code > and any hard coded fields from an apache config object for use by the spark executor .
24213	Creates an updater for objects with the given field . The Class argument is needed to check that reflective types and generic types match .
24425	Implement buffering on top of the < code > read < /code > method of the wrapped < code > ServletInputStream < /code > .
24483	Load by uri , please using load ( string id ) , it also auto check the id is id '' or a uri .
24688	If the exception is a NullPointerException or IllegalArgumentException , wrap it in an InvalidObjectException and throw that , otherwise rethrow the exception as is .
24873	Indicates whether data should be approved for this data set , i.e . whether this data set is part of a data approval workflow .
25067	Create a DataProvider that specifies in which country a specific circuit can be found ( specify that Monza is in Italy , for example )
25365	Returns true if the specified attribute it a URI and should be escaped appropriately . In HTML URIs are escaped differently than normal attributes .
25496	Indicates whether this query requires aggregation of data . No aggregation takes place if aggregation type is none or if data type is text .
25518	Throws an exception if the current token is not an identifier . Otherwise , returns the identifier string and moves to the next token .
25546	Positions the scan before the first record , which in this case means positioning the index before the first instance of the selection constant .
25592	Check if an end of stream marker was added to the stream A stream with an end of stream marker can not be appended to
25654	Whether the tile zoom animation is enabled . By default it 's enabled in all browsers that support CSS3 Transitions except Android . default true
25895	Verifies that real and imaginary parts of the two complex arguments are exactly the same . Also ensures that NaN / infinite components match .
25915	Keep removing refs from the queue , clearing them , and removing them from the refs list , until the refs list is empty .
25960	Returns a UUID that sorts less than or equal to all RFC 4122 timestamp UUIDs ( version = 1 , variant = 2 ) .
26188	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
26213	Thrown when the VM notices that a program tries to reference , on a class or object , a method that does not exist .
26293	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
26445	Returns a set of members of this object . The set is ordered , and the order is in which the elements were added .
26511	< p > Subtracts the value of another fraction from the value of this one , returning the result in reduced form. < /p >
26597	Return distinct values of the given value . This is typically used within aggregates , for example : max ( distinct ( path ) )
26613	< code > subtract < /code > subtracts the given x , y values from those of this vector creating a new vector object .
26782	Hint : Required method ; if java had a way of allocating a generic I could move this method into the adapter . : (
26833	Rotate the region around the specified point . < p > The instance is not modified , a new instance is created. < /p >
27246	For each of an array of angles ( in radians ) , return the equivalent angle in the range [ -PI , PI ] .
27402	For every method , this calls parseMethod , storing the list of Instructions in the method_info object , and also constructs the corresponding CFG .
27732	Verifies that the two arguments are exactly the same , either both NaN or infinities of same sign , or identical floating point values .
27778	You have used up your daily quota of % num0 Support Petitions . You can not make any more inquiries with this account today .
27806	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
27825	Feature switch for initial load entries augmentation ( creation of partition-specific query for entries ) Defaults to < code > true < /code > .
28247	Returns a TimeZone object based upon a time zone ID . Method defaults to server 's time zone if tzID is null or empty .
28399	Set it to false if you do n't want the map to zoom beyond min/max zoom and then bounce back when pinch-zooming . default true
28524	Apply some predicate on all group member 's objects < br > Should be used only to change state of the group or its members
28826	Send a no-args command , or a command taking just indexName which is automatically added ( e.g. , commit , closeIndex , startIndex ) .
28869	Removes the specified permission from this attachment . < p > If the permission does not exist in this attachment , nothing will happen .
28937	Checks if the < code > unsigned short < /code > < code > item < /code > is a member of this list .
28940	Returns this object . This method prevents a subclass from declaring a < code > writeReplace < /code > method with an alternate implementation .
28992	Sort two arrays simultaneously , using the sort order of the values in the first array to determine the sort order for both arrays .
29186	Clears the current node , by removing the NamedateBundle associated to this Node and the links to all the other nodes from this one .
29202	Judge the passed in column is an id column or not . The column named id or _id will be considered as id column .
29281	filters out Locals. < br > returns < code > null < /code > if < code > val < /code > is null .
29342	Finds the closest matching segments among the given list of edges for the given dragged edge , and returns these as a list of matches
29359	Tests whether this audio input stream supports the < code > mark < /code > and < code > reset < /code > methods .
29504	This attribute is only for exception rules . If true - do not use url blocking rules for urls where referrer satisfies this rule .
29712	This method is used to translate from 'Old ' binary fifo to new tri-state fifo . false means no fifo , true means always .
29731	Check whether this alive timer is currently active . An alive timer is considered active it has been started and has not expired yet .
29733	true - text of comment will be visible to the user false - text of comment will be invisible to the user ( default )
29737	When TombStones are Dead , first Door opens 457 = First Door in Tormet > 118 after second Boss 64 = Second Door in Terror
29825	Create a new child instance . < p > Custom implementations should override this method to return a new instance of the appropriate type .
29862	Write a newline at the end of the document . < p > Pass the event on down the filter chain for further processing .
29942	Creates a JNDI API InitialContext object if none exists yet . Then looks up the string argument and returns the associated JMS administrated object .
29992	Method called when the field has been selected from a combo box and may need to be initialised Will be be overridden if necessary .
30043	Java main to test creating events in elasticsearch . Set the following ENV VARS to point to a local ES running in OpenShift PIPELINE_ELASTICSEARCH_HOST=elasticsearch.vagrant.f8 ELASTICSEARCH_SERVICE_PORT=80
30052	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
30153	Close the consumer if : a. the connection is dropped b. connection is open ( graceful close ) and there are no pending message acks
30544	Returns true if the specified character is a valid name start character as defined by production [ 4 ] in the XML 1.1 specification .
30588	Return constant value as a string . If the constant type is varchar , the output string will be surrounded by single quotation marks .
30715	Returns an instance equivalent to this one but with a different work tree . This does not initialize or alter the given work tree .
30777	You have joined the private channel % 1 at Channel % 0 . Confirm if you selected the channel in the chatting tab option .
30986	Reads in a json-formatted file and creates a TableMetadata instance from it . Files are expected to be in the format provided by TableMetadata }
31190	Check if the < code > set < /code > method for the given data field can accept values of a given target type .
31237	You have joined the private channel % 1 at Channel % 0 . Confirm if you selected the channel in the chatting tab option .
31268	Java main to test creating events in elasticsearch . Set the following ENV VARS to point to a local ES running in OpenShift PIPELINE_ELASTICSEARCH_HOST=elasticsearch.vagrant.f8 ELASTICSEARCH_SERVICE_PORT=80
31435	Shows a dialog used to accept input for editing a ray . < p > Returns null if the dialog is closed or canceled .
31437	method that will return whether the permission is accepted . By default it is true if the user is using a device below version 23
31439	This method always throws < code > UnsupportedOperationException < /code > since < code > FileJoinAdminState < /code > should never update a log .
31467	Return a character value for the < code > read ( ) < /code > method . < p > This implementation returns zero .
31623	Required becuse we use this in the UniqueRepoQueue and in a few other places to ensure we do n't add multiples of the same repo
31965	ID of the user whose friend request is to be declined or who is to be deleted from the current user 's friend list .
31998	Add the specified gating sequences to this instance of the Disruptor . They will safely and atomically added to the list of gating sequences .
32214	Checks whether the input stmt is an implicit break/continue A abrupt stmt is implicit if the SETLabelNode is null or the label.toString results in null
32293	Returns true if the specified constraint either implements RelativeTimeConstraint or is an instance of ConstraintAlternatives with elements that implement RelativeTimeConstraint , and false otherwise .
32318	Registers the path of a source folder that has been incorrectly generated outside of the default location ( $ { buildDir } /generated . )
32431	Default way of leaving a BPMN 2.0 activity : evaluate the conditions on the outgoing sequence flow and take those that evaluate to true .
32435	Whether to fill the path with color . Set it to false to disable filling on polygons or circles . < /br > default true
32459	This method creates the object of type clazz within context defined by the top web element and the frame path provided as the parameter .
32717	Does the escaping of tag values . This function assumes you 'll put double quotes ( ' '' ' ) around your tag value .
32935	Returns the current stream as a hexadecimal string of values . Shows the entire stream , and the remaining data at the current position .
32986	Looks up a given ( undirected ) edge in a selected graph . The edge is described based on the label of its vertices .
33056	Returns true if the specified character is a valid name start character as defined by production [ 4 ] in the XML 1.1 specification .
33192	Retrieves the hash code for this modification . The hash code returned will be the hash code for the attribute included in this modification .
33420	Returns a copy of this year-month with the new year and month , checking to see if a new object is in fact required .
33460	Returns < CODE > true < /CODE > if the attribute has an image syntax and < CODE > false < /CODE > otherwise .
33649	Reports whether or not this < code > DropTarget < /code > is currently active ( ready to accept drops ) . < P >
33684	Adds a button listener . All the button listeners will be notified when the buttons are clicked ( by the user or programmatically ) .
33693	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
33823	Specifies the password to unlock the keystore . Defaults to no password . The password will be cleared after the keystore has been loaded .
33915	Determines if a method has a `` similar '' signature , especially if wrapping primitive argument types would result in an exactly matching signature .
33965	Update whether the device is very small , i.e . Notifications can be in both the top and the bottom stack at the same time
34064	Certain logging behaviors are available for debugging beyond those that should be enabled in production . Enables a particular extended logging in the sdk .
34104	Checks if this year is equal to another year . < p > The comparison is based on the time-line position of the years .
34115	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
34134	Returns < code > false < /code > since this < code > ImageInputStream < /code > does not maintain a main memory cache .
34172	Specifies an attribute filter which will be used to determine which attributes will be compared . By default only user attributes will be compared .
34206	Serializes an < code > XMPMeta < /code > -object as RDF into an < code > OutputStream < /code > with default options .
34247	Add an extension with the given oid and the passed in byte array to be wrapped in the OCTET STRING associated with the extension .
34286	Puts a new key-value pair into this dictionary . If key or value are null , no operation will be performed on the dictionary .
34311	Invoke this method if you 've totally changed the children of node and its children 's children ... This will post a treeStructureChanged event .
34319	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
34406	Checks whether or not the specified < CODE > SampleModel < /CODE > is compatible with this < CODE > ColorModel < /CODE > .
34410	Adds a button listener . All the button listeners will be notified when the buttons are clicked ( by the user or programatically ) .
34535	This method create nre properties from the origianl one and remove any key with the password , then call toString method on this prperties .
34606	Returns < code > true < /code > if OpenAM policy data is migrated to a form that entitlements service can operates on them .
34640	Prints a message to the console debug file . The message will only be written if the the debug level is set to Error .
34991	Converts all of the characters in this < code > String < /code > to upper case using the rules of the given locale .
35014	This is called from Component by way of reflection . Do NOT change the name unless you change the code in Component as well .
35029	Process the attributes , which means to write out the currently collected attributes to the writer . The attributes are not cleared by this method
35119	Returns the encoded URL , rewritten to include the session id . Cookie will be written to the URL in as a query string .
35167	Reduces the number of points in a polyline while retaining its shape , giving a performance boost when processing it and also reducing visual noise
35176	read ( ) is implemented using read ( byte [ ] , int , int ) so subclasses only need to override the latter .
35180	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
35361	Get an observable that observes all events that are send with the key and are of the type of the event class < p >
35408	Generate a key parameter for use with a MAC derived from the password , salt , and iteration count we are currently initialised with .
35416	Returns a copy of this duration multiplied by the scalar . < p > This instance is immutable and unaffected by this method call .
35439	Returns the current number of permits available in this semaphore . < p > This method is typically used for debugging and testing purposes .
35467	Sets whether the parent 's environment variables should be inherited by the child process . Defaults to < code > true < /code > .
35582	Find a vacant area that will fit the given bounds nearest the requested cell location . Uses Euclidean distance to score multiple vacant areas .
35639	Return the error page entry for the specified HTTP error code , if any ; otherwise return < code > null < /code > .
35768	Chekcs if the attribute is a service identifier ( i.e. , in the case of LDAP it would be the COS Specifier attribute ) .
35806	Updates the barcode instance from the detection of the most recent frame . Invalidates the relevant portions of the overlay to trigger a redraw .
35848	Report an internal entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
36057	Generates a String representation of a Java Date object . The string is formatted according to the specification for GnuStep ASCII property list dates .
36125	< p > If true , the proxy is for an MXBean , and appropriate mappings are applied to method parameters and return values .
36408	Closes this stream . If this stream is connected to an input stream , the input stream is closed and the pipe is disconnected .
36498	Writes a message to the access logger with information about the search result entry that matches the criteria associated with the provided search operation .
36508	Convert dp to pixel . Preserve the negative value as it 's used for representing MATCH_PARENT ( -1 ) and WRAP_CONTENT ( -2 ) .
36626	Add an extension with the given oid and the passed in byte array to be wrapped in the OCTET STRING associated with the extension .
36958	Flushes this stream to ensure all pending data is written out to the target stream . In addition , the target stream is flushed .
37015	Try the best we can to convert a Java encoding to a XML-style encoding . < p > This is not a public API .
37056	Shows a region of a previously rendered component . This will return true if successful , false otherwise . The default implementation returns false .
37087	Calculates the dot product of this vector with another . The dot product is defined as x1*x2+y1*y2+z1*z2 . The returned value is a scalar .
37271	Returns a cookie with a specified name and value and sets a path for the cookie to which the client should return the cookie .
37326	The Dictionary can take up a lot of memory , so we restart the server to implicitly unregister the validator and free the memory .
37350	Returns < CODE > true < /CODE > if the Security was enabled for replication and < CODE > false < /CODE > otherwise .
37351	Constructs a cookie with a specified name and value and sets a path for the cookie to which the client should return the cookie .
37388	The read request will lookup the relationshipField and ask for the reverse property to validate its setting is compatible with the requested relationship field .
37563	Moves the longest-waiting thread , if one exists , from the wait queue for this condition to the wait queue for the owning lock .
37604	Initialize this object for signing . If this method is called again with a different argument , it negates the effect of this call .
37640	Initialize this object for signing . If this method is called again with a different argument , it negates the effect of this call .
37757	Paints the border of the content area of a tool bar . This implementation invokes the method of the same name without the orientation .
37913	Returns a copy of this formatter with a new DecimalStyle . < p > This instance is immutable and unaffected by this method call .
38195	Find a vacant area that will fit the given bounds nearest the requested cell location . Uses Euclidean distance to score multiple vacant areas .
38235	Determines the next object by invoking < code > updateNextIndex < /code > and if not succesful < code > findNextValidParent < /code > .
38321	Tell if the current template rule is null , i.e . if we are directly within an apply-templates . Used for xsl : apply-imports .
38527	Searches for people containers in this organization using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
38764	Returns true if the specified character is a valid NCName character as defined by production [ 5 ] in Namespaces in XML 1.1 recommendation .
38832	Returns the value of the < code > topDown < /code > parameter . The default is < code > false < /code > .
38902	Returns < code > true < /code > if the writer can write out images as a series of passes of progressively increasing quality .
39150	Downloads content from the specified url using specified proxy ( or do not using it ) . Returns null if there 's an error .
39204	Resets this stream to the beginning of the underlying byte array . All subsequent writes will overwrite any bytes previously stored in this stream .
39283	Interrupts the reading of the output ( or error ) of the process . The method does not return until the reading is over .
39338	Returns a query expression that represents a matching constraint on a string argument . The value must end with the given literal string value .
39358	Paints the tool bar 's border if the < code > borderPainted < /code > property is < code > true < /code > .
39369	Determines if a method has a `` similar '' signature , especially if wrapping primitive argument types would result in an exactly matching signature .
39492	Searches for users in this organizational unit using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
39525	Show the loading view . No animations , because sometimes loading things is pretty fast ( i.e . retrieve data from memory cache ) .
39629	I should make the corners all ints and lines join at corners It kind of work at the beginning ... but then it falls apart
39732	Returns < code > true < /code > if the data store supports authentication of identities . Used by IdRepo framework to authenticate identities .
39765	Indicates whether this entry meets the criteria to consider it an LDAP subentry ( i.e. , it contains the `` ldapSubentry '' objectclass ) .
39985	Formats an LDAP filter using the provided template and assertion values . Values will be safely escaped in order to avoid potential injection attacks .
40052	Parse the content of the specified input stream using this Digester . Returns the root element from the object stack ( if any ) .
40267	Inserts the specified text at the specified position . Does nothing if the model is null or if the text is null or empty .
40280	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
40638	Flushes this stream to ensure all pending data is sent out to the target stream . This implementation then also flushes the target stream .
40979	Notifies all listeners that the value of the cell at < code > [ row , column ] < /code > has been updated .
41040	Returns true if the specified character is a valid NCName character as defined by production [ 5 ] in Namespaces in XML 1.1 recommendation .
41249	Regrettably , serializing a TreeSet causes it to forget its bounds . This is unlike a serialized TreeMap which retains its bounds when serialized .
41336	Creates a new color object from an integer that contains the blue , green , and red bytes in the lowest order 24 bits .
41384	Generate a key parameter for use with a MAC derived from the password , salt , and iteration count we are currently initialised with .
41427	Removes any white space from a string . This is used to convert strings such as `` Windows NT '' to `` WindowsNT '' .
41477	Invokes when the FM received the Single-Sign-On and Federation response from the IDP , this is called before any processing started on SP side .
41573	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML recommendation .
41657	Removes any descendants of the < code > TreePaths < /code > in < code > toRemove < /code > that have been expanded .
41685	Returns true if the popup menu is a standalone popup menu rather than the submenu of a < code > JMenu < /code > .
41807	The static flag of a class is n't stored in the classfile 's access flags ; instead , its stored in the InnerClasses attribute .
41956	Mark a component completely dirty . < b > aComponent < /b > will be completely painted during the next paintDirtyRegions ( ) call .
42062	Shows the button . < p > This method will animate the button show if the view has already been laid out. < /p >
42074	Create Tag Field using ogg key This method is provided to allow you to create key of any value because VorbisComment allows arbitary keys .
42087	Checks if this instant is before the specified instant . < p > The comparison is based on the time-line position of the instants .
42110	Create a new child instance . < p > Custom implementations should override this method to return a new instance of the appropriate type .
42187	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML recommendation .
42266	Attempts to remove the parameter from the local collection . This method < i > does not < /i > modify the default collection .
42785	Wrap the specified clear byte array using the provided offset and length values . Used only when the SASL server has negotiated confidentiality/integrity processing .
42918	Since this object is incomplete without the length and the offset , we have to convert to a string when this function is called .
43024	Decodes a URL safe string into its original form using the default string charset . Escaped characters are converted back to their original representation .
43134	Defined in rfc 2617 as KD ( secret , data ) = H ( concat ( secret , `` : '' , data ) )
43141	The background color , foreground color , and font are already set to the defaults from the defaults table before this method is called .
43168	Creates a condition which evaluates to < code > true < /code > if and only if a particular property has any values specified .
43216	Checks if this instant is after the specified instant . < p > The comparison is based on the time-line position of the instants .
43235	Return a byte value for the < code > read ( ) < /code > method . < p > This implementation returns zero .
43282	Returns the unsigned remainder from dividing the first argument by the second where each argument and the result is interpreted as an unsigned value .
43325	Try the best we can to convert a Java encoding to a XML-style encoding . < p > This is not a public API .
43327	Registers a < code > ScriptEngineFactory < /code > to handle a language name . Overrides any such association found using the Discovery mechanism .
43431	Sets the size limit for the query request . Defaults to 0 . The size limit will be enforced by the underlying backend technology .
43457	Report an internal entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
43502	Paints the progress bar 's border if the < code > borderPainted < /code > property is < code > true < /code > .
43572	Retrieves the next attribute in this < code > SQLInputImpl < /code > object as a < code > java.sql.Timestamp < /code > object .
43576	Returns the hash code for this DIT content rule . It will be calculated as the hash code of the structural object class OID .
43654	Returns a clone of this enumeration value , which to preserve the semantics of enumeration values is the same object as this enumeration value .
43735	Return the node at the top of the stack without popping the stack . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
43800	Removes an acquired lock from the lock manager . If the lock did not exist in the lock manager the operation is a no-op .
44012	Generate a key parameter for use with a MAC derived from the password , salt , and iteration count we are currently initialised with .
44081	Get an observable that observes all events that are send with the key and are of the type of the event class < p >
44243	Called from calculate_doors ( ) . The shape of the room p_result may change inside this function . Wow ... . pippo interesting ... .
44325	Moves the longest-waiting thread , if one exists , from the wait queue for this condition to the wait queue for the owning lock .
44346	Paints the border of the content area of a tool bar . This implementation invokes the method of the same name without the orientation .
44408	Create Tag Field using ogg key This method is provided to allow you to create key of any value because VorbisComment allows arbitary keys .
44452	A < code > ListSelectionListener < /code > that forwards < code > ListSelectionEvents < /code > when there is a column selection change .
44541	Determines whether an SSL client with the provided certificate chain should be trusted . In this case , all client certificates will be trusted .
44596	Searches for users in this people container using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
44700	Indicates whether this < code > Timestamp < /code > object is earlier than the given < code > Timestamp < /code > object .
44757	Generate a key parameter for use with a MAC derived from the password , salt , and iteration count we are currently initialised with .
44769	Tests a given String to see if it contains only valid characters within the Base64 alphabet . Currently the method treats whitespace as valid .
44865	Searches for people containers in this organization using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
44886	Returns a string containing a concise , human-readable description of this object . In this case , the enum constant 's name is returned .
45163	Creates and returns a new ComponentHandler . This is used for the large model to mark the validCachedPreferredSize as invalid when the component moves .
45173	Deregisters the provided log retention policy with the Directory Server . If no such policy is registered , then no action will be taken .
45182	Use this static method for getting the Objectify service object in order to make sure the above static block is executed before using Objectify .
45185	Paints the popup menu 's border if the < code > borderPainted < /code > property is < code > true < /code > .
45215	Ensures that < code > offset < /code > is a valid offset into the model for < code > text < /code > .
45286	Hides the button . < p > This method will animate the button hide if the view has already been laid out. < /p >
45398	Removes the attribute with the specified name ( key ) from this Map . Returns the previous attribute value , or null if none .
45572	Check if this class is one of the supported types . If the class is supported , returns true . Otherwise , returns false .
45607	Replace colon to make the name more Windows friendly . e.g . `` 12:00 A.M.-1:00 A.M. '' - > `` 12.00 A.M.-1.00 A.M . ''
45622	Returns true if the specified arguments are equal , or both null . NB : Do not replace with Object.equals until JDK-8015417 is resolved .
45634	Puts all tree entries overlapping with p_shape on layer p_layer into the list p_risul_tree . If p_layer < 0 , the layer is ignored .
45850	Waits for an incoming request and blocks until the connection is opened . This method returns a socket object representing the just opened connection .
46023	Returns true if a single sign on token is valid . Your token may have its idle time reset . You have been warned .
46101	Creates an argument exception which should be used when an attempt is made to set the naming property for a managed object during creation .
46156	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
46175	Registers a < code > ScriptEngineFactory < /code > to handle a mime type . Overrides any such association found using the Discovery mechanism .
46202	Create a new child DN from a given parent DN . The child RDN is formed from a given attribute type and string value .
46498	Get an observable that observes all events that are send with the key and are of the type of the event class < p >
46513	Returns a read only JEditorPane containing the provided text with the provided font . The JEditorPane will assume that the text is HTML text .
46707	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
46723	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
46930	Return true if an accurate address can be determined for this host . If false , reliable VMID can not be generated from this host
47004	Obtains the secondary order of the specified collation element , i.e . the 16th to 23th bits , inclusive . This value is unsigned .
47030	Creates and initializes the components which make up the aggregate combo box . This method is called as part of the UI installation process .
47090	The aggregate components which comprise the combo box are unregistered and uninitialized . This method is called as part of the UI uninstallation process .
47284	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
47327	Returns true if the specified character is a valid name start character as defined by production [ 5 ] in the XML 1.0 specification .
47362	Indicates whether the specified entry exists in the Directory Server . The caller is not required to hold any locks when invoking this method .
47436	Called when a fragment is being created as part of a view layout inflation , typically from setting the content view of an activity .
47445	Returns the length of the year . < p > This returns the length of the year in days , either 365 or 366 .
47458	Returns an unmodifiable list containing the set of available alias dereferencing policies indexed on their integer value as defined in RFC 4511 section 4.5.1 .
47533	Returns true if the specified character is a valid name start character as defined by production [ 5 ] in the XML 1.0 specification .
47594	Checks if this chronology is equal to another chronology . < p > The comparison is based on the entire state of the object .
47670	Adds a button listener . All the button listeners will be notified when the buttons are clicked ( by the user or programatically ) .
47709	Search for the next method invocation that we 've traced , stopping when we reach an event with an instruction on a different line .
47878	Allows the timer MBean to perform any operations it needs before being unregistered by the MBean server . < P > Stops the timer .
48200	Moves the longest-waiting thread , if one exists , from the wait queue for this condition to the wait queue for the owning lock .
48391	Pushes the specified amount of characters back into the input stream . They will be read again by then next call of the scanning method
48764	The method is called when all identities in the repository are changed . This could happen due to a organization deletion or permissions change etc
48860	Returns the next attribute name , or null if the input has been exhausted . Returns wth the cursor on the delimiter that follows .
49033	Messaged when this node is removed from its parent , this messages < code > removedFromMapping < /code > to remove all the children .
49103	Returns the encoded URL , rewritten to include the session id . Cookie will be written to the URL in as a query string .
49242	Returns a hash code for this byte string . It will be the sum of all of the bytes contained in the byte string .
49252	Returns the length of the epochMonth . It is computed from the start of the following month minus the start of the requested month .
49469	Returns < CODE > true < /CODE > if the server start Id was found and < CODE > false < /CODE > otherwise .
49488	Moves the longest-waiting thread , if one exists , from the wait queue for this condition to the wait queue for the owning lock .
49666	Indicates whether the specified entry exists in the Directory Server . The caller is not required to hold any locks when invoking this method .
49837	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
49840	Remove the error page for the specified error code or Java language exception , if it exists ; otherwise , no action is taken .
50100	Enqueues a TopologyMsg for all the connected directory servers in order to let them know the topology ( every known DSs and RSs ) .
50226	Parse the content of the specified input source using this Digester . Returns the root element from the object stack ( if any ) .
50273	Returns < CODE > true < /CODE > if the index is a VLV index and < CODE > false < /CODE > otherwise .
50537	Load data from URL . url must be not null . Note , this method does n't check if data or url is null .
50580	Converts all of the characters in this < code > String < /code > to upper case using the rules of the given locale .
50642	Indicates whether the Directory Server is configured with information about one or more mail servers and may therefore be used to send e-mail messages .
50790	Return the error page entry for the specified Java exception type , if any ; otherwise return < code > null < /code > .
50865	Method will be called only if object to retain is not yet created , or loader was recreated i.e . because of app process recreation
50924	Validates if the Jwt Session Cookie is valid and the idle timeout or max life has expired . Calls into the underlying Jaspi module .
50979	Returns the first tab index with a given < code > title < /code > , or -1 if no tab has this title .
51033	Called when a fragment is being created as part of a view layout inflation , typically from setting the content view of an activity .
51156	Creates a Finder instance that returns an injected instance of a resource . Prevents multiple instances of the same resource class being created unnecessarily .
51292	Searches for users in this people container using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
51465	Check that the encoding decoding of historical information works by encoding decoding and checking that the result is the same as the initial value .
51658	Called when a fragment is being created as part of a view layout inflation , typically from setting the content view of an activity .
51693	Decides if the messageReceived should be invoked will always return false since we rely on the lazy map to do all the messaging for us
51888	Tells whether the provide index name corresponds to a database index or not . Database indexes are not modifiable and for internal use only .
51892	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
51946	Presents the QueryBuilder in a human readable format . Note : This function is not performant and should only be used for debugging purposes .
52047	Is the transition local time midnight at the end of day . < p > The transition may be represented as occurring at 24:00 .
52064	Deregisters the provided log rotation policy with the Directory Server . If no such policy is registered , then no action will be taken .
52201	the zookeeper is first create , if interrunpted , I will retry , if throws the zookeeper exception , I will re new the zkconfig
52380	Add a filter mapping to this Context before the mappings defined in the deployment descriptor but after any other mappings added via this method .
52404	Returns true if the specified character is a valid name start character as defined by production [ 5 ] in the XML 1.0 specification .
52489	Release any resources held by this engine . Returns the stream allocation held by this engine , which itself must be used or released .
52811	Searches for the first occurence of the given argument , beginning the search at index , and testing for equality using the equals method .
52846	Executes task r in the caller 's thread , unless the executor has been shut down , in which case the task is discarded .
53233	Check if the Double Metaphone values of two < code > String < /code > values are equal , optionally using the alternate value .
53271	Searches for users in this organizational unit using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
53282	Search the given ClassLoader for an instance of the specified class and return a string representation of the URL that points to the resource .
53283	Prints a message to the console debug file . The message will only be written if the the debug level is set to Error .
53338	Queries for a provider . This may return if no provider has been registered for a service . The highest priority provider is returned .
53396	Returns a query expression that represents a matching constraint on a string argument . The value must start with the given literal string value .
53481	Pad strings or numbers with given characters ( ' 0 ' by default ) . e.g . `` 1 '' - > `` 01 ''
53700	Ascertains whether the last value read from this < code > SQLInputImpl < /code > object was < code > null < /code > .
53757	Clones the password . The resulting clone will be completely independent of the parent , which means it will have to be separately cleared .
53782	Called when the component containing the caret gains focus . This is implemented to set the caret to visible if the component is editable .
53814	Returns true if this is a directory entry . A directory entry is defined to be one whose name ends with a '/ ' .
53972	Forcefully removes any resource bundles associated with the provided definition and locale . < p > This method is intended for internal testing only .
54035	Returns a copy of this date-time with the new date and time , checking to see if a new object is in fact required .
54328	Return the node at the top of the stack without popping the stack . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
54527	Indicates whether this < code > Timestamp < /code > object is later than the given < code > Timestamp < /code > object .
54766	Retrieves the hash code for this stack frame . It will be the sum of the hash codes for the class and method name .
54827	Replace slash and backslash to make sure the result is not a file path . e.g . `` V_MPEG4/ISO/AVC '' - > `` V_MPEG4.ISO.AVC ''
54916	Indicates whether the provided attribute type is in the list of required or optional attributes for this objectclass or any of its superior classes .
55088	Report an internal entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
55091	Formats a date-time object using this formatter . < p > This formats the date-time to a String using the rules of the formatter .
55118	Removes the specified permission from this attachment . < p > If the permission does not exist in this attachment , nothing will happen .
55139	Indicates whether the user 's password has been administratively reset and the user must change that password before any other operations will be allowed .
55254	Set the attribute names to return , if any specific attributes are required to be pulled back from this query in their result entries .
55328	Request the Image or ImageProducer to start delivering pixels and wait for all of the pixels in the rectangle of interest to be delivered .
55468	Executes task r in the caller 's thread , unless the executor has been shut down , in which case the task is discarded .
55524	Update the Server State with a CSN . All operations with smaller CSN and the same serverID must be committed before calling this method .
55553	Called for entries that have reached the tail of the least recently used queue and are be removed . The default implementation does nothing .
55578	Currently drills are allowed to SMD-pins . Returns true , if vias throw the pads of this pins are allowed , false , otherwise .
55779	Returns true if the specified character is a valid name start character as defined by production [ 4 ] in the XML 1.1 specification .
55798	When performing an accessibility drop , onDrop is sent immediately after onDragEnter . So we need to complete all transient states based on timers .
55850	Returns a String representation of the < code > LogoutResponse < /code > object . This method translates the response to an XML string .
55871	Send a < code > Notification < /code > which contains the specified string as a < code > jmx.modelmbean.generic < /code > notification .
55895	Increments the cumulative count of evaluations and recalculates the rate . < br/ > Only synchronizes the count increment , NOT the whole method .
55944	Reads one byte . If there is no data in the underlying buffer , this operation can block until the data will be available .
55996	add attribute to the wrapped component with the input < code > key < /code > and < code > value < /code > .
56076	Determines the next object by invoking < code > updateNextIndex < /code > and if not succesful < code > findNextValidParent < /code > .
56105	Used internally to reload the script back when coming back from the persisted state ( therefore we do n't want to record this . )
56186	Searches for the first index of the specified character . The search for the character starts at the beginning and moves towards the end .
56214	Adds a table sort key . The table will be sorted according to the case-insensitive string ordering of the cells in the specified column .
56296	Decodes the contents of the provided entry as a recurring task . The resulting recurring task will not actually be added to the scheduler .
56308	Tells you if the last footer needs to be skipped ( for instance if the footer says `` continued on the next page '' )
