25	Determine whether the given class has a method with the given signature . < p > Essentially translates < code > NoSuchMethodException < /code > to `` false '' .
26	Verifies that there is at least one principal , that none of the principals is < code > null < /code > , and that there are no duplicates .
494	Extract location information from an Element node , and create a new SimpleLocator object from such information . Returning null means no information can be retrieved from the element .
883	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
926	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
1207	Checks the return type of the elements in the provided list . < p/ > Raises an exception if any element specifies a return type other than 'void ' .
1215	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
1362	Identifier of an album owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
1377	Computes the Kendall 's Tau rank correlation matrix for the columns of the input rectangular array . The columns of the array represent values of variables to be correlated .
2048	Add this CP to the list of interfaces supposedly implemented by this class . Note that the CP ought to be a ClassCP to make sense to the VM .
2443	Limit of number of returned ads . Used only if `` ad_ids '' parameter is 'null ' , and `` campaign_ids '' parameter contains ID of only one campaign .
2498	Joins together the results from three patterns via their plans . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
2741	Joins together the results from two patterns via their plans . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
2804	Process a new response from the license server . Since we are n't performing any caching , this equates to reading the LicenseResponse . Any ResponseData provided is ignored .
3144	Checks if the element we 're searching for is represented by a file. < br > e.g . a java class PSI element , or an actual PsiFile element .
3459	Inserts an array of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
3553	Asserts that the given object is not < code > null < /code > . If this is not the case , some kind of unchecked exception is thrown .
3727	Joins together the results from four patterns via their plans . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
4173	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
4440	Called each frame . Not abstract so that the button can be used without it being drawn and simply as a way to test for input within certain bounds .
4541	Disconnect all consumers on this dispatcher ( server side close ) . This triggers channelInactive on the inbound handler which calls dispatcher.removeConsumer ( ) , where the closeFuture is completed
4684	Maximum pokemon level for a trainer , from the trainer level . That 's usually trainerLevel + 1.5 , but the maximum is 40 ( http : //pokemongo.gamepress.gg/power-up-costs ) .
4981	Updates the Android Gradle 'experimental ' plugin version , and optionally the Gradle version of a given project . This method notifies the user if the version update failed .
5311	Set the periodic ownership sync interval in milliseconds . If periodic handshake is enabled , the handshake will sync ownership if the elapsed time is larger than sync interval .
5511	Asserts the next message is equals to a string literal . < p > This is a convenience method to avoid having to escape special characters in the regex .
5661	Determine context has access to the given permission . This is a workaround for RuntimeException of Parcel # readException . For more detail , check this issue https : //github.com/hotchemi/PermissionsDispatcher/issues/107
5687	Verifies that there is at least one principal , that none of the principals is < code > null < /code > , and that there are no duplicates .
5844	< code > dot < /code > calculates the dot product of this vector with a provided vector . If the provided vector is null , 0 is returned .
5856	Returns true if the specified < code > String < /code > matches any IANA-defined top-level domain . Leading dots are ignored if present . The search is case-insensitive .
5985	Blocking strategy for recursive calls -- Enable blocking strategy for recursive calls . Blocking strategy is a 1CFA model for recursive calls . This model significantly improves the precision .
6007	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
6059	Writes < code > len < /code > bytes from the specified byte array starting at offset < code > off < /code > to this buffered output stream .
6096	Clears both the memory and disk cache associated with this ImageCache object . Note that this includes disk access so this should not be executed on the main/UI thread .
6254	Marks the service ready for use . This method should only be called from the code that performs the service initialization , and it should only be called once .
6291	Removes the first occurrence of the specified element from this array , if it is present . If the array does not contain the element , it is unchanged .
6349	Clears both the memory and disk cache associated with this ImageCache object . Note that this includes disk access so this should not be executed on the main/UI thread .
6743	This method will write the data in thrift format to disk . This method will not be guided by parameter dictionary_one_chunk_size and complete data will be written as one chunk
6788	List of services or websites the update will be exported to , if the user has so requested . Sample values : `` twitter '' , `` facebook '' .
7089	Sets how much spaces should be used to indent each line . < p > The minimum value this may be is 2 , and the maximum is 9 .
7592	Checks if the partition has the given vertex ( labels in vertex ) . This implementation enforces at least one of the labels in partition is present in vertex .
7632	Gets how much spaces should be used to indent each line . < p > The minimum value this may be is 2 , and the maximum is 9 .
7663	Indicates whether the filters of this query spans more than one partition . If true it means that a period filter exists and that the periods span multiple years .
7725	If the aggregation being averaged is a sketch , it will become a sketch merge , and need to be estimated for summing to work at the outer level .
8058	Checks if the potion is in an upgraded state . This refers to whether or not the potion is Tier 2 , such as Potion of Fire Resistance II .
8397	Blocks concurrent calls to Space while clean is being performed . When clean operation will finish , a notifyAll ( ) will be invoked awakening all waiting concurrent operations .
8559	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
8602	Override the default behavior of the Android back button . If overridden , when the back button is pressed , the `` backKeyDown '' JavaScript event will be fired .
8798	Computes the covariance between the two arrays , using the bias-corrected formula . < p > Array lengths must match and the common length must be at least 2 .
8814	Create a wavefront compatible string representation of the metric value . If the metric value is empty or not representable in wavefront , an empty optional will be returned .
8957	Sets how much spaces should be used to indent each line . < p > The minimum value this may be is 2 , and the maximum is 9 .
8965	Record the event that one message has been processed by the application . Periodically , it sends a Flow command to notify the broker that it can push more messages
9115	Inserts an array of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
9187	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
9240	The URL to the retina sized version of the icon shadow image . If not specified , no shadow image will be created . Used for Retina screen devices .
9327	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
9368	Inserts a SparceArray of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
9400	Deletes all artifacts created by the TableSet during the run for the provided scan ID . This method should be called at some point after the scan is complete .
10232	Returns < code > true < /code > if < code > signature < /code > is the signature of the < code > java.lang.Object < /code > type .
10343	< p > Multiplies the value of this fraction by the passed < code > BigInteger < /code > , returning the result in reduced form . < /p >
11001	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
11226	< code > toString < /code > returns the string representation of this vector . The format is : < p/ > org.jme.math.Vector3f [ X=XX.XXXX , Y=YY.YYYY , Z=ZZ.ZZZZ ]
11376	Returns whether any data was returned . When a user requests too many cells/wrong cell level/cells too far away from the users location , the server returns empty MapCells .
11527	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
11564	Verifies that the activation identifier is not < code > null < /code > , and that the constraints on this invocation handler and the underlying proxy are consistent .
11587	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
11718	Sets the < code > include < /code > flag to false so that the manifest will < i > not < /i > contain information about this element .
11821	< code > dot < /code > calculates the dot product of this vector with a provided vector . If the provided vector is null , 0 is returned .
11982	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
11984	Sets or returns the ProtectionDomain of this class , called by getProtectiondomain . We need an artificial field variable to handle this . native void setProtectionDomain0 ( java.security.ProtectionDomain ) ;
12592	< code > toString < /code > returns the string representation of this object . The form is : `` Radius : RRR.SSSS Center : < Vector > '' .
12827	< p > Gets the fraction as a < code > BigDecimal < /code > . This calculates the fraction as the numerator divided by denominator . < /p >
13182	Decrement the numeric badge label . If the current badge label can not be converted to an integer value , its label will be set to `` 0 '' .
13259	< code > toString < /code > returns the string representation of this object . The form is : `` Radius : RRR.SSSS Center : < Vector > '' .
13321	Override default behavior to call normalize ( ) on this Node 's children . It is up to implementors or Node to override normalize ( ) to take action .
13339	Can be called on any thread . < p > Note : This method does not change the guiScoreDirector because that can only be changed on the event thread .
13887	Iterates over the predecessors of this instruction , and merges all the post-instruction register types for the given register . Any dead , unreachable , or odexed predecessor is ignored
14190	Returns the label corresponding to the given offset . The default implementation of this method creates a label for the given offset if it has not been already created .
14339	Creates the dialog . If the passed bridge instance needs to be destroyed after the dialog is finished , it should be taken care of in the callback implementation .
14443	Blocking strategy for recursive calls -- Enable blocking strategy for recursive calls . Blocking strategy is a 1CFA model for recursive calls . This model significantly improves the precision .
14798	Convert absolute pixels to scale dependent pixels . This scales the size by scale dependent screen density ( accessibility setting ) and the global display setting for message composition fields
14863	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
15347	Converts stressed phone to regular phone . This method merely removes the last character of the phone . Subclasses should override this if another method is to be used .
15521	Add a new row to the table and return the VisualItem for that row . Only allowed if there is no parent table , otherwise an exception will result .
15664	This method initializes and starts the AliveTimer . Since it 's initialized it periodically takes action to send AliveTag to TIM server ( using ProcessMessageSender 's JMS queue connection )
15679	Called each frame . Not abstract so that the button can be used without it being updated and simply as a way to test for input within certain bounds .
15947	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
16156	Add column to be either retrieve or deleted , if empty will either returns all elements in a find query or delete all elements in a column family entity .
16322	The equals ( ) method asked for by the Comparable interface . Returns true if the compared object is a FeatureComparator with the same internal index , false otherwise .
16888	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
16970	Returns whether a permission is enabled across Android . Not all permissions can be disabled globally , so the default is true , but can be overwritten in sub-classes .
17505	Limit of number of returned ads . Used only if `` ad_ids '' parameter is 'null ' , and `` campaign_ids '' parameter contains ID of only one campaign .
17548	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
17604	If we claimed a task but fail to execute it before the initial TTL then let it expire rather than holding onto it for an indeterminate amount of time .
17644	Add column to be either retrieve or deleted , if empty will either returns all elements in a find query or delete all elements in a column family entity .
17742	Function to synchronize adapter content loading . Call it every time , when part of content was loaded . When all content will be loaded IContentLoadListener callback will fire .
17785	Calculates the Glory Bonus Reward for Winner and Looser Team individually . 200 ( Win+BossKilled ) : 150 ( Win ) 125 ( Loss+BossKilled ) : 75 ( Loss )
17824	Focuses the EditText and makes the label visible without the normal animation that occurs on focus . This is particularly useful when auto-focusing the first field on a form .
18264	Creates a newly allocated byte array . Its size is the current size of this output stream and the valid contents of the buffer have been copied into it .
18272	Returns the forward transform of the specified integer data set.The integer transform can not be inverted directly , due to a scaling factor which may lead to double results .
18333	Returns the number string list of the given string starting at the given index . E.g. , expandNumberAt ( `` 1100 '' , 1 ) gives `` one hundred ''
18383	Remove an element described by ObjectInfo . [ Head ] - .. - [ beforeOi ] - [ oi ] - [ afterOi ] - .. - [ Tail ]
18449	Inserts a SparceArray of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
18569	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
18876	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
19127	Shows timing stats . If overall is non-zero , it represents the overall processing time and a percentage of overall time for this timer should be calculated and displayed .
19204	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
19317	Returns the first passed String if not null , otherwise the second if not null , otherwise the third if not null , otherwise an empty but non-null String .
19553	Returns true if the exception is a JsonProcessingException whose root cause is not a premature end of data , since this is more likely caused by a connection error .
19583	Consumes the current token if 'alwaysConsume ' is true or if it 's one of the expected types. < br > Otherwise , returns false and reports an error .
19826	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
19913	Returns the current execution stack as an array of classes . NOTE : an array of object may be created . protected native java.lang.Class getClassContext ( ) [ ] ;
20078	establishes parent-child ( if there is one ) relation between this and aq query the relation expresses the relative level of specificity between queries with the parent being more specific
20213	Positions to a DLSN greater than the current value - this may not correspond to an actual LogRecord , its just used by the positioning logic to position the reader
20266	Removes the comparable object from the tree returning true if the comparable was found and removed < p > If the given comparable is null , false is returned .
20272	Converts stressed phoneme to regular phoneme . This method merely removes the last character of the phone . Subclasses should override this if another method is to be used .
20398	Add attribute sets for the service . The resulting set will be used for all future joins . The attribute sets are also added to all currently-joined lookup services .
20609	Called after plugin construction and fields have been initialized . Prefer to use pluginInitialize instead since there is no value in having parameters on the initialize ( ) function .
20837	Returns true if the specified < code > String < /code > matches any IANA-defined top-level domain . Leading dots are ignored if present . The search is case-insensitive .
21870	Waits for all tasks to complete then shuts down the thread . Should be called when the cache is closed on server shutdown . Synchronized to prevent simultaneous start .
21876	Convert scale dependent pixels to absolute pixels . This scales the size by scale dependent screen density ( accessibility setting ) and the global display setting for message composition fields
22094	Gets how much spaces should be used to indent each line . < p > The minimum value this may be is 2 , and the maximum is 9 .
22297	Inserts a List of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
22306	Returns true if string s is letters only . NOTE : This should handle i18n version to support European characters , etc . since it now uses Character.isLetter ( )
22444	Return true if and only if this cap contains the given other cap ( in a set containment sense , e.g . every cap contains the empty cap ) .
22542	Joins together the results from several patterns via their plans . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
22603	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
22605	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
22970	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
23012	Consumes the current token if 'alwaysConsume ' is true or if it 's one of the expected types. < br > Otherwise , returns false and reports an error .
23112	Clears both the memory and disk cache associated with this ImageCache object . Note that this includes disk access so this should not be executed on the main/UI thread .
23175	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
23246	Can be used by your ICyberware implementation 's setQuality function . Helper method that writes a quality to an easily accessible NBT tag . See the partner function , readQualityTag
23337	Functional implementation . The actual calculation will only be performed if the input does n't match the input from the most recent invocation . Null inputs are never remembered .
23358	Joins together the results from several patterns via their plans . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
23590	Flags this object as being synchronized with the data source . The entity engine will call this method immediately after populating this object with data from the data source .
23808	Convert scale dependent pixels to absolute pixels . This scales the size by scale dependent screen density ( accessibility setting ) and the global display setting for message composition fields
24012	Number of communities to return . Note that you can not receive more than first thousand of results , regardless of `` count '' and `` offset '' values .
24051	Creates a newly allocated byte array . Its size is the current size of this output stream and the valid contents of the buffer have been copied into it .
24229	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
24296	Will be called by the EventLogImpl with events which the listener registered for . Since this will not be registered for any events , this will never be called .
24407	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
24972	Check if the given class represents an array of primitives , i.e . boolean , byte , char , short , int , long , float , or double .
25166	Hide the graphic when the corresponding object was not detected . This can happen for intermediate frames temporarily , for example if the object was momentarily blocked from view .
25432	Copy and convert bytes from an < code > InputStream < /code > to chars on a < code > Writer < /code > , using the specified encoding .
25616	Given the UserPage number , this method restrict it to be sure it 's an existing page . It takes care of using the user defined pages if any .
25678	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
26135	Inlines the method < code > inlinee < /code > into the < code > container < /code > at the point < code > toInline < /code > .
26270	There are 2 default activities : 1 - level . Works similar to secure.setUserLevel ; 2 - points , saves points amount Any other value is for saving completed missions
26491	Makes sure the media player exists and has been reset . This will create the media player if needed . reset the existing media player if one already exists .
26521	Returns the number string list of the given string starting at the given index . E.g. , expandNumberAt ( `` 1100 '' , 1 ) gives `` one hundred ''
26641	Handles a failed SendData request . This can either be because of the stick actively reporting it or because of a time-out of the transaction in the send thread .
26643	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
26763	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
26848	Assigns value to baseObjId . This will override the original value . < b > Never call this method unless you know exactly what you are doing. < /b >
26871	Calculate the frequency of the topline at time < code > time < /code > . This is calculated as a linear function of topStart , topEnd and time .
27113	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
27386	< code > toString < /code > returns the string representation of this vector object . The format of the string is such : com.jme.math.Vector2f [ X=XX.XXXX , Y=YY.YYYY ]
27615	Determines whether or not the Element is a concrete type . If the element is a generic type or contains generic type arguments , this method will return false .
28061	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
28133	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
28385	Make this element anonymous . Remove any < tt > id < /tt > or < tt > name < /tt > attribute present in the element 's attributes .
28745	Decrement the numeric badge label . If the current badge label can not be converted to an integer value , its label will be set to `` 0 '' .
29105	Inserts a List of Parcelable values into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
29216	Cancels the download . If a callback is associated to the download task , its onCancel ( ) method will be raised instead of the onComplete ( ) one .
29276	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
29352	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
29394	Returns a QueueReader object which will contain ONLY NEW methods which will be found to be reachable , but not those that have already been found to be reachable .
29402	Prepares for another batch of output . Larger groups of output ( such as all output associated with a single FreeTTSSpeakable ) should be grouped between a reset/drain pair .
29491	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
29518	Convert absolute pixels to scale dependent pixels . This scales the size by scale dependent screen density ( accessibility setting ) and the global display setting for message composition fields
29719	Creates a new page based on the provided values . name is omitted ( default one is set by AEM ) . During creation specified template is used in CreatePageWindow
30002	Calculate the frequency of the baseline at time < code > time < /code > . This is calculated as a linear function of baseStart , baseEnd and time .
30004	Verifies that there is at least one principal , that none of the principals is < code > null < /code > , and that there are no duplicates .
30293	Calculates the Abyss Bonus Reward for Winner and Looser Team individually . 5156 ( Win+BossKilled ) : 3163 ( Win ) 3024 ( Loss+BossKilled ) : 1031 ( Loss )
30312	Returns the first passed String if not empty , otherwise the second if not empty , otherwise the third if not empty , otherwise an empty but non-null String .
30603	Identifier of an item owner community Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
30713	Make this element anonymous . Remove any < tt > id < /tt > or < tt > name < /tt > attribute present in the element 's attributes .
30867	Parses and formats the given char sequence , preserving all data . < p/ > Equivalent to < code > eval ( in ) .getExactly ( ) < /code >
30963	Takes a byte [ ] and decodes it into a Record . This method assumes that the input byte [ ] represents a record that corresponds to this schema .
31124	Return the average area of cells at this level . This is accurate to within a factor of 1.7 ( for S2_QUADRATIC_PROJECTION ) and is extremely cheap to compute .
31568	Close the stream without necessarily flushing immediately . This may be called if the stream is in error such as after a previous write or close threw an exception .
31708	Start a RTM connection . Fetch the web socket url to connect to , current user details and list of channel ids where the current user has had conversation .
31823	Merge function for combining stream elements to a map . If two or more strings map and are not identical , then log a warning and throw an exception .
32021	Updates the Android Gradle 'experimental ' plugin version , and optionally the Gradle version of a given project . This method notifies the user if the version update failed .
32103	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
33051	Returns the data as a byte array . The most significant bit of the array is bit zero ( as in < code > java.math.BigInteger < /code > ) .
33061	Returns the hash code value for this context . The hash code is computed by exclusive or-ing the hash code of all the protection domains in the context together .
33401	Initialize this node test by setting the whatToShow property and the namespace and local name , and calculating the score that this test will return if a test succeeds .
33402	Default function to be overwritten in derived classes . Returns the return_state of this state , if the state is left after the method , or else this state .
33477	Returns < CODE > true < /CODE > if the provided DN corresponds to an entry that can be deleted and < CODE > false < /CODE > otherwise .
33515	Returns the label corresponding to the given offset . The default implementation of this method creates a label for the given offset if it has not been already created .
33532	Updates position and rank of all the children in the view . It essentially removes all views from all the pages and then adds them again in appropriate page .
33560	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
33621	Gets if this chunk was newly created or not . < p > Note that if this chunk is new , it will not be populated at this time .
33793	Creates an unmodifiable simple bind request of the provided request . < p > The returned bind request creates defensive copies of the password in order to maintain immutability .
33844	Returns the `` encoding '' string argument . < br > < i > N.B : the ' i ' short option is also used by cli < /i >
34046	Enter a traced zone by the name of metricReference for the current thread . This puts the enter timestamp and all lost call calculations will be based on this timestamp
34364	Writes a message to the access logger with information about the result of the provided abandon operation . < p > The default implementation is to not log anything .
34370	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
34487	Returns an iterator over the elements contained in this collection , with an ordering that respects the orderings set by the < code > setOrdering < /code > method .
34578	As of Java 2 platform v1.4 this method is no longer used . Do not call or override . All the functionality of this method is in the MetalPropertyChangeListener .
34604	Find the length of bytes that represents the superior DN of the given DN key . The superior DN is represented by the initial bytes of the DN key .
34612	Checks if all three units of this period are zero . < p > A zero period has the value zero for the years , months and days units .
34720	Force from ID3v22 FrameIdentifier to ID3v23 , this is where the frame and structure has changed from v2 to v3 but we can still do some kind of conversion .
34770	Updates the contents of a COS definition with the new contents . The COS definition must already exist in the persistent layer , before its contents can be replaced .
34827	The bulk collection methods are overridden to protect against an unscrupulous collection whose contains ( Object o ) method senses when o is a Map.Entry , and calls o.setValue .
34878	Gets the resource ID . For root Schema config , this will be null . Otherwise , it will be the name of the schema type this provider addresses .
34883	Creates a new change record ( an add , delete , modify , or modify DN request ) using the provided lines of LDIF decoded using the default schema .
34994	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
34997	Searches in this vector for the index of the specified object . The search for the object starts at the end and moves towards the start of this vector .
35148	Tell if this expression or it 's subexpressions can traverse outside the current subtree . NOTE : Ancestors tests with predicates are problematic , and will require special treatment .
35210	Flush the output buffer to the underlying character stream , without flushing the stream itself . This method is non-private only so that it may be invoked by PrintStream .
35389	Adds the < code > referenceParameter < /code > to the < code > W3CEndpointReference < /code > instance < code > wsa : ReferenceParameters < /code > element .
35507	An interpolator whose value at each point is divided by the provided value . < strong > note that this does not guard against division by 0 < /strong >
35660	Registers a class that can resolve a set of attributes to a Java class . The last class registered is the first to be called in the resolution chain .
35761	Return the LogStream identified by the given name . If a log corresponding to `` name '' does not exist , a log using the default stream is created .
36025	Synchronize the view 's cached values with the model . This causes the font , metrics , color , etc to be re-cached if the cache has been invalidated .
36077	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
36188	Factory method for `` SsoServerIdRepoSvc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
36309	< p > Register a new Rule matching the specified pattern . This method sets the < code > Digester < /code > property on the rule. < /p >
36522	Tells if this iterator can have nodes added to it or set via the < code > setItem ( int node , int index ) < /code > method .
36698	Returns a UUID whose content is based on the normalized content of this DN . Two equivalent DNs subject to the same schema will always yield the same UUID .
37144	Factory method for `` SsoServerSessSvc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
37325	Returns a < code > Set < /code > of the keys contained < em > only < /em > in this < code > ResourceBundle < /code > .
37396	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
37517	Factory method for `` SsoServerAuthSvc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
37557	Utility method to flag the last item in a collection as being the last item . This is then used in our templates to help with formatting the output .
37708	Perform work as a particular < code > Subject < /code > . Here the work will be granted to a < code > null < /code > subject .
38019	An < code > UndoableEditListener < /code > method . This invokes < code > addEdit < /code > with < code > e.getEdit ( ) < /code > .
38556	This method converts the Date value to its corresponding long value , this method assumes that the date format is the same as the format being returned by the ParseUtils.parseStringAsDate
39040	Adjusts the given row if possible to fit within the layout span . Since all adjustments were already calculated by the LineBreakMeasurer , this is implemented to do nothing .
39079	Updates the data associated to the Adapter . Useful when the query has been changed . If the query does not change you might consider using the automaticUpdate feature .
39087	Removes all the child components from the split pane . Resets the < code > leftComonent < /code > and < code > rightComponent < /code > instance variables .
39566	This method returns < code > true < /code > , if the audio file is encoded with & quot ; Variable Bitrate & quot ; . < br >
39674	called by BeanContextSupport superclass during construction and deserialization to initialize subclass transient state . subclasses may envelope this method , but should not override it or call it directly .
39955	Creates a condition which evaluates to < code > true < /code > if and only if all of its sub-conditions are < code > true < /code > .
40008	Deregisters the provided alternate root bind DN from the server . This will have no effect if there was no mapping defined for the provided alternate root bind DN .
40031	This method allows you to add an external appender . This is useful for the case when you want to log to a different log stream than a file .
40076	Store the relevant attributes of the specified JavaBean , plus a < code > className < /code > attribute defining the fully qualified Java class name of the bean .
40370	Sends this internal frame to the back . Places this internal frame at the bottom of the stacking order and makes the corresponding adjustment to other visible internal frames .
40380	Force from ID3v22 FrameIdentifier to ID3v23 , this is where the frame and structure has changed from v2 to v3 but we can still do some kind of conversion .
40381	Registers the provided log rotation policy with the Directory Server . If a policy is already registered for the provided configuration entry DN , then it will be replaced .
40420	Factory method for `` CtsConnectionFailureRate '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
40844	This method is used to clear the entire SDK cache in the event that EventService notifies that all entries have been modified ( or should be marked dirty ) .
41076	Factory method for `` SsoServerSAML2Svc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
41248	Factory method for `` SsoServerTopology '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
41364	Read a line of text . Whenever a < a href= '' # lt '' > line terminator < /a > is read the current line number is incremented .
41659	This implements the unsynchronized semantics of ensureCapacity . Synchronized methods in this class can internally call this method for ensuring capacity without incurring the cost of an extra synchronization .
41795	This method is overridden to protect the backing set against an object with a nefarious equals function that senses that the equality-candidate is Map.Entry and calls its setValue method .
41817	Make sure a time is local . If the time zone is not the local zone , the time is adjusted and the time zone set to be local .
41834	Reads All Account 's federation Info from data store for given user identity and returns a Set of ProviderIDs with which user is federated ( FedStatus is Active ) .
41865	Checks if the potion is in an upgraded state . This refers to whether or not the potion is Tier 2 , such as Potion of Fire Resistance II .
41898	Returns the HTML representation of a plain text string which is obtained by converting some special characters ( like ' < ' ) into its equivalent escaped HTML representation .
42053	Flushes the output buffer to the underlying character stream , without flushing the stream itself . This method is non-private only so that it may be invoked by PrintStream .
42126	Searches in this vector for the index of the specified object . The search for the object starts at the beginning and moves towards the end of this vector .
42246	Returns true if this edit is in progress -- that is , it has not received end . This generally means that edits are still being added to it .
42304	Force from ID3v2.30 FrameIdentifier to ID3v2.40 , this is where the frame and structure has changed from v3 to v4 but we can still do some kind of conversion .
42381	Checks if any corner of the polyline goes back to the first point It does happen if you are not careful while splitting , should not happen , really ...
42532	Creates a newly allocated byte array . Its size is the current size of this output stream and the valid contents of the buffer have been copied into it .
42613	Adds a PropertyChangeListener to the listener list . The listener is registered for all properties . < p > A PropertyChangeEvent will get fired when the selection mode changes .
42891	Invoked when a key has been pressed . Checks to see if the key event is a navigation key to prevent dispatching these keys for the first letter navigation .
42955	Indicates whether this entry meets the criteria to consider it an alias ( e.g. , it contains the `` aliasObject '' objectclass and a `` alias '' attribute ) .
43195	Tells whether the list of unreliable contains the entry with LDAPURL url . It assumes that we previously called containsChildrenOf ( there 's no check of the host/port ) .
43669	Finishes writing the contents of the ZIP output stream without closing the underlying stream . Use this method when applying multiple filters in succession to the same output stream .
43692	This method was extracted to encourage VM to inline callers . TODO : when we have a VM that can actually inline , move the test in here too !
43738	Encrypts or decrypts data in a single-part operation , or finishes a multiple-part operation . The data is encrypted or decrypted , depending on how this cipher was initialized .
44200	This method generates handler for async methods in REST APIs . Use the result directly and invoke ` toString ` as the response . The content type is JSON .
44236	Skips the remaining entries in the directory at the top of the stack . This method is a no-op if the stack is empty or the walker is closed .
44467	Retrieves a three-character string that is the UNIX mode for the provided file permission . Each character of the string will be a numeric digit from zero through seven .
44639	Returns < code > true < /code > if the object whose capabilities are encapsulated in this < code > ImageCapabilities < /code > can be or is accelerated .
44647	Brings this internal frame to the front . Places this internal frame at the top of the stacking order and makes the corresponding adjustment to other visible internal frames .
44797	Method for directly inserting specified bytes in output at current position . < p > NOTE : only use this method if you really know what you are doing .
44822	Gets a pre-configured SAXParser provider that caches parser instances in a per-thread LRU cache . The created parsers are configured to avoid various entity expansion and remote DTD attacks .
44980	Copy and convert bytes from an < code > InputStream < /code > to chars on a < code > Writer < /code > , using the specified encoding .
45024	Removes the data from the marked position to the current read position . The method is usefull when it is needed to delete one message from the internal buffer .
45680	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
45886	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
46081	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
46091	Writes a message to the access logger with information about the completion of the provided search operation . < p > The default implementation is to not log anything .
46294	Notify this controller that authentication data have changed in the connection pool for the specified url . The controller starts refreshing the node which represent entries from the url .
46522	Returns the default column model object which is a < code > DefaultTableColumnModel < /code > . A subclass can override this method to return a different column model object
46655	Adds a title to an existing border , with the specified positioning and using the default font and text color ( determined by the current look and feel ) .
46830	Returns < code > true < /code > if the open data values this open type describes are primitive arrays , < code > false < /code > otherwise .
46908	Initializes this analyzer . This method is called just before the execution of control flow analysis loop in # analyze . The default implementation of this method does nothing .
47067	React to a failed authorization response by looking up new credentials . Returns a request for a subsequent attempt , or null if no further attempts should be made .
47196	Checks if the day-of-month is valid for this year-month . < p > This method checks whether this year and month and the input day form a valid date .
47313	Sets the time limit for the query request . Defaults to 0 seconds - no time limit . The time limit will be enforced by the underlying backend technology .
47357	Determines whether each attribute in the attribute set is valid . Iterates though the set checking each element to see if there is a validator that needs to execute .
47830	Method for directly inserting specified byte in output at current position . < p > NOTE : only use this method if you really know what you are doing .
47912	Closes the cache and deletes all of its stored values . This will delete all files in the cache directory including files that were n't created by the cache .
48038	Returns true if this edit is < code > alive < /code > and < code > hasBeenDone < /code > is < code > true < /code > .
48103	Returns the `` configfile '' string argument . < br > < i > N.B : the ' f ' short option is also used by filename < /i >
48129	Gets zone strings , initializing them if necessary . Does not create a defensive copy , so make sure you do so before exposing the returned arrays to clients .
48402	Stops the current editing session . This has no effect if the tree is n't being edited . Returns true if the editor allows the editing session to stop .
48412	Creates an argument exception which should be used when a property value argument is invalid because it does not contain a separator between the property name and its value .
48537	Change the size requests for this shape . An invalidate ( ) is propagated upward as a result so that layout will eventually happen with using the new sizes .
48678	Factory method for `` SsoServerFedEntities '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
49017	Checks the invalid session idle time . If this session is invalid and idle for more than 3 minutes , we will need to remove it from the session table
49160	This method is used to clear the entire SDK cache in the event that EventService notifies that all entries have been modified ( or should be marked dirty ) .
49245	Creates an argument exception which should be used when a property modification argument is invalid because it does not contain a separator between the property name and its value .
49305	Factory method for `` SsoServerSvcMgmtSvc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
49430	Factory method for `` SsoServerWSSAgents '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
49495	Perform work as a particular < code > Subject < /code > . Here the work will be granted to a < code > null < /code > subject .
49521	Factory method for `` CtsMonitoring '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
49572	Creates a tunnel to an intermediate proxy . This method is < i > not < /i > implemented in this class . It just throws an exception here .
49637	This method is used to clear the entire SDK cache in the event that EventService notifies that all entries have been modified ( or should be marked dirty ) .
49848	Method for directly inserting specified bytes in output at current position . < p > NOTE : only use this method if you really know what you are doing .
49862	Called if InstanceID token is updated . This may occur if the security of the previous token had been compromised . This call is initiated by the InstanceID provider .
49953	Determines whether each attribute in the attribute set is valid . Iterates though the set checking each element to see if there is a validator that needs to execute .
50184	Returns true if the < code > MouseEvent < /code > is considered a popup trigger by the < code > JPopupMenu < /code > 's currently installed UI .
50392	Returns the `` sasloption '' string argument . < br > < i > N.B : the ' o ' short option is also used by outputLDIF. < /i >
50654	Add the given components , in order , to the identifier . Duplicate instances are not added -- only one instance of a component will exist in the identifier .
50681	Marks the present position in the stream . The < code > mark < /code > for class < code > PushbackReader < /code > always throws an exception .
50813	Creates a world with the specified options . < p > If the world already exists , it will be loaded from disk and some options may be ignored .
50836	Factory method for `` SsoServerFedCOTs '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
51081	For a given integer in the set it returns the single bit value used within a given word that represents whether the integer is in the set or not .
51274	Clears both the memory and disk cache associated with this ImageCache object . Note that this includes disk access so this should not be executed on the main/UI thread .
51416	Creates a new additional log item using the provided source , key , and value . The value will not be surrounded by quotes when serialized as a string .
51573	Factory method for `` CtsConnectionSuccessRate '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
51654	This method may be overridden by subclasses to provide their own initialization behaviors . When invoked any resources required by the BeanContextChild should be obtained from the current BeanContext .
52059	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the change flings forward and overshoots the last value then comes back .
52132	This resets the double buffer . Actually , it marks the double buffer as invalid , the double buffer will then be recreated on the next invocation of getOffscreenBuffer .
52216	Returns the `` useSSL '' boolean argument . < br > < i > N.B : the ' Z ' short option is also used by ldapsport. < /i >
52228	Method which gets invoked before an entry is deleted . The deletion type configured in Sun Java System Access Manager is also passed as a parameter to this method .
52246	Adds the specified attribute to this attribute set if it is not already present , first removing any existing in the same attribute category as the specified attribute value .
52483	Invoked when a key has been pressed . Checks to see if the key event is a navigation key to prevent dispatching these keys for the first letter navigation .
52547	Removes the subtree rooted at this node from the tree , giving this node a null parent . Does nothing if this node is the root of its tree .
52665	Convert the JList relative coordinate to the row that contains it , based on the current layout . If y0 does n't fall within any row , return -1 .
52697	Peeks at the next input character , refilling the buffer if necessary . If this character is a newline character ( `` \n '' ) , it is discarded .
53140	Checks the validity of the launch daily information and updates the provided collection of messages with the errors that have been found . The associated labels are also updated .
53189	Creates a newly allocated byte array . Its size is the current size of this output stream and the valid contents of the buffer have been copied into it .
53223	Encode a string into a QR code with dimensions width x height , using error-correction level L and the smallest version for which he contents fit into the QR-code ?
53261	Makes this Component displayable by connecting it to a native screen resource . This method is called internally by the toolkit and should not be called directly by programs .
53355	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the change flings forward and overshoots the last value then comes back .
53592	Invoked for a file that could not be visited . < p > Unless overridden , this method re-throws the I/O exception that prevented the file from being visited .
53810	Factory method for `` SsoServerIDFFSvc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
54123	Peeks at the next input character , refilling the buffer if necessary . If this character is a newline character ( `` \n '' ) , it is discarded .
54359	Closes this < code > FileCacheImageInputStream < /code > , closing and removing the cache file . The source < code > InputStream < /code > is not closed .
54422	This method is overridden to protect the backing set against an object with a nefarious equals function that senses that the equality-candidate is Map.Entry and calls its setValue method .
54453	Method for directly inserting specified byte in output at current position . < p > NOTE : only use this method if you really know what you are doing .
54497	Returns the contents of this ByteArrayOutputStream as a string . Any changes made to the receiver after returning will not be reflected in the string returned to the caller .
54521	This method was extracted to encourage VM to inline callers . TODO : when we have a VM that can actually inline , move the test in here too !
54679	Force from ID3v2.40 FrameIdentifier to ID3v2.30 , this is where the frame and structure has changed between v4 to v3 but we can still do some kind of conversion .
54731	Encrypts or decrypts data in a single-part operation , or finishes a multiple-part operation . The data is encrypted or decrypted , depending on how this cipher was initialized .
54771	Called if InstanceID token is updated . This may occur if the security of the previous token had been compromised . This call is initiated by the InstanceID provider .
54831	Reverses the provided interpolator . For any value of 'input ' , the value ' 1-input ' will be used on the provided interpolator and the result will be returned
54838	Returns the label corresponding to the given offset . The default implementation of this method creates a label for the given offset if it has not been already created .
54849	Factory method for `` SsoServerSAML1Svc '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
54988	Creates a new instance of a dialog displaying the rationale for the use of the location permission . < p/ > The permission is requested after clicking 'ok ' .
55002	Creates a special block that is marked as not allowing jumps in . This should not be used for rewriting BlockExpression itself , or anything else that supports jumping .
55134	Merges all sets of variable bindings into a single scope to use when evaluating the script . Bindings later in the list will override bindings earlier in the list .
55159	Returns site ID based on the host name . The site ID will be in Base64 encoded format . This method will print out site ID to the standard output
55277	Copy the template contents into the result tree . The content of the xsl : template element is the template that is instantiated when the template rule is applied .
55313	Removes an audience restriction condition < code > AudienceRestrictionCondition < /code > from this < code > Conditions < /code > object wherein the specified audience has been defined .
55324	Sends < code > undo < /code > to all contained < code > UndoableEdits < /code > in the reverse of the order in which they were added .
55369	Returns an editor for this snapshot 's entry , or null if either the entry has changed since this snapshot was created or if another edit is in progress .
55396	Returns the x coordinates of the point nQ , where Q is the base point . < p > Used to generate a public key from a secret key .
55506	Loads a set of rules that have been specified in terms of CSS1 grammar . If there are collisions with existing rules , the newly specified rule will win .
55662	The next two methods are overridden to protect against an unscrupulous List whose contains ( Object o ) method senses when o is a Map.Entry , and calls o.setValue .
55974	Removes InternalSession from the session table so that another server instance can be an owner . This is the server side of distributed invocation initiated by calling releaseSession ( )
55999	Factory method for `` SsoServerInstance '' group MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
56016	Writes a message to the access logger with information about the termination of an existing client connection . < p > The default implementation is to not log anything .
56264	Gets how much spaces should be used to indent each line . < p > The minimum value this may be is 2 , and the maximum is 9 .
56276	Explicitly flush any stored events to the server . Implicit flushes may happen depending on the value of getFlushBehavior . This method allows for explicit , app invoked flushing .
