48	Adds the given path to the list of 'renderscript ' directories . It also creates the directory in the file system .
83	[ % SkillTarget ] is in the movement speed increase state because [ % SkillCaster ] used [ % SkillName ] .
131	Get a hashCode for the 2D vector . < p > All NaN values have the same hash code. < /p >
142	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
165	Starts the output of a set of data . Audio data for a single utterance should be grouped between begin/end pairs .
457	Gets called when a parameter is added to an effect . Can be overridden in subclasses but must be called through .
471	Returns the Object argument as a parameterized Map if the Object argument is an instance of Map . Otherwise returns null .
480	Retrieve the values in this set , mapped by their tags . Scalar values will be mapped onto the empty Tags .
495	Starts the output of a set of data . Audio data for a single utterance should be grouped between begin/end pairs .
499	Checks if the adapter collection is empty . If it is , hide the RecyclerView content and show the empty view .
515	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
633	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
640	Asks for tag refresh from DAQ level ( DAQ cache refresh ) . Value already in cache will be filtered out .
690	[ % SkillCaster ] will receive the decrease flight time effect in a moment because he used [ % SkillName ] .
694	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
700	Create an EntityManagerFactory instance for the named persistence unit for accessing a local in-memory Derby test database instance . < p >
938	Reinitialize the logging properties and reread the logging configuration , and initiate probes if the probe interval is greater than zero .
1080	This calculates a constraint tables and applies them to the widgets TODO break up into creation of a constraint table and apply
1096	Encodes a raw byte array into a BASE64 < code > String < /code > representation i accordance with RFC 2045 .
1106	Reads a `` long '' value from an InputStream . The value is converted to the opposed endian system while reading .
1566	Iterations -- Iterations of analysis . We can run multiple times of the geometric analysis to continuously improve the analysis precision .
1757	[ % SkillTarget ] is in the flight time recovery state because [ % SkillCaster ] used [ % SkillName ] .
1792	Calls putEnv for each entry in the Map , thus allowing for the additional flexibility in naming supported in that method .
1838	`` Only for advertising agencies . '' ID of the client with the advertising account where the group will be created .
1846	Return < code > true < /code > if used cluster schema , otherwise < code > false < /code > .
1905	Creates the equipment object from the properties and validates them . The returned object has not been inserted in the cache .
2050	Iterations -- Iterations of analysis . We can run multiple times of the geometric analysis to continuously improve the analysis precision .
2103	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
2141	Calls putEnv for each entry in the Map , thus allowing for the additional flexibility in naming supported in that method .
2274	Call this method to stop the applet from your launcher class < code > MyAppletLauncher.stop ( ) < /code > method .
2280	Returns a new TrustSource containing the same trusted CAs as this TrustSource , plus the trusted CAs in the specified TrustSource .
2376	Number of characters after which to truncate the previewed comment . To preview the full comment , specify `` 0 '' .
2433	Called when the system received an HTTP authentication request . Plugin can use the supplied HttpAuthHandler to process this auth challenge .
2528	Randomly sample a set of invalid values from a specified column . Values are considered invalid according to the Schema / ColumnMetaData
2709	The number of keys in this CounterMap ( not the number of key-value entries -- use totalSize ( ) for that )
2727	Resolve logger property by its name - system property value if available , or logger property extracted from the log configuration .
2865	Destroy all tabs in this model . This will check to see if the tab is already destroyed before destroying it .
2915	Lock the flushing mechanism in order to prevent a thread flushing this buffer while another thread is doing a physiological operation .
2997	If we 're not on a git branch which tracks a remote , we have no way of determining a WorkingSet .
3062	Call this method to destroy the applet from your launcher class < code > MyAppletLauncher.destroy ( ) < /code > method .
3073	Returns true if < code > m < /code > is the same node < code > n < /code > .
3079	Adds the given path to the list of 'excluded ' directories . It also creates the directory in the file system .
3096	Filter-line of the request ( for 'countries , regions , cities , streets , schools , interests , positions ' ) .
3195	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
3272	Shows or hides a checkbox based on a given API level and the max API level for which it should be shown
3430	This is the default implementation of TObjectHashingStrategy : it delegates equality comparisons to the first parameter 's equals ( ) method .
3540	[ % SkillTarget ] 's flight time increased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
3633	Put a key/value pair in the JSONObject , where the value will be a JSONArray which is produced from a Collection .
3679	Resets all custom offsets set via setViewPortOffsets ( ... ) method . Allows the chart to again calculate all offsets automatically .
3769	Destroys the specified surface . Note the EGLSurface wo n't actually be destroyed if it 's still current in a context .
3779	< p > Divide the value of this fraction by another , returning the result in reduced form . < /p >
3838	Synchronize the entity data . This is special because of the way that the `` fast '' version stores the information .
4103	[ % SkillTarget ] is in the convert damage healing state because [ % SkillCaster ] used [ % SkillName ] .
4204	Lyrics ID ( which can be obtained with the audio.get ] ] , audio.getById , or [ [ audio.search method ) .
4248	Add a request id to pass to druid . Only added if x-request-id follows the format specified at : https : //devcenter.heroku.com/articles/http-request-id
4268	Appends the JSON representation of the specified < code > float < /code > value to the end of this array .
4312	Adds the given path to the list of 'res ' directories . It also creates the directory in the file system .
4333	Hides the `` See all '' iv possibilities link if the iv scan result reports that there are too many possibilities .
4406	Return the Type for the given ParameterizedType , resolving actual type arguments where possible ; uses recursiveBounds to limit the recursion .
4432	Check the string against XML 's definition of acceptable names for elements and attributes and so on using the XMLCharacterProperties utility class
4445	Places settings ( for public pages only ) . < p > Possible values : false - disabled ; true - enabled
4470	Returns the capacity of the hash table . This is the true physical capacity , without adjusting for the load factor .
4550	Returns < code > true < /code > if the item is a JSML document ( Java Speech Markup Language ) .
4562	This returns a String representation of a config , at the moment it 's using a multiline approach for CustomConfiguration rendering .
4603	Called when the system received an HTTP authentication request . Plugins can use the supplied HttpAuthHandler to process this auth challenge .
4656	Changes the program . The previous program will be released . < p/ > The appropriate EGL context must be current .
4672	Check for and report literal-out-of-bounds error . If the constant is error-marked , there exists a literal out of bounds error .
4715	Unsubscribes JMS container for the given process id , if this one can be found ( o.w . does nothing ) .
4718	Convert byte to unsigned int . Java only has signed types so we have to do more work to get unsigned ops
4939	Qualified access for wildcard types . Since they have no ordinary package and type name we just return the bound access .
5278	Determine if playback file is streaming or local . It is streaming if file name starts with `` http : // ''
5332	[ % SkillTarget ] is in the boost recovery skill state because [ % SkillCaster ] used [ % SkillName ] .
5377	Creates a new Map based from an existing map with just valid parameters . Tries to convert parameters to required type .
5551	This function can be used with any API level and will return false if the multi window feature is not supported .
5579	Unescape < code > charToEscape < /code > in the string with the escape char < code > escapeChar < /code >
5611	Returns the full text of a given document , including dateline and other elements as a String . Tags are removed .
5651	To be called internally only within a dataTag synchronized block . Does not notify listeners . Should not be made public .
5759	Checks whether all required parameters depending on the mode are specified via command lines arguments . Only iTunes-specific parameters are validated .
5807	Returns the Object argument as a parameterized List if the Object argument is an instance of List . Otherwise returns null .
5809	notify ( if requested ) when the object is not active any more- i.e . not accumulating fifo events for the template
6120	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
6154	Adds the given path to the list of generated resource directories . It also creates the directory in the file system .
6192	Try to determine whether this application is running under Windows or some other platform by examing the `` os.name '' property .
6208	Put a key/value pair in the JSONObject , where the value will be a JSONObject which is produced from a Map .
6223	`` Only for advertising agencies . '' ID of the client with the advertising account where the group will be created .
6252	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
6270	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
6326	[ % SkillTarget ] 's MP was reduced by % num0 because [ % SkillCaster ] used [ % SkillName ] .
6341	Verifies that serialization preserves equals and hashCode . Serializes the object , then recovers it and checks equals and hash code .
6411	Get a hashCode for the 2D vector . < p > All NaN values have the same hash code. < /p >
6454	Convenience method . Check if < code > exclusion < /code > is a substitution group exclusion for this element declaration .
6521	[ % SkillTarget ] 's flight time increased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
6577	Perform a mathematical operation ( add , subtract , scalar max etc ) on the specified integer column , with a scalar
6580	Get a hashCode for the 3D vector . < p > All NaN values have the same hash code. < /p >
6753	Adds the given path to the list of 'aidl ' directories . It also creates the directory in the file system .
6809	Create the GUI and show it . For thread safety , this method should be invoked from the event dispatch thread .
6811	Initializes the statistics manager . Note that this manager should be initialized < em > after < /em > system recovery .
6851	Scale the specified bitmap to properly fit as a notification icon . If the argument is null the function returns null .
6928	[ % SkillCaster ] inflicted % num0 damage and the rune carve effect on themselves by using [ % SkillName ] .
6933	The SyncAdapter runs on a background thread . To update the UI , onStatusChanged ( ) runs on the UI thread .
6966	Creates a media controller and attaches it to the activity . This method is for activities that contain a video player .
6999	Tries to publish a message to the given topic , with the provided payload , quality of service and retained flag .
7119	Returns true if the non-null object is equal to any of the elements of the array with index less than i .
7145	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
7197	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
7204	Use to get recommendations based on a user 's playlist . User ID . By default , the current user ID .
7226	Two UnitValueBoxPairs are equal iff they the Unit they hold are 'equal ' and the ValueBoxes they hold are 'equal ' .
7300	Show message , set text colour according to whether message is informational ( black ) or an error ( red ) .
7307	Executes the next Spotlight animation in the queue . If no more animations are found , resetTour ( ) is called .
7328	Gets the opcode out of an opcode unit , the latter of which may also include one or more argument values .
7505	Return true if this is a top-level face cell ( more efficient than checking whether level ( ) == 0 ) .
7519	Returns the full text of a given document , including dateline and other elements as a String . Tags are removed .
7522	Returns an array containing the string names in this object . This method returns null if this object contains no mappings .
7569	The SyncAdapter runs on a background thread . To update the UI , onStatusChanged ( ) runs on the UI thread .
7570	Called when a tab is being closed . When called , the closing tab will not be part of the model .
7585	This method is called when a new object is not found in the database . The default implementation is to call executor.addForInsert
7696	Appends the JSON representation of the specified < code > int < /code > value to the end of this array .
7718	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
7752	Switches to the next browser tab . If called when last tab is active , then switches to the first one .
7763	Regex to match a tag , possibly with nested tags such as < a href= '' < MTFoo > '' > .
7766	[ % SkillCaster ] 's [ % SkillName ] was cancelled as [ % SkillTarget ] is under too many effects .
7892	Removes all leases from the managed set of leases . This method does not request the cancellation of the removed leases .
7942	Absolute file paths are prohibited -- the TempDirTestFixture used in these tests will prepend it 's own root to the path .
8080	[ % SkillTarget ] 's flight time increased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
8247	% 0 is where it is indicated on the map , but the path leading to it can not be found .
8387	Comments sort order ( `` asc '' - from old to new , `` desc '' - from new to old )
8426	Decrement the number of references to the DataStore by one . If the DataStore is completely dereferenced it will be closed .
8509	[ % SkillTarget ] is in the elemental maximum defense state because [ % SkillCaster ] used [ % SkillName ] .
8618	Centers the viewport to the specified y-value on the y-axis . This also refreshes the chart by calling invalidate ( ) .
8662	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
8784	Replaces the enumeration from the stream with a real one . This ensures that the correct flag is set for SYSTEM .
8818	Calls an event with the given details . < p > This method only synchronizes when the event is not asynchronous .
8820	Checks if the given name is a valid Android application package ( which has additional requirements beyond a normal Java package )
8886	Inflates layout from < code > xml < /code > and encapsulates it with < code > RecyclerViewHeader < /code > .
9045	Replaces the enumeration from the stream with a real one . This ensures that the correct flag is set for SYSTEM .
9068	Put a key/value pair in the JSONObject , where the value will be a JSONArray which is produced from a Collection .
9111	Identifier of a user or community to add a video to . Use a negative value to designate a community ID .
9114	Organizes spawns in all processed walker groups . Must be called only when spawning all npcs for the instance of world .
9258	Perform a mathematical operation ( add , subtract , scalar max etc ) on the specified double column , with a scalar
9264	For an int value x , this method returns +1 if x > = 0 and -1 if x < 0 .
9277	Returns < code > true < /code > if entry is transient , otherwise < code > false < /code > .
9324	Get a hashCode for the 1D vector . < p > All NaN values have the same hash code. < /p >
9332	Called by < code > Voice < /code > during loading , derived voices should override this to provide customized loading .
9345	Removes the last occurrence of the word `` and '' from the given string , including potential trailing spaces , case-insensitive .
9455	Writes a `` double '' value to an OutputStream . The value is converted to the opposed endian system while writing .
9464	Tries to publish a message to the given topic , with the provided payload , quality of service and retained flag .
9568	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
9602	Returns the dependencies that are NOT included in the specified module . Note : the version of the dependency is disregarded .
9716	1 ) using window to get DecorView , 2 ) remove content view of DecorView , 3 ) replace with new content
9746	Adds the given path to the list of 'source ' directories . It also creates the directory in the file system .
10198	Gets called when a parameter is removed from an effect . Can be overridden in subclasses but must be called through .
10228	Returns the given integer value as an unsigned short , throwing an IllegalArgumentException if the value is negative or too large .
10236	SCIPIO : Clones item . < p > NOTE : if modelMenu/parentSubMenu are null , they are taken from this item .
10485	Produce a JSONArray of JSONObjects from a comma delimited text string , using the first row as a source of names .
10519	Indicates whether this params specifies follow up for the given program . Follow up can be specified as true or false .
10532	The position of the cell center along the Hilbert curve over this face , in the range 0.. ( 2**kPosBits-1 ) .
10567	Returns the field ref node having this node as its base , and field as its field ; null if nonexistent .
10596	Album ID . If the parameter is not set , comments on all of the user 's albums will be returned .
10881	Computes t test statistic for 2-sample t-test . < p > Does not assume that subpopulation variances are equal. < /p >
10934	Receives all key events in the AWT and processes the ones that originated from the current window with the glass pane .
10939	Load Products , Customers , Suppliers , Product Categories , customer reviews to db from respective xml 's and Generate Stock .
11170	Tests whether the user has the given authority . Returns true in any case if the user has the ALL authority .
11369	It closes the producer from server-side and sends command to client to disconnect producer from existing connection without closing that connection .
11430	`` Only for advertising agencies . '' ID of the client with the advertising account where the group will be created .
11443	Disables IDEA 's Java and Android builders for Gradle-imported projects . They are no longer needed since we build with Gradle .
11498	Returns the filename assigned to this table . Currently , the filename is the table name followed by `` .tbl '' .
11508	[ % SkillTarget ] was put in the forced crash state because [ % SkillCaster ] used [ % SkillName ] .
11532	Determine if playback file is streaming or local . It is streaming if file name starts with `` http : // ''
11693	Equality purely based on ID , not anything else . This allows multiple AddToValue runnables with the same ID to collapse .
11704	Enables the line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
11795	The number of leaf cells covered by the union . This will be no more than 6*2^60 for the whole sphere .
11809	Given the number of buckets that can be used per element , return a specification that minimizes the false positive rate .
11901	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
11905	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
11941	Returns a set containing all keys on this object . If possible , use the keys iterator instead for improved performance .
12060	Retrieves and removes ( thus `` consumes '' ) the SSL timing information from the connection cache for the specified address .
12120	Indicate that the ResultSet object 's cursor is scrollable but generally sensitive to changes to the data that underlies the ResultSet .
12183	Compute the signum of a number . The signum is -1 for negative numbers , +1 for positive numbers and 0 otherwise
12206	Adds the given exception to the list of exceptions thrown by this method unless the exception is already in the list .
12210	Auto generating bean ids to avoid the error Configuration problem : Id is required for element when used as a top-level tag
12247	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
12365	Creates new Ack obj ( inner class ) , with all the req info and adds it to the acks vec .
12380	Clears this data object from all DataSets and removes all Entries . Do n't forget to invalidate the chart after this .
12477	Puts the given NodeListCache in the free list . Note : The owner node can keep using it until we reuse it
12561	Appends a new line at the end of the message then prints the message to the standard output and to logger .
12848	Submit events for users within the context of a specific application and experiment . Each event is an impression or action .
12937	Number of characters after which to truncate the previewed comment . To preview the full comment , specify `` 0 '' .
13242	Resets all custom offsets set via setViewPortOffsets ( ... ) method . Allows the chart to again calculate all offsets automatically .
13256	Gets whether the given method is an entry point , i.e . one of the initial seeds belongs to the given method
13331	Controls if scrollable resultsets will be used with initial load operation . Defaults to < code > true < /code > .
13387	Invokes the delegate 's < code > write ( char [ ] , int , int ) < /code > method .
13453	[ % SkillTarget ] is in the elemental maximum defense state because [ % SkillCaster ] used [ % SkillName ] .
13485	[ % SkillTarget ] blocked the [ % SkillName ] used by [ % SkillCaster ] with the protective shield effect .
13674	This method updates UI . Simply setting params like mode and brightness wo n't bringing effect until this method is called .
13702	Writes a `` short '' value to an OutputStream . The value is converted to the opposed endian system while writing .
13756	[ % SkillTarget ] is in the boost spell skill state because [ % SkillCaster ] used [ % SkillName ] .
13827	% 0 has been lowered to % 1 because you have n't killed the lower level targets for a certain time .
13851	Remove a child edge from the Tree . The child node and its subtree will also be removed from the Tree .
13860	The offset of the popup position . Useful to control the anchor of the popup when opening it on some overlays .
13952	Resets the bonus potential . 0.16 % unique , 0.4 % epic , else rare . No chance on 2nd/3rd lines .
13999	Adds the given path to the list of 'Cpp ' directories . It also creates the directory in the file system .
14005	[ % SkillTarget ] is in the convert death healing state because [ % SkillCaster ] used [ % SkillName ] .
14029	Sorts the given list using the given comparator . The algorithm is stable which means equal elements do n't get reordered .
14052	Add this to the list of interfaces supposedly implemented by this class . Note that each CP is usually a ClassCP .
14059	Reads a `` double '' value from an InputStream . The value is converted to the opposed endian system while reading .
14231	Shuts down the < code > SpringEmbeddedCacheManager < /code > instance created by this < code > FactoryBean < /code > .
14293	Returns whether the native library was found and successfully initialised . Native functions will not be called unless this is true .
14472	An easy way to set up non-home ( no back button on the toolbar ) activity to enable go back action .
14477	Prints a formatted string to standard output , using the specified format string and arguments , and then flushes standard output .
14513	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
14533	Clears the header view cache . Headers will be recreated and rebound on list scroll after this method has been called .
14689	For callbacks on JSpace Proxies ( non-cluster and clustered ) to verify that proxy is still alive before performing non-transactional take .
14818	Returns true if this class is an interface . If this class is not defined , then this will throw an UnresolvedClassException
14978	Creates a storable headphone fence which will be valid ( during around 5seconds ) when headphones are plugged in to the device
15002	Attempts to set the formatting template and returns a string which contains the formatted version of the digits entered so far .
15211	Filter-line of the request ( for 'countries , regions , cities , streets , schools , interests , positions ' ) .
15256	Perform a HTTP PUT request and track the Android Context which initiated the request . And set one-time headers for the request
15284	You have reached the daily Private Store trading limit of % 0 Kinah , so the trade can not be completed .
15293	[ % SkillTarget ] 's % 0 resistance effects were weakened because [ % SkillCaster ] used [ % SkillName ] .
15386	Add a select operator to the QueryPlan with a list of column names . Can only specify one set of selections .
15427	% 0 has been conditioned as much as it can be . You can not condition it to Level % 1 .
15527	Do some operation on repository ( delete or update resource etc ) with wrapped session ( automatically opened and closed ) .
15543	Parses the given input string as JSON . The input must contain a valid JSON value , optionally padded with whitespace .
15563	Checks if WebElement with specified name is present on the specified list and clicks it if it is on the list .
15617	[ % SkillTarget ] is in the movement speed increase state because [ % SkillCaster ] used [ % SkillName ] .
15644	Get a hashCode for the 2D vector . < p > All NaN values have the same hash code. < /p >
15730	You inflicted % num0 damage and the rune carve effect on [ % SkillTarget ] by using [ % SkillName ] .
15732	Produce a JSONArray of JSONObjects from a comma delimited text string , using the first row as a source of names .
15746	Returns the position within an orgUnit path at which the orgUnit UID will be found for a given data approval level .
15828	Adds the given path to the list of generated source directories . It also creates the directory in the file system .
15895	Produce a JSONArray of JSONObjects from a comma delimited text string using a supplied JSONArray as the source of element names .
15996	Creates a new Map based from an existing map with just valid parameters . Tries to convert parameters to required type .
16009	Enables the highlight-line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
16130	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
16220	For dimensions with NoOpSearchProvider , the dimension rows are unknown . So , returning an empty Set would prevent any NullPointerException .
16222	Do some operation on repository ( delete or update resource etc ) with wrapped session ( automatically opened and closed ) .
16321	You are forced to resurrect at the bind point because [ % SkillCaster ] used [ % SkillName ] on you .
16360	Check whether an object is NOT empty , will see if it is a String , Map , Collection , etc .
16427	Inner method for invalidating all tags from the live cache with a given < code > TagQualityStatus < /code > flag .
16479	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
16620	Append either the value < code > true < /code > or the value < code > false < /code > .
16851	Clears the subheader view cache . Subheaders will be recreated and rebound on list scroll after this method has been called .
16918	Returns true if this indexRange contains ( if the value is in between ) the given value , false if not .
17100	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
17206	From the result of the FFT ( in the frequency domain ) , compute the log amplitude for each positive frequency .
17246	Queues a DiscoveryTask to attempt , through unicast discovery , to discover the lookup service associated with the given LocatorReg instance .
17506	Removes the edge e from the call graph . Returns true iff the edge was originally present in the call graph .
17510	Call this method to start the applet from your launcher class < code > MyAppletLauncher.start ( ) < /code > method .
17714	Create an HTTP Partial Content response . The calendar converter will use this response when a calendar is only partially updated .
17728	Removes from the given list the elements at the given indexes . Ignores indexes which are out of bounds of list .
17756	Helper method for registering for use in situations where the interface does not rely on 'TARGET.this ' , such as Block .
17852	the method will return flag ( true or false ) depending on the existence of the direct dictionary columns in conditional expression
17862	Creates a reference to a primitive type based on its name in the protocol buffer language , with default cardinality optional .
17890	ID of the user to whom the reply is addressed ( if the comment is a reply to another comment ) .
17906	is the entry returned already matched against the searching template currently is true if the underlying scan made by CacheManager : :EntriesIter
17939	Remove all keys in the array map that do < b > not < /b > exist in the given collection .
17989	Execute the < code > function < /code > by the scheduler . It would be submitted to any executor randomly .
18231	Returns < code > true < /code > if this < code > FlexibleMapAccessor < /code > contains a nested expression .
18371	Cancels all running and scheduled display image tasks. < br / > ImageLoader still can be used after calling this method .
18416	Indicates whether this parameters specifies follow up for the given program . Follow up can be specified as true or false .
18462	Enables the line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
18610	Appends the JSON representation of the specified < code > double < /code > value to the end of this array .
18655	Set a request type integer . Helpful when app has different types of pick requests that should be distinguished when getting result
18666	If msg is a JMS ObjectMessage , it returns the containing POJO . Otherwise , it returns the same argument object .
18924	Returns true if the object passed in is an instance of Type with the same type hash . Returns false otherwise .
18934	Escape < code > charToEscape < /code > in the string with the escape char < code > escapeChar < /code >
18967	[ % SkillTarget ] is in the boost recovery skill state because [ % SkillCaster ] used [ % SkillName ] .
19031	Checks to see if the given Vector3f is equals to the data stored in the buffer at the given data index .
19118	true - audio file will not be available for search false - audio file will be available for search ( default )
19222	Marks the end of a set of data . Audio data for a single utterance should be groupd between begin/end pairs .
19348	Replaces the enumeration from the stream with a real one . This ensures that the correct flag is set for SYSTEM .
19438	[ % SkillTarget ] is in the boost % 0 state because [ % SkillCaster ] used [ % SkillName ] .
19503	Writes a < code > long < /code > to the bytes message stream as eight bytes , high byte first .
19682	% 0 ca n't apply to join the selected group as he or she is already a member of an alliance .
19689	Cancels all running and scheduled display image tasks. < br / > ImageLoader still can be used after calling this method .
19744	Creates a new Map based from an existing map with just valid parameters . Tries to convert parameters to required type .
19773	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
19795	Appends the JSON representation of the specified < code > boolean < /code > value to the end of this array .
19866	[ % SkillTarget ] is in the no elemental defense state because [ % SkillCaster ] used [ % SkillName ] .
20021	Tests if the interior of this < code > Polygon < /code > entirely contains the specified set of rectangular coordinates .
20194	Removes initial ( leading ) whitespace characters from s. Member whitespace ( see above ) defines which characters are considered whitespace .
20288	Initializes the overlay before the first use , if applicable . This is a good place to initialize resources like colors .
20443	Creates the default probability density test expected values . These and all other test values are generated by R , version 1.8.1
20444	Returns < code > true < /code > , if the given listener is registered for receiving updates of that tag .
20500	Clears the header view cache . Headers will be recreated and rebound on list scroll after this method has been called .
20672	[ % SkillCaster ] will receive the decrease flight time effect in a moment because he used [ % SkillName ] .
20793	Guesses the length of a formatted protocol version . Needed to guess the length of a formatted request or status line .
20934	This function must be called before calling the get ( ) method , because of the dependency on the config object .
20943	Remove a child edge from the Tree . The child node and its subtree will also be removed from the Tree .
21352	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
21448	Executes the EntityQuery and returns the result count If the query generates more than a single result then an exception is thrown
21451	Appends the JSON representation of the specified < code > long < /code > value to the end of this array .
21690	Wait for the all incoming values to be dealt with , then expire the thread . Does nothing if already shutdown .
21845	Convert a sequence to a set of individual values ( by treating each value in each sequence as a separate example )
21896	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
21897	Preserve source-level annotations -- . Preserves annotations of retention type SOURCE . ( for everything but package and local variable annotations )
21969	Validates this SootClass for logical errors . Note that this does not validate the method bodies , only the class structure .
22015	Compute the signum of a number . The signum is -1 for negative numbers , +1 for positive numbers and 0 otherwise
22112	Notifies the attached observers that the underlying data has been changed and any View reflecting the data set should refresh itself .
22193	Make a name for the role type corresponding to the subject ( i.e . domain ) of an OWL object property .
22200	Assert the specified values have been received in the declared order . Values storage should be enabled to use this method .
22321	Explicit implementation of cloneNode ( ) to ensure that cache used for getRows ( ) and getTBodies ( ) gets cleared .
22392	This method gives you any AnnotationView that is available to be reused . It 'll return null if no annotationView is available
22428	Converts milliseconds to hours. < br > For instance if millis = 1 hr 32 min , 1 hour will be returned
22783	Changes the program . The previous program will be released . < p/ > The appropriate EGL context must be current .
22879	Finds a view that was identified by the id attribute from the XML that was processed in onCreate ( Bundle ) .
23073	Resolve logger property by its name - system property value if available , or logger property extracted from the log configuration .
23076	[ % SkillCaster ] inflicted % num0 damage and the rune carve effect on you by using [ % SkillName ] .
23086	is the entry returned already matched against the searching template currently is true if the underlying scan made by CacheManager : :EntriesIter
23115	Returns < code > true < /code > if this class Replicatable , otherwise < code > false < /code > .
23155	This method is called in case of cache-miss It can return NULL if it 's not possible to resolve the missing instance
23379	This all-in-one method reads a message log from the given file and turns that into a list of MQTT message objects .
23506	`` Only for advertising agencies . '' ID of the client with the advertising account where the group will be created .
23509	Read from cache by group but if the is not data available then read from the loader and cache its element .
23634	given a class name return the SL of matching templates . This API is more efficient than direct use of templates iterator
23709	Handle a puncture . Does nothing because the only purpose of a puncture is to punch a hole in the NAT .
23717	Checks whether the given value is present among the options in the option set of this attribute , matching on code .
23725	Starts the output of a set of data . Audio data for a single utterance should be grouped between begin/end pairs .
23753	Calculates the angle between two given lines . The provided Entry objects mark the starting and end points of the lines .
23756	Perform a HTTP PUT request and track the Android Context which initiated the request . And set one-time headers for the request
23835	% 0 is where it is indicated on the map , but the path leading to it can not be found .
23858	Print every value on a separate line . Use tabs ( < code > \t < /code > ) for indentation .
23884	Invalidates this table 's cached schema . This method should be called whenever columns are added or removed from this table .
24087	Filter-line of the request ( for 'countries , regions , cities , streets , schools , interests , positions ' ) .
24173	Request for enable the device 's bluetooth asynchronously . Throw a NullPointerException if the device does n't have a bluetooth module .
24265	Clicks the item in the dropdown list . Item is identified by the provided index . First item has index 0 .
24289	Create the GUI and show it . For thread safety , this method should be invoked from the event dispatch thread .
24397	Update the global references . If table is complete , move on to next table , else move to next row .
24416	Reads a `` float '' value from an InputStream . The value is converted to the opposed endian system while reading .
24419	Identifier of a user or community to add a video to . Use a negative value to designate a community ID .
24441	Adds the given path to the list of 'test ' directories . It also creates the directory in the file system .
24458	Shuts down the < code > EmbeddedCacheManager < /code > instance created by this < code > FactoryBean < /code > .
24467	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
24473	Switches to the previous browser tab . If called when first tab is active , then switches to the last one .
24595	Add the given file to the representation . This is a no-op if the given path already exists within the tree .
24679	Writes a `` float '' value to an OutputStream . The value is converted to the opposed endian system while writing .
24694	[ % SkillTarget ] is in the weaken % 0 state because [ % SkillCaster ] used [ % SkillName ] .
24748	Determine whether the current invoker should be rescheduled , given that it might not have received a message in a while .
24926	Preserve source-level annotations -- . Preserves annotations of retention type SOURCE . ( for everything but package and local variable annotations )
24939	This method converts dp unit to equivalent pixels , depending on device density . NEEDS UTILS TO BE INITIALIZED BEFORE USAGE .
24994	Every time the state changes we write all the jobs in one swath , instead of trying to track incremental changes .
25005	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
25098	Call for extending classes to override for getting additional information for an entry from the tab state when it is deserialized .
25219	Returns true if this range contains ( if the value is in between ) the given value , false if not .
25321	[ % SkillTarget ] 's mantra skill MP consumption has decreased because [ % SkillCaster ] used [ % SkillName ] .
25328	Get a hashCode for the real vector . < p > All NaN values have the same hash code. < /p >
25387	Split sequences into 1 or more other sequences . Used for example to split large sequences into a set of smaller sequences
25572	It stops the thread and removes the reference to the PersistenceManager object so its memory can be released by the garbage collector
25577	Produce a JSONArray of JSONObjects from a comma delimited text string , using the first row as a source of names .
25604	`` Only for advertising agencies . '' ID of the client with the advertising account where the group will be created .
25762	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
25792	Saves an offline copy for the specified tab that is bookmarked . A snackbar will be shown to notify the user .
25893	Converts milliseconds to minutes. < br > For instance if millis = 1 hr 32 min , 32 min will be returned
25976	Returns a number clamped between two other numbers . < p > This method assumes that min & le ; max .
26023	Returns the integer value stored in this object for the given key . Returns 0 if there is no such key .
26040	Add an object o to the vector if it is not already present as defined by the function HashSet.contains ( o )
26053	Invalidates this table 's cached schema . This method should be called whenever columns are added or removed from this table .
26070	Check if a given point in the CoordinatorLayout 's coordinates are within the view bounds of the given direct child view .
26137	Loads configurations : Process PIK and Process Configuration . Catches RuntimeException coming from errors while parsing PIK or Configurations XML files .
26184	Checks whether all required parameters depending on the mode are specified via command lines arguments . Only DPP-specific parameters are validated .
26303	Enables the highlight-line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
26329	Does the roll back process , writes a rollback record to the log , and flushes the log record to disk .
26382	is the entry returned already matched against the searching template currently is true if the underlying scan made by CacheManager : :EntriesIter
26384	Make a name for the role type corresponding to the object ( i.e . range ) of an OWL object property .
26407	Open the SlidingMenu and show the secondary menu view . Will default to the regular menu if there is only one .
26524	is the entry returned already matched against the searching template currently is true if the underlying scan made by CacheManager : :EntriesIter
26554	Reads a `` short '' value from an InputStream . The value is converted to the opposed endian system while reading .
26562	Connects to all the registered brokers ( individual JMSSenders should implement this on separate threads if the connection is unessential ) .
26622	Remove all key/value assocaition . This tries to save a bit of GC'ing by at least keeping the fBuckets array around .
26856	NodeList method : Return the Nth immediate child of this node , or null if the index is out of bounds .
26877	Convenient function that maps new Locals to the originating Local , and finds the appropriate array index into the naming structures .
26932	Will be called before any tests of a class are invoked . Creates an APIServerConnector and tries to ping the service .
26965	Returns the field ref node having this node as its base , and field as its field ; null if nonexistent .
26966	Creates a lint client used for in-editor single file lint analysis ( e.g . background checking while user is editing . )
27103	Returns true is new operations can still attach to this transaction , false otherwise ( transaction was already committed for example )
27111	Enables the highlight-line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
27132	Writes an < code > int < /code > to the bytes message stream as four bytes , high byte first .
27276	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
27289	Tests whether the user has the given authority . Returns true in any case if the user has the ALL authority .
27387	If the Pokemon has been `` caught '' it plays a sound and displays a message to let the user know .
27456	[ % SkillCaster ] has caused [ % SkillTarget ] to recover HP over time by using [ % SkillName ] .
27501	Computes the normalized quaternion ( the versor of the instance ) . The norm of the quaternion must not be zero .
27507	Id of the name change request to be canceled . If this paremeter is sent , all the others are ignored .
27581	Prints a formatted string to standard output , using the specified format string and arguments , and then flushes standard output .
27658	Get the high order bits from the mantissa . Equivalent to adding and subtracting HEX_40000 but also works for very large numbers
27717	% 0 entrusted % 1 with the league leadership authority . From now on , % 1 is the league leader .
27966	Adds the given path to the list of 'java ' directories . It also creates the directory in the file system .
27973	Attempts to reduce the memory consumption of this builder by reducing its capacity to a smaller , yet still sufficient value .
28073	Returns the double value stored in this object for the given key . Returns 0.0 if there is no such key .
28103	Adds the given diphone to the DB . Diphones are kept in a map so they can be accessed by name .
28107	Animates the appearance of the search provider icon sprite . This should be called after the panel open animation has finished .
28214	This is called when Soot finishes executing all interprocedural phases . Paddle uses it to stop profiling if profiling is enabled .
28280	The object in field is retrieved out by field ID . private static native java.lang.Object getObjectFieldValue ( java.lang.Object , long ) ;
28498	Attempts to record the final status for a job . Logs any errors , but always returns without throwing an exception .
28518	Returns the boolean value stored in this object for the given key . Returns false if there is no such key .
28580	Converts rFrameRate in a form `` 50/1 '' or `` 50 '' to the edit rate form `` 50 1 '' .
28875	< code > add < /code > adds the values of a provided vector storing the values in the supplied vector .
29195	Generate a text representation of the vuid , breaking out its individual components -- user , app , isolated , etc .
29266	Check whether the given String is an identifier according to the EJB-QL definition . See The EJB 2.0 Documentation Section 11.2.6.1 .
29449	Produce a JSONArray of JSONObjects from a comma delimited text string using a supplied JSONArray as the source of element names .
29808	Clears this data object from all DataSets and removes all Entries . Do n't forget to invalidate the chart after this .
29829	Perform a mathematical operation ( add , subtract , scalar max etc ) on the specified long column , with a scalar
29863	decrement the number of users using ( i.e locking + waiting + finished & not released yet ) of the lock object
29933	is the entry returned already matched against the searching template currently is true if the underlying scan made by CacheManager : :EntriesIter
29979	Sets the flag to indicate that there will be no more tests . Waits for reporting thread to finish its job .
29989	For a long value x , this method returns +1L if x > = 0 and -1L if x < 0 .
30121	Starts the output of a set of data . Audio data for a single utterance should be grouped between begin/end pairs .
30181	Returns the set of objects pointed to by instance field f of the objects pointed to by l in context c .
30195	[ % SkillTarget ] is in the boost % 0 state because [ % SkillCaster ] used [ % SkillName ] .
30198	Parse a boolean query parameter value Unlike Boolean.parseBoolean this will treat any value except null , false and 0 as true .
30211	Sets this vector to the interpolation by changeAmnt from this to the finalVec this= ( 1-changeAmnt ) *this + changeAmnt * finalVec
30214	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
30223	Returns the string value stored in this object for the given key . Returns null if there is no such key .
30238	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
30243	Get a hashCode for the 3D vector . < p > All NaN values have the same hash code. < /p >
30356	Cancels an Activity and removes it from this manager , called by an Activity when the activity needs to be cancelled .
30362	Events settings ( for public pages only ) . < p > Possible values : false - disabled ; true - enabled
30389	This method converts dp unit to equivalent pixels , depending on device density . NEEDS UTILS TO BE INITIALIZED BEFORE USAGE .
30395	convert tempo to microsecond with given tempo Does not take tempo changes into account . Does not work for SMPTE timing !
30431	Returns true if this method is not phantom , abstract or native , i.e . this method can have a body .
30504	Adds the given path to the list of 'resources ' directories . It also creates the directory in the file system .
30520	[ % SkillTarget ] is in the no elemental defense state because [ % SkillCaster ] used [ % SkillName ] .
30524	Returns the set of objects pointed to by instance field f of the objects pointed to by l in context c .
30585	Links settings ( for public pages only ) . < p > Possible values : false - disabled ; true - enabled
30652	Writes a < code > short < /code > to the bytes message stream as two bytes , high byte first .
30692	Tracks the # of bytes that have been moved . Returns true if the splitter should create a new destination segment .
30776	Returns the long value stored in this object for the given key . Returns 0 if there is no such key .
30782	[ % SkillTarget ] is in the elemental maximum defense state because [ % SkillCaster ] used [ % SkillName ] .
30895	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
30921	Removes the reference to the module from the settings file , if present . Must be run inside a write action .
30934	Put a key/value pair in the JSONObject , where the value will be a JSONObject which is produced from a Map .
30977	Append either the value < code > true < /code > or the value < code > false < /code > .
31008	Returns a histogram that approximates the join frequency distribution of the projected values from the specified histograms onto the specified fields .
31068	Returns the WorkspacePath for the given absolute file , if it 's a child of this WorkspaceRoot . Otherwise returns null .
31103	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
31128	ID of the user or community that owns the audio file . Use a negative value to designate a community ID .
31232	Cancels the particle system and all the animations . To stop emitting but animate until the end , use stopEmitting instead .
31262	Execute the full sequence of transformations for a single time series ( sequence ) . May return null if example is filtered
31299	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
31417	[ % SkillCaster ] suffered % num0 damage and dispelled some of its magical buffs by using [ % SkillName ] .
31655	Perform a HTTP PUT request and track the Android Context which initiated the request . And set one-time headers for the request
31687	Marks the end of a set of data . Audio data for a single utterance should be groupd between begin/end pairs .
31729	Enables the highlight-line to be drawn in dashed mode , e.g . like this `` - - - - - - ''
31794	Return the object that contains the JSpaceProxyWrapper . If the object stored as MarshalledObject , so returns the unMarshalling object . get
31904	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
31939	Highlights the value at the given x-position in the given DataSet . Provide -1 as the dataSetIndex to undo all highlighting .
31950	Check for and report literal-out-of-bounds error . If the constant is error-marked , there exists a literal out of bounds error .
32043	Filter-line of the request ( for 'countries , regions , cities , streets , schools , interests , positions ' ) .
32093	Look for the specified class . Return a ClassSource for it if found , or null if it was not found .
32388	Removes the last occurrence of the word `` or '' from the given string , including potential trailing spaces , case-insensitive .
32424	Produce a JSONArray of JSONObjects from a comma delimited text string , using the first row as a source of names .
32483	Sets the transform of the provided Graphics context to be the transform of this Display and sets the desired rendering hints .
32639	[ % SkillTarget ] was put in the magical counterattack state because [ % SkillCaster ] used [ % SkillName ] .
32756	It tells if the current ( in-memory ) tree representing a product 's bill of materials is completely configured or not .
32806	Removes the content with the given uid . Returns true if a content with the given uid existed and was removed .
32894	[ % SkillTarget ] is in the weaken % 0 state because [ % SkillCaster ] used [ % SkillName ] .
33038	Creates a new attribute which has the same attribute type and attribute options as the provided attribute but no attribute values .
33054	Merges all runs on the stack until only one remains . This method is called once , to complete the sort .
33059	Invoked when the mouse button has been moved on a component ( with no buttons no down ) . < P >
33110	Dispatch the order to the infrastructure layer . Here we simply save the order to the persistence and modify inventory changes .
33152	Returns the children of the receiver . If the receiver is not currently expanded , this will return an empty enumeration .
33351	Requeues a periodic task unless current run state precludes it . Same idea as delayedExecute except drops task rather than rejecting .
33541	Constructs a new < code > String < /code > by decoding the specified array of bytes using the UTF-8 charset .
33585	Decodes a < code > String < /code > native for use as a < code > DataFlavor < /code > .
33628	This method will be invoked when a service 's schema has been changed . It is a no-op for this implementation .
33742	Converts String representation of IP address to a long . No nee for error checking as IP has already been validated .
33825	Forwards the message from the < code > CellEditor < /code > to the < code > delegate < /code > .
33913	Registers the provided internal plugin with this plugin config manager and ensures that it will be invoked in the specified ways .
33990	Returns an iterator over the elements in this queue . The iterator does not return the elements in any particular order .
34037	Determine the exact visual footprint of the all apps button , taking into account scaling and internal padding of the drawable .
34230	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
34395	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
34503	Reads the bytes to the buffer . This method will try to read as many bytes as the buffer can hold .
34585	Checks for interrupt , returning THROW_IE if interrupted before signalled , REINTERRUPT if after signalled , or 0 if not interrupted .
34663	This method adds an attribute the the current element , but should not be used for an xsl : attribute child .
34695	Invoked when a key has been typed . This event occurs when a key press is followed by a key release .
34706	Alters the configuration of the SASL EXTERNAL mechanism handler so that it uses the Subject DN to User Attribute certificate mapper .
34714	Create Link to Image File , not recommended because if either flac or image file is moved link will be broken .
34748	Tells whether the user specified to have a script-friendly output or not . This method must be called after calling parseArguments .
34788	Generates and initializes a < i > Certificate Revocation List < /i > ( CRL ) from the provided input stream .
34831	Overridden to fix 4759054 . Must return true so that content is painted when inside a CellRendererPane which is normally invisible .
34836	7.2.20 parseTypeOtherPropertyElt start-element ( URI == propertyElementURIs , attributes == set ( idAttr ? , parseOther ) ) propertyEltList end-element ( )
34843	Move the current point < i > ( x , y ) < /i > , omitting any connecting line segment .
35000	Load the local class equivalent of the specified stream class description , by using the class loader assigned to this Context .
35020	Marshals to < code > output < /code > the value in this < code > ShortHolder < /code > object .
35233	Closes the current subpath by appending a straight line segment from the current point to the starting point of the subpath .
35265	Returns the number of < code > Subject < /code > elements in this < /code > Subjects < /code > object
35388	Removes the listener from the organization for the given listener ID . The ID was issued when the listener was registered .
35412	Converts the given < code > int < /code > to the corresponding < code > SetOverrideType < /code > instance .
35423	Removes the peer for this list . The peer allows us to modify the list 's appearance without changing its functionality .
35469	This method is called when the beginning of a matching XML element is encountered . The default implementation is a NO-OP .
35486	Initializes this plugin configuration manager . This should only be called at Directory Server startup and before user plugins are loaded .
35589	Paints the foreground of a progress bar . is responsible for providing an indication of the progress of the progress bar .
35594	Returns a string representation of this stub . Returns the same string for all stubs that represent the same remote object .
35886	Indicates whether or not provided value has the same hour and minute as the < code > compareDate < /code > .
35895	Writes a message to the access logger with information about the modify DN request associated with the provided modify DN operation .
35924	Searches for filtered roles in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
35940	Creates and configures a new unmarshalling pipe line . Depending on the setting , we put a validator as a filter .
35950	Build authentication mechanism that will log out at the end of RoboZonky 's operations . This will ignore the access tokens .
36245	Returns true if debug information is enabled for this < code > JComponent < /code > or one of its parents .
36466	Returns a < a href= '' ../../../../serialized-form.html # java.util.concurrent.atomic.LongAdder.SerializationProxy '' > SerializationProxy < /a > representing the state of this instance .
36611	Obtains the primary order of the specified collation element , i.e . the first 16 bits . This value is unsigned .
36640	Tell the menu selection to close and unselect all the menu components . Call this method when a choice has been made
36734	Marks the present position in the stream . Subsequent calls to reset ( ) will reposition the stream to this point .
36822	Check if the values in the specified implementation are valid . Currently this just involves checking the values are non null .
36850	Returns < code > true < /code > if option is to be displayed as text area in web based CLI .
36949	A new service is available from the nesting BeanContext . Subclasses may override this method in order to implement their own behaviors
37037	Unregisters the listener from the component for the given listener ID . The ID was issued when the listener was registered .
37133	Returns a schema initialized with new attributes types `` at1 '' , `` at2 '' , ... , `` at9 '' .
37140	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
37197	Utility method to run the query on the db and return the value in the first column of the first row .
37345	Tells whether the user specified to have an interactive operation or not . This method must be called after calling parseArguments .
37400	Returns the TaskRunnable previous to this TaskRunnable in the linked-list . The correct HeadTaskRunnable must be locked before calling this function .
37482	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
37509	Method to to distinguish struct elements from other elements of the logical tree ( like mcr or struct tree root ) .
37513	Return the unicode code point represented by the high/low surrogate pair . < p > This is not a public API .
37544	This flag is set if the parsing code saw : targetattr= '' * '' or targetattr ! = `` * '' .
37552	Normalize the request resource specifically for entitlement . Get rid of ? * for entitlement engine . Also used by URLResourceName .
37592	reverse the elements ' sequence < br > the method will modify the current List and wo n't generate a new List
37685	Searches for dynamic groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
37700	Tells whether the user specified to have a quite operation or not . This method must be called after calling parseArguments .
37736	NodeList method : Return the Nth immediate child of this node , or null if the index is out of bounds .
37812	Creates a < code > Service < /code > instance . The created instance is configured with the web service features .
37834	Flushes this buffered output stream . This forces any buffered output bytes to be written out to the underlying output stream .
37948	Searches for all roles in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
37991	Returns true if there are some marker associated with component < code > comp < /code > in a markers ' queue
38096	Create and return a < code > MBeanParameterInfo < /code > object that corresponds to the parameter described by this instance .
38099	Find and set the byte value of a given field named < code > name < /code > in the receiver .
38107	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
38164	Checks if the < code > hostName < /code > is the same as the one used by the OpenAM SDK .
38249	Sets the tracker color used by the barcode scanner , By default this is Material Red 500 ( # F44336 ) .
38252	Replaces the enumeration from the stream with a real one . This ensures that the correct flag is set for SYSTEM .
38257	Copies or connects an object . Used by local stubs to copy an actual parameter , result object , or exception .
38351	Specifies whether this resource is an abstract type and therefore can not be created . Only non-abstract sub-types can be created .
38416	Adds the provided optional attributes to the list of attribute types that entries subject to this DIT content rule may contain .
38441	Called whenever DATABASE_VERSION is incremented . This is used whenever schema changes need to be made or new tables are added .
38766	Computes the hash code of this reference . The hash code is the sum of the hash code of its addresses .
38822	Certain logging behaviors are available for debugging beyond those that should be enabled in production . Disables all extended logging behaviors .
38904	Reset the header buffer if an error occurs during the writing of the headers so the error response can be written .
38958	Forwards the message from the < code > CellEditor < /code > to the < code > delegate < /code > .
38972	Writes a CharSequence to a file creating the file if it does not exist using the default encoding for the VM .
39005	Returns the first unmatched node of the given mode , or null if none . Used by methods isEmpty , hasWaitingConsumer .
39068	Messaged when the menubar selection changes to activate or deactivate this menu . Overrides < code > JMenuItem.menuSelectionChanged < /code > .
39165	Writes a String to a file creating the file if it does not exist using the default encoding for the VM .
39271	Visits a type instruction . A type instruction is an instruction that takes the internal name of a class as parameter .
39422	Returns the first unmatched node of the given mode , or null if none . Used by methods isEmpty , hasWaitingConsumer .
39454	Returns a hash code value for this integer attribute . The hash code is just this integer attribute 's integer value .
39623	Removes the listener from the organization for the given listener ID . The ID was issued when the listener was registered .
39670	Merges all runs on the stack until only one remains . This method is called once , to complete the sort .
39910	Makes the area outside this Outline to Keepout , Reinserts this Outline into the search trees , if the value changes .
39983	Adds the node < code > newChild < /code > to the end of the list of children of this node .
39991	When this handler is connected to a replication server , specifies if a wanted server is connected to this replication server .
40004	Determines if the object is enabled . Objects that are enabled will also have the AccessibleState.ENABLED state set in their AccessibleStateSets .
40019	Returns a hash code value for the object which is the same for all stubs that represent the same remote object .
40063	Creates a function which extracts the user 's credentials from custom HTTP header in addition of the standard HTTP Basic one .
40255	Generates a mock request which will simulate the required behaviour of requesting the now deprecated behaviour of returning the remaining results .
40302	Finds a view that was identified by the id attribute from the XML that was processed in onCreate ( Bundle ) .
40319	Destroys the specified surface . Note the EGLSurface wo n't actually be destroyed if it 's still current in a context .
40368	Adds the provided membership exception so that it will be thrown along with the set of results for this member list .
40510	Writes out an error debug ( if a throwable and debug message are provided ) and returns a user-facing error page .
40631	Stores received data . The source data is not cloned , just the array reference is remembered into the buffer field .
40680	Returns true if this DigitList represents Long.MIN_VALUE ; false , otherwise . This is required so that getLong ( ) works .
40694	Depending on the Connection State ( Session ) encrypts and compress the provided data , and packs it into TLSCiphertext structure .
40738	Paints the foreground of a progress bar . is responsible for providing an indication of the progress of the progress bar .
40742	Invoked when a window is in the process of being closed . The close operation can be overridden at this point .
41037	Returns < code > true < /code > if this authentication module instance editable by this user and/or in this realm .
41283	add Collection to set of Children ( Unsupported ) implementations must synchronized on the hierarchy lock and `` children '' protected field
41314	Returns < code > true < /code > since this < code > ImageInputStream < /code > maintains a file cache .
41315	Writes a `` short '' value to an OutputStream . The value is converted to the opposed endian system while writing .
41473	Invalidates all drill pages intersecting with p_shape , so the they must be recalculated at the next call of get_ddrills ( )
41486	Find and set the float value of a given field named < code > name < /code > in the receiver .
41490	Forwards the message from the < code > CellEditor < /code > to the < code > delegate < /code > .
41510	Returns < code > true < /code > if current service configuration uses the realm model to store the configuration data .
41527	Invoke this method to print the component . This method invokes < code > print < /code > on the component .
41574	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
41713	Registers the provided initialization completed listener with the Directory Server so that it will be notified when the server initialization completes .
41756	Writes a message to the access logger with information about the modify DN response associated with the provided modify DN operation .
41837	This marks that player has collided with tile . The brick logic will not be run unless this condition is satisfied .
41861	Alters the configuration of the SASL EXTERNAL mechanism handler so that it uses the Subject DN to User Attribute certificate mapper .
41897	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
42003	Helper method that returns the number of bytes that would be used by the boolean fields when appended to a ByteArrayBuilder .
42010	Adds a < code > PropertyChangeListener < /code > to the listener list . The listener is registered for all properties .
42044	Searches for static groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
42130	Brings up a dialog where the number of choices is determined by the < code > optionType < /code > parameter .
42211	Returns a shallow copy of this < tt > HashSet < /tt > instance : the elements themselves are not cloned .
42244	Registers for changes to the component 's configuration . The object will be called when configuration for this component is changed .
42519	Provides the command line arguments to the < CODE > mainDiff < /CODE > method so that they can be processed .
42552	Reloads all edit modes . User defined edit modes are loaded after global modes so that user modes supercede global modes .
42558	Returns the TaskRunnable next to this TaskRunnable in the linked-list . The correct HeadTaskRunnable must be locked before calling this function .
42583	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
42639	Terminates the current element , usually a page . Sets the next element to be the size specified in the argument .
42660	Converts the Attribute to an attribute name , set of String values map and adds it to the map passed in .
42688	Returns the hash code for this name form . It will be calculated as the hash code of the numeric OID .
43052	Removes the provided optional attribute in the list of attribute types that entries subject to this DIT content rule may contain .
43165	Returns a Map containing the specified key and value . The map can not be modified . The map is serializable .
43200	Creates a button which will be used as the control to show or hide the popup portion of the combo box .
43210	Unregisters the listener from the component for the given listener ID . The ID was issued when the listener was registered .
43220	Remove any configuration attribute associated with the specified name . If there is no such attribute , no action is taken .
43240	Trims the string , removing all whitespace at the beginning and end of the string . Non-breaking whitespaces are also removed .
43373	Searches for all roles in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
43400	generate an X509 certificate , based on the current issuer and subject , using the passed in provider for the signing .
43443	Add an object in this queue . If the object is already in the waiting sub-queue , it is silently ignored .
43471	Obtains the tertiary order of the specified collation element , i.e . the last 8 bits . This value is unsigned .
43479	Removes a membership listener from the channel. < br > Membership listeners are uniquely identified using the equals ( Object ) method
43501	Adds a segment to the subpath . Note : each new segment shall start at the end of the previous segment .
43505	add a given extension field for the standard extensions tag ( tag 3 ) copying the extension value from another certificate .
43519	Adds the given type name to the import list . Returns an empty string so that the output is not affected .
43554	Mappings can share the same link tables . Establish the relationship between the mappings and determine the proper link type to use
43614	Returns the number of < code > Condition < /code > elements in this < /code > Conditions < /code > object
43731	Returns the other room of this door , or null , if p_roon is neither equal to this.first_room nor to this.second_room .
43879	Helper method that returns the number of bytes that would be used by the long fields when appended to a ByteArrayBuilder .
43963	Creates assignable dynamic group . Takes serviceNameAndAttr map so that services can be assigned to the group which is just created .
44049	This method for implementing ServiceListener . As this object listens for changes in schema of amConsoleService . this method is No-op .
44145	Stop processing messages for this provider . Post an empty message to our message processing queue that signals us to quit .
44250	Returns a scroll pane border listener that will apply a border on the bottom and on the top of the scroll .
44261	Removes the listener from the service for the given listener ID . The ID was issued when the listener was registered .
44340	Returns the hash code for this matching rule . It will be calculated as the hash code of the numeric OID .
44389	Registers for changes to the component 's configuration . The object will be called when configuration for this component is changed .
44409	Calls an event with the given details . < p > This method only synchronizes when the event is not asynchronous .
44586	Get response stream from POST to URI . It is the responsibility of the calling method to close the returned stream .
44630	Registers a task . The Control Panel creates a task every time an operation is made and they are stored here .
44676	Inserts content from the given stream which is expected to be in a format appropriate for this kind of content handler .
44695	Unregisters the listener from the service for the given listener ID . The ID was issued when the listener was registered .
44711	Merges all runs on the stack until only one remains . This method is called once , to complete the sort .
44734	Causes the Runnable r to be added to the message queue . The runnable will be run on the main thread .
44819	This methods adds a new name to the specified NameTree . It throws an exception , if the name already exists .
44823	This method for implementing ServiveListener . As this object listens for changes in schema of amConsoleService . this method is No-op .
44911	Marks the present position in the stream . Subsequent calls to reset ( ) will reposition the stream to this point .
44930	Append the current template element to the current template element , and then push it onto the current template element stack .
44945	When the handler is connected to a replication server , specifies the replication server has remote LDAP servers connected to it .
45036	Writes a `` double '' value to an OutputStream . The value is converted to the opposed endian system while writing .
45087	Stops the Logic Execution and goes to display final ending sequence based on whether player failed or succeeded in completed stage .
45114	Returns the number of < code > ResponseProvider < /code > elements in this < /code > ResponseProviders < /code > object
45116	Figure out if we 're executing a toplevel expression . If so , we ca n't be inside of a predicate .
45259	Undeclare the namespace that is currently pointed to by a given prefix . Inform SAX handler if prefix was previously mapped .
45320	Determine if two types ( JAXBContext in this case ) will generate a ClassCastException . For example , ( targetType ) originalType
45341	Check if a String from a Matcher group is absent . Matcher returns empty strings for optional groups that are absent .
45361	This method translates the < code > AssertionArtifact < /code > to an XML document String based on the SAML schema .
45375	Removes the provided required attribute in the list of attribute types that entries subject to this DIT content rule must contain .
45494	Returns a < a href= '' ../../../../serialized-form.html # java.util.concurrent.atomic.LongAccumulator.SerializationProxy '' > SerializationProxy < /a > representing the state of this instance .
45501	If the Fireball has collided and resources are freed , and the Fireball object is ready to be removed from game-loop .
45566	Called when the component containing the caret loses focus . This is implemented to set the caret to visibility to false .
45587	This method is called when the end of a matching XML element is encountered . The default implementation is a NO-OP .
45609	Searches for sub organizations in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
45718	Convenience method that moves this component to position 0 if its parent is a < code > JLayeredPane < /code > .
45785	Decodes a byte array from Base64 format . No blanks or line breaks are allowed within the Base64 encoded input data .
45989	Invalidates all drill pages intersecting with p_shape , so the they must be recalculated at the next call of get_ddrills ( )
46058	Do whatever is needed when a backup is started . We need to make sure that the serverState is correctly save .
46089	Notifies the registered LDIF import task listeners that the server has completed processing on an import task with the provided information .
46145	Guesses the length of a formatted protocol version . Needed to guess the length of a formatted request or status line .
46200	Constructs a SOAPMessage with specified fault code and fault string . The fault code will have same namespace of soap envelope .
46203	Adds a membership listener to the channel. < br > Membership listeners are uniquely identified using the equals ( Object ) method
46495	Marshals to < code > output < /code > the value in this < code > ByteHolder < /code > object .
46536	Clears the default hyphenation tree cache . This method can be used if the underlying data files are changed at runtime .
46539	Generates the endpoints for the CRUD Operations table . The endpoints for this table take one index - the operation type .
46618	returns true if there no files to verify . should only be called after all the META-INF entries have been processed .
46666	Create and return a < code > ModelMBeanNotificationInfo < /code > object that corresponds to the attribute described by this instance .
46699	Removes the listener from the service for the given listener ID . The ID was issued when the listener was registered .
46749	Adds a member to the list that shows methods overriding this . < br > TODO : Better name for this method
46972	Creates a new entry change notification response control with the provided change type and optional previous distinguished name and change number .
47024	generate an X509 certificate , based on the current issuer and subject , using the passed in provider for the signing .
47037	Indicates whether the provided attribute type is included in the required attribute list for this or any of its superior objectclasses .
47068	Adds the provided argument to the set of arguments handled by this parser and puts the argument in the default group .
47094	An easy way to set up non-home ( no back button on the toolbar ) activity to enable go back action .
47141	Returns a < a href= '' ../../../../serialized-form.html # java.util.concurrent.atomic.DoubleAdder.SerializationProxy '' > SerializationProxy < /a > representing the state of this instance .
47148	Append a DN to this ByteArrayBuilder by converting it to a String then encoding that string to a UTF-8 byte array .
47164	DOM Level 3 Returns whether this text node contains whitespace in element content , often abusively called `` ignorable whitespace '' .
47174	Removes all of the geometry from this < code > Area < /code > and restores it to an empty area .
47479	Marshals to < code > output < /code > the value in this < code > TypeCodeHolder < /code > object .
47532	Do nothing as this is an abstract class . All subclasses will need to define their behavior if it is different .
47553	Find and set the short value of a given field named < code > name < /code > in the receiver .
47585	Writes a `` float '' value to an OutputStream . The value is converted to the opposed endian system while writing .
47603	Creates a < code > TextHitInfo < /code > at the specified offset , associated with the character after the offset .
47620	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
47677	This method needs to override AxesWalker.acceptNode because FilterExprWalkers do n't need to , and should n't , do a node test .
47702	Potentially update the oldest CSN stored in this entry historical with the provided CSN when its older than the current oldest .
47756	Initializes the configuration framework using the application 's class loader as the parent class loader , and the provided install/instance path .
47863	Adds a channel listener to the channel. < br > Channel listeners are uniquely identified using the equals ( Object ) method
47902	Marshals to < code > output < /code > the value in this < code > CharHolder < /code > object .
47923	Find and set the char value of a given field named < code > name < /code > in the receiver .
48091	Merges all runs on the stack until only one remains . This method is called once , to complete the sort .
48201	Find and set the int value of a given field named < code > name < /code > in the receiver .
48280	Use the DN from the geteffectiverights control 's authzId as the client DN , rather than the authorization entry 's DN .
48514	Returns a copy of the listeners with DN as strings . Use strings to avoid holding copies on the old schema .
48595	Returns a copy of the permissions component . < p > The returned set is a modifiable copy of the permissions .
48667	Notifies the activity that a support action mode has finished . Activity subclasses overriding this method should call the superclass implementation .
48808	Updates the module instance table for the authentication service if the module instance table was already cached for the provided realm .
49057	Append an int to this ByteArrayBuilder by converting it to a String then encoding that string to a UTF-8 byte array .
49159	Adds this matching rule use definition to the schema overwriting any existing matching rule use definition with the same numeric OID .
49177	Resolves the correct port for this scheme . Returns the given port if it is valid , the default port otherwise .
49283	This method is required to conform to the < code > MenuElement < /code > interface , but it not implemented .
49341	Returns true if the version of the server is an OEM one , and therefore does n't support the JE backend .
49476	Searches for filtered roles in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
49516	This method for implementing ServiveListener . As this object listens for changes in schema of amConsoleService . this method is No-op .
49561	Figure out if we 're executing a toplevel expression . If so , we ca n't be inside of a predicate .
49626	Inflate a rectangle by the passed value . The method return a new inflated rectangle and can alter the origin too .
49683	This protected method is final because , contrary to the superclass , it 's not used anymore by the other methods .
49807	Creates a new DIGEST-MD5 SASL bind request having the provided authentication ID and password , but no realm or authorization ID .
49981	Notifies the activity that a support action mode has finished . Activity subclasses overriding this method should call the superclass implementation .
49987	Append a long to this ByteArrayBuilder by converting it to a String then encoding that string to a UTF-8 byte array .
50117	Return the node at the tail of the vector without popping Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
50222	Returns < code > true < /code > if the attribute is searchable ; < code > false < /code > otherwise
50237	Searches for static groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
50602	Deletes a backend . The code assumes that the server is not running and that the configuration file can be edited .
50669	Checks if the binary version is the same than the instance version . If not , a configuration exception is thrown .
50721	Looks up touching pins at the first corner and the last corner of the trace . Used to avoid acid traps .
50818	Indicates whether or not provided value has the same hour and minute as the < code > compareDate < /code > .
50833	Checks if the Relation Service is active . Current condition is that the Relation Service must be registered in the MBean Server
50915	Invoked when a mouse button is pressed on the menu and then dragged . Delegates the mouse event to the MenuSelectionManager .
50939	Creates the peer for the list . The peer allows us to modify the list 's appearance without changing its functionality .
50976	Find and set the boolean value of a given field named < code > name < /code > in the receiver .
51071	Find and set the Object value of a given field named < code > name < /code > in the receiver .
51105	Marks the present position in the stream . Subsequent calls to reset ( ) will reposition the stream to this point .
51190	Visits the enclosing class of the class . This method must be called only if the class has an enclosing class .
51211	Apppends p_padstack to the list of via padstacks . Returns false , if the list contains already a padstack with p_padstack.name .
51212	Destroys this key . A call to any of its other methods after this will cause an IllegalStateException to be thrown .
51228	Creates a new instance of the specified class name Package private so this code is not exposed at the API level .
51249	Completes the hash computation by performing final operations such as padding . The digest is reset after this call is made .
51358	Creates a < code > TextHitInfo < /code > at the specified offset , associated with the character before the offset .
51458	Reset the collation elements to their initial state . This will move the 'cursor ' to the beginning of the text .
51565	Does nothing . If the developer really wants to change the size of one of the views JSplitPane.resetToPreferredSizes should be messaged .
51666	adjust the byte counts so that byteCount2 represents the upper long ( less 3 bits ) word of the byte count .
51732	Stores the contents of the model into the given stream . By default this will store the model as plain text .
51736	Remove a single node from the tree model . It takes care to cancel all the tasks associated to this node .
51860	Return the node one position from the tail without popping . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
51934	Reads a `` float '' value from an InputStream . The value is converted to the opposed endian system while reading .
51957	Accepts the user-defined task for execution . Note that by design this method is called only when this thread is idle .
51988	Search through each permission bind rule associated with this body and try and match a single right of the specified rights .
52086	Reads a `` double '' value from an InputStream . The value is converted to the opposed endian system while reading .
52123	Marshals to < code > output < /code > the value in this < code > ObjectHolder < /code > object .
52551	Broadcast a configuration change that just happened to the whole topology by sending a TopologyMsg to every entity in the topology .
52590	Changes the program . The previous program will be released . < p > The appropriate EGL context must be current .
52637	Indicates to the stream that all data has been written out , and any GZIP terminal data can now be written .
52742	Returns < CODE > true < /CODE > if the value changed and < CODE > false < /CODE > otherwise .
52789	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
52925	Perform any required finalization tasks for all authentication policies currently defined . This should only be called at Directory Server shutdown .
53011	Used , when the board frame with all the subwindows is disposed You should not mess up with the list of subwindows
53049	Creates and configures a new unmarshalling pipe line . Depending on the setting , we put a validator as a filter .
53082	Creates a new DIGEST-MD5 SASL bind request having the provided authentication ID and password , but no realm or authorization ID .
53096	Returns true if the Mapped object is considered to be a library object . Library objects are not to be modified .
53097	Inserts line breaks into the provided buffer to wrap text at no more than the specified column width ( 80 ) .
53137	Updates to `` bound '' properties will cause a `` PropertyChange '' event to get fired when the property is changed .
53141	Gets the next index . If we 're at the end of the table , we wrap back around to 0 .
53294	Adds a < code > VetoableChangeListener < /code > to the listener list . The listener is registered for all properties .
53297	Create and return a < code > ModelMBeanAttributeInfo < /code > object that corresponds to the attribute described by this instance .
53604	Converts the buffer 's contents into a string , translating bytes into characters according to the platform 's default character encoding .
53605	Convert this MutableBigInteger to a long value . The caller has to make sure this MutableBigInteger can be fit into long .
53754	Indicates whether or not scrolling will take place in response to the mouse wheel . Wheel scrolling is enabled by default .
53840	If this view is attached to window , and before the state chaned the rippling is play , start animation automatically .
53846	DOM Level 3 Returns whether this text node contains whitespace in element content , often abusively called `` ignorable whitespace '' .
53855	Returns the TLS handshake of the connection that carried this response , or null if the response was received without TLS .
53892	Searches for roles in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
53961	Invoked when a mouse button is pressed on the menu and then dragged . Delegates the mouse event to the MenuSelectionManager .
54070	Searches for organizations in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
54088	Given the last character in the resource , affirm whether a valid zero or more wildcard exists next in the tree .
54108	Returns the hash code for this object class . It will be calculated as the hash code of the numeric OID .
54130	ProgressUpdateListener implementation . Here we take the ProgressUpdateEvent and create a ProgressDescriptor that will be used to update the progress dialog .
54137	Adds testParams to the list of all failed test parameters , so that we know to NOT null it out later .
54220	Tells whether the user specified to have a quiet uninstall or not . This method must be called after calling parseArguments .
54297	Append the contents of the Access Log , Error Log , Debug Loggers , System.out , System.err to the specified buffer .
54366	Searches for dynamic groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
54406	Append to dest the remaining lines starting from pos If src_pos is zero and dest is empty this actually copy the list
54494	Writes this control value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
54646	Invokes the delegate 's < code > write ( char [ ] , int , int ) < /code > method .
54655	Creates the default editor kit ( < code > PlainEditorKit < /code > ) for when the component is first created .
54666	Returns true if this component is lightweight , that is , if it does n't have a native window system peer .
54678	Unregisters the listener from the service for the given listener ID . The ID was issued when the listener was registered .
54829	Append the current template element to the current template element , and then push it onto the current template element stack .
54900	Adds the given key and value pair into the map if the map does not already contain a value for that key
54969	Removes all the foos where uuid = & # 63 ; and companyId = & # 63 ; from the database .
55016	Visits the enclosing class of the class . This method must be called only if the class has an enclosing class .
55143	This sample has a single Activity , so we need to manually record `` screen views '' as we change fragments .
55157	Compares this < code > Timestamp < /code > object to the given < code > Date < /code > object .
55207	Serializes an < code > XMPMeta < /code > -object as RDF into an < code > OutputStream < /code > .
55241	Returns the hash code for this attribute syntax . It will be calculated as the hash code of the numeric OID .
55266	Checks for interrupt , returning THROW_IE if interrupted before signalled , REINTERRUPT if after signalled , or 0 if not interrupted .
55281	This method always returns false for unresolved permissions . That is , an UnresolvedPermission is never considered to imply another permission .
55329	Closes the path , fills it using the non-zero winding number rule to determine the region to fill and strokes it .
55333	Searches for sub organizations in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
55387	Determines if the client knows about the session , either from local object pre serialization or the stored value post serialization .
55538	Find and set the double value of a given field named < code > name < /code > in the receiver .
55545	Checks for interrupt , returning THROW_IE if interrupted before signalled , REINTERRUPT if after signalled , or 0 if not interrupted .
55547	Clamp the yTranslation of the child down such that its end is at most on the beginning of the bottom stack .
55560	Searches for organizational units in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
55575	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
55601	This flag is set if the parsing code saw : targetattr= '' + '' or targetattr ! = `` + '' .
55627	Tells whether the user specified to have a verbose uninstall or not . This method must be called after calling parseArguments .
55638	Overridden method to stop it being protected . Decrease the number of available permits by the amount in the supplied argument .
55647	Write a ByteChunk out at the current write position . A null ByteChunk is encoded as a string with length 0 .
55693	Return the node one position from the tail without popping . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
55810	If the start / end trim are offset to begin with , store them so that animation starts from that offset .
55834	Returns < code > true < /code > if the attribute is searchable ; < code > false < /code > otherwise
55886	Checks for interrupt , returning THROW_IE if interrupted before signalled , REINTERRUPT if after signalled , or 0 if not interrupted .
55920	Returns a copy of the flags component . < p > The returned set is a modifiable copy of the flags .
55937	Helper method that returns the number of bytes that would be used by the CSN fields when appended to a ByteArrayBuilder .
55982	Returns true if the SSOToken is valid , allowing the idle time to be reset only if the flag is true .
56092	Notifies the registered LDIF export task listeners that the server has completed processing on an export task with the provided information .
56103	Marshals to < code > output < /code > the value in this < code > AnyHolder < /code > object .
