225	Stops Sync if a user is currently signed in . Affects native sync , the invalidation controller , and the Android sync settings .
255	Tests if the specified < code > File < /code > is newer than the specified < code > Date < /code > .
318	Removes this user from the list of contacts of the Skype account . If the user is n't a contact , nothing happens .
448	Convenience method to create a new token with the type set to array and with the starting index set to the given index .
620	Returns true if given key greater than or equal to least and less or equal to fence . Needed mainly in submap operations .
707	Only Array Ref -- Annotate only array references . Annotate only array-referencing instructions , instead of all instructions that need null pointer checks .
843	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
984	Synchronous ad-blockers detection This is blocking and should be called in a separated thread . In Android activities , prefer the asynchronous version .
1110	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
1167	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
1195	Convenience method to create a new token with the type set to field and with the starting index set to the given index .
1266	Used for testing -- input is a full csv line : < freq , domain , ip , ts , opt : generic >
1337	Checks if the < code > byte < /code > < code > item < /code > is a member of this list .
1369	Returns the long value stored in this object for the given key . Returns the default value if there is no such key .
1426	Adds a ProductPromoAction to be used for free shipping ( must be of type free shipping , or nothing will be done ) .
1466	Is called when it gets detached from the view . It also removes all listeners like click , focusChange listeners and background selectors .
1470	Logs the rule in the specific log4j log , using the log4j renderer in the configuration file ( done after every update ) .
1475	method for reading the carbon dictionary sort index data from columns sortIndex file . In case of no member empty list will be return
1553	[ % Protector ] received % num0 damage inflicted on [ % SkillTarget ] , because of the protection effect cast on it .
1603	Add a notification task to the pending queue , and start an instance of the Notifier thread if one is n't already running .
1750	New caption for the photo . If this parameter is not set , it is considered to be equal to an empty string .
1831	Test whether the given node is unseen . If so , move current to it , and remember it as a seen node .
2031	Starts sync if the master sync flag is enabled . Affects native sync , the invalidation controller , and the Android sync settings .
2043	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
2158	Prints a formatted string to standard output , using the locale and the specified format string and arguments ; then flushes standard output .
2306	Print a start tag with attributes . The tag will be followed by a newline , and the indentation level will be increased .
2409	Returns the integer value stored in this object for the given key . Returns the default value if there is no such key .
2493	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
2494	Checks the current Variations parameters associated with the active group as well as the Chrome preference to determine if the service is enabled .
2523	Sets the fetch size that will be used when working with scrollable results . Defaults to < code > 100 < /code > .
2822	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
3007	Tests if the specified < code > File < /code > is older than the reference < code > File < /code > .
3077	X.logEquals ( ) calculates the natural logarithem of each element of the matrix . The result is stored in this matrix object again .
3222	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
3397	Checks whether this abstraction entails the given abstraction , i.e . this taint also taints everything that is tainted by the given taint .
3404	Tests if the specified < code > File < /code > is older than the specified < code > Date < /code > .
3438	Given a count of black/white/black pixels just seen and an end position , figures the location of the center of this black/white/black run .
3730	Returns the schema of the output table . The schema consists of the group fields , plus one field for each aggregation function .
3792	You are now under level % 0 curse of the Empyrean Lords for killing too many lower level targets in the opposition territory .
4029	Provides a string representation of an array . Calls < code > toString ( StringBuffer , Object , Class ) < /code > .
4067	Initiate fetching the user accounts data ( images and the full name ) . Fetched data will be sent to observers of ProfileDownloader .
4068	Translates the specified character , which is assumed to be in the `` Base 64 Alphabet '' into its equivalent 6-bit positive integer .
4166	Checks if there is any data to transmit so that the periodic flush task can determine if there is anything it needs to do
4273	Indicates if a given class type is a primitive integer type ( one of byte , short , int , or long ) .
4394	Instructs the LogNode to print the log data provided . Other LogNodes can be chained to the end of the LogNode as desired .
4455	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
4490	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
4493	Provides a string representation of an array . Calls < code > toString ( StringBuffer , Object , Class ) < /code > .
4873	Tests if the specified < code > File < /code > is newer than the specified < code > Date < /code > .
4978	Closes this zip file . This method is idempotent . This method may cause I/O if the zip file needs to be deleted .
4994	Return true whether this template should match by uid only ( if such provided ) or with full match regardless present if uid .
5020	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
5076	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
5171	Adds the specified value to the page at the position denoted by currentPos . Then increments currentPos by the size of the value .
5228	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
5255	Invokes the delegate 's < code > read ( byte [ ] ) < /code > method , detecting and optionally skipping BOM .
5312	When this option is set , the TileLayer only loads tiles that are in the given geographical bounds . < /br > default null
5581	Tests if the specified < code > File < /code > is newer than the specified < code > Date < /code > .
5631	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
5813	Returns the appropriate name for the 'android ' command , which is 'android.exe ' for Windows and 'android ' for all other platforms .
5866	Replaces the most recently stored value with the given value . There must be at least one element stored to call this method .
6097	Resets the component . The component can query the component manager about any features and properties that affect the operation of the component .
6136	true - additional fields `` likes , can_comment , can_repost , photos '' will be returned . These fields are disabled by default .
6185	Adds the name of a module that depends on a library , but the library is missing the path of the binary file .
6193	Returns < code > true < /code > if the character at start is ' Z ' , '+ ' or '- ' .
6226	Print a start tag without attributes . The tag will be followed by a newline , and the indentation level will be increased .
6281	Gets the fraction as a < tt > double < /tt > . This calculates the fraction as the numerator divided by denominator .
6407	Max redirects that is allowed per request . If < i > redirects < /i > are exhausted , fail the request immediately .
6735	Checks whether this name is the name of a well-known Android listener attribute . This is a function to allow for future extension .
6790	Registers a type URL for Any together with a default instance . Only instances which are registered here are rendered in clear text .
6793	Set the properties that the org.quartz Scheduler will use . Can only be called once , and only before a Job is added .
6886	Indicates whether the given JsonNode is empty , which implies that the node is not null and has a size greater than 0 .
6912	Returns true if the specified character is a valid name character as defined by production [ 4 ] in the XML 1.0 specification .
6950	< p > Constructs a < code > NumericEntityEscaper < /code > outside of the specified values ( exclusive ) . < /p >
6953	The original field name adjusted , if necessary , to conform to Avro 's field name requirements by prefixing it with an underscore .
7081	Loads and initializes OpenCV library from current application package . Roughly , it 's an analog of system.loadLibrary ( `` opencv_java '' ) .
7257	Is called when it gets detached from the view . It also removes all listeners like click , focusChange listeners and background selectors .
7420	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
7425	Only Array Ref -- Annotate only array references . Annotate only array-referencing instructions , instead of all instructions that need null pointer checks .
7797	Throws an exception if the current token is not an integer . Otherwise , returns that integer and moves to the next token .
7910	Tests if the specified < code > File < /code > is older than the specified < code > Date < /code > .
8070	Wire it up to use the passed Context , otherwise Robolectric uses a hidden Context and does n't actually do the correct thing .
8125	Specifies whether results should be read from the cache ( or written to the cache if the results have not yet been cached )
8195	returns if this entity triggers Block.onEntityWalking on the blocks they walk on . used for spiders and wolves to prevent them from trampling crops
8322	If true , panning wo n't fire movestart event on start ( used internally for panning inertia ) . < /br > default false
8351	You received % num0 damage as the [ % SkillName ] you used on [ % SkillTarget ] was reflected back at you .
8415	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
8416	[ % SkillCaster ] made [ % SkillTarget ] more resistant to crashing and prohibitions on flying by using [ % SkillName ] .
8440	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
8807	Notify that the given model has had its data changed . It should only be called if the model retained the same position .
8937	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
9033	Adds a report to the list of subreports of this report and adjusts the success flag and message ( message is appended ) .
9077	< code > add < /code > adds the provided values to this vector , creating a new vector that is then returned .
9196	Parse OMA entry from the SharedPrefs String TODO ( qinmin ) : use a file instead of SharedPrefs to store the OMA entry .
9294	Tests if the specified < code > File < /code > is older than the reference < code > File < /code > .
9326	Zooms in or out by the given scale factor . x and y are the values ( NOT PIXELS ) of the zoom center..
9446	Make a prettyprinted JSON text of this JSONObject . < p > Warning : This method assumes that the signalData structure is acyclical .
9474	You inflicted % num0 damage on [ % SkillTarget ] and dispelled some of its magical buffs by using [ % SkillName ] .
9525	< p > Computes an average estimated module size based on estimated derived from the positions of the three finder patterns. < /p >
9642	Rolls-back the pending changes . After this method has been called , no more writes or reads can be made from this transaction .
9860	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
9908	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
9970	Starts the recording . To accomplish this , ( i ) the line is started and ( ii ) the thread is started .
10065	Sets the world of the Notice . ( This is only needed for sending a notification at a Vec3 position to everyone ; )
10074	Sets the fetch size that will be used when working with scrollable results . Defaults to < code > 100 < /code > .
10187	If the associated model of self model is null , the FK value in database should be cleared if it exists when updating .
10233	Characters are inserted into the clob based on the position given of the clob . The emphasis is on insert rather than overwrite .
10495	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
10520	Returns true if the DIP publication contains an array . In this case the DIPHardwareAddress object refers to a field within the array .
10644	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
10739	Method that provides some notion of the current time in milliseconds since the beginning of the epoch . Default implementation calls System.currentTimeMillis ( )
10752	Creates a single-threaded executor that is registered by this class in order to shut it down later ( when it becomes necessary ) .
10774	Used for copying error messages from other ActionResult object , when action is called within other action , as they do not throw exceptions
10851	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
10953	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
11114	Indicates if the given period is valid for data entry for this data set . Returns true if the given period is null .
11227	DOM Level 3 WD- Experimental . Override inherited behavior from ParentNode to support deep equal . isEqualNode is always deep on Attr nodes .
11242	Analyze the associations of baseObj and store the result in it . The associations will be used when deleting referenced data of baseObj .
11251	Starts the recording . To accomplish this , ( i ) the line is started and ( ii ) the thread is started .
11336	Moves the left side of the current viewport to the specified x-index . This also refreshes the chart by calling invalidate ( ) .
11424	Type a character that is neither an alphabetic character and not in list of known characters ( see list defined in this class )
11565	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
11667	Used for testing -- input is a full csv line : < freq , domain , ip , ts , opt : generic >
11817	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
11828	Return a collector that creates a LinkedHashMap dictionary using the given key function . This collector assumes the elements being collected are distinct .
12037	Round the date time back to the beginning of the nearest ( inclusive ) month of January , April , July , October .
12061	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
12129	Returns whether the background color specified in the Intent is valid . A background color is n't valid if its value is ShortcutHelper.MANIFEST_COLOR_INVALID_OR_MISSING .
12223	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
12418	Print a start tag with attributes . The tag will be followed by a newline , and the indentation level will be increased .
12452	Returns true if the arguments are both NaN , are equal , or are within the range of allowed error ( inclusive ) .
12462	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
12504	The opposition has abandoned the Chantra Dredgion infiltration mission . You will leave the Chantra Dredgion when the mission ends in % DURATIONTIME0 .
12624	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
12688	Return true if lng_.lo ( ) & gt ; lng_.hi ( ) , i.e . the rectangle crosses the 180 degree latitude line .
12757	Synchronous ad-blockers detection This is blocking and should be called in a separated thread . In Android activities , prefer the asynchronous version .
12852	Characters in the < > characters < / > tag . Decide to not use this method temporarily . Use value attribute instead .
12873	Validate a single glob pattern . If it 's invalid , returns an error message . Otherwise , returns null . < p >
12879	Only Regular Locals -- . Only propagate copies through `` regular '' locals , that is , those declared in the source bytecode .
12963	Move the Cursor returned by the query into the ListView adapter . This refreshes the existing UI with the data in the Cursor .
13088	Adds the given data schema to the registry . If there was an existing schema with the same name , it is replaced .
13142	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
13283	Tell whether the string contains a positive or negative number delta , i.e. , a number with an obligatory + or - sign .
13289	Returns an array consisting of all the keys associated with this map . This does not include any mappings in the parent map .
13320	Creates a single-threaded scheduler that is registered by this class in order to shut it down later ( when it becomes necessary ) .
13419	Returns true if the argument is a `` very dangerous '' double to have around , namely one that is infinite or NaN .
13582	You have invited % 0 's alliance to the Alliance League . % 0 's alliance has a total of % 1 members .
13610	Tests if this input stream supports the < code > mark < /code > and < code > reset < /code > methods .
13790	Tries to create the directory incl . all super directories , returns true if at the end of the operation the directory exists .
14086	Prints a formatted string to standard output , using the locale and the specified format string and arguments ; then flushes standard output .
14165	Removes all ( key , value ) associations from the receiver . Implicitly calls < tt > trimToSize ( ) < /tt > .
14393	Check a feature . If feature is known and supported , this method simply returns . Otherwise , the appropriate exception is thrown .
14457	Consumes the current token iff it 's one of the expected types. < br > Otherwise , returns false and reports an error .
14501	First it parses framePath string parameter into FramePath and then performs injection in context defined by the provided the scope WebElement and FramePath .
14605	Check the trustedCertificateIndex for the cert to see if it is already trusted and failing that check the KeyStore if it is available .
14744	Animate a pan to the specified location in absolute ( item-space ) co-ordinates and zoom to the given scale using the provided duration .
14806	Sets < code > data [ i ] = value < /code > for each i in < code > tiesTrace. < /code >
14832	Override this method if you wish to be called when the underlying PSI file is available and you would like to parse it .
14861	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
14890	Compare the embedded timestamps of the given UUIDs . This is used when it is OK to return an equality based on timestamps alone
14990	Sets the fetch size that will be used when working with scrollable results . Defaults to < code > 100 < /code > .
15015	Given a JobRow , and the URI of the request , serializes the JobRow into the version to be sent to the user .
15022	This method opens a sort plan for the specified plan . The sort plan ensures that the underlying records will be appropriately grouped .
15046	Override to process entities after it has been retrieved from storage and before it is returned to the view . Entities is null-safe .
15097	Returns < code > true < /code > if this entry defined as FIFO , otherwise < code > false < /code > .
15146	Tests if the specified < code > File < /code > is older than the specified < code > Date < /code > .
15446	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
15800	Given the device pose in start of service frame , calculate the position and orientation of the depth sensor in OpenGL coordinate frame .
15809	verifies that f ( x [ i ] ) = y [ i ] for i = 0..n-1 where n is common length .
15871	Returns true if the specified character is a valid NCName character as defined by production [ 5 ] in Namespaces in XML recommendation .
15981	Interprets a string as a URL . If the string is n't a valid URL , prints an error message and returns null .
16073	Store < code > persistentProperties < /code > and any hard coded fields in an apache config object for propagation to spark executors .
16194	Try to start keyboard mode with the specified key , as long as the timepicker is not in the middle of a touch-event .
16225	Tell whether the string contains a positive or negative number delta , i.e. , a number with an obligatory + or - sign .
16381	Update the number of tokens in the bucket based . Caps at the bucket capacity , but allows taking the bucket into deficit .
16390	Animate a pan to the specified location in screen ( pixel ) co-ordinates and zoom to the given scale using the provided duration .
16399	An unchecked conversion occurs when converting from a raw type G to a generic type G < T1 , ... , Tn > .
16507	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
16526	Accessor method that returns the value of the < code > boolean < /code > variable < code > bDiscarded < /code > .
16628	Flushes the internal state of the list , setting the capacity of the empty list to < tt > capacity < /tt > .
16682	Mapping to escape < a href= '' https : //secure.wikimedia.org/wikipedia/en/wiki/ISO/IEC_8859-1 '' > ISO-8859-1 < /a > characters to their named HTML 3.x equivalents .
16765	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
16797	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
17029	The request for a proxy petition has failed . ( The user is currently offline . ) The error code is % 0 .
17040	< p > Constructs a < code > NumericEntityEscaper < /code > outside of the specified values ( exclusive ) . < /p >
17135	Returns the appropriate name for the 'mksdcard ' command , which is 'mksdcard.exe ' for Windows and 'mkdsdcard ' for all other platforms .
17136	Converts a package name to a path by replacing all ' . ' characters with the File.separatorChar character . Is therefore platform independent .
17139	Set the properties that the org.quartz Scheduler will use . Can only be called once , and only before a Job is added .
17618	If true , the control will be collapsed into an icon and expanded on mouse hover or touch . < /br > default true
17651	Removes only the specified < code > ASModel < /code > from the list of < code > ASModel < /code > s .
17657	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
17775	Advances the current position to the next row and adds margins on the left , right , and top of the new row .
17818	This check contains a workaround for an issue in AEM 6.1 , when after the deploy occasionally Insert Window contains an empty list .
17866	Returns the natural log of the values in this column , after adding 1 to each so that zero values do n't return -Infinity
17867	This method will increment the access count for a column by 1 whenever a column is getting used in query or incremental data load
17878	Throws an exception if the current token is not a string . Otherwise , returns that string and moves to the next token .
17982	Creates new host from provided hostname . Displays a popup dialog if wrong hostname is provided or the host has already been defined .
18026	Returns an expression . Evaluating this expression for a record produces the value that will be stored in the record 's target field .
18049	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
18093	Check if this service is valid - if any of the user 's values are bad , we should n't install this service .
18256	Called whenever a side swipe scroll event is triggered . This gives the new delta X that represents how much scroll took place .
18377	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
18526	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
18572	Add a job to the master list , persisting it if necessary . If the JobStatus already exists , it will be replaced .
18609	Possibly better in ultra low memory environments ? Reuses the above method by creating a queue with one element and passes it in .
18667	Indicates if the given file ends with a file extension of `` .gz '' or `` .Z '' , indicating a GZip file .
18687	Return true whether this template should match by uid only ( if such provided ) or with full match regardless present if uid .
18716	Gets the fraction as a < tt > float < /tt > . This calculates the fraction as the numerator divided by denominator .
18842	Specifies whether results should be read from the cache ( or written to the cache if the results have not yet been cached )
18990	Selects the specified file in the project view . < b > Note : < /b > Must be called with read access .
19089	Tests if the interior of this < code > Polygon < /code > intersects the interior of a specified set of rectangular coordinates .
19119	Tags a text file , each sentence in a line and writes the result to an output file with a desired output format .
19214	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
19270	Returns true if the specified character is a valid Pubid character as defined by production [ 13 ] in the XML 1.0 specification .
19419	`` true '' - poll is in a board , `` false '' - poll is on a wall ( by default ) .
19436	Sets the visibility of the given models , and notifies that the items changed if the new visibility is different from the previous .
19439	Removes the half edges specified by the given interior edge index . < p > This method removes both halves of the edge .
19484	Sends the given packet data on the given < code > MulticastSocket < /code > through the network interface that is currently set .
19490	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
19575	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
19593	Returns the string value stored in this object for the given key . Returns the default value if there is no such key .
19639	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
19784	Called whenever the beginning of a side swipe scroll is detected . This lets inheriting classes trigger any side swipe behavior they want .
19808	Utility method for traversing a single node when we know a-priori that the node if partially selected and is not a text node .
19818	Retrieve framePath from the parameter object and then call inject ( Class & lt ; T & gt ; clazz , FramePath framePath )
19883	Given a count of black/white/black pixels just seen and an end position , figures the location of the center of this black/white/black run .
19919	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
19980	Binds listener for user actions that start any update the edit permissions for the public link to the views receiving the user events .
20072	Set < code > ranks [ i ] = Double.NaN < /code > for each i in < code > nanPositions. < /code >
20124	Get a filtered iterator over the row numbers of this table , returning only the rows whose tuples match the given filter predicate .
20239	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
20357	Generates a Cypher MATCH pattern for the vertex , example : < p > ( alias : Label1 : Label2 ) < /p >
20375	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
20423	Provides a string representation of a vector of objects . Calls < code > toString ( StringBuffer , ... ) < /code > .
20585	Set the properties that the org.quartz Scheduler will use . Can only be called once , and only before a Job is added .
20618	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
20634	Wrapper method for ContextCompat.checkSelfPermission ( ) . Determine whether < em > the app < /em > has been granted a particular permission .
20696	Clears the user approval level cache , for unit testing when the same user ID may have different approval levels in quick succession .
20736	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
20906	find ( ) finds the ( int ) name of the set containing a given element . Performs path compression along the way .
20950	Checks to see if the user id is the same for the two uids , i.e. , they belong to the same user .
21154	Called whenever a ClearMapEvent is posted to the bus . Posted when the user wants to clear map of any pokemon or marker .
21199	Returns < code > true < /code > if this class defined as FIFO , otherwise < code > false < /code > .
21282	Tests if the interior of this < code > Polygon < /code > intersects the interior of a specified set of rectangular coordinates .
21398	You can no longer use the % 2 % 0 skill ( Level % 1 ) because your Linked Stigma combination has changed .
21486	If we have just opted in or opted out of document mode , perform pending migration tasks such as cleaning up the recents .
21613	Tests if the specified < code > File < /code > is older than the reference < code > File < /code > .
21692	Set the properties that the org.quartz Scheduler will use . Can only be called once , and only before a Job is added .
21705	Sets the custom eviction strategy to be used by the space , When using a Custom Cache Policy this property must be set .
21760	Parameter for requesting the next results page . Value for transmitting here is returned in the `` next '' field in a reply .
21783	Tests if the specified < code > File < /code > is newer than the specified < code > Date < /code > .
21910	Returns whether the CRC function is `` reflected '' . Reflected CRCs process data LSB-first , whereas `` normal '' CRCs are MSB-first .
21998	If this name is in the set of reserved names , then return a quoted version of it . Else pass it through .
22050	Called by < code > load ( ) < /code > during loading , derived voices should override this to provide customized loading .
22099	You should implement this function to specify whether the given url should be crawled or not ( based on your crawling logic ) .
22135	Current action is saving or not . Note that update the record by saving the already saved record again belongs to save action .
22588	Mark the current scan position as a `` point of interest '' - start of a tag , cdata , processing instruction etc .
22676	Sets the visibility of the given models , and notifies that the items changed if the new visibility is different from the previous .
22759	Make the data associated with this provider eligible to be expired if not enough space remains on disk . By default is true .
22788	Returns true if the provided string argument is to be considered numeric . Matches using a lenient pattern where leading zeros are allowed .
22838	Set the properties that the org.quartz Scheduler will use . Can only be called once , and only before a Job is added .
22898	Check a feature . If feature is known and supported , this method simply returns . Otherwise , the appropriate exception is thrown .
22971	Current action is updating or not . Note that update the record by saving the already saved record again belongs to save action .
23002	Filter by ads . Serialized JSON array with ad IDs . If the parameter is 'null ' , all ads will be shown .
23017	Clicks OK button at the bottom of edit Window . Assumes invalid data was entered and waits for the validation message to appear .
23220	Mapping to escape < a href= '' https : //secure.wikimedia.org/wikipedia/en/wiki/ISO/IEC_8859-1 '' > ISO-8859-1 < /a > characters to their named HTML 3.x equivalents .
23225	Peek for ( get ) the resource status . Do not descend to children and DO NOT affect sync cache in any way !
23277	Sets the context of the Command . This can then be used to do things like get file paths associated with the Activity .
23413	Instructs the LogNode to print the log data provided . Other LogNodes can be chained to the end of the LogNode as desired .
23450	The number of doubles that can currently be read from this double data source without blocking . This number can change over time .
23604	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
23620	return null if all IDREF values have a corresponding ID value ; otherwise return the first IDREF value without a matching ID value .
23664	Filter by ads . Serialized JSON array with ad IDs . If the parameter is 'null ' , all ads will be shown .
23910	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
23989	Returns whether the theme color specified in the Intent is valid . A theme color is n't valid if its value is ShortcutHelper.MANIFEST_COLOR_INVALID_OR_MISSING ;
23998	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
24062	Make a prettyprinted JSON text of this JSONObject . < p > Warning : This method assumes that the data structure is acyclical .
24065	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
24110	ClassToSourceMap is for classes whos names do n't match the source file name - ex : multiple top level classes in a single file
24122	Equivalent of setting both top left and bottom right padding to the same value . < /br > default [ 0 , 0 ]
24335	Wall post id . Note that stats are available only for `` 300 '' last ( newest ) posts on a community wall .
24431	Provides a binder object that clients can use to perform actions on the queue of operations , except the addition of new operations .
24506	Check if this is possibly an instance of http : //b.android.com/164378 . If likely , this adds a message with the recommended workaround .
24585	hash code method to check get the hashcode based . for generating the hash code only column name and column unique id will considered
24599	Returns the boolean value stored in this object for the given key . Returns the default value if there is no such key .
24638	Determines whether the given class can be classified as a DocumentActivity ( this includes both regular document activity and incognito document activity ) .
24762	Tests if the specified < code > File < /code > is newer than the reference < code > File < /code > .
24771	Tests if the specified < code > File < /code > is newer than the reference < code > File < /code > .
25083	Sets the context of the Command . This can then be used to do things like get file paths associated with the Activity .
25185	Starts the recording . To accomplish this , ( i ) the line is started and ( ii ) the thread is started .
25300	Returns true if object < code > a < /code > follows object < code > b < /code > in the Chain .
25331	Moves the left side of the current viewport to the specified x-position . This also refreshes the chart by calling invalidate ( ) .
25423	Initializes a new repository in a temporary directory using the given environment vars . < p > The new repo is not bare .
25526	Wait until the engine is a consistent state , which means it has no pending operations that will be lost when closing the engine
25580	Clone method that can be used by the server core and other modules to obtain their own copy of the equipment cache object .
25582	Compute a list of patches to turn text1 into text2 . text2 is ignored , diffs are the delta between text1 and text2 .
25614	Adds a command class to the list of supported command classes by this endpoint . Does nothing if command class is already added .
25704	Flushes the internal state of the list , setting the capacity of the empty list to < tt > capacity < /tt > .
25784	This method is called with an existing object that is not found in the new source . The default implementation is to call executor.addForTermination
25919	Finds the total of all counts in the counter . This implementation iterates through the entire counter every time this method is called .
25945	< code > subtract < /code > subtracts the provided values from this vector , creating a new vector that is then returned .
26008	Tests if the specified < code > File < /code > is older than the specified < code > Date < /code > .
26168	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
26210	Returns true if this node is the potential source of a interprocedural assignment edge which may be added during on-the-fly call graph updating .
26214	Returns true if this node is the potential target of a interprocedural assignment edge which may be added during on-the-fly call graph updating .
26323	A future task is obsolete if it should not be monitored anymore , either because it has has completed , canceled or timed-out .
26352	check if the view is declared to be aware of the connectivity . if yes , start a broadcast receiver to get udpates .
26577	Converts an object that can be the NoneType to the actual object if it is not or returns the default value if none .
26599	Mark the current scan position as a `` point of interest '' - start of a tag , cdata , processing instruction etc .
26780	Region Id used for encoding logs in the namespace . The region id is useful when the namespace is globally spanning over regions .
26822	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
26858	< p > Computes an average estimated module size based on estimated derived from the positions of the three finder patterns. < /p >
27255	Returns true if the specified character is a valid name character as defined by production [ 4a ] in the XML 1.1 specification .
27314	Called when the host is being saved for serialisation . Takes the state from the host and puts what we need to store .
27413	Sets the context of the Command . This can then be used to do things like get file paths associated with the Activity .
27516	Returns the double value stored in this object for the given key . Returns the default value if there is no such key .
27575	Returns the integer encoded value of each cell in this column . It can be used to lookup the mapped string in the lookupTable
27674	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
27781	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
27850	When some fields are added into the class after last upgrade , the table should synchronize the changes by adding the corresponding columns .
27979	Invoked before the Action is handed over to the scheduler . Can be used for wrapping/decorating/logging . The default is just a passthrough .
28150	Writes the summary to the given file . The file should be in a directory which has already been created by the caller .
28158	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
28181	Checks to see if given parameter is a valid hex color string ( # xxx and # xxxxxx , xxx , xxxxxx ) .
28326	Loads and initializes OpenCV library from current application package . Roughly , it 's an analog of system.loadLibrary ( `` opencv_java '' ) .
28376	Indicates whether the given list of grids have at least one grid which is not null and has more than zero visible columns .
28410	Constructs a scope out of the scope factory and the parent field , then searches for the field with selector in this scope .
28511	Returns true if the code is in [ 200..300 ) , which means the request was successfully received , understood , and accepted .
28537	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
28927	Adds a pointer to the given < code > node < /code > with the key < code > tag < /code > .
28972	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
29130	Invokes the delegate 's < code > read ( ) < /code > method if the current position is less than the limit .
29189	This method should be called when the ViewPager changes to another page . For best results call this method in the adapter 's setPrimary
29512	Starts the recording . To accomplish this , ( i ) the line is started and ( ii ) the thread is started .
29517	Sets the visibility of the given model , and notifies that the item changed if the new visibility is different from the previous .
29605	Tests if the specified < code > File < /code > is newer than the reference < code > File < /code > .
29632	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
29682	Answers whether this class is an immediate descendant ( as subclass or as an implementation of an interface ) of the given class .
29848	Close the most recently opened tag . The tag will be followed by a newline , and the indentation level will be decreased .
29860	This only checks against the completed pending compactions that are in memory currently , but not against the pending compactions that are in progress
29888	If true , the marker will get on top of others when you hover the mouse over it . < /br > default false
30098	Override to process entities after it has been retrieved from storage and before it is returned to the view . Entities is null-safe .
30232	Check whether this SourceDataQuality object represents a VALID value . The method will return true if the quality code is anything else but SourceDataQuality.OK
30272	The max number of pixels a user can shift his finger during touch for it to be considered a valid tap . default 15
30306	Possibly better in ultra low memory environments ? Reuses the above method by creating a queue with one element and passes it in .
30352	By calling this method , any custom maximum value that has been previously set is reseted , and the calculation is done automatically .
30372	Called when a button is clicked ( the button in the layout file attaches to this method with the android : onClick attribute )
30383	tell tha adapter there will be more data , so the progress will show , and the load more callback will be invoked .
30418	Skip to the i-th point in the Halton sequence . < p > This operation can be performed in O ( 1 ) .
30540	Normalizes tokens of a string s. This function converts all dates to `` DATE '' , numbers to `` NUMBER '' , etc .
30686	Only Regular Locals -- . Only propagate copies through `` regular '' locals , that is , those declared in the source bytecode .
30746	Fires an < code > onUnsubscribe ( ) < /code > event to all registered < code > TagSubscriptionListener < /code > listeners .
30787	verifies that f ( x [ i ] ) = y [ i ] for i = 0..n-1 where n is common length .
31057	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
31076	By calling this method , any custom minimum value that has been previously set is reseted , and the calculation is done automatically .
31227	Detach the given device from the client . Device and shadow synchronization will be stopped after the device is detached from the client .
31384	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
31400	Sends a note to the business layer , to confirm that the equipment is not properly configured , or connected to its data source
31413	Check if the fragment was created with an empty layout . An empty fragment ca n't show file details , must be replaced .
31550	Wait for a new element to become available . May be interrupted , in which case it will return before the wakeup arrives .
31611	check if the threshold has been reached for the number of values that can kept in memory and then flush the data to file
31746	Tests if the specified < code > File < /code > is older than the reference < code > File < /code > .
31861	If a poll will be added to a community it is required to send a negative group identifier . Current user by default .
31877	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
31888	Returns < code > true < /code > if this class defined as FIFO , otherwise < code > false < /code > .
31899	Remove a custom data handler for a given column name . Subsequent to this method , the column will use the default handler .
31944	Filter by ads . Serialized JSON array with ad IDs . If the parameter is 'null ' , all ads will be shown .
32009	Creates a file with the specified contents and file path in the test project , and asserts that it 's parsed as a BuildFile
32425	Mapping to escape < a href= '' https : //secure.wikimedia.org/wikipedia/en/wiki/ISO/IEC_8859-1 '' > ISO-8859-1 < /a > characters to their named HTML 3.x equivalents .
32469	Record the time at which the activity started . This should be called asap after the start of the activity 's onCreate function .
32528	Tests if the specified < code > File < /code > is newer than the reference < code > File < /code > .
32666	Print a comment in the XML document . The comment will be printed according to the current spacing and followed by a newline .
32865	Convenience method to create a new token with the type set to object and with the starting index set to the given index .
33046	Returns one of the objects in the set , or < code > null < /code > if the set contains no objects .
33114	Returns a < code > PropertyChangeListener < /code > that will be installed on the horizontal < code > JScrollBar < /code > .
33147	Removes toRemove from base . If there are duplicate items in base , then only one is removed for each item in toRemove .
33251	Check if number is within a values range . This method not consider the sign and the upper and lower values limit order .
33385	Prints this TypeConstraintException and its stack trace ( including the stack trace of the linkedException if it is non-null ) to the PrintStream .
33421	Returns < CODE > true < /CODE > if the user clicked on cancel and < CODE > false < /CODE > otherwise .
33630	Prints the contents of a Set with no indentation this method calls the toString method of the objects which are in the set .
33758	Called by the < code > MenuSelectionManager < /code > when the < code > MenuElement < /code > is selected or unselected .
33940	Remove an online store whose seller is < code > sellerId < /code > . This is used to close an online store .
34008	Creates the peer of the canvas . This peer allows you to change the user interface of the canvas without changing its functionality .
34220	Formats this date-time using the specified formatter . < p > This date-time will be passed to the formatter to produce a string .
34250	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
34276	Returns if the command output is quite ; ie the log output is only written to the file and not to the console .
34278	Creates a new fatal decode exception with the provided message and root cause . The associated input source can no longer be used .
34435	Check whether the header of the file is ok. Of course , this has to be the first action on successive file reads .
34613	A hash code for this chronology . < p > The hash code should be based on the entire state of the object .
34623	Returns < code > false < /code > since this < code > ImageOutputStream < /code > does not maintain a file cache .
34646	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
34651	Method responsible for keeping the local references to a session up to date . Call if the Session handle or restricted ids change .
34745	Returns true if the menu is a 'top-level menu ' , that is , if it is the direct child of a menubar .
34803	Returns true if the specified character is a valid name character as defined by production [ 4 ] in the XML 1.0 specification .
34828	Parses the command-line arguments , establishes a connection to the Directory Server , sends the password modify request , and reads the response .
34918	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
35099	Modifies the standard behavior to allow results to be delivered to fragments . This imposes a restriction that requestCode be < = 0xffff .
35229	Remove an online store whose seller is < code > sellerId < /code > . This is used to close an online store .
35329	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
35363	Given a count of black/white/black pixels just seen and an end position , figures the location of the center of this black/white/black run .
35508	Appends p_value to the text pane after transforming it to the user coordinate sytem . Returns false , if that was not possible .
35556	Shut down the server . This should only be called at the end of the test suite and not by any unit tests .
35617	Concatenate the list of stuff that we are keeping around and also the text corresponding to these structures ( that we parsed ) .
35637	Returns < CODE > true < /CODE > if the server is already installed and < CODE > false < /CODE > otherwise .
35821	If < code > true < /code > only complete CRLs are returned . Defaults to < code > false < /code > .
35870	Return the set of children Containers associated with this Container . If this Container has no children , a zero-length array is returned .
35893	Ensures the truth of an expression involving the state of the calling instance , but not involving any parameters to the calling method .
35968	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
35983	Detaches the walker from the set which it iterated over , releasing any computational resources and placing the iterator in the INVALID state .
36071	Called when view is being unbind from presenter component . It will be called no later than Activity/Fragment onStop ( ) method call .
36100	Checks whether the given symbol can be accepted , that is , if the given symbols is found at the current parsing position .
36113	Paints the background of the divider of a split pane . This implementation invokes the method of the same name without the orientation .
36131	Chooses an alias for the client side of an SSL connection to authenticate it with the specified public key type and certificate issuers .
36149	Creates a condition which evaluates to < code > true < /code > if and only if a property contains a particular value .
36312	Returns the index of the tab for the specified tab component . Returns -1 if there is no tab for this tab component .
36339	Override equals and agree that we 're equal if the passed object is a string and it matches the name of the arg .
36353	Constrains < code > want < /code > to fit in the minimum size specified by < code > min < /code > .
36411	Generates and initializes a collection of < i > Certificate Revocation List < /i > ( CRL ) from the provided input stream .
36418	Informs that an index has been modified . The method will notify to all the index listeners that an index has been modified .
36450	Decodes a quoted-printable string into its original form using the default string charset . Escaped characters are converted back to their original representation .
36543	Transfers node , if necessary , to sync queue after a cancelled wait . Returns true if thread was cancelled before being signalled .
36599	Formats this year using the specified formatter . < p > This year will be passed to the formatter to produce a string .
36675	This draws a variant `` Flush 3D Border '' It is used for things like active toggle buttons . This is used rarely .
36691	Returns true if the specified character is a valid name character as defined by production [ 4a ] in the XML 1.1 specification .
36970	Returns < CODE > true < /CODE > if the user clicked on cancel and < CODE > false < /CODE > otherwise .
37158	Called immediately before the transport transmits HTTP request headers . This is used to observe the sent time should the request be cached .
37218	Gets the status of an index creation event . Allows a user to check on the status of the indexing for an index .
37504	Returns the hash code value of the present value , if any , or 0 ( zero ) if no value is present .
37564	requireNonNull is explicitly declared here so as not to create an extra dependency on java.util.Objects.requireNonNull . PrintStream is loaded early during system initialization .
37580	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
37595	Sleep a while : counters are updated just after sending thread is unblocked and let time for the update to reach other servers .
37702	If true , the new value shall be committed as soon as a selection is made ( commonly with the pointing device ) .
37745	Get the contents of a < code > URLConnection < /code > as a < code > byte [ ] < /code > .
37932	Returns < CODE > true < /CODE > if the index has been modified and < CODE > false < /CODE > otherwise .
38064	Compares two strings in a case insensitive manner , that also allows for either of the strings to be null , without issue .
38081	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
38084	Parses the command-line arguments , establishes a connection to the Directory Server , sends the password modify request , and reads the response .
38155	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
38193	Returns a representation of the packet . Used to log packets and their contents if logging is enabled for the RADIUS server functionality .
38295	This method notifies the < code > DragSource < /code > that the drop transfer ( s ) are completed . < P >
38343	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
38396	Invokes when the OpenAM Server received the Single-Sign-On response from the IDP , this is called before any processing started on SP side .
38550	Returns true if the specified character is a valid NCName character as defined by production [ 5 ] in Namespaces in XML recommendation .
38650	Tests if the specified < code > File < /code > is older than the reference < code > File < /code > .
38710	Return true if obj is an instance of FontRenderContext and has the same transform , antialiasing , and fractional metrics values as this .
38759	Clear a set attribute . Regardless of whether the attribute was set , it will be cleared as a result of this call .
38762	Applies the operation < code > & tau ; ( ) < /code > to an < code > ECPoint.F2m < /code > .
38768	This method adds the field to the last page in the document . If there 's no pages , creates a new one .
38798	Returns the RepaintManager for the specified AppContext . If a RepaintManager has not been created for the specified AppContext this will return null .
38815	Reset a dtm document to its initial ( empty ) state . The DTMManager will invoke this method when the dtm is created .
38823	Import an entry in the schema . < p > FIXME : attributeTypes and objectClasses are the only elements currently taken into account .
38849	Returns the next available reference from the queue , removing it in the process . Waits indefinitely for a reference to become available .
38851	Returns the object stored at the given index . Equivalent to < code > getArray ( ) [ i ] < /code > .
38947	Returns a < code > PropertyChangeListener < /code > that will be installed on the vertical < code > JScrollBar < /code > .
38964	Adds the specified observer to the list of observers . If it is already registered , it is not added a second time .
39051	Messaged when the node has expanded . This updates all of the receivers children rows , as well as the total row count .
39054	Adjust indices in starts to reflect an insertion after pos . Any index in starts greater than pos will be increased by 1 .
39148	Attempts to acquire a write lock on the specified entry , trying as many times as necessary until the lock has been acquired .
39192	Returns a shallow copy of this < tt > ArrayList < /tt > instance . ( The elements themselves are not copied . )
39206	Delete a subtree of entries . We can not use the subtree delete control because it is not supported by the config backend .
39334	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
39348	Adds the provided auxiliary classes to the list of auxiliary object classes that entries subject to this DIT content rule may belong to .
39351	This method asserts that this container has a descriptor with the specified key , means returns an existing or creates a new descriptor .
39557	Write up to nbytes of data from the given buffer , starting at offset off , to the underlying stream in GZIP format .
39571	This method creates a copy of the current object . < br > All data will be copied , too . < br >
39579	Returns < CODE > true < /CODE > if the user clicked on cancel and < CODE > false < /CODE > otherwise .
39690	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
39694	Invoke this method if you 've totally changed the children of node and its childrens children ... This will post a treeStructureChanged event .
39699	This determines if this address is a wildcard address . That is < code > Address.getAddress.getUserInfo ( ) == * ; < /code >
39784	Formats this time using the specified formatter . < p > This time will be passed to the formatter to produce a string .
39948	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
40065	Detaches the walker from the set which it iterated over , releasing any computational resources and placing the iterator in the INVALID state .
40184	Check if this MSG will change the DN of the target entry to be the same as the dn given as a parameter .
40365	Visits a local variable instruction . A local variable instruction is an instruction that loads or stores the value of a local variable .
40452	Decodes a quoted-printable string into its original form using the specified string charset . Escaped characters are converted back to their original representation .
40537	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
40692	Convert a byte array to a Pascal string . The first byte is the byte count , followed by that many active characters .
40904	Generates a String representation of a Java Date object . The string is formatted according to the specification for XML property list dates .
40932	This is called when the service is added for the first time and it will change the default install value of an attribute .
41041	Tests whether or not a given file name matches any file name pattern in the given set . The match is performed case-sensitively .
41048	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
41050	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
41104	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
41197	Called before the request is executed using the underlying HttpClient . < p > Overwrite in subclasses to augment the request. < /p >
41242	Invokes the delegate 's < code > read ( byte [ ] ) < /code > method , detecting and optionally skipping BOM .
41316	Closes this zip file . This method is idempotent . This method may cause I/O if the zip file needs to be deleted .
41331	Called immediately before the transport transmits HTTP request headers . This is used to observe the sent time should the request be cached .
41539	add a signer , specifying the digest encryption algorithm to use - no attributes other than the default ones will be provided here .
41607	Puts a new key-value pair into this dictionary . If the value is null , no operation will be performed on the dictionary .
41611	Checks whether the given symbol can be accepted , that is , if the given symbols is found at the current parsing position .
41759	Returns an enumeration of the values in this Cache . Use the Enumeration methods on the returned object to fetch the elements sequentially .
41780	Translates the specified character , which is assumed to be in the `` Base 64 Alphabet '' into its equivalent 6-bit positive integer .
41833	Not run by default by JUnit , but can be run by Vogar by specifying it explicitly ( or with main method below )
41954	Returns < CODE > true < /CODE > if the user clicked on cancel and < CODE > false < /CODE > otherwise .
41958	Searches for users in this role using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
42121	Throw an exception if we are parsing . < p > Use this method to detect illegal feature or property changes. < /p >
42189	Reads an instance of this class from a file restore transient files to a proper value note that act_log is updated using set_log method
42225	Returns one of the objects in the set , or < code > null < /code > if the set contains no objects .
42300	Returns < CODE > true < /CODE > if the Synchronization Provider was created and < CODE > false < /CODE > otherwise .
42306	Searches for assignable dynamic groups in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
42354	Encode the header for the start message . This uses the version 1 of the replication protocol ( used for compatibility purpose ) .
42366	Return the current refresh token value . Can be used to reload cached group instances if there has been a group instance change .
42627	Sends an event to the bus ATTENTION : all observers that are observing the class of the event will retrieve it < p >
42708	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
42747	Splits this trace and overlapping traces , and combines this trace . If p_clip_shape ! = null , splitting is restricted to p_clip_shape .
42768	Shutdown the environment . < p > The log DBs are not closed by this method . It assumes they are already closed .
42867	Translates the specified character , which is assumed to be in the `` Base 64 Alphabet '' into its equivalent 6-bit positive integer .
42946	Get a TransformerHandler object that can process SAX ContentHandler events into a Result , based on the transformation instructions specified by the argument .
43018	Get the contents of a < code > URI < /code > as a < code > byte [ ] < /code > .
43027	Forces an abandon check on the connection pool . If connections that have been abandoned exists , they will be closed during this run
43064	Run the HTTP server , listening on the chosen port . < p > Use stop ( ) to shut the server down .
43065	Called when view handled by this presenter is available . It will be called no later than Activity/Fragment onStart ( ) method call .
43078	Detaches the walker from the set which it iterated over , releasing any computational resources and placing the iterator in the INVALID state .
43082	Chooses an alias for the server side of an SSL connection to authenticate it with the specified public key type and certificate issuers .
43095	add a signer , specifying the digest encryption algorithm to use - no attributes other than the default ones will be provided here .
43161	This method generates a key according to the key parameters , and creates a key entry and registers it in the supplied map .
43198	Reset the wrapped filter to pass-through ; i.e. , when the CAF filter becomes unavailable or is in the process of being reconstructed .
43237	Tests if the specified < code > File < /code > is older than the specified < code > Date < /code > .
43331	Returns flag used by the IDP to decide if < code > SessionContextStatement < /code > needs to be generated for discovery bootstrapping .
43349	Removes the object at the top of this stack and returns the next object at the top as the value of this function .
43417	Adds keyboard actions to the JComboBox . Actions on enter and esc are already supplied . Add more actions as you need them .
43518	Returns the charset specified in the Content-Type of this header , or the HTTP default ( ISO-8859-1 ) if none can be found .
43828	Returns an unmodifiable list containing the set of available search scopes indexed on their integer value as defined in RFC 4511 section 4.5.1.2 .
43977	Regrettably both `` file : /tmp/foo.txt '' and `` file : ///tmp/foo.txt '' are legal URIs , and different implementations emit different forms .
43984	Checks if there are any object in the cache generated on the base of encoding with prefix corresponding to the specified hash code .
44140	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
44175	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
44204	called to signal that the drop is acceptable using the specified operation . must be called during DropTargetListener.drop method invocation . < P >
44291	Report the start of DTD declarations , if any . Any declarations are assumed to be in the internal subset unless otherwise indicated .
44372	Returns the < code > Pattern < /code > this < code > Scanner < /code > is currently using to match delimiters .
44392	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
44446	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
44473	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
44490	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the change bounces at the end .
44573	Removes the provided object class in the list of auxiliary object classes that entries subject to this DIT content rule may belong to .
44635	Prints this JAXBException and its stack trace ( including the stack trace of the linkedException if it is non-null ) to the PrintWriter .
44785	Copies the bytes of < code > srd < /code > to < code > dst < /code > at the specified offset .
44820	Messages < code > cancelCellEditing < /code > to the < code > realEditor < /code > and removes it from this instance .
44836	Notifies the peer that the < code > Transferable < /code > 's < code > DataFlavor < /code > s have changed .
45012	Given the device pose in start of service frame , calculate the position and orientation of the depth sensor in OpenGL coordinate frame .
45048	Method to check if Caching is enabled or disabled . To be called by all other LRU Caches that are created in AM SDK
45194	Returns true if the component being painted is the root component that was previously passed to < code > repaintRoot < /code > .
45211	Sets the working directory of the child process . If not set the working directory will be the same as the parent 's .
45289	Unwind if an object does not satisfy the given predicate e.g . ( 0..9 ) *.check { it < 10 } .sum ( )
45317	Determines whether two attribute values are equal . Use arrayEquals for arrays and < tt > Object.equals ( ) < /tt > otherwise .
45366	Appends a straight line segment from the current point to the point < CODE > ( x , y ) < /CODE > .
45471	Add an extension with the given oid and the passed in value to be included in the OCTET STRING associated with the extension .
45602	Returns true if the specified character is a valid name character as defined by production [ 4 ] in the XML 1.0 specification .
45636	Returns < CODE > true < /CODE > if the user updated the contents and < CODE > false < /CODE > otherwise .
45697	Validates each of the provided members of the Set to confirm that it conforms to the expected validation - only a-z/A-Z , 0-9 .
45767	Parse the content of the specified file using this Digester . Returns the root element from the object stack ( if any ) .
45976	Searches for sub organizational units in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
46083	Register the extension namespace for an ElemExtensionDecl or ElemFunction , and prepare a support object to launch the appropriate ExtensionHandler at transformation runtime .
46103	Formats this time using the specified formatter . < p > This time will be passed to the formatter to produce a string .
46114	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
46120	Returns a hashcode for the activation id . Two identifiers that refer to the same remote object will have the same hash code .
46211	Brings up a internal dialog panel where the number of choices is determined by the < code > optionType < /code > parameter .
46217	A service provided by the nesting BeanContext has been revoked . Subclasses may override this method in order to implement their own behaviors .
46308	Invokes the delegate 's < code > read ( ) < /code > method if the current position is less than the limit .
46364	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
46446	DOM Level 3 : This method checks if the specified < code > namespaceURI < /code > is the default namespace or not .
46451	Adds the provided auxiliary classes to the list of auxiliary object classes that entries subject to this DIT content rule may belong to .
46511	Generates a String representation of a Java Date object . The string is formatted according to the specification for XML property list dates .
46542	Returns < CODE > true < /CODE > if the Replication domain was created and < CODE > false < /CODE > otherwise .
46724	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
46750	Formats this date-time using the specified formatter . < p > This date-time will be passed to the formatter to produce a string .
46913	Returns a Jedis instance to be used as a Redis connection . The instance can be newly created or retrieved from a pool .
46959	Gets and processes the Single < code > LogoutRequest < /code > from IDP and return < code > LogoutResponse < /code > .
47103	Returns the hash code value of the present value , if any , or 0 ( zero ) if no value is present .
47110	Initialize this node test by setting the whatToShow property , and calculating the score that this test will return if a test succeeds .
47157	Get the ordering priority of the previous collation element in the text . A single character may contain more than one collation element .
47190	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
47297	returns true if this session is the primary session , if that is the case , the manager can expire it upon timeout .
47344	Searches for sub organizational units in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
47385	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
47415	Returns the tab index corresponding to the tab whose bounds intersect the specified location . Returns -1 if no tab intersects the location .
47564	Parses the XML date string and creates a Java Date object from it . This function is synchronized as SimpleDateFormat is not thread-safe .
47680	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
47720	Upgrades this server . < p > Upgrades the server configuration and application data so that it is compatible with the installed binaries .
47769	Get the ordering priority of the next collation element in the text . A single character may contain more than one collation element .
47789	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
47853	Returns true if the channel for this key is connected . If the channel does not need connecting , this always return true .
47861	Puts a new key-value pair into this dictionary . If the value is null , no operation will be performed on the dictionary .
47968	Paints the background of the tool bar 's content area . This implementation invokes the method of the same name without the orientation .
48089	< p > Computes an average estimated module size based on estimated derived from the positions of the three finder patterns. < /p >
48272	Modifies the standard behavior to allow results to be delivered to fragments . This imposes a restriction that requestCode be < = 0xffff .
48292	Compares any two arbitrary objects - including collections , for equality . It also handles either of the objects being null without issue .
48453	Check the trustedCertificateIndex for the cert to see if it is already trusted and failing that check the KeyStore if it is available .
48459	Changes the tree entries from p_keep_at_start_count + 1 to new_shape_count - 1 - keep_at_end_count to p_changed_entries . Special implementation for change_trace for performance reasons
48536	Called by CoRoutineSAXParser . Launches the CoroutineSAXParser in a thread , and prepares it to invoke the parser from that thread upon request .
48655	Returns the hash code value of the present value , if any , or 0 ( zero ) if no value is present .
48670	Transfers node , if necessary , to sync queue after a cancelled wait . Returns true if thread was cancelled before being signalled .
48751	Compiles the specified class using the JIT compiler and indicates if compilation has been successful . Does nothing and returns false on Android .
48758	Concatenate the list of stuff that we are keeping around and also the text corresponding to these structures ( that we parsed ) .
48925	Gets all JavaBean or < tt > BeanContext < /tt > instances currently nested in this < tt > BeanContext < /tt > .
48966	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
49015	Performs common bookkeeping for poll and take : Replaces first element with last and sifts it down . Call only when holding lock .
49087	Transfers node , if necessary , to sync queue after a cancelled wait . Returns true if thread was cancelled before being signalled .
49121	Equality function specialized for the variable name . If the argument is not a qname , it will deligate to the super class .
49174	Send a < code > Notification < /code > to all registered listeners as a < code > jmx.modelmbean.general < /code > notification .
49302	Button subclasses that support mirroring the selected state from the action should override this to return true . AbstractButton 's implementation returns false .
49382	Returns the first component of this list . Throws a < code > NoSuchElementException < /code > if this vector has no components .
49414	Paints the border of a tab of a tabbed pane . This implementation invokes the method of the same name without the orientation .
49447	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
49449	Removes a single instance of the specified element from this queue , if it is present , whether or not it has expired .
49474	Returns a message digest length . < BR > The method overrides `` engineGetDigestLength ( ) '' in class MessageDigestSpi . < BR >
49490	Returns an enumeration of the values in this Cache . Use the Enumeration methods on the returned object to fetch the elements sequentially .
49553	Paints the background of the tool bar 's content area . This implementation invokes the method of the same name without the orientation .
49696	Paints the background of a tab of a tabbed pane . This implementation invokes the method of the same name without the orientation .
49740	Forces this dispatcher to quit immediately . If any requests are still in the queue , they are not guaranteed to be processed .
49855	Returns < code > true < /code > if this TelURL is global i.e . if the TelURI has a global phone user .
50018	Returns an unmodifiable list containing the set of available result codes indexed on their integer value as defined in RFC 4511 section 4.1.9 .
50095	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
50137	Returns < CODE > true < /CODE > if the schema check is enabled and < CODE > false < /CODE > otherwise .
50174	Subclassed to make the decimal separator navigable , as well as making the character between the integer field and the next field navigable .
50198	Appends a new menu item to the end of the menu which dispatches the specified < code > Action < /code > object .
50224	Normalize the character sequence < code > src < /code > according to the normalization method < code > form < /code > .
50245	Similar to String.indexOf , but allows an upper bound ( this is slower in that it will still check string starting at start .
50337	Restarts the < code > Timer < /code > , canceling any pending firings and causing it to fire with its initial delay .
50359	Tests if the specified < code > File < /code > is newer than the reference < code > File < /code > .
50551	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
50584	Check if the value of a character belongs to a certain interval that indicates it 's the higher part of a surrogate pair .
50720	Returns a Connection object with the specified properties and a network and address type of `` IN '' and `` IP4 '' respectively .
50828	Does nothing , since < code > IIOMetadataNode < /code > s do not contain < code > Text < /code > children .
50851	Detaches the walker from the set which it iterated over , releasing any computational resources and placing the iterator in the INVALID state .
50940	Searches for users in this role using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
51103	Flushes any buffered output by calling flush ( ) , and then close the handler and free all associated resources with this handler .
51117	Loads an encoded object class into this compressed schema . This method may called by implementations during initialization when loading content from disk .
51142	Messaged when the selection changes in the tree we 're displaying for . Stops editing , messages super and displays the changed paths .
51214	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
51235	Used when reading the next point from a logfile . Calls complete , because only 1 additional point is stored in the logfile .
51252	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
51363	Initializes the configuration framework using the application 's class loader as the parent class loader , and the provided install and instance paths .
51561	Visits a field instruction . A field instruction is an instruction that loads or stores the value of a field of an object .
51642	There are cases where an authentication session is created but never used . In these cases we should remove it from the store .
51870	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
51961	Indicates whether this entry contains the specified attribute . Any subordinate attribute of the specified attribute will also be used in the determination .
52016	Return true if the character is the low member of a surrogate pair . < p > This is not a public API .
52106	Returns true if the code is in [ 200..300 ) , which means the request was successfully received , understood , and accepted .
52144	Adds a notification handler for a service . This handler is used by the Platform Low Level servlet to pass notifications for processing .
52329	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
52350	Returns true if and only if the message contains a 0x00 byte in the decrypted text ( except of the first 8 bytes )
52389	Adds the given type name to the import list . Returns an empty string so that the output is not affected in snippets .
52409	Informs that a backup has been created . The method will notify to all the backup listeners that a backup has been created .
52452	Searches for assignable dynamic groups in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
52540	Add a user for the in-memory realm . All created apps use this by default , can be replaced using setRealm ( ) .
52587	Searches for users in this organization using wildcards and attribute values . Wildcards can be specified such as a* , * , *a .
52683	Updates the table model contents , sorts its contents depending on the sort options set by the user and updates the column structure .
52830	Returns the hash code value of the present value , if any , or 0 ( zero ) if no value is present .
52840	Copies object to a specified document . Works only for objects that are read from existing document , otherwise an exception is thrown .
52951	Returns an enumeration of the values in this hashtable . Use the Enumeration methods on the returned object to fetch the elements sequentially .
53042	Detaches the NodeIterator from the set which it iterated over , releasing any computational resources and placing the iterator in the INVALID state .
53292	Returns true if the specified character is a valid Pubid character as defined by production [ 13 ] in the XML 1.0 specification .
53587	Check if the value of a character belongs to a certain interval that indicates it 's the lower part of a surrogate pair .
53644	Return true if the character is the high member of a surrogate pair . < p > This is not a public API .
53652	Formats this month-day using the specified formatter . < p > This month-day will be passed to the formatter to produce a string .
53675	Marks the present position in the stream . Subsequent calls to reset ( ) will attempt to reposition the stream to this point .
53839	Flushes the stream . This is done by writing any buffered output bytes to the underlying output stream and then flushing that stream .
53942	Retrieves a constant indicating whether it is possible to store a < code > NULL < /code > value in the designated column .
54058	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
54095	Selects the specified column in the table header . Repaints the affected header cells and makes sure the newly selected one is visible .
54133	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
54189	Returns the hash code value of the present value , if any , or 0 ( zero ) if no value is present .
54244	Called when component Activity is being removed from the memory ( it 's finishing , i.e . because of back button press action )
54284	Creates a title layer . A title layer is not really a layer but a collection of layers under the same title heading .
54301	Converts a size in pixel coordinates to view coordinates . Subclasses of viewport that support `` logical coordinates '' will override this method .
54318	Returns < CODE > true < /CODE > if the Replication Server was created and < CODE > false < /CODE > otherwise .
54363	Return all of the web resource collections protected by this security constraint . If there are none , a zero-length array is returned .
54369	Returns < code > true < /code > if service schema supports multiple configurations ; < code > false < /code > otherwise .
54390	Formats this year-month using the specified formatter . < p > This year-month will be passed to the formatter to produce a string .
54579	Removes the object at the top of this stack and returns the next object at the top as the value of this function .
54661	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
54667	Returns < CODE > true < /CODE > if the read process is over and < CODE > false < /CODE > otherwise .
54677	Creates and flushes parent tree entry for the page . Effectively this means that new content must n't be added to the page .
54738	Transforms the encoding of the text , starting from the character at index start and transforming count characters , using the specified context .
54780	Tests if the specified < code > File < /code > is newer than the specified < code > Date < /code > .
54786	Returns true if the specified character is a valid name character as defined by production [ 4 ] in the XML 1.0 specification .
54856	Returns < CODE > true < /CODE > if the Synchronization Provider was enabled and < CODE > false < /CODE > otherwise .
54902	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
54984	Throw an exception if we are parsing . < p > Use this method to detect illegal feature or property changes. < /p >
55037	Get the contents of a < code > URL < /code > as a < code > byte [ ] < /code > .
55249	Opens a new session . This method will use the application id from the associated meta-data value and an empty list of permissions .
55403	Causes a redraw of the canvas . The drawing code of canvas will handle highlighted nodes and etc based on data retrieved from Model
55533	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
55598	Returns , if keepout is generated outside the board outline . Otherwise only the line shapes of the outlines are inserted as keepout .
55599	Checks that the given id is not null , if so will generate an unique id , and then returns the non-null id .
55686	Indicates whether the provided string appears Germanic ( starts with `` VAN `` , `` VON `` , or `` SCH '' ) .
55713	Visits a local variable instruction . A local variable instruction is an instruction that loads or stores the value of a local variable .
55877	Initializes the list with the values ranges ( letter and digits ) for random class to generate a new password for a user .
56064	Removes a single instance of the specified element from this queue , if it is present , whether or not it has expired .
56072	Adds a new status code - > status text mapping . This is a static method because the mapping is a static variable .
56209	Overridden for performance reasons . See the < a href= '' # override '' > Implementation Note < /a > for more information .
56231	Read from monitored file , report any changed values to the supplied handler . Not thread-safe , only call from a single thread .
56239	Returns < CODE > true < /CODE > if the refresh icon is displayed and < CODE > false < /CODE > otherwise .
56249	Increases the capacity if necessary to ensure that it can hold at least the number of elements specified by the minimum capacity argument .
56292	Returns < CODE > true < /CODE > if the node is a leaf and < CODE > false < /CODE > otherwise .
