40	Whether to use the new handshake endpoint to exchange ownership cache . Enable this when the servers are updated to support handshaking with client info .
98	Player enemies : < br > - different race < br > - duel partner < br > - in pvp zone - in ffa zone
118	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
222	Returns the tangent of a value . If USE_FAST_TRIG is enabled , an approximate value is returned . Otherwise , a direct value is used .
254	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
380	Invalidates the cache of the latest bound view . Forces the next binding of the view to run through all the interceptors ( again ) .
551	Sends a broadcast in order to the interested activities can update their view TODO - no more broadcasts , replace with a callback to subscribed listeners
576	Returns the adapter position of the first visible view . This position does not include adapter changes that were dispatched after the last layout pass .
608	Converts a Collection containing java.io.File instanced into array representation . This is to account for the difference between File.listFiles ( ) and FileUtils.listFiles ( ) .
678	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
751	This is an implementation of the apply ( ) method . It executes the funcBody text in an `` anonymous '' method call with arguments .
791	Returns a shallow copy of this < tt > ConcurrentSkipListMap < /tt > instance . ( The keys and values themselves are not cloned . )
859	Returns the adapter position of the first visible view . This position does not include adapter changes that were dispatched after the last layout pass .
865	Contacts the remote server to verify that a facet of the object implements this type . Raises a local exception if a communication error occurs .
937	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
1164	Adds a subset of the values in the array < tt > vals < /tt > to the end of the list , in order .
1230	Rejects all certificates . At most , this is useful in testing . Use in a production app will cause us to question your sanity .
1244	Create an instance of a class . Delegates to method < code > getProviderClass ( ) < /code > in order to load the class .
1309	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
1460	Store a new task in the map for providing cancellation . This method is used by AndroidAnnotations and not intended to be called by clients .
1627	This method will be used to get the hascode , this will be used to the index for inserting ArrayWrapper object as a key in Map
1654	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
1769	Creates a new Builder for DataQueryParams based on the given query . The builder state will be equal to the state of the given query .
1864	Adds a reference to the module to the settings file , if there is not already one . Must be run inside a write action .
2351	Correct for mistakes in the search query ( e.g. , if you enter `` Beetles '' , the system will search for `` Beatles '' )
2374	Repositions this audio input stream to the position it had at the time its < code > mark < /code > method was last invoked .
2481	Persist token to third-party servers . Modify this method to associate the user 's FCM InstanceID token with any server-side account maintained by your application .
2688	Creates an empty new document builder . < p > The new documents will not validate , will ignore comments , and will support namespaces .
2736	Returns true if an access to < code > target < /code > is legal from code in < code > container < /code > .
2777	[ % SkillTarget ] received % num0 damage and was put in the pull state because [ % SkillCaster ] used [ % SkillName ] .
2919	Waits for resume . If this audio player is paused waits for the player to be resumed . Returns if resumed , cancelled or shutdown .
3105	The doPost method of the servlet . < br > This method is called when a form has its tag value method equals to post .
3151	Returns the adapter position of the last visible view . This position does not include adapter changes that were dispatched after the last layout pass .
3298	Send new AionServerPacket to connection that is owner of this packet . This method is equvalent to : getConnection ( ) .sendPacket ( msg ) ;
3389	Closes this stream and releases any system resources associated with it . If the stream is already closed then invoking this method has no effect .
3622	Returns the adapter position of the last visible view . This position does not include adapter changes that were dispatched after the last layout pass .
3725	The default search results are added to the results of a global search for all users and groups , it can be disabled by passing 0
3733	Extended SSA ( SSI ) -- Compute extended SSA ( SSI ) form.. If enabled , Shimple will created extended SSA ( SSI ) form .
3955	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
4073	Waits for resume . If this audio player is paused waits for the player to be resumed . Returns if resumed , cancelled or shutdown .
4161	Returns the best jar to add to IntelliJ . < p > We prefer the interface jar if one exists , otherwise the class jar .
4398	Answer whether the provided repository location already has an exact match location The location string corresponds to the Strin returned by ISVNRepositoryLocation # getLocation ( )
4399	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
4411	The doGet method of the servlet . < br > This method is called when a form has its tag value method equals to get .
4647	Force this element to preclosed status , meaning that an end-tag has been seen but the element can not yet be closed for structural reasons .
4652	Implement length limitation on top of the < code > read < /code > method of the wrapped < code > ServletInputStream < /code > .
4686	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
4781	Returns the index ( i , j ) translated into the one-dimensional array used to store the upper triangular part of the symmetric covariance matrix .
4799	Returns the expected response < tt > y < /tt > given the value of the predictor variable < tt > x < /tt > .
4961	Determines if an owner has read permission on a table . This always calls back to the authorizer and will not return a cached value .
5042	This method is called only once when the Fragment is first created . If retained , it will not be called again across configuration changes .
5138	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
5182	Walk down the graph as far as possible according to the features in fv , and return the data in the leaf node found there .
5380	Invalidates the cache of the latest bound view . Forces the next binding of the view to run through all the interceptors ( again ) .
5406	Returns a list of values for the specified fields . There is a one-one correspondence between this list of values and the list of fields .
5430	Binds listener for user actions that start any update the hide file listing permissions for the public link to the views receiving the user events .
5639	Notifies that the resource was released . This is called by the thread when releasing the resource and may be called concurrently with a removal .
5711	Write the request log object of the current thread as JSON . The thread 's request log is cleared after a call to this method .
5944	Starts this service to perform action Baz with the given parameters . If the service is already performing a task this action will be queued .
6061	Following methods add a new node to the end of the nodeStack arrayList Since that node becomes the closest target of an implicit break or continue
6086	when we load a new patch , we need to rewrite the patch.info file . but patch info corrupted , we ca n't recover from it
6095	Asynchronously executes a query and stores the results in the given table instance . All data processing is done in a separate thread of execution .
6260	Thrown when the virtual machine notices that a program tries to reference , on a class or object , a field that does not exist .
6346	Inform this audio input stream not to expect any further calls to append ( ) , and report end-of-stream when all data has been read .
6667	Verifies a user supplied restore code against the stored restore code . If the code can not be verified a descriptive error string is returned .
6686	Invalidates the cache of the latest bound view . Forces the next binding of the view to run through all the interceptors ( again ) .
6878	Tests whether the credentials contain all needed parameters to perform an account restore . If a parameter is missing a descriptive error string is returned .
6890	Gets the authenticated session id . If it is not found , an authentication flow will be started so that a proper session id is available
6994	Creates an empty plain XML document . < p > The new document will not validate , will ignore comments , and will support namespaces .
7045	Add an index in-memory cache after it has been created in ElasticSearch . Called by the writing of a new Index if it was successful .
7299	Return the parent Node from the current node , after applying filter , whatToshow . If result is not null , set the current Node .
7403	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
7454	Attempts to decode Base64 data and deserialize a Java Object within . Returns < tt > null < /tt > if there was an error .
8149	Request an authentication token API and write the response to the console . Use preemptive Basic authentication : username = oauth password = gimmeatoken Use /v1/oauth2/token
8178	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
8460	Starts this service to perform action Foo with the given parameters . If the service is already performing a task this action will be queued .
8503	Add an element without checking whether it is already in the set . It is up to the caller to guarantee that it is n't .
8567	Indicates whether this parameters represents a single data value set , implying that it contains exactly one of data sets , periods and organisation units .
9091	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
9312	Returns a hash code value calculated from the < code > host < /code > and < code > port < /code > field values .
9350	Stops the timer mechanism . No more checks are made on the alive timers . < p > Can be restarted using the start method .
9392	Make sure that the JimpleBody is well formed . If not , throw an exception . Right now , performs only a handful of checks .
9519	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML 1.1 recommendation .
10284	We call this to guarantee that we fetch a fresh policy from the server . This is to be used if the URL is invalid .
10327	Given a pose in start of service or area description frame calculate the corresponding position and orientation for a 3D object in the Rajawali world .
10809	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
10826	Repositions this audio input stream to the position it had at the time its < code > mark < /code > method was last invoked .
10870	NON-DOM Factory method ; creates a Notation having this Document as its OwnerDoc . ( REC-DOM-Level-1-19981001 left the process of building DTD information unspecified . )
10903	Retrieve framePath from object and then call inject ( Class & lt ; T & gt ; clazz , WebElement scope , FramePath framePath ) .
10921	Draw an horizontal , centered zig-zag line . The color and style used for the drawing will be the current ones in the graphics context .
11283	Callback to be invoked when there has been an error during an asynchronous operation ( other errors will throw exceptions at method call time ) .
11316	Put up supplements to subtraction queue , so that when moving they would not decrease , need update as confirmation To update use updateSupplements ( )
11405	Indicates whether the specified object is equal to this event type , returning < code > true < /code > if the objects are identical .
11590	NOTE : conservatively returns a reference pointing to the only copy of the class loader . private static native java.lang.ClassLoader latestUserDefinedLoader ( ) throws java.lang.ClassNotFoundException ;
11597	Verify if the timeout has been reached . If yes , throws a TimeoutException will not throw anything if the timer has never been started .
11654	Convert the specified column ( s ) from a categorical representation to a one-hot representation . This involves the creation of multiple new columns each .
11761	A method which can be overwritten in mock classes - to NOT read from a socketChannel , but from e.g . a predefined byte array .
11792	Draw a vertical , centered zig-zag line . The color and style used for the drawing will be the current ones in the graphics context .
11927	Returns whether the AccountIdProvider can be used . Since the AccountIdProvider queries Google Play services , this basically checks whether Google Play services is available .
11959	The method first sorts its two underlying scans on their join field . It then returns a mergejoin scan of the two sorted table scans .
11975	Builds a new array of the given type if it is a base type or increments the dimensions of the given array by 1 otherwise .
11999	Returns a < code > WebSiteProperties < /code > instance initialized to the settings found in the < code > url.properties < /code > file .
12111	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
12176	[ % SkillCaster ] inflicted % num0 damage on [ % SkillTarget ] and caused the Rune Carve effect by using [ % SkillName ] .
12294	Called during early init to make this InvalidationClientNameGenerator the default . This should be called very early during initialization to setup the invalidaiton client name .
12344	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
12448	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
12634	Parse the path provided as a string and then call inject ( Class & lt ; T & gt ; clazz , FramePath framePath ) .
12640	Create a new regular ( non-range ) slider for interacting with the query . This allows you to select a single value at a time .
12909	Get the SHA1 hash of the first signing certificate inside a keystore , encoded as base16 ( each byte separated by ' : ' ) .
13360	Closes this stream and releases any system resources associated with it . If the stream is already closed then invoking this method has no effect .
13521	Called by the root element to leave DTD mode and if any DTD parts were printer , will return a string with their textual content .
13524	Closes this stream and releases any system resources associated with it . If the stream is already closed then invoking this method has no effect .
13710	Performs gens by iterating over the units use-boxes . If the value of a use-box is a binopExp then we add it to the outSet .
14401	If true , the control is updated on moveend , otherwise it 's always up-to-date ( updated on move ) . < /br > default false
14402	It should return a constant for TimeZone Gets the TimeZone for the given ID . private static native java.lang.String getSystemTimeZoneID ( java.lang.String , java.lang.String ) ;
14538	Waits for resume . If this audio player is paused waits for the player to be resumed . Returns if resumed , cancelled or shutdown .
15070	intersects determines if this Bounding Box intersects with another given bounding volume . If so , true is returned , otherwise , false is returned .
15145	Convenience method to create a new token with the type set to a null value and with the starting index set to the given index .
15333	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
15520	Callback to be invoked when there has been an error during an asynchronous operation ( other errors will throw exceptions at method call time ) .
15559	Computes the objective function value . This method < em > must < /em > be called by subclasses to enforce the evaluation counter limit .
15662	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
15663	Returns a new circular bitmap drawable by creating it from a bitmap , setting initial target density based on the display metrics of the resources .
15734	Computes the objective function value . This method < em > must < /em > be called by subclasses to enforce the evaluation counter limit .
15965	Returns true if this object is structurally equivalent to c. For Constants , equality is structural equality , so we just call equals ( ) .
16496	This method is called when the XPath handler matches the XPath expression . Subclasses can override this method to provide default handling upon a match .
17071	Generate a new token for the intent that has user gesture . This will invalidate the token on the previously launched intent with user gesture .
17074	Converts a Collection containing java.io.File instanced into array representation . This is to account for the difference between File.listFiles ( ) and FileUtils.listFiles ( ) .
17145	Decodes data from web safe Base64 notation . Web safe encoding uses '- ' instead of '+ ' , ' _ ' instead of '/ '
17389	Given the device pose in start of service frame , calculate the corresponding position and orientation for a OpenGL Scene Camera in the Rajawali world .
17396	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
17531	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
17569	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
17717	Attempts to decode Base64 data and deserialize a Java Object within . Returns < tt > null < /tt > if there was an error .
17735	Converts a Collection containing java.io.File instanced into array representation . This is to account for the difference between File.listFiles ( ) and FileUtils.listFiles ( ) .
17819	The `` safe '' square root of the input value , handling negative values by simply making them positive and then negating the return value .
17855	Check whether the specified role can perform a lookup for the specified destination . For that the caller needs to have producer or consumer permission .
17870	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
17880	Add a row to this table . All data columns will be notified and will take on the appropriate default values for the added row .
17971	Asynchronously executes a query and stores the results in the given table instance . All data processing is done in a separate thread of execution .
18331	Send new LsServerPacket to connection that is owner of this packet . This method is equivalent to : getConnection ( ) .sendPacket ( msg ) ;
18410	Adds a subset of the values in the array < tt > vals < /tt > to the end of the list , in order .
18557	This is overridden to set < code > updatingListSelectionModel < /code > and message super . This is the only place DefaultTreeSelectionModel alters the ListSelectionModel .
18574	Returns a list of strings , where the strings are the result of calling String.valueOf ( Object ) of each object in the given collection .
18696	Test whether this type is assignable from the other Class ; returns true if this type is not parameterized and the raw type is assignable .
18746	Returns true if exceptions of type exceptionType are handled in the try-with-resources statement or any containing statement within the directly enclosing method or initializer block .
19037	NON-DOM Factory method ; creates an Entity having this Document as its OwnerDoc . ( REC-DOM-Level-1-19981001 left the process of building DTD information unspecified . )
19047	Does an orderly shutsdown of the underlying threads . All pending tasks will be executed . No additional tasks can be scheduled after calling this .
19111	Returns the expected response < tt > y < /tt > given the value of the predictor variable < tt > x < /tt > .
19310	NON-DOM Factory method ; creates a DocumentType having this Document as its OwnerDoc . ( REC-DOM-Level-1-19981001 left the process of building DTD information unspecified . )
19459	Return the cell at the previous level or at the given level ( which must be less than or equal to the current level ) .
19498	the utility api of copying all data in `` inputstream '' to `` outputstream '' . please refers copy ( in , out , boolean )
19506	Removes the key ( and its corresponding value ) from this map . This method does nothing if the key is not in the map .
19581	Types read from annotations should be converted to Soot type . However , to maintain compatibility with Soot code most type will not be converted .
19939	If false , the marker will not emit mouse events and will act as a part of the underlying map . < /br > default true
20164	Converts a Collection containing java.io.File instanced into array representation . This is to account for the difference between File.listFiles ( ) and FileUtils.listFiles ( ) .
20260	Gets a string from the resource bundle and binds it with the given arguments . If the key is not found , return the key .
20263	Reads a MapleStory convention lengthed ASCII string . This consists of a short integer telling the length of the string , then the string itself .
20573	Decodes data from web safe Base64 notation . Web safe encoding uses '- ' instead of '+ ' , ' _ ' instead of '/ '
20656	Waits for resume . If this audio player is paused waits for the player to be resumed . Returns if resumed , cancelled or shutdown .
20969	Send new LsServerPacket to connection that is owner of this packet . This method is equivalent to : getConnection ( ) .sendPacket ( msg ) ;
20977	Start the value scope for the specified identity constraint . This method is called when the selector matches in order to initialize the value store .
21131	Invalidate the bounds of all VisualItems in this visualization . This will cause the bounds to be recomputed for all items upon the next redraw .
21186	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
21566	Get the number of bins in the histogram . The range of the histogram defined by min and max is divided into this many bins .
21599	Returns true if the specified response is an HTTP redirect response , i.e . a 300 , 301 , 302 , 303 , or 307 .
21667	Increments the sent packet counter and records the last sent time This is simply used for statistical purposes to assess the health of a node .
21806	Puts the new key/value-pair if no mapping for the given key was in the in the map before , otherwise it returns the existing mapping .
21820	If this is set , then word wrapping the legend is enabled . This means the legend will not be cut off if too long .
21833	If using comparator , return a ComparableUsingComparator , else cast key as Comparable , which may cause ClassCastException , which is propagated back to caller .
21836	Recycle viewHolder and its underlying view . This may because the view is removed or reused . Either case , this method will be called .
21936	A Level % 0 Fatigue Penalty has been applied because you have played too long . Monitor your fatigue level with the '/Fatigue ' command .
21963	Add a matching rule in the canonical MIME T form such as `` image/* '' or a MIME T literal such as `` text/html '' .
22047	Verifies that real and imaginary parts of the two complex arguments differ by at most delta . Also ensures that NaN / infinite components match .
22072	This method interrupts all blocked threads awaiting on enqueue . This is usually called when the Queue is no longer needed and should be discarded .
22081	Create an instance of a class . Delegates to method < code > getProviderClass ( ) < /code > in order to load the class .
22219	Shimple Node Elimination Optimizations -- Node elimination optimizations . Perform some optimizations , such as dead code elimination and local aggregation , before/after eliminating nodes .
22452	Cancels the AckDataEntry notify delegator , using its Lease.cancel ( ) Also it removes the current producer from the producers list held by the m_session .
22518	Creates a bookmark folder or returns its ID if it already exists . This method does not update the last modified folder in the UI .
22619	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
22730	Returns a StoredList instance according to the JVM Version . Equivalent to calling < code > getStoredList ( false , false ) ; < /code >
22731	Returns a cryptic identifier for this < code > ThrowableSet < /code > , used to identify a set when it appears in a collection .
22920	Interrupt the shell . If the user is waiting for query results , tell the server to stop sending them . Otherwise , exit normally .
23049	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
23071	Called by the root element to leave DTD mode and if any DTD parts were printer , will return a string with their textual content .
23074	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
23266	[ a-zA-Z_ : ] [ a-zA-Z0-9_ : ] * This is what i need to match Removing all characters that do not meet the regex .
23439	Override to process a single entity after it has been retrieved from storage and before it is returned to the view . Entity is null-safe .
24257	Called when a ringtone is chosen . < p > By default , this saves the ringtone URI to the persistent storage as a string .
24270	Asynchronously executes a query and stores the results in the given table instance . All data processing is done in a separate thread of execution .
24342	Increments the received packet counter and records the last received time This is simply used for statistical purposes to assess the health of a node .
24445	Returns the current value of the < code > include < /code > flag . If true the manifest will contain information about this element .
24605	Process the LPC coefficients and/or the residual in place . This method does nothing ; subclasses may want to override it to do something meaningful .
24633	Returns the < a href= '' http : //mathworld.wolfram.com/RegularizedBetaFunction.html '' > regularized beta function < /a > I ( x , a , b ) .
24652	Removes and returns the entry associated with the specified key in the HashMap . Returns null if the HashMap contains no mapping for this key .
24977	Return a unit-length vector that is orthogonal to `` a '' . Satisfies Ortho ( -a ) = -Ortho ( a ) for all a .
25104	Shimple Node Elimination Optimizations -- Node elimination optimizations . Perform some optimizations , such as dead code elimination and local aggregation , before/after eliminating nodes .
25384	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
25670	Return a value representing a collection-valued parameter . The type may be < code > Object < /code > if the parameter is not declared .
25727	Removes and returns the entry associated with the specified key in the HashMap . Returns null if the HashMap contains no mapping for this key .
26056	Sends a broadcast in order to the interested activities can update their view TODO - no more broadcasts , replace with a callback to subscribed listeners
26071	Feature switch for initial load entries augmentation ( creation of partition-specific query for entries ) . Defaults to < code > true < /code > .
26256	Indicates whether the specified object is equal to this reverb type , returning < code > true < /code > if the objects are identical .
26404	Returns a map of range - & gt ; event count . The elements of the stream are a mutable copy of the internal data .
26550	Invalidates the cache of the latest bound view . Forces the next binding of the view to run through all the interceptors ( again ) .
26725	Called when the SERP finishes loading , this records the duration of loading the SERP from the time the panel was opened until the present .
26785	Returns the < a href= '' http : //mathworld.wolfram.com/RegularizedBetaFunction.html '' > regularized beta function < /a > I ( x , a , b ) .
26842	Override to process a single entity after it has been retrieved from storage and before it is returned to the view . Entity is null-safe .
26898	Send new AionServerPacket to connection that is owner of this packet . This method is equvalent to : getConnection ( ) .sendPacket ( msg ) ;
26907	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
26930	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
26968	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
26986	If false , the vector will not emit mouse events and will act as a part of the underlying map . < /br > default true
27232	only lets non-Locals through. < br > returns < code > null < /code > if < code > val < /code > is null .
27397	Check whether lighter or darker foreground elements ( i.e . text , drawables etc . ) should be used depending on the given background color .
27486	Getter returning true if we 'll use the defined margin value , false if we 'll use the current distance between anchors as a margin .
27651	Extended SSA ( SSI ) -- Compute extended SSA ( SSI ) form.. If enabled , Shimple will created extended SSA ( SSI ) form .
27747	If this is set , then word wrapping the legend is enabled . This means the legend will not be cut off if too long .
27768	If false , the vector will not emit mouse events and will act as a part of the underlying map . < /br > default true
27791	Sends an accessibility event to mMessageView announcing that this window was added so that the mMessageView content description is read aloud if accessibility is enabled .
28056	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
28360	Remove the last extension of file . If no extension found then return the input file E.g . a.out.log -- > a.out a.diff -- > a
28369	Closes this stream and releases any system resources associated with it . If the stream is already closed then invoking this method has no effect .
28583	Send new GsServerPacket to connection that is owner of this packet . This method is equivalent to : getConnection ( ) .sendPacket ( msg ) ;
28774	Contacts the remote server to verify that a facet of the object implements this type . Raises a local exception if a communication error occurs .
28859	This method will clear the dictionary access count after its usage is complete so that column can be deleted form LRU cache whenever memory reaches threshold
28865	Reads a MapleStory convention lengthed ASCII string . This consists of a short integer telling the length of the string , then the string itself .
28955	Gets a string from the resource bundle and binds it with the given arguments . If the key is not found , return the key .
29252	Attempts to connect to a gapis server . < p/ > Will launch a new server process if none has been started . < p/ >
29278	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
29569	Force this element to preclosed status , meaning that an end-tag has been seen but the element can not yet be closed for structural reasons .
29575	Just returns true . User need to present username and password for each action that requires credential so logout does not do anything for basic authentication
29661	Returns true if element is declared to be empty . HTML elements are defines as empty in the DTD , not by the document syntax .
29932	Verifies that there is at least one element , and returns a new array of the elements , in arbitrary order , with duplicates removed .
30030	The Alarm implementation of this method also sets the JMS topic name for distribution to the client . TODO used for LASER or TIM publication ?
30186	Reset the instance as if built from a pole . < p > The circle is oriented in the trigonometric direction around pole. < /p >
30187	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
30416	Creates a group to re-target ads for users who visited advertiser 's site ( viewed information about the product , registered , etc . ) .
30417	Attempts to decode Base64 data and deserialize a Java Object within . Returns < tt > null < /tt > if there was an error .
30516	Request an authentication token API and write the response to the console . Use preemptive Basic authentication : username = oauth password = gimmeatoken Use /v1/oauth2/token
30613	Returns true if the DIP publication is a structure . In this case , the DIPHardwareAddress object refers to a given field within the structure .
30657	You summon % 0 Spirit . Cooldown time begins when it is unsummoned , and takes longer when the spirit is killed by an enemy .
30961	Asynchronously executes a query and stores the results in the given table instance . All data processing is done in a separate thread of execution .
31120	Returns < code > true < /code > if this solver has tried to leak an edge originating from the given source to its caller .
31181	Converts the provided String to bytes using the UTF-8 encoding . If the input is malformed , invalid chars are replaced by a default value .
31308	Decodes data from web safe Base64 notation . Web safe encoding uses '- ' instead of '+ ' , ' _ ' instead of '/ '
31519	Unregister the receiver such as : Messenger.getDefault ( ) .unregister ( this ) '' in onDestroy in the Activity is required avoid to memory leak !
31558	Shim to set the result type of the extraction . This is useful if you want to return a super class where expressions generate subclasses .
31714	Notifies of the presence of an XMLDecl line in the document . If present , this method will be called immediately following the startDocument call .
31791	If a test fails , take the seed printed below and add `` initRandom ( seed ) '' at the top of the test case .
32008	Add a root element to the model . Root elements are collected during merging and used to compute the transitively reachable set of referenced elements .
32045	Records the total count of times the promo panel has *ever* been opened . This should only be called when the user is still undecided .
32058	wraps a value into a EquivalentValue . returns < code > null < /code > if < code > val < /code > is null .
32080	Asynchronously executes a query and stores the results in the given table instance . All data processing is done in a separate thread of execution .
32277	Inform this audio input stream not to expect any further calls to append ( ) , and report end-of-stream when all data has been read .
32409	Convert a locale into a string that is conform with XML 's xml : lang attribute . Basically it is language-COUNTRY , e.g . en-US .
32456	Simple method to create a soft reference to the given row list . Performed in a method to allow unit-tests to override for controlled testing .
32521	< code > mult < /code > multiplies this vector by a scalar . The resultant vector is supplied as the second parameter and returned .
32566	If this sets to true and the log printed in an inner class , then this inner class name would also printed before method name .
32644	Handle unknown CatalogEntry types . < p/ > < p > This method exists to allow subclasses to deal with unknown entry types. < /p >
33032	Insert room for operation . This WILL set the length value of the operation , and will update the length value for the total expression .
33136	generate an X509 certificate , based on the current issuer and subject using the default provider `` BC '' and the passed in source of randomness
33148	Scale the image to an absolute size . This method will < em > not < /em > preserve the width-height ratio of the image .
33210	Primary method of this class . Used to communicate via the appropriate delegate for this realm out to a Push communication service such as SNS .
33268	Given a pose in start of service or area description frame calculate the corresponding position and orientation for a 3D object in the Rajawali world .
33453	Returns true if a node , always one that was initially placed on a condition queue , is now waiting to reacquire on sync queue .
33533	Adds a directed edge to the graph . The outNodes list of this node is updated and the in-degree of the other node is incremented .
33685	Convenience method to append all the characters in < code > iterator < /code > to the StringBuffer < code > result < /code > .
33944	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
33955	Returns the < code > TypeCode < /code > object corresponding to the value held in this < code > CharHolder < /code > object .
34124	Checks the size of the table and of the scroll bar where it is contained , and depending on it updates the auto resize mode .
34213	Tells whether the user chose to save the changes in the panel , to not save them or simply cancelled the selection in the tree .
34281	Resets the stream . The < code > reset < /code > method of < code > PushbackReader < /code > always throws an exception .
34626	Checks whether the given symbols can be accepted , that is , if one of the given symbols is found at the current parsing position .
34627	Create an instance of a class . Delegates to method < code > getProviderClass ( ) < /code > in order to load the class .
34773	Awaits the next HTTP request , removes it , and returns it . Callers should use this to verify the request sent was as intended .
34787	Creates a modder that injects a single static method call < i > ( void ) < /i > at the beginning of a method .
34912	Returns the string representation of this object . This method translates the response to an XML document string based on the Response schema described above .
35114	The default behavior of this method is to call sendError ( int sc , String msg ) on the wrapped response object . Not serialized .
35168	WARNING this is used for searching in a Vector . Because Vector.indexOf does n't take a comparator , this method is ill-defined and ignores strength .
35187	Sets the position to getEndIndex ( ) -1 ( getEndIndex ( ) if the text is empty ) and returns the character at that position .
35648	Checks if element belongs to a class responsible for logging ( includes the Thread class that may be used to get the stack trace ) .
35837	Recycle viewHolder and its underlying view . This may because the view is removed or reused . Either case , this method will be called .
35846	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML 1.1 recommendation .
35927	This convenience method will do all assertions necessary to validate that an annotated class was correctly annotated and that it conforms to the OpenAM conventions .
35949	Creates a new LDAP exception with the provided result code and cause . The diagnostic message will be taken from the cause , if provided .
35984	Checks whether the given serverID is a really existing serverid in the current configuration . It returns false if the given id is a siteID !
36107	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
36225	Notifies all listeners that rows in the range < code > [ firstRow , lastRow ] < /code > , inclusive , have been updated .
36586	Parses the specified string as a signed decimal byte value . The ASCII character \u002d ( '- ' ) is recognized as the minus sign .
36646	This is the final step of the resize . Here we save the new widget size and position to LauncherModel and animate the resize frame .
36787	Return the security role link for the specified security role reference name , if any ; otherwise return < code > null < /code > .
36816	Create Frame for Id3 Key Only textual data supported at the moment , should only be used with frames that support a simple string argument .
36825	If the reply has already been sent to the requesting thread , the rpc callback can handle any data that comes in after the fact .
36956	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
36972	Creates a new GSSAPI SASL bind request having the provided authentication ID and password , but no realm , KDC address , or authorization ID .
36987	Indicates whether the specified object is equal to this reverb type , returning < code > true < /code > if the objects are identical .
37313	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
37371	Checks whether the given symbols can be accepted , that is , if one of the given symbols is found at the current parsing position .
37602	Tells whether the user chose to save the changes in the panel , to not save them or simply cancelled the selection in the tree .
37662	Returns true if a node , always one that was initially placed on a condition queue , is now waiting to reacquire on sync queue .
37787	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
37967	Compute the distance between the position and the step line ( the closest point ) , and checks if it 's within the off-route threshold .
38329	Removes all of the elements from this Vector . The Vector will be empty after this call returns ( unless it throws an exception ) .
38383	Depending on whether we want to replicate or not , we do have to start the server temporarily to update its configuration and initialize data .
38397	Returns a hashcode for the group 's identifier . Two group identifiers that refer to the same remote group will have the same hash code .
38425	Escape quotes , \ , / , \r , \n , \b , \f , \t and other control characters ( U+0000 through U+001F ) .
38493	Certain logging behaviors are available for debugging beyond those that should be enabled in production . Disables a particular extended logging behavior in the sdk .
38515	Returns a non-empty string representation of this Expected suitable for debugging . The exact presentation format is unspecified and may vary between implementations and versions .
38646	Returns a DN which is subordinate to this DN and having the additional RDN components contained in the provided DN decoded using the default schema .
38670	Create an instance of a class . Delegates to method < code > getProviderClass ( ) < /code > in order to load the class .
38673	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
38733	Returns true if the < code > e < /code > is a valid KeyEvent to use in processing the key bindings associated with JComponents .
38736	This implementation is correct if whenever an `` EMPTY '' octagon is needed the EMPTY instance is used That may not be the case , always
38774	Adds an object to the end of the list by automatically creating a a new node and adding it to the end of the list .
38843	Attempts to decode Base64 data and deserialize a Java Object within . Returns < tt > null < /tt > if there was an error .
38923	Prints a message to the console debug file . The message will only be written if the the debug level is set greater than Error .
39303	Persist token to third-party servers . Modify this method to associate the user 's FCM InstanceID token with any server-side account maintained by your application .
39393	Tells you if the first header needs to be skipped ( for instance if the header says `` continued from the previous page '' ) .
39641	build TStore. < br > < br > < code > buildValueAccess -- -- the value to store < br > TStore index < /code >
39952	Returns true if the attribute is a service identifier ( i.e. , in the case of LDAP it would be the COS Specifier attribute ) .
40136	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
40189	Notifies all listeners that rows in the range < code > [ firstRow , lastRow ] < /code > , inclusive , have been inserted .
40547	Return the set of container listeners associated with this Container . If this Container has no registered container listeners , a zero-length array is returned .
40615	When loading additional scripts , we need to remember its source text so that when we come back from persistence we can load them again .
40788	Sets the ID of the user logically associated with this span , or pass in null if no such user ID exists or is appropriate .
40798	Returns true if the given thread is currently queued . < p > This implementation traverses the queue to determine presence of the given thread .
40881	Invoked by < code > installUI < /code > to create a layout manager object to manage the < code > JTabbedPane < /code > .
40981	Add a matching rule in the canonical MIME T form such as `` image/* '' or a MIME T literal such as `` text/html '' .
41025	Adds an extension attribute to the < code > W3CEndpointReference < /code > instance 's < code > wsa : EndpointReference < /code > element .
41047	This is mainly for debugging purposes so you can say `` this is a rough idea of the CrestQuery object I 've been handed '' .
41137	Given the device pose in start of service frame , calculate the corresponding position and orientation for a OpenGL Scene Camera in the Rajawali world .
41142	Updates the toggle button to contain the Icon < code > icon < /code > , and Action < code > action < /code > .
41192	Checks if the value is within the valid range . < p > This checks that the value is within the stored range of values .
41357	No way ( or need ) to indent anything , so let 's block any attempts . ( should we throw an exception instead ? )
41361	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
41436	Try to get user locale from the session , if possible . IMPLEMENTATION NOTE : this method has explicit support for Tapestry 3 and Struts 1.x
41483	This method calls < code > flush < /code > , writes the closing postamble and then closes the output stream associated with this stream .
41829	Paints the border of an arrow button . Arrow buttons are created by some components , such as < code > JScrollBar < /code > .
41844	Updates the admin connector contents displaying with what is specified in the provided ServerDescriptor object . This method must be called from the event thread .
41909	Utility method to query if this member is a method handle invocation ( invoke or invokeExact ) . Also returns true for the non-public MH.invokeBasic .
41995	Execute a statement that returns a 1 by 1 table with a text value . For example , SELECT COUNT ( * ) FROM table ;
42059	Public as a result of Timer . If the scrollBar is null , or not adjusting , this stops the timer and updates the sizing .
42073	Create a < code > View < /code > that should be used to hold a a row 's worth of children in a flow .
42141	Removes any previous compression quality setting . < p > The default implementation resets the compression quality to < code > 0.75F < /code > .
42296	Finds a connection and returns it if it is healthy . If it is unhealthy the process is repeated until a healthy connection is found .
42319	Prints a message to the console debug file . The message will only be written if the the debug level is set greater than Error .
42413	This method is called for all identities that are renamed in a repository . The universal identifier of the identity is passed in as an argument
42484	Perform synchronous search based on specified ldap filter . This is low level API which assumes caller knows how to construct a data store filer .
42591	Returns < code > true < /code > since this < code > ImageOutputStream < /code > caches data in order to allow seeking backwards .
42711	Parse JSON text into java object from the input source . Please use parseWithException ( ) if you do n't want to ignore the exception .
42719	Create an instance of a class . Delegates to method < code > getProviderClass ( ) < /code > in order to load the class .
42734	Adds < code > applet < /code > to the list of < code > Component < /code > s that need to be repainted .
42764	Updates the error message and the result code of the operation . This method is called because no workflows were found to process the operation .
42859	Get the contents of a < code > byte [ ] < /code > as a String using the default character encoding of the platform .
43160	Removes the subject with the given name from the realm . This method would throw PolicyException if the subject is being used by any policy .
43302	Return the Principal associated with the specified username and credentials , if there is one ; otherwise return < code > null < /code > .
43420	Writes the line separator . This is overriden to make sure we do n't replace the newline content in case it is outside normal ascii .
43550	Returns whether this object can accept focus or not . Objects that can accept focus will also have the AccessibleState.FOCUSABLE state set in their AccessibleStateSets .
43571	Receives Site and Server configuration information from WebtopNaming . Information is saved and the corresponding Monitoring MBeans are created after the Agent ports are started .
43573	Returns a string value corresponding to this integer attribute . The string value is just this integer attribute 's integer value converted to a string .
43590	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
43621	Closes this piped output stream and releases any system resources associated with this stream . This stream may no longer be used for writing bytes .
43807	Removes all of the elements from this list . The list will be empty after this call returns ( unless it throws an exception ) .
43894	Converts the specified integer into its binary string representation . The returned string is a concatenation of ' 0 ' and ' 1 ' characters .
44038	Check that the window configuration has been successful by reading the monitoring information and checking that we do have 2 entries with the configured max-rcv-window .
44073	Returns true if the specified character is a valid NCName start character as defined by production [ 4 ] in Namespaces in XML 1.1 recommendation .
44216	Checks whether a descriptor already exists. < br > Name , stream number and language index are compared . Data and data type are ignored .
44228	Removes all the local backends that were registered with the server . This function is intended to be called when the server is shutting down .
44305	Computes the hash code of this LDAP name . The hash code is the sum of the hash codes of individual RDNs of this name .
44313	Decodes data from web safe Base64 notation . Web safe encoding uses '- ' instead of '+ ' , ' _ ' instead of '/ '
44491	Returns a copy of this duration with the specified duration subtracted . < p > This instance is immutable and unaffected by this method call .
44544	Acquire the lock of this ShutdownManager . The function will block if other thread is holding the lock or return false if shutdown is called .
44580	Certain logging behaviors are available for debugging beyond those that should be enabled in production . Checks if a particular extended logging behavior is enabled .
44650	This method is used in foreground processing of a delete operation . It uses the specified set to perform base DN searching for each element .
44657	Converts a Collection containing java.io.File instanced into array representation . This is to account for the difference between File.listFiles ( ) and FileUtils.listFiles ( ) .
44709	Writes messages under a given package in the file handler defined when calling initLogFileHandler . Note that initLogFileHandler should be called before calling this method .
44770	Make a clone ( deep copy ) of this object . You can use this if you want to modify a request while preserving the original
44787	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
44821	If true , the field can contain multiple lines of text ; if false , the field 's text is restricted to a single line .
45141	Convert to a string given an indentation ( for pretty printing ) . This is useful for debugging the system in lieu of a debugger .
45237	Paints the background of an arrow button . Arrow buttons are created by some components , such as < code > JScrollBar < /code > .
45302	Print the Activity 's state into the given stream . This gets invoked if you run `` adb shell dumpsys activity < activity_component_name > '' .
45353	Returns a non-empty string representation of this Optional suitable for debugging . The exact presentation format is unspecified and may vary between implementations and versions .
45387	Persist registration to third-party servers . Modify this method to associate the user 's GCM registration token with any server-side account maintained by your application .
45393	Tells whether the user chose to save the changes in the panel , to not save them or simply canceled the selection in the tree .
45433	If invalidated , will subsequently refuse to produce events . < p/ > Should be called when the wrapped object is unregistered from the Bus .
45455	Reduces the number of points in a polyline while retaining its shape , giving a performance boost when processing it and also reducing visual noise .
45496	Returns < CODE > true < /CODE > if we can write on the provided path and < CODE > false < /CODE > otherwise .
45592	If the compensated sum is spuriously NaN from accumulating one or more same-signed infinite values , return the correctly-signed infinity stored in the simple sum .
45731	Subclassed to message the UI with < code > finishedPaintingChildren < /code > after super has been messaged , as well as painting the border .
45745	Removes all of this node 's children , setting their parents to null . If this node has no children , this method does nothing .
45817	Calls < code > paint ( g ) < /code > . This method was overridden to prevent an unnecessary call to clear the background .
45823	reset the underlying cipher . This leaves it in the same state it was at after the last init ( if there was one ) .
45833	Establishes the heap invariant ( described above ) in the entire tree , assuming nothing about the order of the elements prior to the call .
46013	Does the frame identifier meet the syntax for a idv3v2 frame identifier . must start with a capital letter and only contain capital letters and numbers
46056	Change the child views . This is implemented to provide the superclass behavior and invalidate the grid so that rows and columns will be recalculated .
46129	Persist token to third-party servers . Modify this method to associate the user 's FCM InstanceID token with any server-side account maintained by your application .
46413	Creates a new server-side response control with the provided sort result and attribute description . The attribute description will be decoded using the default schema .
46461	Destroy a Internal Session , depending on the value of the user 's permissions . Performs no action if the sessionID can not be matched .
46578	Check to make sure the factory is able to perform the function it is asked to do . Invoked by readMessage/writeMessage before those methods proceed .
46598	Handles ' A ' , ' E ' , ' I ' , ' O ' , ' U ' , and ' Y ' cases
46624	Paints the border of an arrow button . Arrow buttons are created by some components , such as < code > JScrollBar < /code > .
46677	Attempts to remove the specified operation from this queue if it has not yet been picked up for processing by one of the worker threads .
46719	Report a parsed external entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
46781	Signs the XML document representing < code > NameIdentifierMappingRequest < /code > using the certificate indicated by the property `` com.sun.identity.saml.xmlsig.certalias '' in AMConfig.properties file .
46808	Remove the given element from this set if it is present . Return < code > true < /code > if the element was removed .
46817	Skip until the given end tag is matched in the stream . When returned , the context is positioned past the end of the tag .
46975	Creates an argument exception which should be used when an attempt is made to reset a mandatory property that does not have any default values .
47008	Unregister authentication data . If for the given url there 's a connection , try to bind as anonymous . If unbind fails throw LdapException .
47036	Returns true if the given thread is currently queued . < p > This implementation traverses the queue to determine presence of the given thread .
47069	No way ( or need ) to indent anything , so let 's block any attempts . ( should we throw an exception instead ? )
47333	Notifies all listeners that rows in the range < code > [ firstRow , lastRow ] < /code > , inclusive , have been deleted .
47395	Tests a given byte array to see if it contains only valid characters within the Base64 alphabet . Currently the method treats whitespace as valid .
47631	Returns a < code > Shape < /code > whose interior defines the stroked outline of a specified < code > Shape < /code > .
47748	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
47791	Returns the OID from the provided syntax definition , assuming the definition is valid . < p > This method does not perform any check .
47823	Closes the cache entry and makes the socket available for reuse . This should be invoked when the end of the body has been reached .
47896	Returns a copy of this duration with the specified duration added . < p > This instance is immutable and unaffected by this method call .
48032	Returns < code > true < /code > since this < code > ImageInputStream < /code > caches data in order to allow seeking backwards .
48180	Is this a Vorbis Comment header , check Note this check only applies to Vorbis Comments embedded within an OggVorbis File which is why within here
48237	Flips the provided interpolator . For the result value of the provided interpolator using the input value , the value ' 1-result ' will be provided
48362	Converts the physical instance of this shape to a simpler physical instance , if possible . ( For example a Simplex to an IntOctagon ) .
48854	Closes this piped output stream and releases any system resources associated with this stream . This stream may no longer be used for writing characters .
48872	Report a parsed external entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
49065	Adds a < code > component < /code > with the specified tab title . Cover method for < code > insertTab < /code > .
49084	Returns true if < code > event < /code > is a < code > MouseEvent < /code > and the click count is 1 .
49240	Makes a copy of this < code > PageFormat < /code > with the same contents as this < code > PageFormat < /code > .
49258	Creates an argument exception which should be used when an argument , which is mandatory when the application is non-interactive , has not been specified .
49280	Returns true if a node , always one that was initially placed on a condition queue , is now waiting to reacquire on sync queue .
49386	Invokes before single logout process started on FM side . This method is called before the user token is invalidated on the service provider side .
49466	Recursively expands any environment variable ( s ) defined within a String . If expansion is not possible , the original string will be returned .
49484	Returns the < code > TypeCode < /code > object corresponding to the value held in this < code > AnyHolder < /code > object .
49554	Returns true if the given thread is currently queued . < p > This implementation traverses the queue to determine presence of the given thread .
49564	Decodes data from web safe Base64 notation . Web safe encoding uses '- ' instead of '+ ' , ' _ ' instead of '/ '
50156	Returns the index of the column that < code > point < /code > lies in , or -1 if it lies out of bounds .
50164	Asynchronously closes the Websocket session . This will wait until all remaining messages have been sent to the Client and then close the Websocket session .
50187	Sets this entitlement 's current application to null . For ensuring that we read the Application fresh from its store next time we access it .
50192	Returns true if the given thread is currently queued . < p > This implementation traverses the queue to determine presence of the given thread .
50202	Attempts to decode Base64 data and deserialize a Java Object within . Returns < tt > null < /tt > if there was an error .
50223	Returns true if the < tt > value < /tt > parameter is greater than or equal to the expected minimum degree , false otherwise .
50286	Parses the specified string as a signed decimal short value . The ASCII character \u002d ( '- ' ) is recognized as the minus sign .
50380	Create Frame for Id3 Key Only textual data supported at the moment , should only be used with frames that support a simple string argument .
50438	Removes the page at the specified position in this tree . Shifts any subsequent elements to the left ( subtracts one from their indices ) .
50600	Returns true if this ExifTag contains value ; otherwise , this tag will contain an offset value that is determined when the tag is written .
50633	Does the frame identifier meet the syntax for a idv3v2 frame identifier . must start with a capital letter and only contain capital letters and numbers
50639	Updates the java version contents displaying with what is specified in the provided ServerDescriptor object . This method must be called from the event thread .
50711	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
50753	Change the child views . This is implemented to provide the superclass behavior and invalidate the grid so that rows and columns will be recalculated .
50962	Adds < code > window < /code > to the list of < code > Component < /code > s that need to be repainted .
51022	Tries to add the provided operation to the work queue if not full so that it will be processed by one of the worker threads .
51158	Returns true if the serializer is used for temporary output rather than final output . This concept is made clear in the XSLT 2.0 draft .
51172	Prints a message to the console debug file . The message will only be written if the the debug level is set greater than Error .
51276	Returns true if the user is allowed to access the given URL and HTTP method combination . The HTTP method is optional and case insensitive .
51631	Returns < tt > true < /tt > if and only if this < tt > TabularData < /tt > instance contains the specified value .
51639	Returns a Connection object with the specified address . This is equivalent to createConnection ( `` IN '' , `` IP4 '' , addr ) ;
51846	This method exists for legacy reasons to provide backwards compatibility . It will not exist at runtime and should not be used under any circumstances .
51849	Execute a statement that returns a 1 by 1 table with a numeric value . For example , SELECT COUNT ( * ) FROM table ;
52030	Exploits unsafety to throw an exception that the compiler would n't permit but that the runtime does n't check . See Java Puzzlers # 43 .
52033	Merges the set options of a another options object with this . If the other options set is null , this objects stays the same .
52078	Performs any further cleanup following run state transition on invocation of shutdown . A no-op here , but used by ScheduledThreadPoolExecutor to cancel delayed tasks .
52124	Adds an extension element to the < code > W3CEndpointReference < /code > instance 's < code > wsa : EndpointReference < /code > element .
52226	Checks for concurrent writes which are not permitted . This object has no state information so the call chain is CoyoyeOutputStream- > OutputBuffer- > CoyoteResponse .
52270	Parses the specified string as a signed decimal integer value . The ASCII character \u002d ( '- ' ) is recognized as the minus sign .
52336	Reset the membership and start over fresh . i.e. , delete all the members and wait for them to ping again and join this membership .
52704	Elaborates a new search scope according to the current search scope . The new scope is intended to be used for searches on subordinate workflows .
52749	If using comparator , return a ComparableUsingComparator , else cast key as Comparable , which may cause ClassCastException , which is propagated back to caller .
52765	Find a starting cell position that will fit the given bounds nearest the requested cell location . Uses Euclidean distance to score multiple vacant areas .
52826	Prints a message to the console debug file . The message will only be written if the the debug level is set greater than Error .
52945	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
53025	Checks if this instant is equal to the specified instant . < p > The comparison is based on the time-line position of the instants .
53027	Sets this MutableBigInteger 's value array to a copy of the specified array . The intLen is set to the length of the new array .
53093	Returns a string representation of this signature object , providing information that includes the state of the object and the name of the algorithm used .
53118	Signs the XML document representing < code > NameIdentifierMappingResponse < /code > using the certificate indicated by the property `` com.sun.identity.saml.xmlsig.certalias '' in AMConfig.properties file .
53349	Returns < code > true < /code > since this < code > ImageOutputStream < /code > caches data in order to allow seeking backwards .
53412	Unwrap the specified byte array using the provided offset and length values . Used only when the SASL server has negotiated confidentiality or integrity processing .
53442	Sets the position to getEndIndex ( ) -1 ( getEndIndex ( ) if the text is empty ) and returns the character at that position .
53510	Tries to add the provided operation to the work queue if not full so that it will be processed by one of the worker threads .
53544	Indicates whether the specified object is equal to this event type , returning < code > true < /code > if the objects are identical .
53689	Marshals the value held by this < code > StringHolder < /code > object to the output stream < code > output < /code > .
53722	Notify that log file has been rotated for provided log . The last rotation time is persisted to a file and read at startup time .
53780	Searches for the first occurrence of < code > elem < /code > , beginning the search at < code > index < /code > .
53912	Returns < code > true < /code > since this < code > ImageInputStream < /code > caches data in order to allow seeking backwards .
53975	Print the the trace of methods from where the error originated . This will trace all nested exception objects , as well as this object .
54003	Processes an < a href= '' http : //www.ietf.org/rfc/rfc1867.txt '' > RFC 1867 < /a > compliant < code > multipart/form-data < /code > stream .
54008	Brings the mnemonic property in accordance with model 's mnemonic . This is called when model 's mnemonic changes . Also updates the displayedMnemonicIndex property .
54011	Returns the string representation of this object . This method translates the response to an XML document string based on the Response schema described above .
54140	Reduces the number of points in a polyline while retaining its shape , giving a performance boost when processing it and also reducing visual noise .
54279	Returns true if the < tt > value < /tt > parameter is lower than or equal to the expected maximum degree , false otherwise .
54281	Updates the error message and the result code of the operation . This method is called because no workflow was found to process the operation .
54382	Returns true if a node , always one that was initially placed on a condition queue , is now waiting to reacquire on sync queue .
54451	Sets this MutableBigInteger 's value array to a copy of the specified array . The intLen is set to the length of the specified array .
54656	Sets the position to getEndIndex ( ) -1 ( getEndIndex ( ) if the text is empty ) and returns the character at that position .
54812	Generates a copy of this composite name . Changes to the components of this composite name wo n't affect the new copy and vice versa .
54912	Method which checks all the parent organizations of this entry till the base DN , and returns true if any one of them is deleted .
54945	Report a parsed external entity declaration . < p > Only the effective ( first ) declaration for each entity will be reported. < /p >
54979	This method generates a key according to the key parameters , creates a key entry , and optionally registers it in the supplied CryptoManager context .
55072	Repositions this audio input stream to the position it had at the time its < code > mark < /code > method was last invoked .
55117	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
55211	Copies all of the mappings from the specified Map to this provider . Internal method to be called AFTER the security check has been performed .
55340	This mehtod returns whether the audio stream data is error concealed . < br > For now only interleaved concealment is known . < br >
55536	Paints a child . By default that is all it does , but a subclass can use this to paint things relative to the child .
55541	Creates a modder that injects a single static method call < i > ( void ) < /i > at the end of a method .
55766	Recycle a LDAP writer to a thread local cache . < p > The LDAP writer is then available for the thread using the method .
55951	Commits this edit so it is visible to readers . This releases the edit lock so another edit may be started on the same key .
55994	Removes all of this node 's children , setting their parents to null . If this node has no children , this method does nothing .
56116	Brings up an internal dialog panel that displays a message using a default icon determined by the < code > messageType < /code > parameter .
56205	Turns the component with number p_component_no by p_factor times 90 degree around p_pole . Works contrary to Component.turn_90_degree with the undo algorithm of the board .
56283	Sets the position to getEndIndex ( ) -1 ( getEndIndex ( ) if the text is empty ) and returns the character at that position .
