237	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
278	Determines the interfaces implemented by the class or interface represented by this object . public native java.lang.Class getInterfaces ( ) [ ] ;
283	Writes a < code > char < /code > to the bytes message stream as a 2-byte value , high byte first .
524	[ % SkillTarget ] 's flight time has decreased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
705	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
728	Constructs a scope out of the scope factory and the parent field , then searches for the injected field in this scope .
738	Shows the search term in the SearchBar . This should be called when the search term is set without search term resolution .
888	Saves registered IDs to the world . This allows registry objects to have the same integer IDs when the world is reloaded .
962	Constructs a new < code > IllegalArgumentException < /code > with specified nested < code > Throwable < /code > root cause .
978	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
982	Returns a new direct call executor with the specified scheduling context factory used to instantiate a new scheduling context on each resume .
1183	Stores an observable in the cache , using as key a combination of the host UUID and the ID of the request .
1435	calculates the approximate width of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
1610	Handles a key press during the interaction . May be called repeatedly when the user is holding the key for several seconds .
1823	Check a vector ... if it is null or its floats are NaN or infinite , return false . Else return true .
2041	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
2406	true - to post the comment as by the community false - to post the comment as by the user ( default )
2458	Return the string form of this LookupLocator , as a URL of scheme < code > '' jini '' < /code > .
2573	If this component has no YAxisValueFormatter or is only equipped with the default one ( no custom set ) , return true .
3053	Indicates if the given row is fixed , and so will not have its position changed by any layout or distortion actions .
3061	Rotates the bits of < code > in < /code > < code > count < /code > places to the left .
3085	calculates the approximate height of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
3138	Resumes encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
3177	Rotates the bits of < code > in < /code > < code > count < /code > places to the right .
3203	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
3275	Add a plugin class that implements a service to the service entry table . This does not create the plugin object instance .
3291	Tries to catch a pokemon ( will attempt to use a pokeball , if you have none will use greatball etc ) .
3425	Due to warm bootstrap feature , we make region offset to be the same for all DCs and will support different offsets later
3539	Reads the next line from the specified BufferedReader , removing leading and trailing whitespace and comments . Null is returned on EOF .
3629	Sends a note to the business layer , to confirm that the equipment is properly configured , connected to its source and running
3662	Since we appended a gzip extension to the split file name we need to take it off to get the actual split .
3751	Encodes the characters of string that are either non-ASCII characters or are ASCII characters that must be percent-encoded using the UTF-8 encoding .
3753	Controls if scrollable result sets will be used with initial load operation . Defaults to < code > true < /code > .
3805	Replacement for the Math.nextUp ( ... ) method that is only available in HONEYCOMB and higher . Dat 's some seeeeek sheeet .
3868	Invokes the delegate 's < code > read ( byte [ ] data , int , int ) < /code > method .
3870	User ID or community ID . By default , current user ID . Use a negative value to designate a community ID .
3970	Normalizes this FilterSpec by normalizing all FilterSpec objects within < code > expressions < /code > and then sorting the list itself .
4008	Returns true when some < code > SootClass < /code > object declares this < code > SootMethod < /code > object .
4116	Returns true if the provided bytes _could_ be encrypted credentials , even if they ca n't be decrypted by a specific instance .
4155	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
4395	Perform date/time arithmetic on a Timestamp . This is the only accurate way to perform date/time arithmetic across locales and time zones .
4435	Deletes the page with provided title by selecting it and pressing Delete button on Action Bar . Verifies that page is deleted .
4441	Create new TransactionEntry and add it to the list of managed transactions if such xtn does not exist . if it exists=return it
4597	< p > Constructs a < code > NumericEntityEscaper < /code > below the specified value ( exclusive ) . < /p >
4617	Returns < code > true < /code > if this loop certainly loops forever , i.e . if it has not exit .
4875	Serializes a DOM < code > Node < /code > to an < code > OutputStream < /code > using JAXP TrAX .
4887	Subclasses and step classes can call this to update next/previous button state ; this is generally called after parameter validation has finished .
4928	Directly restrict a flag for an ID , this will take priority over the default permission and will override the previous direct permission
4995	Add a plugin class that implements a service to the service entry table . This does not create the plugin object instance .
5068	If this component has no ValueFormatter or is only equipped with the default one ( no custom set ) , return true .
5264	Zooms the view provided by this display by the given scale , anchoring the zoom at the specified point in screen coordinates .
5496	Animate a zoom centered on a given location in absolute ( item-space ) co-ordinates by the given scale using the provided duration .
5559	Update the information with respect to the segment metadata of a particular physical table . This operation should be atomic per table .
5562	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
5618	[ % Protector ] received % num0 damage inflicted on you by [ % SkillCaster ] , because of the protection effect .
5685	Apply some predicate on all group members < br > Should be used only to change state of the group or its members
5812	Clone implementation . All runtime information is frozen in clone , that no longer resides in cache ( such as SupervisionStatus ) .
5836	Splits text into a list of maps ( titles ) and strings ( regular text ) . Only parses strict top-level titles .
5953	Modify the augmentations . Add an [ included ] infoset item , if the current element is a top level included item .
5965	Session id received after the auth.restore method is executed . ( If the password is changed right after the access was restored )
6001	Specifies whether the query should return only values that are active during the specified moment using the specified from/thru field name pairs .
6152	Returns the timestamp ( ms since epoch ) when the first certificate was generated , or 0 if none have been generated .
6158	Write this file part to the given output stream . If this part does n't contain a file this method does nothing .
6171	URL to the tile image to show in place of the tile that failed to load . < /br > default `` ''
6228	Loads a text file forcing the line separator to be of Unix style '\n ' rather than being Windows style '\r\n ' .
6241	Convert a time series value into the string entries for wavefront . Note : the line is not terminated with a newline .
6355	Adds the given path to the list of ' C ' directories . It also creates the directory in the file system .
6459	Some components already scale with the scaling factor . This method returns < code > true < /code > for such components .
6516	Close the given closeable object ( Stream ) in a safe way : check if it is null and catch-log exception thrown .
6612	Searches fv in durTree CART [ ] set of trees , per state , and fill the information in the HTSModel m .
6758	Inserts a mapping in this HashMap from < code > key < /code > to < code > value < /code > .
6774	Search for a xml : lang attribute , and if one is found , put the new [ language ] into effect .
6923	Execute the < code > function < /code > in the executor that assigned by < code > key < /code > .
6980	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
7063	calculates the approximate width of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
7161	Original method view.postInvalidateOnAnimation ( ) only supportd in API > = 16 , This is a replica of the code from ViewCompat .
7196	OSX requires plugged-in USB storage to have path /DCIM/NNNAAAAA to be imported . This is a temporary fix for bug # 1655552 .
7324	User ID or community ID from whose wall the post was deleted . Use a negative value to designate a community ID .
7337	Attempts to cancel the Job that matches the provided tag and endpoint . < p/ > Returns one of the CANCEL_RESULT_ constants .
7444	If the condition is true , returns . Otherwise , marks the test as failed , but does n't stop its execution .
7646	Returns true if the specified character is a space character as defined by production [ 3 ] in the XML 1.0 specification .
7792	A method to be called when some text was deleted from a text node , so that live objects can be notified .
7952	A small routine used all over to improve code efficiency , make a result map with the message and the success response code
8000	Whether a row is editable ( that is , whether the edit/delete buttons should be enabled when this row is selected ) .
8020	Inject in default frame . Frame parameter is sometimes unnecessary , because it will be overridden by Frame annotation on type clazz .
8033	Merges this access path with the given one , i.e. , adds the fields of the given access path to this one .
8063	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
8069	Convert energy from linear scale to db SPL scale ( comparing energies to the minimum audible energy , one Pascal squared ) .
8076	Returns < code > true < /code > if < code > validation.level < /code > is set to lenient or strict .
8344	Returns < code > true < /code > if the analysis could determine that i is always non-null before the statement s .
8346	Called when a selection of drawables has been chosen from the newDrawablesDialog ( ) . Adds the new drawables to the project .
8472	Remove the pre-draw listener if we 're attached to a window and mark that we currently do not need it when attached .
8506	Strips illegal characters from a table name . BigQuery only allows alpha-numeric and underscore . Everything illegal is converted to an underscore .
8554	Adds a static item to the top of the list . A static item is one that is not from the RingtoneManager .
8577	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
8666	Returns a key consisting of statusKey + attributeOptionCombo . This can identify a particular DataApproval object in the return set of statuses .
8668	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
8714	Indicates whether periods are present as a dimension or as a filter . If not this object is in an illegal state .
9236	Reset for the next write cycle . The next write cycle will exclude any data present in the dictionary , during serialization .
9503	Helper method to start this Service for its default action : to show the notification for the Timer with the given id .
9521	[ % SkillTarget ] 's flight time has decreased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
9603	Release the detector when you no longer need it . Remember to call PicassoFaceDetector.initialize ( context ) if you have to re-use .
9935	Your flight time decreased by % num0 due to the effect of [ % SkillName ] used by [ % SkillCaster ] .
10056	Called when he system received an SSL client certificate request . Plugin can use the supplied ClientCertRequest to process this certificate challenge .
10129	Resumes encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
10150	Returns true if the provided String _could_ be encrypted credentials , even if it ca n't be decrypted by a specific instance .
10165	Initializes LISession using previously obtained AccessToken The passed in access token should be one that was obtained from the LinkedIn Mobile SDK .
10311	Initialize a list of service default states if not already created . This method could be called only once per instance initialization .
10378	Clears the cached manifest information . The next get call on one of the properties will cause the information to be refreshed .
10425	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
10445	Invokes the underlying reader 's < code > read ( char [ ] , int , int ) < /code > method .
10649	Returns true if the binding is the master controller in the network . The master controller simply means that we get notifications .
10763	Returns an Iterator for the lines in a < code > File < /code > using the default encoding for the VM .
10767	Appends the content of the value the existing content when inserted , or inserts as usual if no entries match the key .
11194	Determines whether a user can access an organisation unit , based on the organisation units to which the user has been assigned .
11196	Signals if this experiment allows to make changes to its data . This is the case if the current state is DRAFT .
11222	You have gained % num1 XP from % 0 ( Energy of Repose % num2 , Energy of Salvation % num3 ) .
11262	Get the lifecycle listeners associated with this lifecycle . If this Lifecycle has no listeners registered , a zero-length array is returned .
11278	Contacts the remote server to verify that the object implements this type . Raises a local exception if a communication error occurs .
11399	Encodes the characters of string that are either non-ASCII characters or are ASCII characters that must be percent-encoded using the UTF-8 encoding .
11413	Returns a field name in English . This method is intended to be used for debugging/diagnosis and not for display to end-users .
11505	Delete an existing face list according to face list ID . Persisted face images in the face list will also be deleted .
11614	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
11646	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
11707	Toggle the component 's minimized state . If the component is already minimized , it will switch back to the preferred state .
11765	Returns true if the registrars contained in the given ( possibly null ) UnicastResponse instances are equals ( ) to one another .
11799	Returns the next pseudorandom , uniformly distributed < code > boolean < /code > value from this random number generator 's sequence .
11880	The appearance of % 0 can not be modified into % 1 and vice versa as they are different types of item .
11922	( Optional ) Sets the gcGraceSeconds that will be used when creating column families for types . If null will use default value
11943	Copy bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
11995	The appearance of % 0 can not be modified into % 1 and vice versa as they are different type of items .
12014	upgrade a read lock to a write lock . If a lock is already a write lock , this method does nothing .
12205	Determine whether a char is a URI character ( reserved or unreserved , not including ' % ' for escaped octets ) .
12326	Should the entries written to the virtualized queue be fifo or not . Defaults to < code > false < /code > .
12345	escaped an url using `` UTF-8 '' encoding , and will not escape `` ? `` , '' = '' and escaped characters
12674	Sets the < code > include < /code > flag to true so that the manifest will contain information about this element .
12698	Convert the coordinates of one of this view 's subviews into the coordinate space of one of this view 's other subviews .
12945	Suspends encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
12951	Adds the navigation bar to the Theme Editor preview . The layout for that navigation bar depends on the version of layoutlib .
13200	Specifies duration in milliseconds from the start of a scroll during which we 're unsure whether the user is scrolling or flinging .
13335	We could have more xml versions in future , but for now we could do with this to handle XML 1.0 and 1.1
13441	% 0 is grateful and gives you a % 1 as a present ( Times remaining : % 2/ % 3 ) .
13449	Creates the default probability density test expected values . Reference values are from R , version 2.15.3 ( VGAM package 0.9-0 ) .
13716	A method to be called when some text was changed in a text node , so that live objects can be notified .
13809	Hide loading UI . If progress bar is not shown , it disappears immediately . If so , it smoothly fades out .
13880	A method to be called when some text was inserted into a text node , so that live objects can be notified .
13905	Gets the cancellation state of this event . Set to true if you want to prevent buckets from placing water and so forth
14024	Returns a string representation which includes no more than the maxKeysToPrint elements with largest counts and optionally prints one element per line .
14083	Returns the schema of the explain query , which has only one field `` query-plan '' of type varchar ( 500 ) .
14093	< p > Constructs a < code > NumericEntityEscaper < /code > below the specified value ( exclusive ) . < /p >
14108	Resumes encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
14152	Returns the stash root directory for this cluster , or an HTTP not found if stash is not supported by this server .
14271	A small routine used all over to improve code efficiency , make a result map with the message and the error response code
14333	Returns < code > true < /code > if the analysis could determine that i is always null before the statement s .
14405	Subtract the specified number of droidflakes . We just take them off the end of the list , leaving the others unchanged .
15135	Call this after constructing to initialize the plugin . Final because we want to be able to change args without breaking plugins .
15228	Stops the activity manager thread . All scheduled actvities are canceled , and then the thread is then notified to stop running .
15243	A small routine used all over to improve code efficiency , make a result map with the message and the error response code
15330	true - comment will be published on behalf of a community , false - on behalf of a user ( by default )
15478	Returns true if the arguments are both NaN , are equal or are within the range of allowed error ( inclusive ) .
15590	< p > Constructs a < code > NumericEntityEscaper < /code > above the specified value ( exclusive ) . < /p >
15708	Replacement for the Math.nextUp ( ... ) method that is only available in HONEYCOMB and higher . Dat 's some seeeeek sheeet .
15991	Reads the contents of a file into a String using the default encoding for the VM . The file is always closed .
16054	Kill a bookie by index . Also , stops the respective auto recovery process for this bookie , if isAutoRecoveryEnabled is true .
16071	Removes all of the mappings from this map ( optional operation ) . The map will be empty after this call returns .
16213	Tests if headers with the given name are contained within this group . < p > Header name comparison is case insensitive .
16258	Returns the IP address of the host that the process is running on , as a string in the dot-separated integer format .
16391	Check if an element is focusable . If an element is focusable , the cell widget should not steal focus from it .
16569	Check for a given String if it is Empty which means it is either null or has zero length , when trimmed .
16831	If load balancing is enabled , load shedding is enabled by default unless forced off by setting a flag in global zk /admin/flags/load-shedding-unload-disabled
16867	Reverses the order of the polygon points within the given list . < p > This method performs a simple list reverse .
16947	Returns a filter that accepts files whose size is & gt ; = minimum size and & lt ; = maximum size .
16964	Checks if the given char is an octal digit . Octal digits are the character representations of the digits 0 to 7 .
17130	Switches to the next counter and resets it . If the current counter is the last one it switches to he first .
17144	Gets the fraction as an < tt > int < /tt > . This returns the whole number part of the fraction .
17151	Return whether the given array is empty : that is , < code > null < /code > or of zero length .
17154	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
17181	Provide ZooKeeper namespaced to GlobalFullConsistencyTimeStamp data . This is to be used by both DataStore and BlobStore for their respective C* Cluster FCT
17187	Get number of entries in the histogram . This should correspond to the number of times the fill method has been used .
17432	Adds an aspect for which , in addition to the tested aspect , we want to see baseline output of normalization results .
17654	Returns the first passed String if not empty , otherwise the second if not empty , otherwise an empty but non-null String .
17754	Checks if the given plugin is enabled or not < p > Please note that the name of the plugin is case-sensitive .
17763	Add a data processing Action to this Visualization . The Action will be updated to use this Visualization in its data processing .
17806	Centers the viewport to the specified y value on the y-axis . This also refreshes the chart by calling invalidate ( ) .
17897	Calculates the Nth generalized harmonic number . See < a href= '' http : //mathworld.wolfram.com/HarmonicSeries.html '' > Harmonic Series < /a > .
17933	Process the given Data object and returning the processed Data . Can be invoked using OpenSpaces Events when a matching event occurs .
18027	Returns the first passed String if not null , otherwise the second if not null , otherwise an empty but non-null String .
18070	Original method view.postInvalidateOnAnimation ( ) only supportd in API > = 16 , This is a replica of the code from ViewCompat .
18101	Given a count of black/white/black/white/black pixels just seen and an end position , figures the location of the center of this run .
18330	A method for determining the list of modules required to transform the given source data type into the requested target data type .
18444	Inserts < code > toInsert < /code > in the Chain before < code > point < /code > WITHOUT redirecting jumps .
18583	Constructs a scope out of the scope factory and the parent field , then searches for the injected field in this scope .
18657	Returns the preferred dimensions for this layout given the < i > visible < /i > components in the specified target container .
19113	Try to vibrate . To prevent this becoming a single continuous vibration , nothing will happen if we have vibrated very recently .
19196	Parses and initializes the 'stale ' paramer value . Any value different from case-insensitive `` true '' is considered `` false '' .
19211	Loads model x and y sample data , overriding any previous sample . Computes and caches QR decomposition of the X matrix .
19427	Return true if the resource is part of a link ( i.e . a linked resource or one of it 's children .
19527	true - method will return additional fields : likes , can_comment , car_repost , photos . These parameters are not returned by default
19632	Add an integer derived column - for example , the hour of day , etc . Uses timezone from the time column metadata
19812	Flag that specifies whether archived ads shall be shown : false - show only active ads ; true - show all ads .
19834	Logs the outcome of the promo ( first run flow ) . Logs multiple histograms ; with and without the originating gesture .
19835	Creates and starts a Tailer for the given file , starting at the beginning of the file with the default delay of 1.0s
19897	Specifies that each resource should be automatically removed from the pool once a fixed duration has elapsed after the resource 's creation .
20052	Guides the allowed concurrency among update operations . Used as a hint for internal sizing . < p > Defaults to 4 .
20282	Write a log record as control record . The method will be used by Monitor Service to enforce a new inprogress segment .
20371	Recover data for primary space . 1. try to recover in replication group . 2. try to recover notify templates in LB group
20384	[ % SkillTarget ] 's flight time has decreased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
20489	Convert the specified column from an integer representation to a categorical representation , given the specified mapping between integer indexes and state names
20635	Attempts to find the SteamVR manifest file within the given locations . The VR manifest files contain the currently installed steam apps .
20640	NOTE : the same explanation as setIn0 : G.v ( ) .out = parameter private static native void setOut0 ( java.io.PrintStream ) ;
20645	Write this datagram to a random access file or data output stream . Must only be called if data is not null .
20671	Reads the contents of a file into a String using the default encoding for the VM . The file is always closed .
20768	calculates the approximate size of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
20797	remove the slider at the position . Notice : It 's a not perfect method , a very small bug still exists .
21217	< code > detachChildAt < /code > removes a child at a given index . That child is returned for saving purposes .
21247	Pop the previous folder . Use this value to restore a prior last template folder if we pushed a new folder explicitly .
21281	Certificate info to use to generate the root certificate . Reasonable default values will be used if certificate info is not supplied .
21287	Loads the properties from the specified file in hdfs < p > The new properties are added to the current system configuration .
21382	Checks if space mode equals given mode . If true - registers the given listener to election events . Otherwise returns false .
21608	Commit the drop widget We remove it from the scene and set its companion object to point to the newly created NlComponent .
21794	Initializes the catalog manager . Note that the catalog manager should be initialized < em > before < /em > system recovery .
21993	Reads the contents of a file into a String using the default encoding for the VM . The file is always closed .
22111	Remove a DiscoveryListener from the listener set . It does nothing if the DiscoveryListener does not exist in the the listener set .
22224	Adds the given attribute to this node . Attributes have unique names . An attribute with the same name will be overwritten .
22356	Appends the text representation of the given modifier flags , followed by a single space . Used for 3.0 modifiers and annotations .
22621	Stops the activity manager thread . All scheduled actvities are canceled , and then the thread is then notified to stop running .
22651	Deletes the record specified by rid from the table . Make sure to update this.stats , this.freePages , and this.numRecords as necessary .
22743	calculates the approximate width of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
22836	Invoke method name on the specified scripted object . The object may be null to indicate the global namespace of the interpreter .
23165	Awaits the completion of the exploded super graph . When complete , computes result values , shuts down the executor and returns .
23279	Should be subclassed by the more specific types . For an intermediate catch without type , it 's simply leaving the event .
23296	Writes bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
23599	Returns a string representation of this map . The string representation consists of a list of key-value mappings , enclosed in braces .
23631	Factory method to create a < code > Random < /code > using the supplied < code > RandomGenerator < /code > .
23916	The length between two nodes u and v. In a phrase graph , this length is equal to 1.0/ ( v-u ) .
23921	Returns true if the given key is in the kingSectionLikeHash Hashtable , and the value is the same as the given value .
23956	Return true when a resource is a SVN `` meta '' resource . I.e . .svn dir or any file within it .
23980	Gets whether this column is a self incremented update column . SQL update example : UPDATE table SET version = version + 1
24027	Contacts the remote server to verify that the object implements this type . Raises a local exception if a communication error occurs .
24132	Method to get the next block this can be used while scanning when iterator of this class can be used iterate over blocks
24159	Called when he system received an SSL client certificate request . Plugin can use the supplied ClientCertRequest to process this certificate challenge .
24259	If the table for this model have a foreign key column , the value of foreign key id should be saved too .
24295	Return true if the latitude is between -90 and 90 degrees inclusive and the longitude is between -180 and 180 degrees inclusive .
24322	< p > Constructs a < code > NumericEntityEscaper < /code > between the specified values ( inclusive ) . < /p >
24462	Toggle the component 's maximized state . If the component is already maximized , it will switch back to the preferred state .
24484	Returns true if the specified path of URLs is equal to the annotation URLs of the specified loader , and false otherwise .
24536	A proxy petition by the GM has been received , but the user is offline . The petition number is % 0 .
24650	Returns true if the given key is in the kingSectionLikeHash Hashtable , and the value is the same as the given value .
25118	Reset session based parameters . Called before the a session starts . Before the show , regardless if the stack is displayable .
25142	[ % SkillTarget ] 's flight time has decreased by % num0 because [ % SkillCaster ] used [ % SkillName ] .
25203	Creates an intent , adds location data to it as an extra , and starts the intent service for fetching an address .
25211	convert tick to microsecond with given tempo . Does not take tempo changes into account . Does not work for SMPTE timing !
25458	Returns < code > true < /code > if the item contains plain text ( not Java Speech Markup Language text ) .
25954	A small routine used all over to improve code efficiency , make a result map with the message and the success response code
26122	Initialization method that must be called after bean creation . Sets the destination and registers as listener in the Spring listener container .
26197	Suspends encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
26205	Returns a shallow copy of this < tt > EntryPacket < /tt > instance . And also only clone the values array .
26226	This method will create the dictionary map . First time it will create dictionary map with capacity equal to list of byte arrays
26230	Indicates whether the given string contains any of the given search strings . The operation ignores case and leading and trailing blanks .
26307	perform objects equality , cater for null and also first use == which is not always true for various class `` equals ''
26498	< p > Constructs a < code > NumericEntityEscaper < /code > above the specified value ( exclusive ) . < /p >
26575	[ % SkillCaster ] received % num0 damage and was put in the pull state because he used [ % SkillName ] .
26619	If a class is package private , make it public so instrumented code living in a different class loader can instantiate them .
26670	Closes the stream . Call this after parse ( ) , or when there is no longer any need for this object .
26793	Change the submit button 's background color to the one provided , this will not change the circular progress animation 's color .
27005	Localizes an Xliff file by replacing original targets by target where the content has been prepended with a prefix and the locale .
27073	Your flight time decreased by % num0 due to the effect of [ % SkillName ] used by [ % SkillCaster ] .
27303	Indicates if the Display is using high quality ( return value true ) or regular quality ( return value false ) rendering .
27329	Returns a new AnyVal that matches a present Optional . The given value is assigned the value of the optional on match .
27496	Adds a new post on a user wall or community wall . Can also be used to publish suggested or scheduled posts .
27593	Checks if a WebElement is ready to be operated on , ie . is visible and not stale and returns that element .
27691	SCIPIO : Clones item . < p > NOTE : if modelMenu/parentMenuItem are null , they are taken from the current item .
27708	Regenerates item count upon each call // TODO input parameters - based on attacker stats // TODO more precise calculations ( non-linear )
27733	Parses the given string into a Date using the supported date formats . Returns null if the string can not be parsed .
27833	Directly allow a flag for an ID , this will take priority over the default permission and will override the previous direct permission
27900	Suspends encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
27917	calculates the approximate height of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
28094	Helper method to throw an exception when a result is expected as a return value ( e.g . in a ternary operator )
28178	Adds the values in the array < tt > vals < /tt > to the end of the list , in order .
28223	converts < br > 1 - MPQ-Tempo to BPM tempo < br > 2 - BPM tempo to MPQ tempo < br >
28277	Returns true if provided DataSources are independent . Independent means that no DataSource is ( super ) owner of any other DataSource .
28288	Set it to true if you want to prevent users from panning the popup off of the screen while it is open .
28302	Initialize a list of service default states if not already created . This method could be called only once per instance initialization .
28331	Returns true if the given object is equal to this one . Since IntType is a singleton , object equality is fine .
28507	Given a count of black/white/black/white/black pixels just seen and an end position , figures the location of the center of this run .
28549	Creates descriptor for a discrete item created by line segments representing the outline and filled segments with custom dataFactor ad min/max values .
28696	You have invited % 0 's group to the alliance . % 0 's group has a total of % 1 members .
28765	Checks whether the given List of IdentifiableObjects contains an object which is an OrganisationUnit and has the currentParent property set to true .
28784	Indicate that the ResultSet object 's cursor is scrollable but generally not sensitive to changes to the data that underlies the ResultSet .
28813	Reset for the next write cycle . The next write cycle will exclude any data present in the dictionary , during serialization .
28990	[ % SkillCaster ] exchanged his enmity toward [ % SkillTarget ] with his spirit 's by using [ % SkillName ] .
29045	< p > Constructs a < code > NumericEntityEscaper < /code > between the specified values ( inclusive ) . < /p >
29080	A small routine used all over to improve code efficiency , make a result map with the message and the error response code
29236	Starts a new subreport . Stores the name of the subreport on the stack . Creates a timestamped subreport start log entry .
29299	Makes this entry a persistent entry . Can be called only if the entry has not been written yet to the space .
29330	This method relies on the fact that STATE_CURRENT_FOLDER pref is not yet set when onCreate is called for a newly created widget .
29380	Gets the fraction as a < tt > long < /tt > . This returns the whole number part of the fraction .
29456	Broadcast packet with influence update to all players . - Responsible for the message `` The Divine Fortress is now vulnerable . ''
29468	Flag that specifies whether archived ads shall be shown : false - show only active ads ; true - show all ads .
29665	Returns the minimum dimensions needed to layout the < i > visible < /i > components contained in the specified target container .
29666	If the value is a doc or an enum , convert it to a string . Use maximal margin width for this .
29729	Constructs a scope out of the scope factory and the parent field , then searches for field with selector in this scope .
29776	Adds the values in the array < tt > vals < /tt > to the end of the list , in order .
29923	Computes the ordering value only based on the distance of the tab to the center one . Low values have higher priority .
29947	A small routine used all over to improve code efficiency , make a result map with the message and the success response code
29972	Removes all of the elements from this applyTransformToDestination ( optional operation ) . The applyTransformToDestination will be empty after this call returns .
30204	Fired in all cases when the request is finished , after both success and failure , override to handle in your own code
30226	Controls if scrollable result sets will be used with initial load operation . Defaults to < code > true < /code > .
30415	Reads a unsigned short ( 16-bit ) from an InputStream . The value is converted to the opposed endian system while reading .
30453	Start point for apps that use code classifying . Called ones at app start . It creates training task for code classifier .
30563	This gets passed a list and concatenate them together making sure that there is no forbidden characters and remove the if necessary .
30616	calculates the approximate height of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
30626	You are currently unable to open a private store . There are % 0 minute ( s ) left on your ban .
30801	This tells how many valid samples have been read into the current frame ( before applying the optional data processor ! ) .
30862	Checks to see if both uids are referring to the same app id , ignoring the user id part of the uids .
30964	If true , inverses Y axis numbering for tiles ( turn this on for TMS services ) . < /br > default true
31021	Reads the contents of a file into a String using the default encoding for the VM . The file is always closed .
31278	Remove the specified connection from the list of managed connections by this connection factory . If it does n't exist then fail silently
31293	Checks if two types are the same or are equivalent under a variable mapping given in the type map that was provided .
31375	Converts a class name from the Java language naming convention ( foo.bar.baz ) to the JVM internal naming convention ( foo/bar/baz ) .
31610	Tries to resolve the given resource value to an actual RGB color . For state lists it will pick the simplest/fallback color .
31642	Update offset to scroll . This will calculate the delta of previous offset and new offset , then apply it to scroll .
31897	Does the current image have a device frame around it ? Returns true , false , or null if no image computed yet
31941	Recover data for primary space . 1. try to recover in replication group . 2. try to recover notify templates in LB group
31943	Returns < code > true < /code > if there are more tokens , < code > false < /code > otherwise .
31949	Resolves the given DNS host name into an IP address , and returns it in the dot separated format as a string .
32118	Creates a selector for a given protocol . The proxy will be taken from the settings and installed on the dispatch selector .
32212	NOTE : this method just fills in the stack state in this throwable object content . public native java.lang.Throwable fillInStackTrace ( ) ;
32328	Calculates an expiration based on the passed time and a requested duration . Will clip the expiration to the end of the epoch
32414	Verifies that the class is not a primitive or array class , and either is n't final or is assignable to Principal .
32542	If training task future is exists , then classifier was started to train or already trained & classifier is ready to use .
32633	Serializes a DOM < code > Node < /code > to an < code > OutputStream < /code > using JAXP TrAX .
32704	Animate a zoom centered on a given location in screen ( pixel ) co-ordinates by the given scale using the provided duration .
32786	This method notifies of the start of a parameter entity . The parameter entity name start with a ' % ' character .
32809	Clone implementation . All runtime information is frozen in clone , that no longer resides in cache ( such as SupervisionStatus ) .
32872	Adds the value of this fraction to another , returning the result in reduced form . The algorithm follows Knuth , 4.5.1 .
33019	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
33204	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
33216	The default behavior of this method is to return encodeRedirectUrl ( String url ) on the wrapped response object . Not Serialized .
33263	Gets the < code > iconable < /code > property , which by default is < code > false < /code > .
33369	Returns the result of the HS256 algorithm over the challenge using the secret . Returns null if no valid answer was determined .
33389	Stop refreshing below this node . TODO : this method is very costly when applied to something else than the root node .
33392	Resumes encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
33433	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
33545	Writes an array of characters . This method can not be inherited from the Writer class because it must suppress I/O exceptions .
33620	Whether the task will be executed on an online server ( using an LDAP connection and the tasks backend ) or not .
33668	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
33673	Closes this connection change record writer , including the underlying connection . Closing a previously closed change record writer has no effect .
33763	Creates an argument exception which should be used when a property value argument is invalid because it does not a property name .
33789	Returns true if the tree is being edited . The item that is being edited can be returned by getEditingPath ( ) .
33790	Creates a copy of this < code > SimpleDateFormat < /code > . This also clones the format 's date format symbols .
33818	Flushes this writer to ensure all pending data is sent out to the target writer . This implementation flushes the target writer .
33870	check whether the literal is int type < br > also , the requiredType should be int or superclass or Integer or null
33873	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
33889	Remove the specified DN from the pending map , it may not exist if the entries are being migrated so just return .
33938	Asserts that two floats are equal concerning a delta . If the expected value is infinity then the delta value is ignored .
34060	Asserts that two objects refer to the same object . If they are not an AssertionFailedError is thrown with the given message .
34061	Prints this < code > TransformException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
34065	Given the permission name identifies whether that permission already exists . If it does n't it registers creation of a new privilege .
34143	Return the filter definition for the specified filter name , if any ; otherwise return < code > null < /code > .
34222	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
34287	Returns a String representation of the < code > & lt ; samlp : Request & gt ; < /code > element .
34422	The default behavior of this method is to call encodeUrl ( String url ) on the wrapped response object . Not Serialized .
34446	Create an < CODE > Unmarshaller < /CODE > object that can be used to convert XML data into a java content-tree .
34449	Searches for dynamic groups in this organization unit using wildcards . Wildcards can be specified such as a* , * , *a .
34467	If this returns true , the map will extract the diff using getDiff ( ) Otherwise it will serialize the entire object .
34652	Stops editing and returns true to indicate that editing has stopped . This method calls < code > fireEditingStopped < /code > .
34665	Updates the user entry to remove any timestamp indicating that the password has been changed in accordance with the required change time .
34676	Creates an argument exception which should be used when a property modification argument is invalid because it does not a property value .
34814	Returns < code > true < /code > if the request has the < code > arg=newsession < /code > query parameter .
34861	Adds testParams to the list of all test parameters , so it can be null'ed out later if it 's not part .
34880	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
34889	Writes the array of bytes to the output stream and increments the number of bytes written by the size of the array .
34944	Clears the cache of toggled tree paths . This does NOT send out any < code > TreeExpansionListener < /code > events .
34971	Inserts the specified element at the tail of this queue , waiting for space to become available if the queue is full .
34976	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
35137	Gets an array containing all children of this < tt > BeanContext < /tt > that match the types contained in arry .
35206	Given a restricted token , returns the SSOTokenID of the master token can only be used if the requester is an app token
35348	Creates a set of LDAP key store parameters with default options . See the class Javadoc for more information about the parameters .
35407	See the general contract of the < code > mark < /code > method of < code > InputStream < /code > .
35411	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
35512	Return the value for the specified initialization parameter name , if any ; otherwise return < code > null < /code > .
35684	Invokes the delegate 's < code > read ( byte [ ] data , int , int ) < /code > method .
35729	subclasses can override this method to create new subclasses of BCSSServiceProvider without having to override addService ( ) in order to instantiate .
35816	Adds a new header with the name and value . This may be used to add multiple headers with the same name .
35866	Asserts that two floats are equal concerning a delta . If the expected value is infinity then the delta value is ignored .
35936	Gets whether or not the book is being signed . If a book is signed the Material changes from BOOK_AND_QUILL to WRITTEN_BOOK .
35954	Updates the enabled state of the children Components based on the enabled state of the < code > JSpinner < /code > .
36061	Programmatically perform a `` click '' . This does the same thing as if the user had pressed and released the button .
36136	Create an < CODE > Unmarshaller < /CODE > object that can be used to convert XML data into a java content-tree .
36141	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
36152	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
36273	Restore a persistent object , must wait for subsequent setBeanContext ( ) to fully restore any resources obtained from the new nesting BeanContext
36319	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
36365	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
36472	Suspends encoding of the stream . May be helpful if you need to embed a piece of base640-encoded data in a stream .
36541	Adds an action listener to this panel . The action listener will be invoked when the user clicks on the 'Delete ' .
36561	Create a < CODE > Marshaller < /CODE > object that can be used to convert a java content-tree into XML data .
36603	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
36619	Add a set of ACIs to the ACI list . This is usually used a startup , when global ACIs are processed .
36647	Receive notification of the start of the non-text event . This is sent to the current processor when any non-text event occurs .
36684	Adds the provided prohibited attributes to the list of attribute types that entries subject to this DIT content rule must not contain .
36798	Request a SOCKS connection to the application server given . If the request fails to complete successfully , an exception is thrown .
36857	Tries to url encode specified text ( using utf-8 encoding ) . If something gone wrong -- returns input text as is .
36879	Does this thread still have something to execute ? ( as opposed to have finished running , either normally or abnormally ? )
37028	Helper method that will try to load at least specified number bytes in input buffer , possible moving existing data around if necessary
37091	Skips all characters until EOF or the specified target is found . Normally used to skip invalid input until the next separator .
37151	Initialize the document builder factory so that it can be reused and does not need to be reinitialized for each parse action .
37269	Removes the specified menu item from this menu . If there is no popup menu , this method will have no effect .
37295	Creates a panel to ask the user if ( s ) he wants to remove the databases located outside the installation path .
37346	Creates a String representation of the < code > & lt ; samlp : Request & gt ; < /code > element .
37384	Resolves a URI reference against a base URI . Work-around for bug in java.net.URI ( < http : //bugs.sun.com/bugdatabase/view_bug.do ? bug_id=4708535 > )
37408	Searches for all roles in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
37439	Writes this object out to a stream ( i.e. , serializes it ) . We check the guard if there is one .
37465	Translates the Java object to an XML NotificationSet document and sends the corresponding XML document to the URL specified in this method .
37487	All non 401 ( and all 401 not about refreshing the access token ) error responses are handled by the failure handler .
37532	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
37675	Generate a key with initialisation vector parameter derived from the password , salt , and iteration count we are currently initialised with .
37696	Returns the length of the erroneous input . The length is only meaningful for a malformed-input error or an unmappable character error .
37814	Adds a new environment property to the environment of this context . If the property already exists , its value is overwritten .
37850	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
37884	Returns true if the specified character is a space character as defined by production [ 3 ] in the XML 1.0 specification .
37897	Adds IFD data . If IFD data of the same type already exists , it will be replaced by the new data .
37911	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
37934	Restores in memory data needed to build the CNIndexDB . In particular , initializes the changes cursor to the medium consistency point .
37976	The default behavior of this method is to call addIntHeader ( String name , int value ) on the wrapped response object .
38010	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
38027	Returns whether the < i > any policy OID < /i > will be inhibited if it 's included in a certificate .
38063	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
38117	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
38400	Return a String containing a copy of the chars in this buffer , limited to the [ start , end [ range .
38465	Prints this < code > URIReferenceException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
38466	Indicates whether the backend should attempt to perform an incremental backup containing only the changes since the last incremental or full backup .
38573	The default behavior of this method is to return isUserInRole ( String role ) on the wrapped request object . Not serialized .
38588	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
38908	Cache gets cleared after # initialize is called but before # perform , so need to re-get the config options each time .
38912	Write all remaining bytes in buffer to the given channel . If the channel is selectable then it must be configured blocking .
38976	Clears the selection in the object , so that nothing in the object is selected . This will close any open menu .
39045	Parses the provided set of command-line arguments and attempts to contact the Directory Server in order to send it the shutdown request .
39071	Enables exclusive scanning on EAN-13 , EAN-8 , UPC-A , UPC-E , Code-39 , Code-93 , Code-128 , ITF and Codabar barcodes .
39137	Prints this < code > NoSuchMechanismException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
39240	Returns the result of the HS256 algorithm over the challenge using the secret . Returns null if no valid answer was determined .
39430	Generate a key with initialisation vector parameter derived from the password , salt , and iteration count we are currently initialised with .
39441	Removes the provided prohibited attribute in the list of attribute types that entries subject to this DIT content rule must not contain .
39543	Asserts that two doubles are equal concerning a delta . If the expected value is infinity then the delta value is ignored .
39630	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
39723	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
39731	Remove this Session from the active Sessions for this Manager , but not from the Store . ( Used by the PersistentValve )
39733	Notifies the Activity that a support action mode has been started . Activity subclasses overriding this method should call the superclass implementation .
39751	Returns < CODE > true < /CODE > if the panel is extended and < CODE > false < /CODE > otherwise .
39903	Save the state of the < tt > HashMap < /tt > instance to a stream ( i.e. , serialize it ) .
40061	Test that a client that has already seen the first change from server 2 now see the first change from server 1 .
40153	Create the filter object in the heap , setting the header name and value for the filter , based on the configuration .
40203	Notify this controller that an entry has changed . The controller starts refreshing the corresponding node . Child nodes are not refreshed .
40291	Prints this < code > URIReferenceException < /code > , its backtrace and the cause 's backtrace to the specified print stream .
40366	Tries to CAS head to p. If successful , repoint old head to itself as sentinel for succ ( ) , below .
40417	Create a < code > SOAPElement < /code > object initialized with the given < code > Name < /code > object .
40451	Create an < CODE > Unmarshaller < /CODE > object that can be used to convert XML data into a java content-tree .
40489	Returns a field name in English . This method is intended to be used for debugging/diagnosis and not for display to end-users .
40541	Prints this < code > MarshalException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
40569	Creates a zeroed-destination < code > Raster < /code > with the correct size and number of bands , given this source .
40571	Return true if nothing has been sent to this result tree yet . < p > This is not a public API .
40585	Prints this < code > MarshalException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
40666	Adds record of a new file , by filename and path . The path may be relative to a source compilation path .
40804	Returns a name for a natively-typed array field element 's type . < p > May be overridden by individual language contexts .
41064	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
41073	Register interest in sockets listening to the specified address on any port . Thread-safe , can be called from multiple threads concurrently .
41086	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
41230	clears < b > all < /b > saved preferences . Module independent . < b > Erases everything < /b > .
41231	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
41264	Read the Logical VorbisComment Tag from the file < p > Read the CommenyTag , within an OggVorbis file the VorbisCommentTag is mandatory
41274	Indicates whether the LDIF generated should include attribute types ( i.e. , attribute names ) only or both attribute types and values .
41396	Initialize the document builder factory so that it can be reused and does not need to be reinitialized for each parse action .
41435	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
41579	Returns a < code > LayoutManager < /code > that will be set on the < code > JRootPane < /code > .
41809	Adds the given ExifTag to its default IFD and returns an existing ExifTag with the same TID or null if none exist .
41882	Returns whether this object class is a placeholder , i.e . a dummy object class that does not exist in the schema .
41885	Tests if an expected token was not received , i.e. , one or more predecessor tokens have not yet been successfully processed .
41896	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
41915	Returns the hash code for this DIT structure rule . It will be calculated as the hash code of the rule ID .
42222	This is basically the method that is execute in SplashScreen.main but it it assumes that is being called outside the event thread .
42317	Return the index of the last occurrence of n in the argument array . Return -1 if the name is not used .
42509	Create a < CODE > Marshaller < /CODE > object that can be used to convert a java content-tree into XML data .
42540	Paints the border of the track of a slider . This implementation invokes the method of the same name without the orientation .
42556	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
42603	Suspends encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
42831	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
42865	Resets the stream to the most recent mark , or to the beginning of the string if it has never been marked .
42879	Returns < tt > true < /tt > if this map contains an UpdateMsg with the same CSN as the given UpdateMsg .
42907	Copy NodeList members into this nodelist , adding in document order . If a node is null , do n't add it .
42984	True indicates that getOCProperties ( ) was called , may have been modified , and thus its dictionary needs to be reconstructed .
43076	Append a byte to the end of the array . If the array is too small , it 's capacity is doubled .
43079	used to add the key to the page and to the session so it can be retrieved when the final store is done
43125	Report a bound property update to any registered listeners . No event is fired if old and new are equal and non-null .
43132	Tests whether the context represents an external routed request , by checking if the client context is present and that it is external
43365	Converts Java time to DOS time , encoding any milliseconds lost in the conversion into the upper half of the returned long .
43470	Starts the progress bar animation . ( This is an alias of resetAnimation ( ) so it does the same thing . )
43494	Environment to start executing the script in . During sandbox execution , we need to call sandbox interceptor while executing asynchronous code .
43602	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
43706	Searches for assignable dynamic groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
43710	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
43763	Checks whether an object is present in the array or whether it is equal to any of the objects in the array .
43773	Inserts the specified element at the tail of this queue . As the queue is unbounded , this method will never block .
43896	Handles the < code > DragSourceDropEvent < /code > by invoking < code > dragDropEnd < /code > on listener-a and listener-b .
44055	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
44092	Make sure to call this AFTER setting all of the superclass info . Otherwise , it wo n't return the correct answer .
44160	Pop a pair of nodes from the tail of the stack . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
44171	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
44244	Parses the given error message into an array of javac compilation error messages ( one per javac compilation error line number ) .
44285	Paint the button 's border if < code > BorderPainted < /code > property is true and the button has a border .
44327	Gets the total lengths of characters in this line . Other elements ( images , tables ) are not taken into account .
44343	Prints this < code > NoSuchMechanismException < /code > , its backtrace and the cause 's backtrace to the specified print stream .
44404	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
44437	creates current configuration class instance . In every subclass this method should be override and return new instnce of it 's class .
44459	Indicates whether a value stored in the designated column can be used in a < code > WHERE < /code > clause .
44478	This function is currently only being used by Position ( ) and Last ( ) . See respective functions for more detail .
44532	Handles the < code > DragSourceDragEvent < /code > by invoking < code > dragOver < /code > on listener-a and listener-b .
44629	Returns the value obtained by reversing the order of the bytes in the specified < tt > char < /tt > value .
44768	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
44828	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
44878	Register for changes to service 's schema . The object will be called when schema for this service and version is changed .
44958	Forget last bug reported by current detector . Subsequent calls of this method have no effect if no new bugs were reported .
45034	Asserts that two objects refer to the same object . If they are not an AssertionFailedError is thrown with the given message .
45037	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
45038	The default behavior of this method is to return sendRedirect ( String location ) on the wrapped response object . Not serialized .
45165	Reads ECC domain parameters from an inputstream , based on given named curves and point formats . It uses the BC functionality .
45183	Inserts the specified element at the tail of this queue . As the queue is unbounded , this method will never block .
45280	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
45303	Function Checks how the current operator effects the run time stack after being run An operator may increase or decrease the stack size
45352	Persist whatever operations that have been made using this API . Unless this method is called , no other methods have effect .
45354	Returns the < code > KeyStroke < /code > s that are bound in this < code > InputMap < /code > .
45395	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
45545	Reduces the node and then calls the visitor on the reduced expression . Throws an exception if the node is n't reducible .
45557	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
45565	Records that 'hostname ' is known not to have any associated addresses . ( I.e . insert a negative cache entry . )
45597	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
45623	If the bottom of Sprite collided . Checks by using third element in SVGPath Array ( logical count starting from one ) .
45633	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
45778	The default behavior of this method is to call sendError ( int sc , String msg ) on the wrapped response object .
45956	Paints the background of the track of a slider . This implementation invokes the method of the same name without the orientation .
46068	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
46112	Set the parent node . For an extension function , we also need to set the parent node for all argument expressions .
46231	Sends < code > die < /code > to each subedit , in the reverse of the order that they were added .
46275	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
46428	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
46500	Pop a pair of nodes from the tail of the stack . Special purpose method for TransformerImpl , pushElemTemplateElement . Performance critical .
46607	Write an array of characters . This method can not be inherited from the Writer class because it must suppress I/O exceptions .
46678	Sets the security manager to use when checking access to Java packages to the configured system security manager ( if enabled ) .
46767	Handles the < code > DragSourceDragEvent < /code > by invoking < code > dropActionChanged < /code > on listener-a and listener-b .
46850	Returns < code > true < /code > if the < code > Timer < /code > coalesces multiple pending action events .
47027	Generate worker address on event bus . < p > Format : vertx.kue.handler.workers. { eventType } . { addressId } < /p >
47063	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
47106	The default behavior of this method is to return encodeRedirectURL ( String url ) on the wrapped response object . Not serialized .
47239	Returns an Iterator for the lines in a < code > File < /code > using the default encoding for the VM .
47269	The default behavior of this method is to call sendError ( int sc ) on the wrapped response object . Not serialized .
47337	Handles the < code > DragSourceDragEvent < /code > by invoking < code > dragMouseMoved < /code > on listener-a and listener-b .
47393	Adds the given ExifTag to the given IFD and returns an existing ExifTag with the same TID or null if none exist .
47411	Gets the cancellation state of this event . Set to true if you want to prevent buckets from placing water and so forth
47590	Configures a socket for use in unit tests . This should only be used if the socket is not expected to timeout .
47682	Resumes encoding of the stream . May be helpful if you need to embed a piece of base64-encoded data in a stream .
47689	Tests if headers with the given name are contained within this group . < p > Header name comparison is case insensitive .
47925	Write an array of characters . This method can not be inherited from the Writer class because it must suppress I/O exceptions .
47948	Reads a unsigned short ( 16-bit ) from an InputStream . The value is converted to the opposed endian system while reading .
47992	Create ( or allocate ) and return a Response object suitable for receiving the contents of a Response from the responsible Container .
48094	Searches for static groups in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
48138	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
48224	Get the next object of this list ( assumes that first ( ) has been called prior to calling this method . )
48248	Creates a token iterator from a header iterator . This method can be overridden to replace the implementation of the token iterator .
48385	Resumes encoding of the stream . May be helpful if you need to embed a piece of base640-encoded data in a stream .
48392	Creates an argument exception which should be used when a property value argument is invalid because it does not a property value .
48513	Returns a reference , a stub , for the remote object associated with the specified < code > name < /code > .
48568	Unregisters < code > listener < /code > so that it will no longer receive < code > AncestorEvents < /code > .
48578	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
48644	Allows the m-let to perform any operations needed after having been registered in the MBean server or after the registration has failed .
48666	Returns a field name in English . This method is intended to be used for debugging/diagnosis and not for display to end-users .
48699	Register interest in sockets listening to the specified address on any port . Thread-safe , can be called from multiple threads concurrently .
48797	Inputs are selectable ( I ) Outputs that are followed by outputs are selectable Outputs that are followed by input are NOT selectable
48891	Creates a directory with given path if it does not exist and clears the contents of the directory in case it exists .
48892	Adds the given xsl : attribute to the set of collected attributes , but only if there is a currently open element .
48943	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
49067	A factory method to build the appropriate LuminanceSource object based on the format of the preview buffers , as described by Camera.Parameters .
49090	Prints this < code > KeySelectorException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
49141	Returns < code > true < /code > if service schema supports multiple configurations ; < code > false < /code > otherwise
49202	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
49360	Inserts the tree shapes of p_item into all active search trees . This is possibly the entry point in the search tree system
49365	The default behavior of this method is to call addDateHeader ( String name , long date ) on the wrapped response object .
49578	Returns a default renderer to be used when no header renderer is defined by a < code > TableColumn < /code > .
49617	For view re-create , you should save the text currently showed on window which might be changed during a series of processing .
49681	Resolves the specified local name and prefix into a Java.lang.Method . Returns null if the prefix and local name are not found .
49716	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
49865	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
49873	Paints the background of the track of a slider . This implementation invokes the method of the same name without the orientation .
49950	Calls logout , if necessary , on any associated JAASLoginContext . May in the future be extended to cover other logout requirements .
49959	Handles the < code > DragSourceEvent < /code > by invoking < code > dragExit < /code > on listener-a and listener-b .
49964	Inserts the specified element at the tail of this queue , waiting for space to become available if the queue is full .
50160	Creates a String representation of the < code > & lt ; samlp : Response & gt ; < /code > element .
50287	Enlarges the box by p_offset . Contrary to the offset ( ) method the result is an IntOctagon , not an IntBox .
50289	Notifies the Activity that a support action mode has been started . Activity subclasses overriding this method should call the superclass implementation .
50322	Empty the ServerState . After this call the Server State will be in the same state as if it was just created .
50375	Returns a String representation of the < code > & lt ; saml : Attribute & gt ; < /code > element ,
50494	Determines the number of times user failed authentication updates the accountInfo object with the user information and count of failed authentication attempts .
50564	Invokes the underlying reader 's < code > read ( char [ ] , int , int ) < /code > method .
50582	Closes this reader . This implementation releases the buffer used for the pipe and notifies all threads waiting to read or write .
50603	Searches for static groups in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
50609	Calculates the quotient of this div b and places the quotient in the provided MutableBigInteger objects and the remainder object is returned .
50637	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
50683	Sends a RADIUS AccessReject response and cleans up the cache and authentication context if it not null by calling its logout method .
50727	Asserts that two objects refer to the same object . If they are not an AssertionFailedError is thrown with the given message .
50844	Returns < code > true < /code > if the option is an authentication related option such as user ID and password .
50857	Creates a write-enabled log file that appends records to the end of file , with the provided root path and record parser .
50922	Allows the user of this module to verify that asserts are actually being called from JS and that none of them failed .
51026	Prints this < code > KeySelectorException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
51043	Ensures that the value ends with suffix . If it does n't , it 's appended . This operation is case sensitive .
51075	Creates a beveled border of the specified type , using the specified colors for the inner and outer highlight and shadow areas .
51126	Checks if there is any < code > Referral < /code > in this < code > Referrals < /code > object .
51273	Creates a SessionDescription populated with the information contained within the string parameter . Note : unknown field types should not cause exceptions .
51286	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
51384	Adds the provided argument to the set of arguments handled by this parser and puts the argument in the LDAP connection group .
51386	Prints this < code > URIReferenceException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
51395	Prints this < code > XMLSignatureException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
51441	This method gets the node 's value as a String and uses that String as if it were an input character notification .
51559	Create a < CODE > Marshaller < /CODE > object that can be used to convert a java content-tree into XML data .
51595	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
51607	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
51620	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
51712	Registers for changes to service 's configuration . The object will be called when configuration for this service and version is changed .
51718	Asserts that two objects refer to the same object . If they are not an AssertionFailedError is thrown with the given message .
51740	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
51756	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
51785	Retrieves the names of all of all the subcommands that may be used to clear some part of the password policy state .
51936	Pushes a byte back . The next get ( ) will return this byte instead of the value from the underlying data source
51980	Creates an intent , adds location data to it as an extra , and starts the intent service for fetching an address .
51990	Determine if we must drop the connection because of the HTTP status code . Use the same list of codes as Apache/httpd .
52057	Adds the provided argument to the set of arguments handled by this parser and puts the argument in the LDAP connection group .
52062	Searches for filtered roles in this organizational unit using wildcards . Wildcards can be specified such as a* , * , *a .
52089	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
52120	Test that a client that has already seen the first change from server 1 now see the first change from server 2 .
52133	Create ( or allocate ) and return a Request object suitable for specifying the contents of a Request to the responsible Container .
52303	Adds a new environment property to the environment of this context . If the property already exists , its value is overwritten .
52520	In this case , if the entry is associated with a registered group instance , then that group instance will be deregistered .
52623	Returns the last foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
52671	Appends p_point to the text pane after transforming to the user coordinate sytem . Returns false , if that was not possible .
52698	Entry point for classes using the service . Validates requests against the CORS specification , and add headers required to the response .
52720	Prints this < code > XMLSignatureException < /code > , its backtrace and the cause 's backtrace to the standard error stream .
52726	Marks the current position in this stream . Setting a mark is not supported in this class ; this implementation does nothing .
52771	This method does nothing , but a class that extends this class could over-ride it and do some processing of the source .
52801	Returns < code > true < /code > since this < code > ImageOutputStream < /code > maintains a main memory cache .
52862	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
52885	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
52911	Copy NodeList members into this nodelist , adding in document order . If a node is null , do n't add it .
52953	Prints this < code > TransformException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
52962	Returns the < code > LayoutManager < /code > that should be installed on the < code > MetalTitlePane < /code > .
52988	From XSLTC Declare a prefix to point to a namespace URI . Inform SAX handler if this is a new prefix mapping .
53000	Registers for changes to service 's schema . The object will be called when schema for this service and version is changed .
53129	If the right of Sprite collided . Checks by using second element in SVGPath Array ( logical count starting from one ) .
53164	Returns < code > true < /code > if the request has the < code > forward=true < /code > query parameter .
53225	Copy bytes from a < code > byte [ ] < /code > to an < code > OutputStream < /code > .
53375	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
53433	Paints the border of the track of a slider . This implementation invokes the method of the same name without the orientation .
53462	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
53528	Searches for assignable dynamic groups in this organization using wildcards . Wildcards can be specified such as a* , * , *a .
53638	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
53813	Writes this control 's value to an ASN.1 writer . The value ( if any ) must be written as an ASN1OctetString .
54074	Checks whether an object is present in the array or whether it is equal to any of the objects in the array .
54076	The default behavior of this method is to call encodeURL ( String url ) on the wrapped response object . Not Serialized .
54115	Adds a menu choice to the menu which will have a single letter as its key and which returns the provided result .
54208	Invoked when an internal frame is in the process of being closed . The close operation can be overridden at this point .
54212	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
54213	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
54231	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
54264	Prints this < code > MarshalException < /code > , its backtrace and the cause 's backtrace to the specified print stream .
54268	If the right of Sprite collided . Checks by using fourth element in SVGPath Array ( logical count starting from one ) .
54372	Handle sync failure by counting retries on this sync token , passing to ( optional ) post-retry handler when retries are exceeded .
54397	Creates an argument exception which should be used when a property modification argument is invalid because it does not a property name .
54485	Sets up the fixture , for example , open a network connection . This method is called before a test is executed .
54492	Returns the foo with the primary key or returns < code > null < /code > if it could not be found .
54508	Creates a panel to ask the user if ( s ) he wants to remove the logs located outside the installation path .
54559	Updates the foo in the database or adds it if it does not yet exist . Also notifies the appropriate model listeners .
54595	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
54618	Creates a String representation of the < code > & lt ; samlp : Request & gt ; < /code > element .
54857	Returns a clone of this selection model with the same selection . < code > listenerLists < /code > are not duplicated .
54978	Tears down the fixture , for example , close a network connection . This method is called after a test is executed .
55098	Prints this < code > NoSuchMechanismException < /code > , its backtrace and the cause 's backtrace to the specified print writer .
55133	Returns < code > true < /code > since this < code > ImageInputStream < /code > maintains a main memory cache .
55208	This method registers the AMSessionToken AssertionBuilder and InterceptorProvider required to consume a sts instance protected by a SecurityPolicy binding specifying OpenAMToken Assertions .
55210	Returns a filter that accepts files whose size is & gt ; = minimum size and & lt ; = maximum size .
55260	True iff triangle is a member of this triangulation . This method is n't required by AbstractSet , but it improves efficiency .
55390	Writes the array of bytes to the output stream and increments the number of bytes written by the size of the array .
55456	Returns the first foo in the ordered set where uuid = & # 63 ; and companyId = & # 63 ; .
55563	Returns < code > true < /code > if the option is an authentication related option such as user ID and password .
55593	Add a mapping from a config path to the factory function used to build an audit log filter for this config fragment .
55758	Writes the array of bytes to the output stream and increments the number of bytes written by the size of the array .
55891	Reads a Unicode < CODE > String < /CODE > from the font file . Each character is represented by two bytes .
55966	Translation-time validation of the XML document associated with the JSP page . This is a convenience method on the associated TagLibraryValidator class .
56004	Mark an update message as committed , then push all committed local changes to the replicationServer service in a single atomic operation .
56087	Register this factory with the JVM . May be called more than once . The implementation ensures that registration only occurs once .
56257	Adds the provided prohibited attributes to the list of attribute types that entries subject to this DIT content rule must not contain .
56272	Check if the specified attribute type is a DN by checking if its syntax OID is equal to the DN syntax OID .
