186	Helper to launch the UploadFilesActivity for which you would like a result when it finished . Your onActivityResult ( ) method will be called with the given requestCode .
650	( Applies only to a scheduled post . ) Publication date ( in Unix time ) . If used , posting will be delayed until the set time .
842	Inserts a short array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
876	Inserts an int array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
918	Checks if the VM currently has a SecurityManager installed . Note that this may change over time . So the result of this method should not be cached .
1255	Starts emiting particles from a specific view . If at some point the number goes over the amount of particles availabe on create no new particles will be created
1635	Determine if the given type is assignable from the given value , assuming setting by reflection . Considers primitive wrapper classes as assignable to the corresponding primitive types .
1668	We need to override this method to mark the camera for re-configuration ( set proper projection matrix ) since it will be reset by Rajawali on surface changes .
1695	Inserts a float array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
1883	Print debug message ( if the debug level is high enough ) . < p/ > < p > Prints `` the message : spec '' < /p >
2117	This is not a test per say but cleans up old data in the root folder so that there wo n't be any performance issue after a while .
2261	Creates a < CODE > GSObjectMessageImpl < /CODE > object . A < CODE > GSObjectMessageImpl < /CODE > object is used to send a Serializable java object .
2375	Prunes this instance so that it retains only the partitions included in the given set . No operation takes place if the given set is null or empty .
2426	Apply mask penalty rule 1 and return the penalty . Find repetitive cells with the same color and give penalty to them . Example : 00000 or 11111 .
2728	You have removed the Stigma Stone , but you can still use the % 0 skill ( Level % 1 ) as you are equipped with another stone .
2748	Inserts a double array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
2769	Determines if the inputted item stack is Cyberware . This means its item either implements ICyberware or is linked to one ( in the case of vanilla items )
2798	Add an adjustment to the order item ; do n't worry about setting the orderId , orderItemSeqId or orderAdjustmentId ; they will be set when the order is created
3444	Joins the results from a pattern via its plan . < p > < img width= '' 640 '' src= '' https : //raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/and_then_when.png '' alt= '' '' >
4071	Inserts a byte array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
4113	Returns a fraction corresponding to the given edit rate string . The edit rate is assumed to be a list containing of two elements : numerator and denominator .
4506	< code > divide < /code > divides the values of this vector by a scalar and returns the result . The values of this vector remain untouched .
4746	Stops emitting new particles , but will draw the existing ones until their timeToLive expire For an cancellation and stop drawing of the particles , use cancel instead .
4756	Removes a data tag from the control of this activator . Implementing classes should make sure time deadband filtering is deactivated when releasing a tag from their control .
4792	Searches the list back to front for the last index of < tt > value < /tt > , starting at < tt > offset < /tt > .
4897	Inserts a boolean array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
5083	When a image name part can be ambiguously either host or namespace , check which one it is based on a regex of valid characters for the namespace part
5164	Identifier of a community or current user . < p > Note that community id must be negative . `` owner_id=1 '' - user `` owner_id=-1 '' - community
5293	Returns true if element 's closing tag is generally not printed . For example , < tt > LI < /tt > should not print the closing tag .
5316	Creates a < CODE > GSObjectMessageImpl < /CODE > object . A < CODE > GSObjectMessageImpl < /CODE > object is used to send a Serializable java object .
5369	If the comparator decides that the ( non-key ) attributes do no match , this method is called . Default implementation is to call preprocessMatch , followed by executor.addForUpdate
5512	Calculate the next power of 2 , greater than or equal to x. < p > From Hacker 's Delight , Chapter 3 , Harry S. Warren Jr .
5729	IDs requested ads , campaigns , clients or account , separated with a comma , depending on the value set in `` ids_type '' . Maximum 2000 objects .
5767	Use Open Nesting -- Use an open nesting model . Use an open nesting model , where inner transactions are allowed to commit independently of any outer transaction .
5893	Gets whether classes relations status is not complete and should be synchronized . OpenJPA creates class meta data only after an entity is persisted for the first time .
6016	Helper method to startup a new bookie server with the indicated port number . Also , starts the auto recovery process , if the isAutoRecoveryEnabled is set true .
6060	If set to true , the zoom number used in tile URLs will be reversed ( maxZoom - zoom instead of zoom ) . < /br > default false
6255	Inserts a short array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
6447	Indicates whether this info object specified matches this one . To match , the match requirements of the superclass must be met and the types must be equal .
6491	Returns a QueueReader object containing all methods found reachable so far , and which will be informed of any new methods that are later found to be reachable .
6628	Inserts a String array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
6705	Round to nearest integer using the round-half-even method . That is round to nearest integer unless both are equidistant . In which case round to the even one .
6870	Add a given number of rows to this table . All data columns will be notified and will take on the appropriate default values for the added rows .
6997	Check if the given class represents a primitive wrapper , i.e . Boolean , Byte , Character , Short , Integer , Long , Float , or Double .
7052	Called by the LeaseRenewalManager when it can not renew a lease that it is managing , and the lease 's desired expiration time has not yet been reached .
7068	Checks if the job should pause and if so loop endlessly sleeping . Returns true if the job should be terminated and false if it should continue to run
7289	Sets the Color components using the specified integer value in the format RGB565 . This is inverse to the rgb565 ( r , g , b ) method .
7353	Locks the schema , preventing any additional changes . Locked schemas can not be unlocked ! Cloned copies of a locked schema will not inherit this locked status .
7422	Checks if the app is in battery saver mode , and if the user hasnt set the setting to avoid deleting screenshot , and then deletes the screenshot .
7567	Create a directory at the specified location ( if not already present ) . This will also create any parent directories that do n't exist , as well .
7596	Verbose dump file -- Filename for detailed execution log . If you want to save the geomPTA analysis information for future analysis , please provide a file name .
7666	The existing removeAllEdges in the parent class seems to be throwing concurrentmodification exception most of the time . Here is a version that does n't throw that exception .
7761	Given a field name and a tree of json nodes , empty the contents of all the json nodes matching the field name . This method is recursive .
7967	Objects read and written with repetitive must be immutable ( can not be changed as they are kept in underlying map , changing them will affect the next repetitiveRead/Write
8013	Asserts that the given boolean is < code > true < /code > . If this is not the case , some kind of unchecked exception is thrown .
8102	Return true if the actual expiration is greater than or equal to the desired expiration ( e.g . we do n't need to renew this lease any more .
8273	Inserts a char array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
8371	Sets the routing index ( which partition this will `` hit '' ) for the script . Defaults to a random routing . Defaults to a random routing .
8548	Inserts a byte array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
8796	Searches the list back to front for the last index of < tt > value < /tt > , starting at < tt > offset < /tt > .
8979	Returns a copy of the given server proxy having the client method constraints that result after the specified method mapping is applied to the given client method constraints .
9239	Returns true if the provided string argument is to be considered a unit interval , which implies that the value is numeric and inclusive between 0 and 1 .
9901	The main processing method . This happens in a background task . In this case we are just sampling down the bitmap and returning it from a resource .
10028	Computes the Spearman 's rank correlation matrix for the columns of the input rectangular array . The columns of the array represent values of variables to be correlated .
11044	Fill up our buffer from the underlying input stream . Users of this method must ensure that they use all characters in the buffer before calling this method .
11109	The main processing method . This happens in a background task . In this case we are just sampling down the bitmap and returning it from a resource .
11270	Ensure there is at least one animation for every path in group ( linking them by names ) Build the `` current '' path based on the first group
11305	The number of entries to keep in the space . In all bulit in schemas of GigaSpaces , if this is not set , the value is 100000 .
11481	Instance methods , when converted to static methods need to have the subject object as the first parameter . If the method is static , it is unchanged .
11798	Apply mask penalty rule 1 and return the penalty . Find repetitive cells with the same color and give penalty to them . Example : 00000 or 11111 .
11805	Convert a metric to a wavefront string . Empty metrics and histograms do not emit a value . Note : the line is not terminated with a newline .
12017	Inserts a char array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
12089	Register a < code > ServiceConfigListener < /code > instance . The instance will be notified when the < code > serviceengine.xml < /code > file is reloaded .
12229	It visits the in-memory tree that represents a bill of materials and it collects info of its nodes in the Map . Method used for bom summarized explosion .
12248	Called whenever we change contents to update head and see if we need to wake up the queue thread . Assumes the caller holds the lock on contents .
12287	Reads an unsigned short ( 16-bit ) value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
12313	Returns the union ( join ) of this MonitorSet and < code > other < /code > , putting result into < code > this < /code > .
12316	For a polynomial with the given coefficients , compute < code > numSamples < /code > values , equally spaced in the interval [ a , b [ .
12333	Inserts a double array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
12447	Number nodes -- Print node numbers in dumps . When printing debug information about nodes , this option causes the node number of each node to be printed .
12451	If one of the tags used within the rule is marked as simulated , then this < code > ClientRuleTag < /code > is also marked as simulated .
12572	takes < code > node < /code > and redirects all branches to < code > oldTarget < /code > to < code > newTarget < /code > .
12974	Returns true if this mouse button was clicked once . < p > Returns false if the button was double/triple/etc clicked or is currently waiting to be released .
13009	Generates a random sample of double values . Sample size is random , between 10 and 100 and values are uniformly distributed over [ -100 , 100 ] .
13206	Returns whether the current category is managed by the custodian ( e.g . parent , not an enterprise admin ) of the account if the account is supervised .
13342	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
13397	< code > addLocal < /code > adds the provided values to this vector internally , and returns a handle to this vector for easy chaining of calls .
13553	Indicates whether this category combo has at least one category , has at least one category option combo and that all categories have at least one category option .
13566	returns true if this mgr which requires that the txn participants join into the txn in contrary to a mgr which the participants are known prior to txn propagation
13641	Number nodes -- Print node numbers in dumps . When printing debug information about nodes , this option causes the node number of each node to be printed .
13804	Call this method to let the ChartData know that the underlying data has changed . Calling this performs all necessary recalculations needed when the contained data has changed .
13899	Estimates the number of block accesses to compute the index selection , which is the same as the index traversal cost plus the number of matching data records .
14095	< code > subtractLocal < /code > subtracts the provided values from this vector internally , and returns a handle to this vector for easy chaining of calls .
14098	You can not trade , enhance , destroy , sell , extract , or soulbind sealed items , and it takes % 0 days to unseal them completely .
14106	Manually add a command to the command queue. < br > Useful for testing , and for times when the mod might want to add its own commands .
14178	Assuming the user does n't need anything fancy , this will automatically bind this item to the given holder . The user can always override this if necessary .
14555	Prints out the method corresponding to b Body , ( declaration and body ) , in the textual format corresponding to the IR used to encode b body .
14596	Determines if the given primitive is supported by this deserializer . At this time the only exclusions are BINARY , DECIMAL , VARCHAR , CHAR , and UNKNOWN .
14712	Inserts a long array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
14847	Converts the passed role to a DTO . The depth is used to control the amount of association you want . It also prevents potential infinite serialization cycles .
14906	Given a filter String , generates a Set of ApiJobStoreFilters . This method will throw a BadApiRequestException if the filter String can not be parsed into ApiJobStoreFilters successfully .
14915	When the overflow list overflows , the maximum number of elements that may remain in the overflow list ( the rest are moved into the base bit vector )
15125	Checks if the partition has the given vertex ( labels in vertex ) . This implementation enforces that all labels in partition must be present in the vertex .
15391	Increases the pointer to the end of the array by one ( if it is at the end it will return to the start of the array ) .
15614	Check whether this DataTag is the result of a rule . Rules are internal TIM tags as opposed to regular DataTags which are acquired from an external source .
16030	API method . Using default readTimeout which is Long.MAX_VALUE . This call blocks until a message arrives , the timeout expires , or this message consumer is m_closed .
16065	Return a value representing a parameter for the given value . The type may be < code > Object < /code > if the parameter is not declared .
16129	Return true if the latitude and longitude intervals of the two rectangles are the same up to the given tolerance ( see r1interval.h and s1interval.h for details ) .
16214	Identifier of an item owner Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
16935	< code > divide < /code > divides the values of this vector by a scalar and returns the result . The values of this vector remain untouched .
16974	Return response messages from users who have sent a friend request or , if `` suggested '' is set to true , to return a list of suggested friends
16982	You can not continue the battle as you have insufficient Abyss Points . You will be resurrected at % 1 if nothing is entered within % 0 minutes .
17053	Performs post-handling of the given grid . If the query has the single indicator as data filter item , the column at the data dimension index is removed .
17056	If isEmpty is true , call the method to send the job payload to the user else call the method to send the job result to the user .
17211	Determines if an < code > ASModel < /code > itself is valid , i.e. , confirming that it 's well-formed and valid per its own formal grammar .
17558	Tries to CAS right field to skip over apparent successor succ . Fails ( forcing a retraversal by caller ) if this node is known to be deleted .
17623	< code > divide < /code > divides the values of this vector by a scalar and returns the result . The values of this vector remain untouched .
17749	Returns the days between two dates . Positive values indicate that the second date is after the first , and negative values indicate , well , the opposite .
18211	Print Context Counts ( Totals only ) -- Print total number of contexts . Causes Paddle to print the number of contexts and number of context equivalence classes .
18616	Takes volumes from ContainerDescription in format [ /host-directory : /container-directory ] or [ namedVolume : /container-directory ] and puts the suffix for host part of the volume name .
19154	Entry point from client to schedule the provided job . This cancels the job if it 's already been scheduled , and replaces it with the one provided .
19217	Initializes the document sets using a portion of the files of the base directory subtree , either in a stratified or not stratified manner . Assumes non-flat structure .
19318	Return the given gravity value or the default if the passed value is NO_GRAVITY . This should be used for children that are positioned relative to a keyline .
19376	returns true if this mgr which requires that the txn participants join into the txn in contrary to a mgr which the participants are known prior to txn propagation
19787	SCIPIO : Clears the cart , and if it gets destroyed in the process , make sure another is created . < p > Helps with template compatibility .
19803	Call this method to let the ChartData know that the underlying data has changed . Calling this performs all necessary recalculations needed when the contained data has changed .
19825	Returns the hash code for this < code > MarshalledInstance < /code > . The hash code is calculated only from the serialized form of the contained object .
19887	Emit an event that you want all subscribers , both local and remote to be informed of . You can provide any object that can be serialised to json
19890	SCIPIO : Queries run-at-start Job entities . < p > TODO : If commonCondition null , build it ( requires more refactor ) ; commonCondition should be optimization only
19921	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
19961	[ % Protector ] received % num0 damage inflicted on [ % SkillTarget ] by [ % SkillCaster ] , because of the protection effect cast on it .
20014	This class is reused across different clients , and passes itself in as a callback . Check whether the client exercising the callback is the client we expect .
20123	Provides a way to disable crash uploading entirely , regardless of the preferences . Used by tests that trigger crashers intentionally , so these crashers are not uploaded .
20130	Sets the Color components using the specified integer value in the format RGB888 . This is inverse to the rgb888 ( r , g , b ) method .
20453	Returns true if the two leases both implement RemoteMethodControl and have the same constraints for Lease methods , or both do n't implement RemoteMethodControl , else returns false .
21040	Draw the given Token . This will simply find the proper SyntaxStyle for the TokenType and then asks the proper Style to draw the text of the Token .
21075	Generates a random sample of double values . Sample size is random , between 10 and 100 and values are uniformly distributed over [ -100 , 100 ] .
21144	Called when an activity you launched exits , giving you the requestCode you started it with , the resultCode it returned , and any additional data from it .
21320	This is overridden to forward the event to the tree . This will return true if the click count > = 3 , or the event is null .
21670	Creates a < code > JSON < /code > instance from an < code > InputStream < /code > . The method assumes the character set is UTF-8 .
21846	State behaviours . VERB_STARTING - > Successful start , change job to VERB_EXECUTING and post timeout . _PENDING - > Error _EXECUTING - > Error _STOPPING - > Error
21916	Allows the current user to leave a chat or , if the current user started the chat , allows the user to remove another user from the chat .
22008	Rails an int . flite never returns an int more than 19 from a feature processor , we duplicate that behavior here so that our tests will match .
22080	Generates source code instead of a full compilation . This method does nothing if the Gradle model does not specify the name of the Gradle task to invoke .
22213	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
22380	Returns the days between two dates . Positive values indicate that the second date is after the first , and negative values indicate , well , the opposite .
22413	Connects to the System of Record using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
22519	List the possible vocalization names that are available for the given voice . These values can be used in the `` name '' attribute of the vocalization tag .
22577	Puts an existing Map on the BOTTOM of the stack ( bottom meaning will be overriden by lower layers on the stack , ie everything else already there )
22707	Returns true if current position is in the middle of a triple quote delimiter ( 3 x quot ) , and advances 'pos ' by two if so .
22852	The open interface for other classes in CRUD package to query the first record in a table . If the result set is empty , gives null back .
23009	Frees the page to be returned back to the system . The page is no longer valid and can be re-used the next time the user called allocPage .
23127	< code > loadIdentity < /code > sets this matrix to the identity matrix . Where all values are zero except those along the diagonal which are one .
23409	Formats the given time delta , preserving all data . < p/ > Equivalent to < code > new HumanTime ( l ) .getApproximately ( ) < /code >
23543	Inserts a String array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
23612	Returns the estimated number of blocks in the materialized table . It does < em > not < /em > include the one-time cost of materializing the records .
23614	List all people in a person group , and retrieve person information ( including person ID , name , user data and registered faces of the person ) .
23738	Returns < code > true < /code > if < code > attributeValue < /code > is a constant value ( it does not contain an expression ) .
23836	Available answers list , for example : [ `` yes '' , '' no '' , '' maybe '' ] There can be from 1 to 10 answers .
23894	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
24214	< code > addLocal < /code > adds the provided values to this vector internally , and returns a handle to this vector for easy chaining of calls .
24255	Creates preformatted instance of ScrollableContainer to be used in Options dialog . All insets are already initialized to defaults , the client components should have zero outer insets .
24382	Read data from input stream < code > is < /code > , in the appropriate way as determined by our < code > type < /code > .
24465	Determines if the output has been cancelled . Access to the cancelled variable should be within a synchronized block such as this to ensure that access is coherent .
24491	calculate the ProposedOrder quantity and update the quantity property . Read the first ProductFacility.reorderQuantity and calculate the quantity : if ( quantity < reorderQuantity ) quantity = reorderQuantity ;
24542	Starts emiting particles from a specific view . If at some point the number goes over the amount of particles availabe on create no new particles will be created
24718	Winalt notation . Given an integer , return the Windows `` Alt+nnnn '' notation for that character number . Valid range is only from 0032 to 0255 decimal .
24746	For each item in the column , returns the same number with the sign changed . For example : -1.3 returns 1.3 , 2.135 returns -2.135 0 returns 0
24841	Puts the specified grammar into the grammar pool and associate it to a root element name ( this being internal , the lack of generality is irrelevant ) .
25054	Access the code from within the our own code so that a subclass can override it . Use this rather than the public static method in local code .
25059	Inserts a long array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
25217	Method return TaskDefinition , accepts JobDefinition and TaskDefinition Id , filters all TaskDefinitions in the provided job . Returns null if no TaskDefinition with provided id is found .
25332	Indicates if a given class type is a primitive numeric one type ( one of byte , short , int , long , float , or double ) .
25558	Returns < code > true < /code > if the specified URL uses the `` httpmd '' protocol ; returns < code > false < /code > otherwise .
25728	Validates this data tag . At the moment this means only checking if the data tag address is ! = null and then validating the data tag address .
25803	Gym Offense takes the better of No Weave/Weave Damage over 100s and multiplies by the Pokemon 's base attack to arrive at a ranking of raw damage output .
25890	Return < code > True < /code > if all permissions - read and publish should be asked one after another in the same time after logging in .
25966	Create a new FloatBuffer of an appropriate size to hold the specified number of Vector2f object data only if the given buffer if not already the right size .
26432	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
26528	If this is not a dry run , we may have created/changed some files and the project may no longer compile . Let the user know about undo .
26662	The main processing method . This happens in a background task . In this case we are just sampling down the bitmap and returning it from a resource .
26755	Starts emiting particles from a specific view . If at some point the number goes over the amount of particles availabe on create no new particles will be created
26854	Read data from input stream < code > is < /code > , in the appropriate way as determined by our < code > type < /code > .
26905	Inserts a float array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
27025	Connects to the System of Record using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
27200	Scales this point by the given scaling factor . Note that there is no guarantee that the new point will be < em > valid < /em > .
27287	If a request comes to as `` http : //server name/App Name/recordings '' or `` http : //server name/App Name/recordings '' , this function will hold the rest .
27294	Inflate a menu resource into this navigation view . < p/ > < p > Existing items in the menu will not be modified or removed. < /p >
27318	Return response messages from users who have sent a friend request or , if `` suggested '' is set to true , to return a list of suggested friends
27326	Starts emiting particles from a specific view . If at some point the number goes over the amount of particles availabe on create no new particles will be created
27427	Initializes the document sets using a portion of the files of the base directory subtree , either in a stratified or not stratified manner . Assumes non-flat structure .
27603	Access the code from within the our own code so that a subclass can override it . Use this rather than the public static method in local code .
27715	Invalidates the auth token for the account . Must call this method when the auth token is found to have expired or otherwise become invalid for authenticating requests .
27757	Return true if the interval ( which is closed ) contains the point ' p ' . Skips the normalization of ' p ' from -Pi to Pi .
27869	The open interface for other classes in CRUD package to query the last record in a table . If the result set is empty , gives null back .
27893	Sets a repeating alarm that fires request registration Intents . Setting the alarm overwrites whatever alarm is already there , and rebooting clears whatever alarms are currently set .
28004	Requests a location refresh so that a valid location will be available for constructing an X-Geo header in the near future ( i.e . within 5 minutes ) .
28110	Add the key and return it 's index code . If the key already is present , the previous index code is returned and no insertion is done .
28199	Inserts an int array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
28312	Create a new FloatBuffer of an appropriate size to hold the specified number of Vector3f object data only if the given buffer if not already the right size .
28370	Deletes the current record . Deletion is performed by marking the record as `` deleted '' and setting the content as a pointer points to next deleted slot .
28526	If a request comes to as `` http : //server name/App Name/ '' or `` http : //server name/App Name/index.html '' , this function will hold the rest .
28638	Remove and returns the Map from the top of the stack ; if there is only one Map on the stack it returns null and does not remove it
28640	This method uses a region to check case-insensitive equality . This means the internal array does not need to be copied like a toLowerCase ( ) call would .
28749	< code > subtractLocal < /code > subtracts the provided values from this vector internally , and returns a handle to this vector for easy chaining of calls .
28792	Use Open Nesting -- Use an open nesting model . Use an open nesting model , where inner transactions are allowed to commit independently of any outer transaction .
29155	Converts the given number of edit units in old edit rate to a new edit rate . It can be used to convert audio samples to video frames .
29206	Depends on activity_id : 1 - number , current level number ; 2 - number , current user 's points amount < p > Any other value is ignored
29325	Save the updated plane fit pose to update the AR object on the next render pass . This is synchronized against concurrent access in the render loop above .
29362	Returns < code > true < /code > if the specified URL uses the `` https '' protocol ; returns < code > false < /code > otherwise .
29370	Sort time UUIDs deterministically such that , as much as can be determined from the information in the UUID , UUIDs created earlier sort before UUIDs created later .
29566	Method return JobDefinition , accepts StageDefinition and JobDefinition Id , filters all JobDefinitions in the provided stage . Returns null if no JobDefinition with provided id is found .
29784	Verbose dump file -- Filename for detailed execution log . If you want to save the geomPTA analysis information for future analysis , please provide a file name .
30008	Peer ID . < p > < p > For group chat : `` 2000000000 + chat ID '' < p > For community : `` -community ID ''
30111	Build the namespaces chain based on the dimension name . < p > SIZE will contain multiple namespaces SHAPE will contain single namespace other dimensions will contain empty namespace
30724	Inserts a boolean array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
30789	Formats the given time delta , preserving all data . < p/ > Equivalent to < code > new HumanTime ( in ) .getExactly ( ) < /code >
31043	Just returns the first value . The intended usage is for temporarily using the first value , with the second value being what should be used on release .
31104	We thoroughly delete the geometric points-to result for space saving . Some applications such as those needing the call graph only may want to clean the points-to result .
31162	Associates the specified value with the specified key in this map . If the map previously contained a mapping for the key , the old value is replaced .
31197	Connects to the System of Record using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
31516	Returns true if this mouse button was double clicked . < p > Returns false if the button was single/triple/etc clicked or is currently waiting to be released .
31566	Applies a window function to an array of data , storing the result in the data array . Performs a dot product of the data and window arrays .
31609	Start the RabbitMq Server in a detached state . < p > This means the process will exit immediately and no PID file will be written to file .
31662	Connects to the System of Record using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
31962	Print Context Counts ( Totals only ) -- Print total number of contexts . Causes Paddle to print the number of contexts and number of context equivalence classes .
32038	Returns a recyclable FSize instance . calculates the approximate size of a text , depending on a demo text avoid repeated calls ( e.g . inside drawing methods )
32099	Begin the XML document . This must be called before any other formatting methods . This method prints an XML header into the top of the output stream .
32261	Set returnAll param < p > true - also return contacts found using this service before , false - return only contacts found using `` contacts '' field .
32385	Add the resource to the idle cache if present . If the resource was removed for any other reason while being added , it must then be discarded afterwards
32423	Connects to the System of Record using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
32478	Called when an activity you launched exits , giving you the requestCode you started it with , the resultCode it returned , and any additional data from it .
32511	`` SMS '' text to be sent in `` UTF-8 '' encoding . Only Latin letters and numbers are allowed . Maximum size is `` 160 '' characters .
32763	Inserts a CharSequence array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
32913	Inserts a CharSequence array value into the mapping of this Bundle , replacing any existing value for the given key . Either key or value may be null .
32964	Resets the counter to zero . But waiting threads wo n't be released somehow . So this interrupts the threads so that they escape from their waiting state .
33024	Rejects the drag as a result of examining either the < code > dropAction < /code > or the available < code > DataFlavor < /code > types .
33047	Indicates whether the entry meets the criteria to consider it an inherited from RDN collective attributes subentry ( i.e. , it contains the `` inheritedFromRDNCollectiveAttributeSubentry '' objectclass ) .
33223	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
33237	Returns true if all the nodes in the iteration well be returned in document order . Warning : This can only be called after setRoot has been called !
33317	< p > Find the appropriate < code > ClassLoader < /code > to use. < /p > < p > The context ClassLoader is preferred. < /p >
33407	Close the < tt > Handler < /tt > and free all associated resources . This will also close the target < tt > Handler < /tt > .
33414	Returns a Integer promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
33941	Returns the < code > ManageNameIDResponse < /code > in an XML document String format based on the < code > ManageNameIDResponse < /code > schema described above .
34274	Generic collection promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
34484	Inserts the unresolved role specified as an element at the position specified . Elements with an index greater than or equal to the current position are shifted up .
34645	This method uses a region to check case-insensitive equality . This means the internal array does not need to be copied like a toLowerCase ( ) call would .
34678	Removes the specified selected item in the object from the object 's selection . If the specified item is n't currently selected , this method has no effect .
34717	Returns true if all the nodes in the iteration well be returned in document order . Warning : This can only be called after setRoot has been called !
34725	Sets the current bindings aside and starts a new element context . This method should be called at the beginning of the startElement method of the Serializer implementation .
34839	add a given extension field for the standard extensions tag ( tag 3 ) The value parameter becomes the contents of the octet string associated with the extension .
34895	Apply mask penalty rule 1 and return the penalty . Find repetitive cells with the same color and give penalty to them . Example : 00000 or 11111 .
35056	Checks whether a given attribute is defined . This will convert the key over to CSS if the key is a StyleConstants key that has a CSS mapping .
35181	Tell if any of the debugging switches are turned on . If this is the case , it is reasonable to perform extra checks or save extra information .
35254	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the rate of change starts out quickly and and then decelerates .
35417	Reads an unsigned short ( 16-bit ) value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
35624	Returns true if all the nodes in the iteration well be returned in document order . Warning : This can only be called after setRoot has been called !
35703	Returns a map of class names to mapped classes given a map of class names to ClassNodes . Does not link the classes once the mappings are generated .
35779	Generic set promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
36106	Removes the specified selected item in the object from the object 's selection . If the specified item is n't currently selected , this method has no effect .
36120	Generic set promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
36139	Returns whether the < code > gr < /code > parameter is set . Not part on the interface since gruu is not part of the base RFC3261 .
36170	Always returns < code > false < /code > . This method is the default implementation of the < code > org.omg.CORBA.Object < /code > method. < P >
36331	Return the type corresponding uniquely ( 1-1 ) to this MT-form . It might have any primitive returns or arguments , but will have no references except Object .
36469	Compare the specified token against the current group manager token value . Can be used to reload cached group instances if there has been a group instance change .
36533	Associate the specified value with the specified key in this map . If the map previously contained a mapping for this key , the old value is replaced .
36615	Verifies that the username matches the user whose connections are being managed by this factory and closes the pool if this is the case ; otherwise does nothing .
36629	ACONST_NULL , LDC , and LDC_W can push nulls and strings , but these are all accessible in the class file and do n't need to be traced .
36638	Swaps the elements at the specified positions in the specified list . ( If the specified positions are equal , invoking this method leaves the list unchanged . )
36859	Parses the specified string as a signed byte value using the specified radix . The ASCII character \u002d ( '- ' ) is recognized as the minus sign .
36961	Removes the specified selected item in the object from the object 's selection . If the specified item is n't currently selected , this method has no effect .
37062	Gets all items at p_location on the active board layer . If nothing is found on the active layer and settings.select_on_all_layers is true , all layers are selected .
37073	Instructs the < code > LayoutCache < /code > that the bounds for < code > path < /code > are invalid , and need to be updated .
37181	Read syncsafe value from buffer in format specified in spec and convert to int . The buffers position is moved to just after the location of the syncsafe integer
37759	Returns true if this method does n't appear in the classes corresponding source file ( due to the appearance of a SyntheticAttribute in the method 's attribute list )
37854	We draw the background in paintMenuItem ( ) so override update ( which fills the background of opaque components by default ) to just call paint ( ) .
38065	Prints this JAXBException and its stack trace ( including the stack trace of the linkedException if it is non-null ) to < tt > System.err < /tt > .
38080	Pushes the value to the JFormattedTextField if the current value is valid and invokes < code > setEditValid < /code > based on the validity of the value .
38206	Calculates the y2 control point for a linear-out-faster-in path interpolator depending on the velocity . The faster the velocity , the more `` linear '' the interpolator gets .
38213	Applies the border box of the renderer on the given rectangle If the border of a certain side is null , the side will remain as it was .
38417	Asks the current thread to clear its state for the specified domain . < p > Note : This method blocks the current thread until state is cleared .
38675	Returns the `` rootUserDN '' string argument . < br > < i > N.B : the 'D ' short option is also used by bindDN. < /i >
38880	Returns a String promise Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! ! Added to make static imports possible .
38916	Returns a Double promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
39278	Returns a Float promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
39339	The default behavior of this method is to call addCookie ( Cookie cookie ) on the wrapped response object . Serialized . Updates the underlying response if available .
39692	Checks whether a given attribute is defined . This will convert the key over to CSS if the key is a StyleConstants key that has a CSS mapping .
39702	Starts all core threads , causing them to idly wait for work . This overrides the default policy of starting core threads only when new tasks are executed .
40093	Concatenate two compatible header lists , adding the argument either to the beginning or the tail end of this list . A type check is done before concatenation .
40254	Factory method for `` PolicyEvaluation '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
40466	Returns the < code > StatusDetail < /code > in an XML document String format based on the < code > StatusDetail < /code > schema described above .
40714	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the rate of change starts out slowly and and then accelerates .
40843	Ends the current element context and gets back to the parent context . This method should be called at the end of the endElement method of derived classes .
40851	Action to be taken , when this state is completed and exited . Default function to be overwritten in derived classes . Returns the return_state of this state .
40884	Factory method for `` SelfTiming '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
40885	Selects all the text in the < code > TextComponent < /code > . Does nothing on a < code > null < /code > or empty document .
40955	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
41034	Append a String with a zero separator to this ByteArrayBuilder , or only the zero separator if the string is null or if the string length is zero .
41216	Generic list promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
41275	Searches for a byte of specified value in the < code > buffer < /code > , starting at the specified < code > position < /code > .
41327	Called near the end of server shutdown . This ensures that a new InternalClientConnection is created if the server is immediately restarted as part of an in-core restart .
41345	Write out the default serializable data , after ensuring the < code > zoneStrings < /code > field is initialized in order to make sure the backward compatibility .
41461	Associates the specified value with the specified key in this map . If the map previously contained a mapping for this key , the old value is replaced .
41662	Reset all labels in the instruction list . This method should be called before reusing same instructions list between several < code > ClassWriter < /code > s .
41675	Associates the specified value with the specified key in this map . If the map previously contained a mapping for the key , the old value is replaced .
41848	Appends a < CODE > char < /CODE > to the buffer . The < CODE > char < /CODE > is converted according to the encoding ISO-8859-1 .
41912	Return the string representation of the qualified name using the the ' { ns } foo ' notation . Performs string concatenation , so beware of performance issues .
42147	Returns true if the value identified by path is currently collapsed , this will return false if any of the values in path are currently not being displayed .
42921	Adds an image to end of the list of sources . The image is stored as an object in order to allow new node types in the future .
42964	Returns the `` bindDN '' string argument . < br/ > < i > N.B : the 'D ' short option is also used by rootUserDN. < /i >
43068	Returns a Double promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
43362	Returns < code > true < /code > if configuration data has been migrated to Access Manager 7.0 . Else < code > false < /code > otherwise .
43397	Decrements the workerCount field of ctl . This is called only on abrupt termination of a thread ( see processWorkerExit ) . Other decrements are performed within getTask .
43474	Replaces an existing condition with the same name by the current one . If a condition with the same name does not exist , it will be added .
43637	Create a new NamePath where the head ( the last piece ) is removed . If there is no last piece this will return a new empty NamePath .
43698	Start an element in the output document . This might be an XML element ( < elem > data < /elem > type ) or a CDATA section .
43711	Verifies that the signature in this SignedObject is the valid signature for the object stored inside , with the given verification key , using the designated verification engine .
43905	If true , the field ? ? ? s option items shall be sorted alphabetically . This flag is intended for use by writers , not by readers .
43935	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
43951	Returns < code > true < /code > if the two layouts are equal . Two layouts are equal if they contain equal glyphvectors in the same order .
44066	This method returns < code > true < /code > , if the audio file is encoded with & quot ; Lossless & quot ; . < br >
44115	Associates the specified value with the specified key in this map . If the map previously contained a mapping for the key , the old value is replaced .
44743	Update the Server State with a Server State . Every CSN of this object is updated with the CSN of the passed server state if it is newer .
44815	Ensure there is at least one animation for every path in group ( linking them by names ) Build the `` current '' path based on the first group
44850	Causes the < code > Popup < /code > to be sized to fit the preferred size of the < code > Component < /code > it contains .
44856	Tells whether the given method signature is generic . The method is considered generic if its signature ends with something along the lines of `` ) TV ; ''
44889	Generic map promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
44971	Create a new < code > DTMIterator < /code > based only on a whatToShow and a DTMFilter . The traversal semantics are defined as the descendant access .
45108	Registers a listener for the session . If the provided session does not support listeners , calling this method will throw < code > SessionException < /code > .
45110	Makes the < code > Popup < /code > visible . If the < code > Popup < /code > is currently visible , this has no effect .
45201	The main processing method . This happens in a background task . In this case we are just sampling down the bitmap and returning it from a resource .
45262	Removes the ith element from queue without regard for maintaining the heap invariant . Recall that queue is one-based , so 1 < = i < = size .
45377	Returns the < code > StatusResponse < /code > in an XML document String format based on the < code > StatusResponse < /code > schema described above .
45752	This flag is used by the fractional replication ldif import plugin to stop the ( online ) import process if a fractional configuration inconsistency is detected by it .
45770	Checks all of the permissions in this body for a specific access type . Need to walk down each permission-bind rule pair and call it 's hasAccessType method .
45866	Prints this TypeConstraintException and its stack trace ( including the stack trace of the linkedException if it is non-null ) to < tt > System.err < /tt > .
45879	Moves and resizes this component . Unlike other components , this implementation also forces re-layout , so that frame decorations such as the title bar are always redisplayed .
45940	Paints the background of the track of a scrollbar . The track contains the thumb . This implementation invokes the method of the same name without the orientation .
45949	Sets the current bindings aside and starts a new element context . This method should be called at the beginning of the startElement method of the Serializer implementation .
46137	Removes all via headers from < tt > request < /tt > and replaces them with a new one , equal to the one that was top most .
46179	Generic collection promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
46235	Called near the end of server shutdown . This ensures that a new InternalClientConnection is created if the server is immediately restarted as part of an in-core restart .
46264	Reads new input data into the buffer . Call only with pos == end or end == -1 , depending on the desired outcome if the function throws .
46401	Compares < code > count < /code > first bytes in the arrays < code > a < /code > and < code > b < /code > .
46608	Encodes this CSN as a byte string . < p > NOTE : this representation must not be modified otherwise interop with earlier protocol versions will be broken .
46986	Returns the `` bindDN '' string argument . < br/ > < i > N.B : the 'D ' short option is also used by rootUserDN. < /i >
47350	Formats the given < code > Date < /code > into a date/time string and appends the result to the given < code > StringBuffer < /code > .
47399	Compiles all classes whose name matches the specified name using the JIT compiler and indicates if compilation has been successful . Does nothing and returns false on Android .
47417	If Sprite collided with player ( Mario ) . Checks by using fifth element ( hit box ) in SVGPath Array ( logical count starting from one ) .
47498	Invoked when the Window is set to be the focused Window , which means that the Window , or one of its subcomponents , will receive keyboard events .
47662	Returns a Long promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
47901	Checks if the proxying is enabled . It will be checking if the proxy service provider descriptor is set in the session manager for the specific request ID .
47966	Returns a `` deep '' copy of this SHA1MDImpl object . < BR > The method overrides `` clone ( ) '' in class Object . < BR >
48573	Returns the < code > StatusCode < /code > in an XML document String format based on the < code > StatusCode < /code > schema described above .
48863	Is multi sim . You need to declare the below permission in the manifest file to use this properly < uses-permission android : name= '' android.permission.READ_PHONE_STATE '' / >
48906	Associates the specified value with the specified key in this cache . If the cache previously contained a mapping for the key , the old value is replaced .
48936	Finishes writing uncompressed data to the output stream without closing the underlying stream . Use this method when applying multiple filters in succession to the same output stream .
49011	returns Side.ON_THE_LEFT , if this line direction is on the left of p_point , Side.ON_THE_RIGHT , if this line direction is on the right of p_point , Side.COLLINEAR otherwise
49038	We need to override this method to mark the camera for re-configuration ( set proper projection matrix ) since it will be reset by Rajawali on surface changes .
49139	Paints the border of the track of a scrollbar . The track contains the thumb . This implementation invokes the method of the same name without the orientation .
49150	Decrements the workerCount field of ctl . This is called only on abrupt termination of a thread ( see processWorkerExit ) . Other decrements are performed within getTask .
49229	Call < code > addObject ( ) < /code > on < code > pool < /code > < code > count < /code > number of times .
49301	Add the specified name/value pair to the list of parameters . The list of parameters is preserved in order , even though this technically may not be necessary .
49342	Check whether there was an unterminated line at end of input after the line reader reported end-of-input with EOFException . The value is meaningless in any other situation .
49770	Returns true if all the nodes in the iteration well be returned in document order . Warning : This can only be called after setRoot has been called !
49787	Parses a plain string from the current parsing position . The string is made up of all characters to the next whitespace , delimiter token or assignment token .
49861	Parses a plain string from the current parsing position . The string is made up of all characters to the next whitespace , delimiter token or assignment token .
49969	Returns a Long promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
49974	Tries to CAS right field to skip over apparent successor succ . Fails ( forcing a retraversal by caller ) if this node is known to be deleted .
50064	Ends the current element context and gets back to the parent context . This method should be called at the end of the endElement method of derived classes .
50086	Indicates whether this info object specified matches this one . To match , the match requirements of the superclass must be met and the types must be equal .
50209	Performs an action while temporary replacing the current token restriction checking context associated with the running thread After returning from action run ( ) method original context is restored
50274	check if gateway is trusted . true if list is empty OR does not contain `` none '' OR matches the one of the gateways in the list .
50280	Creates an empty border that takes up space but which does no drawing , specifying the width of the top , left , bottom , and right sides .
50356	Returns the < code > ManageNameIDResponse < /code > in an XML document String format based on the < code > ManageNameIDResponse < /code > schema described above .
50947	Indicates whether the entry meets the criteria to consider it an RFC 3671 LDAP collective attributes subentry ( i.e. , it contains the `` collectiveAttributeSubentry '' objectclass ) .
51036	Parses the specified string as a signed short value using the specified radix . The ASCII character \u002d ( '- ' ) is recognized as the minus sign .
51164	Specifies an LDAP object class which is to be associated with any intermediate `` glue '' entries forming the DN template . Multiple object classes may be specified .
51188	Creates an empty border that takes up no space . ( The width of the top , bottom , left , and right sides are all zero . )
51196	For each updatable , the given receiver is called with the updatable and a condition telling if the Updatable is still interested in receiving update ( ) calls .
51243	Return the top object on the stack without removing it . If there are no objects on the stack , return < code > null < /code > .
51248	Checks if the proxying is enabled . It will be checking if the proxy service provider descriptor is set in the session manager for the specific request ID .
51251	Returns the high-level media type , such as `` text '' , `` image '' , `` audio '' , `` video '' , or `` application '' .
51388	Load the text buffer with the given range of text . This is used by the fragments broken off of this view as well as this view itself .
51514	Returns the length of the year represented by this date . < p > This returns the length of the year in days , either 365 or 366 .
51550	Starts all core threads , causing them to idly wait for work . This overrides the default policy of starting core threads only when new tasks are executed .
52015	Whether to allow authentication purely based on client certificates . Note that the checking of the certificates MUST be done by setting jetty up for client auth required .
52044	Does the response contain the given header . < br > Warning : This method always returns < code > false < /code > for Content-Type and Content-Length .
52060	Trims the capacity of this list to be the list 's current size . An application can use this operation to minimize the storage of a list instance .
52061	Return < code > true < /code > if a component < code > a < /code > descends from a component < code > b < /code >
52274	Increases the capacity of this list , if necessary , to ensure that it can hold at least the number of components specified by the minimum capacity argument .
52315	Factory method for `` InternalSessions '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
52415	Turns this < code > UndoManager < /code > into a normal < code > CompoundEdit < /code > . This removes all edits that have been undone .
52495	Returns the < code > StatusMessage < /code > in an XML document String format based on the < code > StatusMessage < /code > schema described above .
53124	Factory method for `` CtsSessions '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
53276	Factory method for `` RemoteSessions '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
53521	Receive notification of the beginning of an element , additional namespace or attribute information can occur before or after this call , that is associated with this element .
53582	Returns true if all the nodes in the iteration well be returned in document order . Warning : This can only be called after setRoot has been called !
53629	Returns the < code > Status < /code > in an XML document String format based on the < code > Status < /code > schema described above .
53715	Tries to CAS right field to skip over apparent successor succ . Fails ( forcing a retraversal by caller ) if this node is known to be deleted .
53832	Tests whether the geometries of the two < code > Area < /code > objects are equal . This method will return false if the argument is null .
53847	Cancels this key . < p > A key that has been canceled is no longer valid . Calling this method on an already canceled key does nothing .
53863	Associates the specified value with the specified key in this map . If the map previously contained a mapping for the key , the old value is replaced .
54039	Waits during LISTEN_TIMEOUT milliseconds . This method is called after a message has been sent so that it has the time to propagate though the sending and receiving stack
54158	Returns < CODE > true < /CODE > if the server starting process finished ( successfully or not ) and < CODE > false < /CODE > otherwise .
54222	Removes the row at < code > row < /code > from the model . Notification of the row being removed will be sent to all the listeners .
54254	Removes the row at < code > row < /code > from the model . Notification of the row being removed will be sent to all the listeners .
54342	Indicates whether the entry meets the criteria to consider it an inherited from DN collective attributes subentry ( i.e. , it contains the `` inheritedFromDNCollectiveAttributeSubentry '' objectclass ) .
54379	Returns the high-level media type , such as `` text '' , `` image '' , `` audio '' , `` video '' , or `` application '' .
54430	Generic map promise . Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
54580	Reads this object out of a serialization stream , handling objects written by older versions of the class that did n't contain all of the fields we use now..
54604	Factory method for `` SubtreeTiming '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
54885	Sets the current bindings aside and starts a new element context . This method should be called at the beginning of the startElement method of the Serializer implementation .
55429	A dummy routine to satisify the abstract interface . If the DTM implememtation that extends the default base requires notification of registration , they can override this method .
55675	Factory method for `` SelfEvaluation '' MBean . You can redefine this method if you need to replace the default generated MBean class with your own customized class .
55749	Return the child < code > Component < /code > of the specified < code > Component < /code > that is the focus owner , if any .
55864	Reset the buffer and cipher . After resetting the object is in the same state as it was after the last init ( if there was one ) .
56029	Test whether both brackets are required in the expression . If not , use setExactMatch ( false ) and formatter will ignore missing right bracket . Advanced feature .
56034	Sizes the header and marks it as needing display . Equivalent to < code > revalidate < /code > followed by < code > repaint < /code > .
56297	< strong > ANDROID INTERPOLATOR < /strong > < br/ > < br/ > An interpolator where the rate of change starts out slowly and and then accelerates .
