440	This default implementation will send a pong in response to the received ping . The pong frame will have the same payload as the ping frame .
942	Reloads the preview contents . Call this method when the theme displayed or any of its attributes has changed in order to get the new preview .
1014	Modify the speed of the disk by multiplying its current speed with the given factor . Hint : You might use this method to decelerate also .
1200	Method checks whether local occurs in the left or right side of the localpair different semantics than the usual contains method which checks something in a list
1405	In case the buffer backing the nextMessage contains more than one HTTP message , move all data after the first message to a new Message object .
1551	Return the next sibling Node from the current node , after applying filter , whatToshow . If result is not null , set the current Node .
1645	Returns the < code > Map.Entry & lt ; K , V & gt ; < /code > type that represents the entries of the given map
1663	Return the previous sibling Node from the current node , after applying filter , whatToshow . If result is not null , set the current Node .
1667	User or community IDs and post IDs , separated by underscores . Use a negative value to designate a community ID . Example : 93388_21539,93388_20904,2943_4276 , -1_1
1693	Private method for notifying all listeners registered for supervision changes to Tags ( i.e . they get a Tag update call on a supervision change also )
1807	Photo album ID . To return information about photos from service albums , use the following string values : `` profile , wall , saved '' .
1810	Returns a range with no lower bound up to the given endpoint , which may be either inclusive ( closed ) or exclusive ( open ) .
1862	Sets the number of parent elements to include in the array `` copy_history '' that is returned if the post is a repost from another wall .
1994	Reload configuration . If the animation was playing it continue the animation with the new configuration . Used only in setRainParticles ( ) and setSnowParticles ( )
2020	Connects to the Databus using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
2044	Indicates whether this data element requires approval of data . Returns true if only one of the data sets associated with this data element requires approval .
2307	Notify model that it 's not active . This means it can stop watching for events etc . It may be activated again in the future .
2606	Item owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
2628	Indicates if the provided string argument is to be considered as a boolean , more specifically if it equals `` true '' or `` false '' .
2697	Performs a binary search for < tt > value < /tt > in the entire list . Note that you < b > must < /b >
2828	A helper function to search for the index of the point with the closest value to the searchX provided , using the default approximate search range .
2909	Determine whether the unit number i is an `` edge '' unit , i.e . a unit marking the start or the end of an utterance .
2985	Tests if the interior of this < code > Polygon < /code > intersects the interior of a specified < code > Rectangle2D < /code > .
3045	Triggered when a consolidation for a specific distributed transaction participant is failed due to timeout or too much backlog accumulation while waiting for other participant parts .
3207	Introduced in DOM Level 3 . < p > Checks if a type is derived from another by restriction . See : http : //www.w3.org/TR/DOM-Level-3-Core/core.html # TypeInfo-isDerivedFrom
3395	Creates an encrypted data file , that used by < code > com.j_spaces.core.filters.MemoryRealm < /code > , it contains space user details and user defined roles .
3470	Override this method in order to let the activity handle the up button . When pressed it will navigate the user to the parent of the activity
3597	Fired when a request returns successfully and contains a json array at the base of the response string . Override to handle in your own code .
3789	Finds all shortest paths on this graph , between vertex < code > 0 < /code > and vertex < code > n-1 < /code > .
3848	Makes a copy of the template query and any sub query ( s ) , changing aggregations . < p > Everything is a shallow copy .
3867	Creates a new model based on the given file descriptor , list of source file names and list of experiments to be enabled for the model .
3962	Return a submonitor for cases when we do not know the number of ticks ... The main task label will be prepended to the subtask label .
3964	Marks zombie tasks as finished with error . A zombie task can be defined as a task that did not complete before its given timeout period .
4153	This methods to be called on entering a first element whose type has this content model . It will return the initial state of the content model
4222	Removes all bookmarks and bookmark folders that the user can edit . Only the permanent bookmark folders remain after this operation , and any managed bookmarks .
4267	Although the following permission concerns the databus it is placed in the `` system '' resource since raw databus access should be controlled by system administrators .
4376	Returns a Bitmap representing the icon to be used for |url| . Private registries such as `` appspot.com '' will not be considered as effective TLDs .
4463	User or community IDs and post IDs , separated by underscores . Use a negative value to designate a community ID . Example : 93388_21539,93388_20904,2943_4276 , -1_1
4520	Performs various functions related to the trust verification process for the current instance of this proxy class , as detailed in the description for this class .
4708	ask view to rescan itself . This is method is wrapped into a runnable object and put in the swing event queue to avoid concurrent modifications .
4945	Load all the parts around the center of the screen , taking into account X and Y offsets , zoom level , and the current page displayed
5007	Create a thread for the given runnable based on the values in this object . May be overridden to give full control over creation of thread .
5094	ID of the user to whom SMS notification is sent . The user shall allow the application to send him/her notifications ( account.getAppPermissions , +1 ) .
5109	Determine whether the unit number i is an `` edge '' unit , i.e . a unit marking the start or the end of an utterance .
5152	A collection of Resources should be sorted such that Resources of the same type should be grouped together , and should be alphabetized within that group .
5577	Packs the four color components which should be in the range 0-255 into a 32-bit . Note that no range checking is performed for higher performance .
5617	Adds an IdentityLink for the given user id with the specified type , but only if the user is not associated with the execution entity yet .
5925	Analyze the associations of baseObj and store the result in it . The associations will be used when deleting referenced data of baseObj . Unused currently .
5930	Skip characters . This method will block until some characters are available , an I/O error occurs , or the end of the stream is reached .
5945	Called immediately after a model is unbound from a view holder . Subclasses can override this if they want alerts on when a model is unbound .
6438	Item owner 's identifier ( user or community ) Note that community id must be negative . `` owner_id=1 '' - user `` owner_id=-1 '' - community
6968	The URL to a retina sized version of the icon image ( absolute or relative to your script path ) . Used for Retina screen devices .
7058	Force all Namespaces to be declared . < p > This method is used on the root element to ensure that the predeclared Namespaces all appear .
7135	This node lost contact and rejoined the cluster again . This event is only fired in the node which rejoined and not to all the connected nodes
7794	Produce a comma delimited text from a JSONArray of JSONObjects . The first row will be a list of names obtained by inspecting the first JSONObject .
7798	Dividers are only drawn between items if both items allow it , or above the first and below the last item if that item allows it .
8019	Emulate the as operator of C # . If the object can be cast to type it will be casted . If not this returns null .
8053	Exceeds the backups threshold if the number of files we keep track of is larger than the number of files we should be keeping as backup .
8257	< p > LINE Login Button Page < p > Login Type is to log in on any desktop or mobile website https : //developers.line.me/web-login/overview # login_flow_type_web
8296	Verifies that author mode is loaded ( author loader is hidden ) and then verifies if given condition is met in medium timeout ( 15 seconds )
8327	Gets the set of labels required at the time of matching the vertex in a Cypher MATCH pattern . This implementation returns all labels in partition .
8332	Get the next number after the given number in the current propagation direction . < p > Assumes T has the same precision as a double .
8359	User or community IDs and post IDs , separated by underscores . Use a negative value to designate a community ID . Example : 93388_21539,93388_20904,2943_4276 , -1_1
8532	Calculates the number of months between the start and end-date . Note this method is taking daylight saving time into account and has a performance overhead .
8779	Wakes up this thread while the current thread is waiting for the specified sleep duration . Invoked by < code > cancel < /code > method .
8793	It stores the current file counter ( indicating the number of lines already processed from the file ) , so they wo n't be treated next time
9038	Extracts a RDD of labeled contexts from a RDD of rows where each row has two string cells containing a word sequence and a tag sequence .
9076	Returns a range from the given endpoint , which may be either inclusive ( closed ) or exclusive ( open ) , with no upper bound .
9199	Fired when a request returns successfully and contains a json object at the base of the response string . Override to handle in your own code .
9242	Returns the adapter position of the last fully visible view . This position does not include adapter changes that were dispatched after the last layout pass .
9506	Writes a `` short '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
9715	Verbose -- Print detailed information about the execution of Spark . When this option is set to true , Spark prints detailed information about its execution .
9984	Create a new DoubleBuffer of an appropriate size to hold the specified number of doubles only if the given buffer if not already the right size .
10293	Ensures that the log records corresponding to the specified LSN has been written to disk . All earlier log records will also be written to disk .
10356	We need to call ReactiveFB.onActivityResult in order to execute the onActivityResult and the login listener callbacks Example : ReactiveFB.onActivityResult ( requestCode , resultCode , data ) ;
10461	< code > intersectWhere < /code > determines if the Ray intersects a triangle . It then stores the point of intersection in the given loc vector
10503	Launches a deep sort on the array of feature vectors . This is public because it can be used to re-index the previously read feature file .
10670	Retrieves browser info from webDriver instance and stores it in the current test . If the webDriver lacks capabilities , browserInfo will create an error entry .
10782	Connects to the QueueService using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
10866	Reports that some operation is a no-op . This will either throw an exception or report the incident to the console , depending on the options .
11000	Needs to be called if a media is added to the editor . Important to be able to delete obsolete media once we 're done editing .
11248	Creates a request and adds it to the array of pending requests . Each created request gets a unique result code for use with requestPermission ( )
11298	Introduced in DOM Level 3 . < p > Checks if a type is derived from another by restriction . See : http : //www.w3.org/TR/DOM-Level-3-Core/core.html # TypeInfo-isDerivedFrom
11317	Config block threshold ( in millis ) , dispatch over this duration is regarded as a BLOCK . You may set it from performance of device .
11477	gets all the sets of one or more consecutive words , in decreasing order of length . Assumes minimum length is 2 and maximum length is 80
11690	The immediately preceding instant of the given timestamp . Envelope defines timestamps as unit-less longs , so the preceding timestamp is the given timestamp minus one .
11695	Print debug message ( if the debug level is high enough ) . < p/ > < p > Prints `` the message '' < /p >
11854	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
11912	Compare two time UUIDs deterministically , first by their embedded timestamp , next by their node-specific sequence number , finally breaking ties using their embedded node identifier.\
11950	Writes a `` double '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
12108	Convenience method to construct a new instance of < code > FormScalingUtil < /code > and apply the default scaling factor to the given component tree .
12163	Produce a comma delimited text from a JSONArray of JSONObjects . The first row will be a list of names obtained by inspecting the first JSONObject .
12165	Get an iterator over all edges that have the given node as a target . That is , edges that link into the given target node .
12215	Creates and adds to the queue a new operation , as described by operationIntent . Calls startService to make the operation is processed by the ServiceHandler .
12327	Update the cardinality count . < p > Note that this method acquires a read lock to query the lucene index for the number of documents .
12346	Return the first child Node from the current node , after applying filter , whatToshow . If result is not null , set the current Node .
12394	Indicates if the given row is currently validated . If not , validateBounds ( ) must be run to update the bounds to a current value .
12469	Removes the job 's execution 's reference to this job , if the job has an associated execution . Subclasses may override to provide custom implementations .
12586	Verbose -- Print detailed information about the execution of Spark . When this option is set to true , Spark prints detailed information about its execution .
12766	Screen name of the user , community ( e.g. , `` apiclub , '' `` andrew '' , or `` rules_of_war '' ) , or application .
12823	User or community IDs and post IDs , separated by underscores . Use a negative value to designate a community ID . Example : 93388_21539,93388_20904,2943_4276 , -1_1
12871	called by the engine after all connections have been closed . < p/ > if the ShotDownString property is set- the string is executed by the SA
12925	[ % SkillCaster ] inflicted % num0 damage on [ % SkillTarget ] and dispelled some of its magical buffs by using [ % SkillName ] .
12948	Collection owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
13004	Removes the job 's execution 's reference to this job , if the job has an associated execution . Subclasses may override to provide custom implementations .
13006	Returns the single variable pointing to all thread objects . This makes our analysis conservative on thread objects . public static native java.lang.Thread currentThread ( ) ;
13077	Returns true if the given token item contains a token that is in a king-like context , e.g. , `` King '' or `` Louis '' .
13456	Returns the adapter position of the first fully visible view . This position does not include adapter changes that were dispatched after the last layout pass .
13533	Verifies that the argument < code > set < /code > is catchable as any of the exceptions in < code > members < /code > .
13575	A convenience method which both registers the target listener and then fires it with the observable 's latest value ( to initialize it , essentially ) .
13742	Filter by advertising campaigns . Serialized JSON array with campaign IDs . If the parameter is 'null ' , ads of all campaigns will be shown .
13861	`` true '' - comments will be returned as numbered objects , in addition lists of `` profiles '' and `` groups '' objects will be returned
13919	Fired when a request returns successfully and contains a json object at the base of the response string . Override to handle in your own code .
14056	apply the left half of a window of the specified type to the data . The left half will be as long as the given len .
14209	Item owner 's identifier ( user or community ) Note that community id must be negative . `` owner_id=1 '' - user `` owner_id=-1 '' - community
14217	[ % Protector ] received the % num0 damage inflicted by [ % SkillCaster ] 's [ % SkillName ] , because of the protection effect .
14256	Performs evaluation of a word , using the dictionary of the category . Words that have not appeared in the category , return a false value .
14637	A convenience method which both registers the target receiver and then fires it with the observable 's latest value ( to initialize it , essentially ) .
14704	Gets a string from the resource bundle . We do n't want to crash because of a missing String . Returns the key if not found .
14797	Determines if the given feature is present . If the feature is not present in the utterance , the feature set of the voice is checked .
14809	Applies rank transform to each of the columns of < code > matrix < /code > using the current < code > rankingAlgorithm < /code > .
14862	Calculate and add a new long column by performing a mathematical operation on a number of existing columns . New column is added to the end .
14927	A callback for the ScanHandler that allows it to force the lexer state to CDATA content ( no markup is recognized except the end of element .
15075	Notifies the design surface that the given screen view ( which must be showing in this design surface ) has been rendered ( possibly with errors )
15079	Convenience method to create a new token with the type set to a boolean false value and with the starting index set to the given index .
15173	Return a submonitor for cases when we do not know the number of ticks ... The main task label will be prepended to the subtask label .
15213	Constructs a nested type from a string description of that type ; allows for package names to be omitted for 'java.lang ' and 'java.util ' classes .
15247	Filter by advertising campaigns . Serialized JSON array with campaign IDs . If the parameter is 'null ' , ads of all campaigns will be shown .
15305	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
15424	Connects to the DedupQueueService using the specified Jersey client . If you 're using Dropwizard , use this factory method and pass the Dropwizard-constructed Jersey client .
15536	Reads a `` short '' value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
15630	Bind the status bar of an activity to a topping so that it 's color is updated when the user/developer updates the color for that topping id
15770	Returns true if the given type can be bound to some type . Note : this should not be used with raw type of generic type .
15929	Returns a string created from the proxy class name , the registrar 's service ID , and the result of the underlying proxy 's toString method .
16245	Adds the given friend to the list < br / > To add a friend in the database , see < tt > PlayerService < /tt >
16251	Introduced in DOM Level 3 . < p > Checks if a type is derived from another by restriction . See : http : //www.w3.org/TR/DOM-Level-3-Core/core.html # TypeInfo-isDerivedFrom
16288	Create a new ByteBuffer of an appropriate size to hold the specified number of ints only if the given buffer if not already the right size .
16516	Performs various functions related to the trust verification process for the current instance of this proxy class , as detailed in the description for this class .
16916	Reads a `` double '' value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
16959	Call to super must be the first line in the overridden implementation , so that the base class can keep a reference to the item parameter .
16968	Add the main content of the RelativeLayout custom view to the subView contentView . This is the main content that will contains the childs of FlowLayout .
17051	Skip characters . This method will block until some characters are available , an I/O error occurs , or the end of the stream is reached .
17081	Photo album ID . To return information about photos from service albums , use the following string values : `` profile , wall , saved '' .
17457	Add Color Tags -- Add color tags to results of array bound check analysis.. Add color tags to the results of the array bounds check analysis .
17542	Copy the result , adding or replacing the value of a metric Do n't add a without column method because removing columns is far less safe .
17667	Returns true if the given token item contains a token that is in a section-like context , e.g. , `` chapter '' or `` act '' .
17761	Tests if the interior of this < code > Polygon < /code > intersects the interior of a specified < code > Rectangle2D < /code > .
17795	Makes a copy of the template query and any sub query ( s ) , changing post-aggregations . < p > Everything is a shallow copy .
17953	Item owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
17988	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
18021	Creates test repo . This uses the repo service directly so it is not meant to test the repo-create command but purely to facilate other tests .
18136	Clears both the header and subheader view cache . Headers and subheaders will be recreated and rebound on list scroll after this method has been called .
18481	Verbose -- Print detailed information about the execution of Paddle . When this option is set to true , Paddle prints detailed information about its execution .
18528	Decides if the operating system matches . < p > This method is package private instead of private to support unit test invocation . < /p >
18530	Collection owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
18532	Reads a `` float '' value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
18903	Enables mobile hacks for supporting instant taps ( fixing 200ms click delay on iOS/Android ) and touch holds ( fired as contextmenu events ) . default true
19034	Write a string as a null terminated character sequence . < p/ > IGV requires all strings to be ascii , so single byte storaged is enough
19085	Called in devices with touchpad when the user starts to adjust the position of the seekbar 's thumb . Will be followed by several onProgressChanged notifications .
19145	Add Color Tags -- Add color tags to results of array bound check analysis.. Add color tags to the results of the array bounds check analysis .
19177	A callback for the ScanHandler that allows it to force the lexer state to CDATA content ( no markup is recognized except the end of element .
19198	Method called to indicate that serialization of a field was omitted due to filtering , in cases where backend data format does not allow basic omission .
19234	Register a transmit complete listener . < p > The listener will be triggered with transmit result when transmit completes . The method should be non-blocking .
19449	Provide the revision to use for the compact request . < p > All superseded keys with a revision less than the compaction revision will be removed..
19525	Returns true if element 's textual contents preserves spaces . This only applies to PRE and TEXTAREA , all other HTML elements do not preserve space .
19536	Signals that this instance can not be modified . This is a HACK because the base type should be an immutable interface rather than a bean .
19578	Creates a new model based on the given file descriptor , list of source file names and list of experiments to be enabled for the model .
19923	Checks if the defined apiKey is valid or not . Only apiKey definition with name as 'key ' and 'in ' as 'query ' are allowed ''
19967	Called immediately after a model is bound to a view holder . Subclasses can override this if they want alerts on when a model is bound .
20228	Decides if the operating system matches . < p > This method is package private instead of private to support unit test invocation . < /p >
20437	Creates a request and adds it to the array of pending requests . Each created request gets a unique result code for use with requestPermission ( )
20472	Asserts that two maps of ModelItems contain the same elements and have the same number of elements . Uses the serialization strategies of the expected items .
20578	Returns true if the given token item contains a token that is in a section-like context , e.g. , `` chapter '' or `` act '' .
20690	Returns < code > true < /code > if the the thread will be daemon thread , returns < code > false < /code > otherwise .
20697	Collection owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
20914	Fired when a request returns successfully and contains a json object at the base of the response string . Override to handle in your own code .
20996	Merges items . < p > SCIPIO : modified for better in-depth cloning . < p > NOTE : the backreferences are always taken from overrideMenuItem .
21179	Performs a binary search for < tt > value < /tt > in the entire list . Note that you < b > must < /b >
21256	Sets the number of parent elements to include in the array `` copy_history '' that is returned if the post is a repost from another wall .
21547	Return the last child Node from the current node , after applying filter , whatToshow . If result is not null , set the current Node .
21575	Dividers are only drawn between items if both items allow it , or above the first and below the last item if that item allows it .
21861	Create a new IntBuffer of an appropriate size to hold the specified number of ints only if the given buffer if not already the right size .
22315	Creates new host from provided hostname and display name . Displays a popup dialog if wrong hostname is provided or the host has already been defined .
22735	true if this object is an eviction indicator . regular locks will wait till eviction performed , eviction will not take place if the object is locked
22897	Flag that specifies whether archived ads shall be shown . ' 0 ' - show only active campaigns ; ' 1 ' - show all campaigns .
23516	Launches a deep sort on the array of feature vectors . This is public because it can be used to re-index the previously read feature file .
23536	For a community : true - to post the topic as by the community false - to post the topic as by the user ( default )
23585	Once the item is given , it can not be used by other characters . Are you sure you want to keep it in % 0 ?
23862	Force all Namespaces to be declared . < p > This method is used on the root element to ensure that the predeclared Namespaces all appear .
23914	Calculates the number of days between the start and end-date . Note this method is taking daylight saving time into account and has a performance overhead .
23924	This methods to be called on entering a first element whose type has this content model . It will return the initial state of the content model
23940	Returns a list of overlays , from bottom to top ( where the later overlays are painted on top of earlier ones if they overlap ) .
24236	Returns < code > true < /code > if the analysis could determine that i is always treated as null after and including the statement s .
24273	Start recording picture on the canvas . If target width and height are set for the canvas scale output picture uniformally using by the smallest dimention .
24557	Returns < code > true < /code > if the analysis could determine that i is always treated as non-null after and including the statement s .
24571	Triggered when a consolidation for a specific distributed transaction participant is failed due to timeout or too much backlog accumulation while waiting for other participant parts .
24625	Returns a string created from the proxy class name , the registrar 's service ID , and the result of the underlying proxy 's toString method .
24780	SCIPIO : Utility method that can be used for security checks to check if controller of current webapp has the specified URI and allows direct/public access .
25106	Converts an < code > Object < /code > to a < code > long < /code > . Returns zero if conversion is not possible .
25240	Join an array of string to one string with joiner . If an element of the array contains nothing or only space , it will be ignored
25248	Flag that specifies whether archived ads shall be shown . ' 0 ' - show only active ads ; ' 1 ' - show all ads .
25278	Reads a packet from the socket ( non-blocking ) . If no packet is received , the method will return < code > null. < /code >
25429	Extracts a top level , single value from the XML structure . Throws an exception if there is not exactly one tag with the given name .
25452	For all ( possibly nested ) prosody elements in the document , calculate their ( possibly cumulated ) prosodic settings and save them in a map .
25611	Adds an image associated with a location string to this factory 's cache . The image will be scaled as dictated by this current factory settings .
25643	We move on until a none null pointer found . In this way , the clients do n't need to be aware of the empty slots .
25775	Start the eviction thread or service , or when < i > delay < /i > is non-positive , stop it if it is already running .
25995	Check if the < code > get < /code > method for the given data field returns values that are compatible with a given target type .
26012	Log a warning message if the capacity is reached ( every 500 times the capacity is reached , so as not to overload the logger ) .
26171	Checks if we need to fetch the Partner bookmarks and kicks the reading off . If reading was attempted before , it wo n't do anything .
26331	Verbose -- Print detailed information about the execution of Paddle . When this option is set to true , Paddle prints detailed information about its execution .
26497	Invalidate the bounds of all VisualItems in the given group . This will cause the bounds to be recomputed for all items upon the next redraw .
26779	Returns the adapter position of the first fully visible view . This position does not include adapter changes that were dispatched after the last layout pass .
26866	Returns < code > true < /code > if any non- < code > null < /code > location annotations have been written to this stream .
26962	Try to determine the locale of the given text . This implementation simply returns the default locale ; subclasses can try to do something fancy here .
27097	Retrieve the initial set of grammars for the validator to work with . REVISIT : does this need to be synchronized since it 's just reading ?
27192	Gets a string from the resource bundle . We do n't want to crash because of a missing String . Returns the key if not found .
27325	Converts an < code > Object < /code > to a < code > double < /code > . Returns zero if conversion is not possible .
27380	Calculate and add a new double column by performing a mathematical operation on a number of existing columns . New column is added to the end .
27631	We need to call ReactiveFB.onActivityResult in order to execute the onActivityResult and the login listener callbacks Example : ReactiveFB.onActivityResult ( requestCode , resultCode , data ) ;
27700	Are these two delegating maps the same in terms of the current layer and their delegates are equal under the definition of equality for that delegate .
27840	If rect is off screen , scroll just enough to get it ( or at least the first screen size chunk of it ) on screen .
28215	Filter by advertising campaigns . Serialized JSON array with campaign IDs . If the parameter is 'null ' , ads of all campaigns will be shown .
28661	Create a new ShortBuffer of an appropriate size to hold the specified number of shorts only if the given buffer if not already the right size .
28776	ask view to rescan itself . This is method is wrapped into a runnable object and put in the swing event queue to avoid concurrent modifications .
29049	Converts an < code > Object < /code > to an < code > int < /code > . Returns zero if conversion is not possible .
29098	Puts ResourceBundle on the BOTTOM of the stack ( bottom meaning will be overriden by higher layers on the stack , ie everything else already there )
29244	Return < code > True < /code > if appsecret_proof should be passed with graph api calls , otherwise return < code > False < /code >
29321	Fest API bug work-around - Double click on FEST moves the mouse between clicks ( to the same location ) , and that fails on Mac .
29326	Returns < code > true < /code > if the log entry is a file marker ( representing the file where the log was extracted ) .
29424	Returns true if all characters in string s are numbers . Accepts non-signed integers only . Does not accept floating point , exponential notation , etc .
29503	Needs to be called if a media is added to the editor . Important to be able to delete obsolete media once we 're done editing .
29505	Adds the given query schema to the registry . < p > If there was an existing schema with the same name , it is replaced .
29645	Fired when a request returns successfully and contains a json array at the base of the response string . Override to handle in your own code .
29811	Convenience method to create a new token with the type set to a boolean true value and with the starting index set to the given index .
29826	The curse of the Empyrean Lords has been reduced to % 0 level because you have n't slaughtered the lower level targets for a certain time .
29878	SCIPIO : Utility method that can be used for security checks to check if controller of current webapp has the specified URI and allows direct/public access .
29952	This default implementation will send a pong in response to the received ping . The pong frame will have the same payload as the ping frame .
30062	Calculate and add a new integer column by performing a mathematical operation on a number of existing columns . New column is added to the end .
30146	Parses the given string and returns a double value . Returns null if the given string is null or can not be parsed as a double .
30192	Check if the < code > get < /code > method for the given data field returns values that are compatible with a given target type .
30296	Writes a `` float '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
30348	If set to true , the tiles just wo n't load outside the world width ( -180 to 180 longitude ) instead of repeating . default false
30590	Clears all query caches . Note : During a transaction , Mithra allocates a special query cache , which will NOT be cleared by this method .
30918	Performs evaluation of a word , using the dictionary of the category . Words that have not appeared in the category , return a false value .
30933	Returns true if the given token item contains a token that is in a king-like context , e.g. , `` King '' or `` Louis '' .
31054	Creates an encrypted data file , that used by < code > com.j_spaces.core.filters.MemoryRealm < /code > , it contains space user details and user defined roles .
31074	apply the right half of a window of the specified type to the data . The right half will be as long as the given len .
31379	Config block threshold ( in millis ) , dispatch over this duration is regarded as a BLOCK . You may set it from performance of device .
31433	Transforms the given array of touch positions ( pixels ) ( x , y , x , y , ... ) into values on the chart .
31541	Fired when a request returns successfully and contains a json array at the base of the response string . Override to handle in your own code .
31667	Collection owner identifier Note that community id in the 'owner_id ' parameter should be negative number . For example 'owner_id'=-1 matches the [ vk.com/apiclub|VK API ] community
31758	Puts InternalRbmWrapper on the BOTTOM of the stack ( bottom meaning will be overriden by higher layers on the stack , ie everything else already there )
32301	Orders this limb to move to a target rotation . The rotation time is dependent on the rotational distance , the limb size , and power .
32336	< code > whichSide < /code > takes a plane ( typically provided by a view frustum ) to determine which side this bound is on .
32714	Returns the adapter position of the last fully visible view . This position does not include adapter changes that were dispatched after the last layout pass .
32735	Hash received after a successful OAuth authorization with a code got by SMS . ( If the password is changed right after the access was restored )
32902	Determine if this is a symbol object . Symbol objects are used so that entity field names and map keys can share the same tree structure .
33026	Creates an LDAP add request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
33280	Print formatting function . Indent and parenthesize for pretty printing . Note -- use the encode method for formatting the message . Hack here to XMLize .
33384	Method used to know if there are unsaved changes or not . It is used by the index selection listener when the user changes the selection .
33446	Skip characters . This method will block until some characters are available , an I/O error occurs , or the end of the stream is reached .
33466	Creates an LDAP add request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
33483	This method determines if the identity exists and returns true or false . This method is only valid for AMIdentity objects of type User and Agent .
33706	Returns the hash code of this RDN . Two RDNs that are equal ( according to the equals method ) will have the same hash code .
33765	Paints the border of the area behind the tabs of a tabbed pane . This implementation invokes the method of the same name without the orientation .
33768	User input value will be store in the callbacks [ ] . When user click cancel button , these input field should be reset to blank .
33784	EL does n't accept windows style path ( with backslashes ) . We need to protect ( escape ) them in order to have parse-able expressions .
33855	Checks if an error message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
33865	Return the Principal associated with the specified chain of X509 client certificates . If there is none , return < code > null < /code > .
33970	Returns the last object contained in this array . Equivalent to < code > getArray ( ) [ getArray ( ) .length-1 ] < /code > .
34144	Returns a new instance of < code > ArtifactResponse < /code > . Caller may need to call setters of the class to populate the object .
34337	Inserts a pin into the board . p_pin_no is the number of this pin in the library package of its component ( starting with 0 ) .
34513	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
34600	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
34746	Checks if an error message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
34926	Searches for people containers in this organizational unit using wildcards and * attribute values . Wildcards can be specified such as a* , * , *a .
34929	Creates the < code > EditorKit < /code > to use by default . This is implemented to return < code > javax.swing.text.StyledEditorKit < /code > .
34933	Creates a < code > TextHitInfo < /code > on the leading edge of the character at the specified < code > charIndex < /code > .
35031	Returns a new instance of < code > ArtifactResolve < /code > . Caller may need to call setters of the class to populate the object .
35038	Adds a < code > ChangeListener < /code > . The change listeners are run each time any one of the Bounded Range model properties changes .
35065	Returns < code > true < /code > if all required extension dependencies have been meet for this < code > ManifestResource < /code > object .
35106	Checks the current state of the builder for any issue with it 's state . If no issue is found , then no exception is thrown .
35590	Selects the last item in path and tries to edit it . Editing will fail if the CellEditor wo n't allow it for the selected item .
35727	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
35922	Method used to know if there are unsaved changes or not . It is used by the schema selection listener when the user changes the selection .
36126	Retrieves the < code > TypeCode < /code > object that corresponds to the value held in this < code > StringHolder < /code > object .
36176	Creates and returns a forward-order enumeration of this node 's children . Modifying this node 's child array invalidates any child enumerations created before the modification .
36336	Returns < CODE > true < /CODE > if the user closed the dialog by cancelling it and < CODE > false < /CODE > otherwise .
36492	The default behavior of this method is to call removeAttribute ( String name ) on the wrapped request object . Updates the underlying request if available .
36507	Returns a new instance of < code > Attribute < /code > . Caller may need to call setters of the class to populate the object .
36544	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onPause ( ) method .
36616	Returns the OID from the provided object class definition , assuming the definition is valid . < p > This method does not perform any check .
36779	Returns the position at the end of the next layout . Does NOT update the current position of this < code > LineBreakMeasurer < /code > .
36880	Deletes an entry from this pool . Only entries that are currently free in this pool can be deleted . Allocated entries can not be deleted .
36910	Retrieves the < code > TypeCode < /code > object that corresponds to the value held in this < code > BooleanHolder < /code > object .
37163	Appends a button for creating a new ObjectInfoWindow with the information of p_object to the text pane . Returns false , if that was not possible .
37196	Plays the audio clip given the URL and a specifier that is relative to it . Nothing happens if the audio clip can not be found .
37205	Compares this object to the specified object . The superclass behavior of comparing rectangles is not desired , so this is changed to the Object behavior .
37249	Return < code > SSOToken < /code > that is casted to < code > Object < /code > Given parameters are used to get SSOToken .
37473	Method used to know if there are unsaved changes or not . It is used by the index selection listener when the user changes the selection .
37476	Returns realm name in `` / '' separated format for the provided realm/organization name in DN format . Null or empty orgName would return `` / ''
37478	Reads a `` short '' value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
37694	Notify all container event listeners that a particular event has occurred for this Container . The default implementation performs this notification synchronously using the calling thread .
37883	Searches for people containers in this organizational unit using wildcards and * attribute values . Wildcards can be specified such as a* , * , *a .
38210	Makes a copy of this < code > PKIXParameters < /code > object . Changes to the copy will not affect the original and vice versa .
38345	Creates a new account usability response control that may be used to indicate that the account is available and provide the number of seconds until expiration .
38587	Delete an old , free pool entry to make room for a new one . Used to replace pool entries with ones for a different route .
38708	Indicates whether or not the factory is configured to produce parsers which are namespace aware ( it simply set feature XmlPullParser.FEATURE_PROCESS_NAMESPACES to true or false ) .
38777	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
38854	Indicates whether the entry meets the criteria to consider it an inherited collective attributes subentry ( i.e. , it contains the `` inheritedCollectiveAttributeSubentry '' objectclass ) .
38961	Returns a new instance of < code > Response < /code > . Caller may need to call setters of the class to populate the object .
39009	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
39064	Updates position of Mario on stage . Needs to be called manually in Mario logic ( the < em > update < /em > method ) .
39078	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onResume ( ) method .
39530	Writes a `` float '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
39767	Returns the OID from the provided attribute type definition , assuming the definition is valid . < p > This method does not perform any check .
39808	Factory method for creating a new element with the given name , given value and given attributes . The value and the attributes may be null .
39817	Sets the timeout after which additional threads ( beyond the core pool size ) will be terminated once pending requests on the queue have been satisfied .
39820	Creates and returns a forward-order enumeration of this node 's children . Modifying this node 's child array invalidates any child enumerations created before the modification .
39875	Allows the timer MBean to perform any operations it needs before being registered in the MBean server . < P > Not used in this context .
40028	This method is called back for all identities that are deleted from a repository . The universal identifier of the identity is passed in as an argument
40238	Utility method , returns true if the options flag indicates that an ack is to be sent after the message has been received but not yet processed
40242	Merge the server contents of this ADSContext with the contents of the provided ADSContext . Note that only the contents of this ADSContext will be updated .
40249	Attempts to read a character from the current position . The caller must ensure that the source string has the data available from the current position .
40431	This module will always return AuthStatus.SEND_SUCCESS as it is not designed to return a SSOToken , ony to validate that one is present on the request .
40641	Creates a new menu item attached to the specified < code > Action < /code > object and appends it to the end of this menu .
40663	Writes a `` double '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
40669	Looks at the object at the top of this stack without removing it from the stack . If the stack is empty , it returns true .
40683	Returns true if a node with the given mode can not be appended to this node because this node is unmatched and has opposite data mode .
40726	Add the certificate in the specified path to the provided keystore ; creating the keystore with the provided type and path if it does n't exist .
40780	Initializes the PushNotification system for this realm . If the system is already up-to-date and operational in the realm , this call will make no changes .
40841	Returns < CODE > true < /CODE > if the configuration has been read at least once and < CODE > false < /CODE > otherwise .
41052	Initializes the servlet . This method does all the `` work '' of gathering the configuration information for , and passing it to the Monitoring service .
41081	Register an option with this managed object definition . < p > This method < b > must not < /b > be called by applications .
41139	Return this previously allocated servlet to the pool of available instances . If this servlet class does not implement SingleThreadModel , no action is actually required .
41278	Converts decoded ASN.1 Integer to int value . If the object represents an integer value larger than 32 bits , the high bits will be lost .
41340	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
41456	Returns the DNs that match the filter . The search is performed from the root suffix ie. , DN . It searchs for SMS objects only .
41524	Method used to know if there are unsaved changes or not . It is used by the entry selection listener when the user changes the selection .
41710	Converts the specified integer into its octal string representation . The returned string is a concatenation of characters from ' 0 ' to ' 7 ' .
41722	Returns a hash code value for this date-time attribute . The hashcode is that of this attribute 's < code > java.util.Date < /code > value .
41997	Determine if this subject has exclusive/excluded state . If the subject is a legacy policy subject then return it 's exclusive state . Otherwise , return false
42014	Helper method that returns the number of bytes that would be used by the CSN fields encoded as a UTF8 string when appended to a ByteArrayBuilder .
42032	Converts the specified long value into its binary string representation . The returned string is a concatenation of ' 0 ' and ' 1 ' characters .
42069	Returns the last object contained in this array . Equivalent to < code > getArray ( ) [ getArray ( ) .length-1 ] < /code > .
42322	This method generates handler for async methods in REST APIs . The result is not needed . Only the state of the async result is required .
42367	Wrapper class that passes an ACI , an ACI 's targets and the specified target match context 's resource entry DN to the main isTargetApplicable method .
42479	Just return the string passed as a parameter but installs an instance of this class as the DatatypeConverter implementation . Used from static fixed value initializers .
42837	Adds a permission to the SocketPermissions . The key for the hash is the name in the case of wildcards , or all the IP addresses .
42866	Closes this reader . This implementation closes the buffered source reader and releases the buffer . Nothing is done if this reader has already been closed .
43162	Return true if ACK was sent ( for client tx ) . For server tx , this is a NO-OP ( we dont send ACK ) .
43234	Writes the specified character < code > oneChar < /code > to this StringWriter . This implementation writes the low order two bytes to the Stream .
43280	Resets the cursor to the beginning of the string . The next call to next ( ) will return the first collation element in the string .
43291	Boolean promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
43528	Removes the specified entry and any subordinates that it may have from the backend . This method assumes that the caller holds the backend write lock .
43642	Must be invoked each time the session changes because , the monitor name is dynamically created with the session name , while monitor registration is static .
43691	Creates an LDAP search request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
43819	Returns a specifier for an indexed-color image format that will pack index values of the given bit depth into array elements of the specified data type .
43835	Returns the OID from the provided name form definition , assuming the definition is valid . < p > This method does not perform any check .
43854	This method is obsolete and its implementation is now a noop . It 's still called by setSelectionPaths and addSelectionPaths , but only for backwards compatibility .
44120	Adds an action listener to this panel . The action listener will be invoked when the user clicks on the 'Edit ' button or the icon .
44126	Returns true if a node with the given mode can not be appended to this node because this node is unmatched and has opposite data mode .
44180	Reads a password from the console without echoing it to the client . FIXME This method should disappear when all the tools will extend to ConsoleApplication .
44213	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onResume ( ) method .
44232	Returns a new instance of < code > Action < /code > . Caller may need to call setters of the class to populate the object .
44239	Indicates whether this branch contains a reference to the specified attribute type , either in the RDN components of the DN or in the extra lines .
44436	Reads a `` float '' value from a byte array at a given offset . The value is converted to the opposed endian system while reading .
44505	Cast result object to a boolean . This always returns true for a RTreeFrag because it is treated like a node-set with a single root node .
44506	Consumes all the messages sent to this broker . This is useful at the start of a test to avoid leftover messages from previous test runs .
44914	Utility - log debug message - highlight it is from the test and not from the server code . Makes easier to observe the test steps .
45000	Checks if an error message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
45061	Creates a CLI exception which should be used when a managed object is retrieved but does not have the correct type appropriate for the associated sub-command .
45210	Called by the background thread after active sessions have been checked for expiration , to allow sessions to be swapped out , backed up , etc .
45245	Returns the size in bytes of a basic Object . This method should only be used for actual Object objects and not classes that extend Object .
45357	Writes a `` short '' value to a byte array at a given offset . The value is converted to the opposed endian system while writing .
45418	Returns a new instance of < code > AuthnStatement < /code > . Caller may need to call setters of the class to populate the object .
45535	Appends a button for creating a new ObjectInfoWindow with the information of p_items to the text pane . Returns false , if that was not possible .
45582	Calculates the distance between two positions in degress , radians , miles , or kilometers . This uses the Haversine formula to account for global curvature .
45666	Reloads the workspace items from the DB and re-binds the workspace . This should generally not be called as DB updates are automatically followed by UI update
45877	Calculates out what percent complete this operation is . If more records get added during the operation , the percent complete could decrease instead of climb .
45960	Add a list of counted nodes that were built in backwards document order , or a list of counted nodes that are in forwards document order .
46174	Important : p_other represent a `` direction '' in a floating point mode Basically the determinant of two `` directions '' is zero if they are colinear
46343	Performs any necessary cleanup in an attempt to delete any temporary schema files that may have been left over after trying to install the new schema .
46361	Looks at the object at the top of this stack without removing it from the stack . If the stack is empty , it returns false .
46594	Creates an LDAP search request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
46900	Search the given Set of TrustAnchor 's for one that is the issuer of the given X509 certificate . Uses the default provider for signature verification .
46903	Adds other to the object . Before , `` this '' must be of reduced degree . After , `` this '' is of reduced degree .
47184	Initializes the servlet . This method does all the `` work '' of gathering the configuration information for , and passing it to the Monitoring service .
47207	Returns < code > true < /code > if any non- < code > null < /code > location annotations have been written to this stream .
47330	Returns the encrypted session string . By doing so it also makes it possible to use this string representation for serializing/deserializing SessionID objects for session failover .
47398	Modify the current clipping path by intersecting it with the current path , using the even-odd rule to determine which regions lie inside the clipping path .
47664	Closes this reader . This implementation closes the buffered source reader and releases the buffer . Nothing is done if this reader has already been closed .
47755	Checks if an access message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
47947	NUMSUBORDINATE HACK numsubordinates is not usable if the displayed entry is listed in in the hacker . Note : *usable* means *usable for detecting children presence* .
48037	Called after a socket connection has been created or retrieved from the pool . Subclasses use this hook to get a reference to the TLS data .
48194	Add the schema elements one by one : we are not sure that the server will handle the adds sequentially if we only send one modification .
48252	Indicates whether this branch contains a reference to the specified attribute type , either in the RDN components of the DN or in the extra lines .
48384	The `` expert '' flag is used to distinguish between those features that are intended for expert users from those that are intended for normal users .
48430	Tests to see if this < code > Timestamp < /code > object is equal to the given < code > Timestamp < /code > object .
48449	Returns a new instance of < code > AuthzDecisionStatement < /code > . Caller may need to call setters of the class to populate the object .
48611	Checks if an error message of the given level would actually be logged by this logger . This check is based on the Loggers effective level .
48623	Adds an ImageConsumer to the list of consumers interested in data for this image and immediately starts delivery of the image data through the ImageConsumer interface .
48821	Returns the next tab stop position after a given reference position . This implementation does not support things like centering so it ignores the tabOffset argument .
49000	Adds a Token operation into the monitoring store . < br/ > The operations per configurable period and cumulative count will be updated for the operation .
49094	Activate/modify the component . Because the List of ObjectMappings is re-assigned based on the updated configuration , this method is safe for both activation and modification .
49110	Deregisters the provided root DN with the Directory Server . This will have no effect if the provided DN is not registered as a root DN .
49275	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
49384	Set this to true if this span is sampleable and should be output to the logging/span collection system , false otherwise . This defaults to true .
49465	This method returns an < code > int < /code > indicating if the source is in the same JVM as the target . < P >
49508	Returns true if the tree is being edited . The item that is being edited can be obtained using < code > getSelectionPath < /code > .
49514	Returns true if the class already has a SVUID field . The result of this method is only valid when visitEnd is or has been called .
49636	Indicates whether the backup process should generate a hash of the data as it is archived that may be validated as part of the restore process .
49698	Returns < CODE > true < /CODE > if we are trying to manage the local host and < CODE > false < /CODE > otherwise .
49718	Closes this < code > MemoryCacheImageInputStream < /code > , freeing the cache . The source < code > InputStream < /code > is not closed .
49910	Returns whether the representation class for this < code > DataFlavor < /code > is < code > java.nio.ByteBuffer < /code > or a subclass thereof .
50031	Closes the socket . It is not possible to reconnect or rebind to this socket thereafter which means a new socket instance has to be created .
50275	Wrap a class name . < p > This is the same as calling < code > on ( Class.forName ( name ) ) < /code >
50371	Returns true if a single sign on token is valid , resetting the token 's idle time if and only if the flag allows us to .
50429	Returns the `` filename '' string argument . < i > N.B : the ' f ' short option is also used by configfile < /i >
50445	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
50480	Remove a session from the internal session cache and make it as no longer local . The Session remains in the ( non-internal ) session cache .
50524	Returns whether the representation class for this < code > DataFlavor < /code > is < code > java.io.Reader < /code > or a subclass thereof .
50800	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onDestroy ( ) method .
50868	which generates the p and g values from the given parameters , returning the DSAParameters object . < p > Note : can take a while ...
50929	Returns a new instance of < code > SubjectLocality < /code > . Caller may need to call setters of the class to populate the object .
50969	Programmatically performs a `` click '' . This overrides the method < code > AbstractButton.doClick < /code > in order to make the menu pop up .
51200	Returns whether we are in automatic expand mode . This mode is used when the user specifies a filter and all the nodes are automatically expanded .
51238	Creates a container listener that will be added to the JToolBar . If this method returns null then it will not be added to the toolbar .
51246	Reloads the mnemonics . This should be invoked when a memonic changes , when the title of a mnemonic changes , or when tabs are added/removed .
51950	Updates the contents of the panel with the indexes on the provided backend . A table with all the indexes of the backend will be displayed .
52213	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onDestroy ( ) method .
52215	WriteObject is called to save the state of the URL to an ObjectOutputStream . The handler is not saved since it is specific to this system .
52388	Register a constraint with this managed object definition . < p > This method < b > must not < /b > be called by applications .
52431	Writes a boolean to this file as a single byte ( 1 for true , 0 for false ) , starting at the current file pointer .
52466	Just calls < code > paint ( g ) < /code > . This method was overridden to prevent an unnecessary call to clear the background .
52638	Indicates whether this entry meets the criteria to consider it an RFC 3672 LDAP subentry ( i.e. , it contains the `` subentry '' objectclass ) .
52772	Creates a new account usability response control that may be used to indicate that the account is not available and provide information about the underlying reason .
52955	Allows the timer MBean to perform any operations needed after having been unregistered by the MBean server . < P > Not used in this context .
53422	The `` hidden '' flag is used to identify features that are intended only for tool use , and which should not be exposed to humans .
53452	Looks at the object at the top of this stack without removing it from the stack . If the stack is empty , it returns false .
53540	Encode this hostport into its string representation . Note that this could be different from the string that has been parsed if something has been edited .
53556	Subtracts other from the object . Before , `` this '' must be of reduced degree . After , `` this '' is of reduced degree .
53640	Creates an invisible component that 's always the specified size . < ! -- WHEN WOULD YOU USE THIS AS OPPOSED TO A STRUT ? -- >
53781	Method used to know if there are unsaved changes or not . It is used by the index selection listener when the user changes the selection .
53905	Processes an object . If the object is indirect , it is added to the list of resources . If not , it is just processed .
53906	Checks the current state of the builder for any issue with it 's state . If no issue is found , then no exception is thrown .
54073	Checks that there are no conflicts with the directory manager passwords . If we are in no prompt mode , check that the password was provided .
54105	Returns a new instance of < code > Attribute < /code > . Caller may need to call setters of the class to populate the object .
54311	Calculates the nearest point on this line to p_from_point between this.a and this.b TODO need to consider that the project may not exist , for whatever reason
54504	Method that control the lifecycle of the view . It should be called in the view 's ( Activity or Fragment ) onPause ( ) method .
54964	Returns a new instance of < code > XACMLAuthzDecisionStatement < /code > . Caller may need to call setters of the class to populate the object .
55006	Returns < CODE > true < /CODE > if the provided DN corresponds to a read-only entry and < CODE > false < /CODE > otherwise .
55044	Looks at the object at the top of this stack without removing it from the stack . If the stack is empty , it returns true .
55121	Start scrolling by providing a starting point and the distance to travel . The scroll will use the default value of 250 milliseconds for the duration .
55305	Write the contents of this BodyJspWriter into a Writer . Subclasses are likely to do interesting things with the implementation so some things are extra efficient .
55382	Utility - log debug message - highlight it is from the test and not from the server code . Makes easier to observe the test steps .
55750	Deletes property from this very renderer , or in case the property is specified on its model element , the property of the model element is deleted
55846	Boolean promise Added to make static imports possible . Create a blocking promise . NOTE BLOCKING PROMISES ARE FOR LEGACY INTEGRATION AND TESTING ONLY ! ! !
55883	Returns the UTF-8 decoded string representation of the provided byte array sub-sequence . If UTF-8 decoding fails , the platform 's default encoding will be used .
55904	Creates an LDAP delete request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
55918	Computes the hash code of this composite name . The hash code is the sum of the hash codes of individual components of this composite name .
55942	Indicates that the Directory Server has received a request to stop running and that this shutdown listener should take any action necessary to prepare for it .
55961	Register an extension namespace handler . This handler provides functions for testing whether a function is known within the namespace and also for invoking the functions .
55985	Back up the current cursor by one char , assumes current.cursor > 0 , and that the char to be pushed back is not '\n ' .
56293	Creates an LDAP delete request that will propagate the common audit transaction id if the target LDAP server supports it ( i.e. , is OpenDJ ) .
